import { environmentProjection } from './environmentRecords';
import { planningProjection } from './planningRecords';
import { choice, count, fixed, flag, list, nullable, object, output, replaceField, sample, text, union, type ContractDefinition, type Payload, type Json } from './schema';
import { authority, toolCall, toolResult, turnState, turn, limits } from './shared';
import { contextScope, generationVector, catalogEntry, catalogBinding, contribution, skillInventoryEntry, observationProjection, projectionHook, contextModelProjection, extendContextRecord as extend } from './contextRecords';
import { toolsResourceRequest, toolsPromptRequest } from './toolsContextAcquisition';
import { modelMetadataRequest, modelCapabilitiesReady, modelCapabilitiesUnavailable, modelBudgetProfile } from './modelRecords';

const edges = (...ids: string[]) => ids.map(id => `lina-context-edge-${id}`);
const round = object({ roundId: text('round-001'), index: count(1) });
const identities = object({ agentId: text('lina-main'), conversationId: text('conversation-demo'), turnId: text('turn-001'), roundId: text('round-001') });
const source = extend(object({ sourceRef: text('history:conversation-001:r7'), revision: text('r7'), kind: choice(['instructions', 'history', 'task', 'task-plan', 'memory', 'tool-catalog', 'artifact']), required: flag(true), status: choice(['loaded', 'referenced', 'unavailable', 'denied']), trust: choice(['harness-instruction', 'project-instruction', 'harness-config', 'untrusted-evidence']) }), { sourceId: text('source:history-001'), digest: text('sha256:fixture-source'), scopeRef: text('context-scope:lina-main:v1'), originRef: text('workspace-demo'), acquisitionRef: sample(nullable(text('acquisition:resource-001')), null), omissionReason: sample(nullable(text('optional-source-unavailable')), null) });
const instruction = extend(object({ sectionId: text('instruction-harness'), precedence: count(0), sourceRef: text('instructions:lina:v1'), revision: text('v1'), text: text('Use permitted tools. Preserve user constraints.'), required: flag(true) }), { kind: choice(['harness', 'agent', 'project', 'activated-skill']), originRef: text('harness:lina:v1'), packageRevision: sample(nullable(text('package:docs-demo:v1')), null), activationId: sample(nullable(text('skill-activation:turn-001:1')), null), hostTrustDecisionRef: text('instruction-trust:harness:v1'), contributionDigest: text('sha256:fixture-harness-instructions'), precedencePolicyRef: text('instructions:precedence:v1') });
const user = object({ recordId: text('input-001'), role: fixed('user'), content: text('What is 2 + 2?'), sourceRef: text('input-001'), protected: fixed(true) });
const assistantCall = object({ recordId: text('assistant-001'), role: fixed('assistant'), calls: list(toolCall, [toolCall.example], 1), sourceRef: text('history:assistant-001'), protected: flag(true) });
const observation = object({ recordId: text('result-001'), role: fixed('tool'), callId: text('call-001'), result: toolResult, sourceRef: text('call-001:result'), artifactRef: nullable(text('artifact:call-001:raw')), protected: flag(true) });
const summaryMessage = object({ recordId: text('summary-001'), role: fixed('summary'), content: text('Earlier work established that arithmetic answers should be concise.'), sourceRef: text('summary:history:r7:1'), protected: flag(false) });
const assistantText = object({ recordId: text('assistant-text-001'), role: fixed('assistant'), content: text('I will inspect the supplied diagram.'), sourceRef: text('history:assistant-text-001'), protected: flag(false) });
const mediaPart = object({ type: choice(['image', 'audio', 'file']), artifactRef: text('artifact:input-001:image-001'), mimeType: text('image/png'), sourceRef: text('input-001:attachment-001') });
const mediaUser = object({ recordId: text('input-001'), role: fixed('user'), content: list(union(object({ type: fixed('text'), text: text('Explain this diagram.') }), mediaPart), [mediaPart.example], 1), sourceRef: text('input-001'), protected: fixed(true) });
export const modelContextMessage = union(user, mediaUser, assistantText, assistantCall, observation, summaryMessage);
const selection = object({ sourceRef: text('input-001'), recordIds: list(text('input-001'), ['input-001'], 1), action: choice(['included', 'omitted', 'masked', 'summarized', 'unavailable']), reason: text('Current user input is protected.'), derivedRef: sample(nullable(text('summary:history:r7:1')), null) });
const reduction = object({ attempt: count(1), policy: choice(['mask-old-observations', 'summary-old-complete-groups']), previousRevision: count(0), revision: count(1), beforeEstimatedTokens: count(950), afterEstimatedTokens: count(650), sourceRefs: list(text('history:conversation-001:r7'), ['history:conversation-001:r7'], 1) });
const budget = extend(object({ accounting: fixed('synthetic-estimate'), estimatorRef: text('fixture-estimator:v1'), modelCapabilitiesRef: text('model-capabilities:demo:v1'), capacity: count(1000), outputReservation: count(200), overheadAndMargin: count(50), instructionTokens: count(100), historyTokens: count(200), taskTokens: count(100), toolTokens: count(100), estimatedInputTokens: count(550), availableInputTokens: count(800), protectedEstimatedTokens: count(300), reductionAttempts: count(0), maxReductionAttempts: count(2), fits: flag(true) }), { activatedSkillTokens: count(0), skillInventoryTokens: count(0), promptMessageTokens: count(0), observationTokens: count(0), mediaEstimateTokens: count(0), hookAddedTokens: count(0), acquisitionWorkUsageRef: sample(nullable(text('usage:resource-attempt-001')), null), summaryWorkUsageRef: sample(nullable(text('usage:context-summary-001')), null), estimationUncertainty: choice(['fixture', 'measured-provider', 'estimated-tokenizer']), modelBudgetProfile });
const tool = catalogEntry;
const evidence = extend(object({ evidenceId: text('task-001'), sourceRef: text('input-001'), revision: text('v1'), kind: choice(['attachment', 'retrieval', 'memory', 'task-note', 'child-task', 'child-result', 'task-plan', 'connector-resource', 'connector-prompt', 'skill-resource']), text: nullable(text('Answer the current arithmetic question.')), artifactRef: sample(nullable(text('artifact:input-001:image-001')), null), trust: fixed('untrusted-evidence') }), { scopeRef: text('context-scope:lina-main:v1'), accountBindingRef: sample(nullable(text('binding:docs-demo:user-demo:v1')), null), namespaceRef: sample(nullable(text('workspace-demo:shared')), null), mimeType: text('text/plain'), digest: text('sha256:fixture-task'), acquisitionRef: sample(nullable(text('acquisition:resource-001')), null), suppliedRole: choice(['user', 'assistant', 'tool', 'evidence'], 'evidence'), status: choice(['included', 'omitted', 'failed']), omissionReason: sample(nullable(text('optional-source-unavailable')), null) });
export const contextPreparation = extend(object({ identities, state: turnState, round, authority, historyRef: text('history:conversation-001:r7'), inputRefs: list(text('input-001'), ['input-001'], 1), toolResultRefs: list(text('call-001:result'), []), instructionSetRef: text('instructions:lina:v1'), toolCatalogRef: text('tools:lina:v1'), contextPolicyRef: text('context:recent-complete-groups:v1'), modelCapabilitiesRef: text('model-capabilities:demo:v1'), requestedRevision: count(0), previousSnapshotRef: sample(nullable(text('context:turn-001:round-001:r0')), null) }), { preparationId: text('prepare:turn-001:round-001:r0'), workspaceId: text('workspace-demo'), requesterId: text('user-demo'), scope: contextScope, sourceGenerations: generationVector, reprepareAttempts: count(0), maxReprepareAttempts: count(2), requestedModelBindingRef: text('model-binding:demo:g1'), requestedModelBudgetProfileRef: text('model-budget:demo:v1'), requestedModelCodecRevision: text('codec:chat:v1') });
const sourceBundle = list(source, [source.example, ...[
  ['instructions:lina:v1', 'instructions', 'harness-instruction'], ['input-001', 'task', 'untrusted-evidence'], ['tools:lina:v1', 'tool-catalog', 'harness-config'], ['tool-schema:calculator:v1', 'tool-catalog', 'harness-config'], ['history:assistant-001', 'history', 'untrusted-evidence'], ['call-001:result', 'history', 'untrusted-evidence'], ['artifact:call-001:raw', 'artifact', 'untrusted-evidence'], ['history:assistant-old-001', 'history', 'untrusted-evidence'], ['call-old-001:result', 'history', 'untrusted-evidence'], ['artifact:old-observation:raw', 'artifact', 'untrusted-evidence'], ['history:old-complete-group', 'history', 'untrusted-evidence'], ['summary:history:r7:1', 'artifact', 'untrusted-evidence'], ['input-001:attachment-001', 'artifact', 'untrusted-evidence'], ['artifact:input-001:image-001', 'artifact', 'untrusted-evidence'], ['history:assistant-text-001', 'history', 'untrusted-evidence'],
].map(([sourceRef, kind, trust]) => ({ ...source.example as object, sourceRef, revision: 'v1', kind, trust }))], 1);
export const contextCandidate = extend(object({ request: contextPreparation, revision: count(0), sources: sourceBundle, instructions: list(instruction), messages: list(modelContextMessage, [user.example], 1), taskEvidence: list(evidence, [evidence.example]), tools: list(tool), selectionManifest: list(selection), reductions: list(reduction, []), budget, canonicalHistoryRef: text('history:conversation-001:r7'), canonicalRecordsPreserved: fixed(true) }), { scope: contextScope, generationVector, catalogBinding, stagedContributions: list(contribution, []), skillInventory: list(skillInventoryEntry, []), observations: list(observationProjection, []), canonicalResultCompletionOrder: list(text('call-001'), []), hookInvocations: list(projectionHook, []), pendingSourceWorkRefs: list(text('acquisition:resource-001'), []), model: contextModelProjection, taskPlanProjection: sample(nullable(planningProjection), null), environmentProjection: sample(nullable(environmentProjection), null), dependencyAvailability: object({ memoryRuntime: fixed('unimplemented'), modelCapabilityRuntime: fixed('design-fixture'), sourceOfCapabilities: fixed('model-resolve-fixture') }) });
const candidate = contextCandidate;
export const contextProjectionHookRequest = object({ candidate: contextCandidate, hook: projectionHook });
const reprepare = (reason: string) => object({ state: turnState, round, request: contextPreparation, preparationId: text('prepare:turn-001:round-001:r0'), reason: text(reason), expectedGenerations: generationVector, currentGenerations: replaceField(generationVector, 'catalog', text('catalog:demo:8')), nextRevision: count(1), reprepareAttempts: count(1), maxReprepareAttempts: count(2), modelAttemptLaunched: fixed(false), roundCountersPreserved: fixed(true), priorValidSnapshotPreserved: fixed(true) });
// Shape-valid records can still violate transcript relationships. This fixture
// reaches validation with a result whose assistant call is absent.
const orphanCandidate = replaceField(candidate, 'messages', list(modelContextMessage, [user.example, observation.example], 1));
const pressuredBudget = sample(budget, { ...budget.example as object, historyTokens: 600, estimatedInputTokens: 950, fits: false });
const oldCall = { ...toolCall.example as object, callId: 'call-old-001' };
const oldAssistant = { ...assistantCall.example as object, recordId: 'assistant-old-001', calls: [oldCall], sourceRef: 'history:assistant-old-001', protected: false };
const oldObservation = { ...observation.example as object, recordId: 'result-old-001', callId: 'call-old-001', result: { callId: 'call-old-001', outcome: 'success', value: 'Verbose earlier observation retained in raw artifact.' }, sourceRef: 'call-old-001:result', artifactRef: 'artifact:old-observation:raw', protected: false };
const recentGroup = [user.example, assistantCall.example, observation.example];
const pressured = replaceField(replaceField(candidate, 'budget', pressuredBudget), 'messages', list(modelContextMessage, [oldAssistant, oldObservation, ...recentGroup], 1));
const reducedBudget = sample(budget, { ...budget.example as object, historyTokens: 300, estimatedInputTokens: 650, reductionAttempts: 1 });
const maskedObservation = { ...oldObservation, result: { callId: 'call-old-001', outcome: 'success', value: '[Older observation masked; read artifact:old-observation:raw if needed.]' } };
const maskedManifest = list(selection, [selection.example, { ...selection.example as object, sourceRef: 'artifact:old-observation:raw', recordIds: ['assistant-old-001', 'result-old-001'], action: 'masked', reason: 'Older completed observation masked; paired call/result and raw artifact retained.', derivedRef: 'context:masked-result-old-001' }]);
const pruned = replaceField(replaceField(replaceField(replaceField(replaceField(pressured, 'revision', count(1)), 'budget', reducedBudget), 'reductions', list(reduction)), 'messages', list(modelContextMessage, [oldAssistant, maskedObservation, ...recentGroup], 1)), 'selectionManifest', maskedManifest);
const compactReduction = replaceField(reduction, 'policy', fixed('summary-old-complete-groups'));
const compacted = replaceField(replaceField(replaceField(pruned, 'messages', list(modelContextMessage, [summaryMessage.example, ...recentGroup], 1)), 'reductions', list(compactReduction)), 'selectionManifest', list(selection, [{ ...selection.example as object, sourceRef: 'history:old-complete-group', recordIds: ['assistant-old-001', 'result-old-001'], action: 'summarized', reason: 'Replace eligible complete older group in this request-local projection.', derivedRef: 'summary:history:r7:1' }, selection.example]));
const summaryWork = object({ workId: text('context-summary-001'), kind: fixed('context-management'), mainAgentRoundStarted: fixed(false), status: choice(['fixture-completed', 'failed', 'cancelled']), modelConfigurationRef: text('summary-model:demo'), usage: object({ accounting: fixed('synthetic-estimate'), inputTokens: count(300), outputTokens: count(50) }), sourceRevision: text('r7'), sourceScopeRef: text('context-scope:lina-main:v1'), sourceHistoryBranchRef: text('history:conversation-001:active'), unresolvedWorkRefs: list(text('approval:call-001'), []), persistence: fixed('request-local'), previousValidSnapshotPreserved: fixed(true) });
export const contextSnapshot = extend(object({ contextSnapshotRef: text('context:turn-001:round-001:r0'), identities, revision: count(0), immutable: fixed(true), modelContext: object({ instructions: list(instruction, [instruction.example], 1), messages: list(modelContextMessage, [user.example], 1), tools: list(tool), taskEvidence: list(evidence) }), sources: sourceBundle, canonicalHistoryRef: text('history:conversation-001:r7'), selectionManifest: list(selection), reductions: list(reduction, []), budget, artifactRefs: list(text('artifact:context-snapshot:001'), ['artifact:context-snapshot:001']), storage: fixed('reference-fixture-not-persisted'), grantsLaunchPermission: fixed(false) }), { scope: contextScope, generationVector, catalogBinding, stagedContributions: list(contribution, []), observations: list(observationProjection, []), hookInvocations: list(projectionHook, []), contributionDigests: list(text('sha256:fixture-skill-review'), []), generationsRecheckedBeforeReady: fixed(true), model: contextModelProjection, taskPlanProjection: sample(nullable(planningProjection), null), environmentProjection: sample(nullable(environmentProjection), null) });
const sourcesLoaded = replaceField(replaceField(replaceField(candidate, 'instructions', list(instruction, [])), 'taskEvidence', list(evidence, [])), 'tools', list(tool, []));
const instructionsBuilt = replaceField(sourcesLoaded, 'instructions', list(instruction));
const taskAdded = replaceField(instructionsBuilt, 'taskEvidence', list(evidence));
const field = (value: Payload, key: string): Payload => ({ schema: value.schema.properties![key], example: (value.example as Record<string, Json>)[key] });
const snapshotFrom = (projection: Payload, ref: string) => {
  let snapshot = replaceField(contextSnapshot, 'contextSnapshotRef', text(ref));
  snapshot = replaceField(snapshot, 'identities', field(field(projection, 'request'), 'identities'));
  for (const key of ['revision', 'sources', 'selectionManifest', 'reductions', 'budget', 'scope', 'generationVector', 'catalogBinding', 'stagedContributions', 'observations', 'hookInvocations', 'model', 'taskPlanProjection', 'environmentProjection']) snapshot = replaceField(snapshot, key, field(projection, key));
  let modelContext = field(snapshot, 'modelContext');
  for (const key of ['instructions', 'messages', 'tools', 'taskEvidence']) modelContext = replaceField(modelContext, key, field(projection, key));
  return replaceField(snapshot, 'modelContext', modelContext);
};
const revisedSnapshot = snapshotFrom(compacted, 'context:turn-001:round-001:r1');
const prunedSnapshot = snapshotFrom(pruned, 'context:turn-001:round-001:pruned-r1');
const secondRound = replaceField(replaceField(round, 'roundId', text('round-002')), 'index', count(2));
const feedbackState = replaceField(replaceField(turnState, 'limits', sample(limits, { roundsStarted: 1, maxRounds: 3, attempts: 1, retriesRemaining: 1 })), 'results', list(toolResult));
const feedbackRequest = replaceField(replaceField(replaceField(replaceField(contextPreparation, 'round', secondRound), 'state', feedbackState), 'identities', replaceField(identities, 'roundId', text('round-002'))), 'toolResultRefs', list(text('call-001:result')));
const feedbackPreparation = replaceField(feedbackRequest, 'preparationId', text('prepare:turn-001:round-002:r0'));
const feedbackCandidate = replaceField(replaceField(candidate, 'request', feedbackPreparation), 'messages', list(modelContextMessage, recentGroup, 1));
const feedbackSnapshot = snapshotFrom(feedbackCandidate, 'context:turn-001:round-002:r0');
const ready = object({ state: turnState, round, contextSnapshot, sourceRequest: contextPreparation });
const terminal = (reason: string) => object({ state: turnState, round, terminal: object({ turn, outcome: fixed('failed'), reason: text(reason), requiredWorkResolved: fixed(true) }), candidate: fixed(null), contextFailure: object({ code: text(reason), sourceRefs: list(text('instructions:lina:v1')), previousValidSnapshotPreserved: fixed(true), canonicalRecordsPreserved: fixed(true), modelAttemptLaunched: fixed(false) }) });
const local = object({ scopePolicy: contextScope, currentGenerationVector: generationVector, coordinatorDependencies: object({ memoryRuntime: fixed('unimplemented'), modelCapabilities: fixed('design-fixture'), credentialMaterialIncluded: fixed(false) }), authority, policyRef: text('context:recent-complete-groups:v1'), sourceAccessRef: text('source-access:lina-main:v1'), sourceRevisionCurrent: flag(true) });
const childScopeBase = replaceField(replaceField(replaceField(replaceField(replaceField(contextScope, 'agentId', text('lina-child-001')), 'historyBranchRef', text('history:child-001:active')), 'parentAgentId', text('lina-main')), 'inheritanceMode', fixed('selected-task-packet')), 'taskPacketRef', text('task-packet:child-001:v1'));
const childScope = replaceField(replaceField(childScopeBase, 'scopeRef', text('context-scope:child-001:v1')), 'excludedSourceRefs', list(text('history:parent-private:r9')));
const childTurn = replaceField(replaceField(turn, 'turnId', text('turn-child-001')), 'conversationId', text('conversation-child-001'));
const childRequestBase = replaceField(replaceField(replaceField(replaceField(contextPreparation, 'scope', childScope), 'identities', object({ agentId: text('lina-child-001'), conversationId: text('conversation-child-001'), turnId: text('turn-child-001'), roundId: text('round-001') })), 'preparationId', text('prepare:turn-child-001:round-001:r0')), 'historyRef', text('history:child-001:r0'));
const childRequest = replaceField(replaceField(childRequestBase, 'state', replaceField(turnState, 'turn', childTurn)), 'sourceGenerations', replaceField(replaceField(generationVector, 'scope', text('context-scope:child-001:v1')), 'history', text('history:child-001:r0')));
const activatedInstructionBase = replaceField(replaceField(replaceField(replaceField(replaceField(replaceField(replaceField(instruction, 'sectionId', text('instruction-skill-review')), 'kind', fixed('activated-skill')), 'precedence', count(3)), 'sourceRef', text('skill:docs-demo:v1:SKILL.md')), 'activationId', text('skill-activation:turn-001:1')), 'packageRevision', text('package:docs-demo:v1')), 'text', text('Review documents using permitted tools. Cite document IDs.'));
const activatedInstruction = replaceField(replaceField(replaceField(activatedInstructionBase, 'originRef', text('plugin:docs-demo:v1')), 'contributionDigest', text('sha256:fixture-skill-review')), 'hostTrustDecisionRef', text('instruction-trust:skill:docs-demo:v1'));
const skillCandidate = replaceField(replaceField(replaceField(instructionsBuilt, 'instructions', list(instruction, [instruction.example, activatedInstruction.example])), 'skillInventory', list(skillInventoryEntry)), 'stagedContributions', list(contribution, [{ ...contribution.example as object, status: 'loaded', type: 'activated-skill' }]));
const resourceEvidence = replaceField(replaceField(replaceField(replaceField(replaceField(evidence, 'kind', fixed('connector-resource')), 'sourceRef', text('docs://guide')), 'accountBindingRef', text('binding:docs-demo:user-demo:v1')), 'mimeType', text('text/markdown')), 'acquisitionRef', text('resource-attempt-001'));
const resourceCandidate = replaceField(replaceField(taskAdded, 'taskEvidence', list(evidence, [resourceEvidence.example])), 'stagedContributions', list(contribution, [{ ...contribution.example as object, type: 'connector-resource', sourceRef: 'docs://guide', status: 'loaded', acquisitionRef: 'resource-attempt-001' }]));
const promptEvidence = replaceField(replaceField(replaceField(replaceField(evidence, 'kind', fixed('connector-prompt')), 'sourceRef', text('prompt:review-document:r7')), 'suppliedRole', fixed('user')), 'acquisitionRef', text('prompt-attempt-001'));
const promptCandidate = replaceField(replaceField(taskAdded, 'taskEvidence', list(evidence, [promptEvidence.example])), 'stagedContributions', list(contribution, [{ ...contribution.example as object, type: 'connector-prompt', sourceRef: 'prompt:review-document:r7', status: 'loaded', acquisitionRef: 'prompt-attempt-001' }]));
const richObservations = list(observationProjection, [
 { ...observationProjection.example as object, callId: 'call-001', canonicalStatus: 'error', content: [{ type: 'text', artifactRef: 'artifact:call-001:error', mimeType: 'text/plain', visibleText: 'Document was not found.' }] },
 { ...observationProjection.example as object, callId: 'call-002', originalResultRef: 'call-002:result', content: [{ type: 'text', artifactRef: 'artifact:search:text', mimeType: 'text/plain', visibleText: 'Two matching documents.' }, { type: 'image', artifactRef: 'artifact:search:image', mimeType: 'image/png', visibleText: null }], structuredOutputRef: 'artifact:search:structured', rawArtifactRefs: ['artifact:search:raw'] },
]);
const richCalls: Json[] = [{ ...toolCall.example as object, name: 'docs_read', arguments: { documentId: 'missing-document' } }, { ...toolCall.example as object, callId: 'call-002', name: 'docs_search', arguments: { query: 'context architecture' } }];
const richMessages = list(modelContextMessage, [user.example, { ...assistantCall.example as object, calls: richCalls }, { ...observation.example as object, result: { callId: 'call-001', outcome: 'error', code: 'document_not_found', message: 'Document was not found.', correctable: true } }, { ...observation.example as object, recordId: 'result-002', callId: 'call-002', result: { callId: 'call-002', outcome: 'success', value: { documentIds: ['doc-1', 'doc-2'] } }, sourceRef: 'call-002:result', artifactRef: 'artifact:search:raw' }], 1);
const richResults = list(toolResult, [
 { callId: 'call-001', outcome: 'error', code: 'document_not_found', message: 'Document was not found.', correctable: true },
 { callId: 'call-002', outcome: 'success', value: { documentIds: ['doc-1', 'doc-2'] } },
]);
const richToolEntries = list(tool, ['read', 'search'].map(kind => ({ ...tool.example as object, toolId: `tool:docs-demo:${kind}`, name: `docs_${kind}`, schemaRef: `tool-schema:docs-${kind}:v1`, schemaDigest: `sha256:fixture-${kind}-schema`, description: kind === 'read' ? 'Read the selected document.' : 'Search documents.', permissionRef: `permissions:turn-001:docs-${kind}`, inputSchema: { type: 'object', properties: { [kind === 'read' ? 'documentId' : 'query']: { type: 'string', minLength: 1 } }, required: [kind === 'read' ? 'documentId' : 'query'], additionalProperties: false }, binding: { adapterRef: 'adapter:mcp-http:v1', connectionId: 'conn-docs-demo', accountId: 'account-demo', ownerId: 'user-demo', readinessGeneration: 3 } })));
const richCandidateBase = replaceField(replaceField(replaceField(replaceField(replaceField(replaceField(feedbackCandidate, 'request', replaceField(feedbackPreparation, 'state', replaceField(feedbackState, 'results', richResults))), 'messages', richMessages), 'observations', richObservations), 'tools', richToolEntries), 'catalogBinding', replaceField(catalogBinding, 'entries', richToolEntries)), 'budget', replaceField(replaceField(budget, 'observationTokens', count(240)), 'estimatedInputTokens', count(790)));

const richCandidate = replaceField(richCandidateBase, 'canonicalResultCompletionOrder', list(text('call-002'), ['call-002', 'call-001']));
const node = (id: string, reads: string[], writes: string[], rules: string[], outputs: ContractDefinition['outputs']): ContractDefinition => ({ nodeId: `lina-context-${id}`, context: local, contextSource: 'Coordinator-supplied dependencies: current authority, configured policy and permitted source revisions. This is separate from the modelContext projection.', reads, writes, rules, outputs });

/** Reference contracts for Context design playback; no real retrieval, token counting,
 * summarizer execution, persistence or model-quality measurement is claimed. */
export const contextAssemblyContracts: ContractDefinition[] = [
  node('scope', ['Correlated preparation and coordinator-approved source/inheritance policy'], ['Scope-bound preparation or classified denial'], ['Check agent, workspace, requester/account and history branch before source reads.', 'Consume an existing scope decision; never grant extra permission. Children use fresh history plus explicitly selected task packets.'], [
    output('context.scope-bound', 'Own-agent scope bound', object({ request: contextPreparation, scope: contextScope }), edges('scope-load'), 'Coordinator scope matches this agent and its own active history branch.'),
    output('context.scope-bound-child', 'Isolated child task scope', object({ request: childRequest, scope: childScope }), edges('scope-load'), 'Declared selected-task-packet inheritance excludes parent-private history before reads.'),
    output('context.scope-denied', 'Foreign history denied', extend(terminal('context_scope_denied'), { requestedSourceRef: text('history:parent-private:r9'), sourceReadOccurred: fixed(false) }), edges('scope-terminal'), 'Requested source exceeds the declared inheritance/account policy.'),
  ]),
  node('load', ['Agent/turn/round identities and allowed versioned source references'], ['Resolved source bundle or classified required-source failure'], ['Read only permitted sources. Keep unavailable optional sources in the manifest.', 'Never reset execution counters or replace authority. Raw history and tool artifacts remain canonical.', 'Resolve missing/stale Model capability metadata before preparing the snapshot. Matching dependency completion resumes this preparation once; metadata does not allocate an attempt.', 'Join catalog, selected skill and acquisition contributions by preparation/agent/turn/round/revision. Setup inventories are deliberately bound under coordinator scope; incoming contributions are not complete candidates.'], [
    output('model.capabilities-requested', 'Resolve versioned model capabilities before Context assembly', modelMetadataRequest, ['lina-model-edge-context-resolve'], 'Required binding/capability/budget revision is missing or stale. Resolve metadata only; retain this preparation and zero model attempts.'),
    output('context.model-capabilities-joined', 'Capability metadata joins the same preparation', extend(sourcesLoaded, { resolvedModelDependency: modelCapabilitiesReady }), edges('load-instructions'), 'The matching metadata dependency is resolved once, and its exact model/capability/budget profile continues through assembly.'),
    output('context.model-capabilities-unavailable', 'Required model metadata unavailable', extend(terminal('required_model_capability_unavailable'), { failedModelDependency: modelCapabilitiesUnavailable }), edges('load-terminal'), 'Model metadata is unsupported, unknown, denied, cancelled or expired; do not infer support or launch a provider.'),
    output('context.resource-requested', 'Acquire selected resource', extend(toolsResourceRequest, { retainedCandidate: candidate }), ['lina-tools-edge-context-resource-request'], 'Required selected resource is a reference; acquisition uses the same preparation and existing permission.'),
    output('context.prompt-requested', 'Acquire selected prompt', extend(toolsPromptRequest, { retainedCandidate: candidate }), ['lina-tools-edge-context-prompt-request'], 'Explicitly selected prompt arguments are available; supplied roles cannot be elevated.'),
    output('context.sources-reprepare-required', 'Source revisions changed', reprepare('source_revision_changed'), edges('load-reprepare'), 'A staged contribution no longer matches the generation vector; coordinator checks the bounded reprepare budget.'),
    output('context.sources-unstable', 'Reprepare bound exhausted', terminal('context_sources_unstable'), edges('load-terminal'), 'Source changes exhausted the separate reprepare budget without launching a model attempt.'),
    output('context.sources-loaded', 'Versioned sources loaded', sourcesLoaded, edges('load-instructions'), 'Required sources are available; optional sources can remain references.'),
    output('context.resource-sources-joined', 'Selected resource joins staged sources', replaceField(resourceCandidate, 'instructions', list(instruction, [])), edges('load-instructions'), 'Correlated acquisition return is joined to the retained preparation; external data is not an instruction authority.'),
    output('context.prompt-sources-joined', 'Selected prompt joins staged sources', replaceField(promptCandidate, 'instructions', list(instruction, [])), edges('load-instructions'), 'Prompt messages retain their supplied roles and exact preparation binding.'),
    output('context.optional-source-unavailable', 'Optional memory source unavailable', replaceField(sourcesLoaded, 'sources', list(source, [...sourceBundle.example as Json[], { ...source.example as object, sourceRef: 'memory:optional:r1', kind: 'memory', required: false, status: 'unavailable', trust: 'untrusted-evidence' }])), edges('load-instructions'), 'Policy permits a degraded projection with explicit optional-source omission.'),
    output('context.required-source-missing', 'Required source unavailable', extend(terminal('required_context_source_unavailable'), { unavailableSource: replaceField(replaceField(source, 'sourceRef', text('instructions:lina:v1')), 'status', fixed('unavailable')) }), edges('load-terminal'), 'Required instructions, history or task evidence cannot be loaded or accessed.'),
  ]),
  node('instructions', ['Versioned harness, agent and applicable project instructions'], ['Ordered instruction sections with origin and precedence'], ['Required instructions cannot be pruned or replaced by retrieved evidence.', 'Instruction precedence follows declared policy; evidence remains untrusted content.', 'Inventory metadata is distinct from activated instruction bodies. Retain activation/package/contribution provenance; selected MCP prompt roles cannot become higher-priority instructions.'], [output('context.instructions-built', 'Instructions ordered', instructionsBuilt, edges('instructions-history'), 'Required instruction versions are available.'), output('context.instructions-skill', 'Activated skill plus metadata inventory', skillCandidate, edges('instructions-history'), 'Only activated skill body is included below harness instructions; inventory stays metadata-only.')]),
  node('history', ['Canonical active-branch records and protected current input'], ['Selected complete conversation/tool groups and selection manifest'], ['Select complete call/result groups; do not fabricate assistant calls for orphan results.', 'Protect current input, unresolved work and required recent groups. Record excluded IDs and reasons without deleting originals.', 'Only the scoped active agent branch is eligible. Reject duplicate/conflicting terminal records; reverse completion order is not call order.'], [
    output('context.history-selected', 'Recent complete history selected', instructionsBuilt, edges('history-task'), 'Initial round selects current input.'),
    output('context.history-tool-feedback', 'Linked tool feedback selected', replaceField(replaceField(feedbackCandidate, 'taskEvidence', list(evidence, [])), 'tools', list(tool, [])), edges('history-task'), 'Selected assistant call-001 and tool result call-001 remain a correlated group.'),
  ]),
  node('task', ['Task attachments, retrieval results, memory results and notes permitted for this agent'], ['Evidence sections with origin/version and omission manifest'], ['Memory owns retrieval and durable writes. Context selects permitted results only.', 'Planning owns canonical task state; attach only the scoped bounded taskPlanProjection. Compaction never completes, drops or mutates canonical tasks.', 'Child task packets are future source forms; shared files never imply access to parent history.', 'Keep source/account namespace, MIME, digest, acquisition and supplied prompt role. Source priority hints cannot widen host access or requiredness.'], [output('context.task-added', 'Task evidence added', taskAdded, edges('task-tools'), 'Allowed task evidence is attached with source references.'),
    output('context.task-resource', 'Connector resource evidence', resourceCandidate, edges('task-tools'), 'Loaded connector resource keeps account binding, MIME and acquisition reference.'),
    output('context.task-prompt', 'Selected user-role prompt evidence', promptCandidate, edges('task-tools'), 'Selected prompt remains user-role evidence under host precedence policy.'),
    output('context.task-tool-feedback', 'Task evidence retains tool feedback', replaceField(feedbackCandidate, 'tools', list(tool, [])), edges('task-tools'), 'Carry selected call/result groups forward while adding task evidence.'),
    output('context.task-media', 'Media task references', replaceField(replaceField(taskAdded, 'messages', list(modelContextMessage, [mediaUser.example, assistantText.example], 1)), 'taskEvidence', list(evidence, [{ ...evidence.example as object, evidenceId: 'attachment-001', sourceRef: 'input-001:attachment-001', kind: 'attachment', text: null, artifactRef: 'artifact:input-001:image-001' }])), edges('task-tools'), 'Media remains an artifact reference; no extracted text is fabricated.'),
  ]),
  node('tools', ['Permitted catalog and linked selected call/result groups'], ['Versioned tool definitions and bounded observations'], ['Do not execute tools or grant permissions.', 'Preserve exact schema constraints, schema digest, stable tool ID, catalog/registry revision and owner/account binding. Empty catalog is valid; skill allowed-tools metadata is a hint, not a grant.'], [output('context.tools-prepared', 'Tool context prepared', candidate, edges('tools-observations'), 'Tool definitions resolve to permitted schemas; results keep their originating call identities.'),
    output('context.tools-feedback', 'Prepared tools retain linked feedback', feedbackCandidate, edges('tools-observations'), 'Retain selected assistant calls and their corresponding outcomes.'),
  ]),
  node('observations', ['Complete canonical correlated results, selected representation and provider content capabilities'], ['Rich projected observations or classified error; optional declared hook request'], ['Preserve original result status, call/batch identities, structured output and raw artifact references.', 'Unresolved effects remain warnings and reconciliation references; they never become successful results.', 'Projection hooks run once per input generation. Their return passes budget and validation; reduction does not reinvoke hooks.'], [
    output('context.observations-shaped', 'Initial context has no observations', candidate, edges('observations-budget'), 'No previous calls exist; an empty observation collection is valid.'),
    output('context.observations-feedback', 'Linked observations shaped', replaceField(feedbackCandidate, 'observations', list(observationProjection)), edges('observations-budget'), 'Canonical terminal call-001 is projected with stable identity and original artifacts.'),
    output('context.observations-rich', 'Known failure plus rich successful peer', richCandidate, edges('observations-budget'), 'Reverse completion order is projected by call identity; known failure and text/image/structured successful peer are retained.'),
    output('context.projection-hook-requested', 'Declared projection hook', contextProjectionHookRequest, edges('observations-hooks'), 'A permitted hook is selected for this candidate generation; mutation is declared and permission-neutral.'),
    output('context.observation-invalid', 'Orphan rich result rejected', extend(terminal('invalid_context_observation'), { issue: text('result references an absent canonical assistant call'), canonicalRecordsPreserved: fixed(true) }), edges('observations-terminal'), 'Required call/result identity or supported required media cannot be established.'),
  ]),
  node('budget', ['Candidate context including instructions, history, task evidence, tool schemas and provider overhead'], ['Fit decision, reduction request or terminal preparation failure'], ['Numbers are declared synthetic estimates, not measured tokenizer/provider usage.', 'Reserve output capacity and margin. Stop when protected content alone cannot fit or reduction attempts are exhausted.', 'Include activated skill bodies, inventory metadata, prompt messages, media and hook-added content; re-budget every changed projection. Acquisition and summary work usage is separate from main model attempts.', 'Budget against the exact accepted Model binding/capabilities/budget-profile revision, including effective reasoning allocation and codec overhead. Changing these requires bounded reprepare.'], [
    output('context.budget-fits-rich', 'Rich correlated result projection fits', richCandidate, edges('budget-validate'), 'Rich image/structured observations consume the declared synthetic estimate while retaining both required outcomes.'),
    output('context.budget-fits', 'Estimated context fits', candidate, edges('budget-validate'), 'Estimated input 550 is below available input 800.'),
    output('context.budget-fits-invalid', 'Fits budget but has an orphan result', orphanCandidate, edges('budget-validate'), 'Token capacity permits preparation, but transcript relationship validation must reject the unmatched call-001 result.'),
    output('context.budget-fits-after-prune', 'Pruned projection fits', pruned, edges('budget-validate'), 'Revision 1 retains masking manifest and protected call/result groups.'),
    output('context.budget-fits-after-compact', 'Compacted projection fits', object({ candidate: compacted, summaryWork }), edges('budget-validate'), 'Recheck the summarized revision without losing context-management evidence.'),
    output('context.budget-fits-feedback', 'Tool feedback fits', feedbackCandidate, edges('budget-validate'), 'Second round retains canonical tool observations and prior counters.'),
    output('context.budget-prune', 'Pruning required', pressured, edges('budget-prune'), 'Estimated input 950 exceeds 800 and pruning remains permitted.'),
    output('context.budget-compact', 'Compaction required', pressured, edges('budget-compact'), 'Eligible older complete groups exist and policy permits summarization.'),
    output('context.protected-too-large', 'Protected context cannot fit', extend(terminal('protected_context_too_large'), { rejectedBudget: sample(pressuredBudget, { ...pressuredBudget.example as object, protectedEstimatedTokens: 850 }) }), edges('budget-terminal'), 'Required instructions, current input or protected groups alone exceed available capacity.'),
    output('context.reduction-exhausted', 'Reduction attempts exhausted', extend(terminal('context_reduction_exhausted'), { rejectedBudget: sample(pressuredBudget, { ...pressuredBudget.example as object, reductionAttempts: 2 }) }), edges('budget-terminal'), 'The bounded reduction policy cannot produce a fitting projection.'),
  ]),
  node('prune', ['Candidate projection and deterministic pruning policy'], ['Revised projection with omission/masking manifest'], ['Never remove required instructions/current input/protected groups or break call/result correlation.', 'Change the projection revision, preserve canonical evidence and recheck the complete budget.', 'A no-progress result consumes an attempt; bounded budget logic prevents infinite loops.'], [
    output('context.pruned', 'Projection pruned', pruned, edges('prune-budget'), 'Fixture masking reduces estimated input from 950 to 650; revision becomes 1 with protected recent call/result group unchanged.'),
    output('context.prune-no-progress', 'Pruning made no progress', replaceField(pressured, 'budget', sample(pressuredBudget, { ...pressuredBudget.example as object, reductionAttempts: 1 })), edges('prune-budget'), 'No eligible records can be removed; the attempt budget advances without publishing a new snapshot.'),
  ]),
  node('compact', ['Eligible older complete groups, preserved current/recent groups and prior valid summary'], ['Derived request-local summary with provenance or explicit failure'], ['Summary is context-management work, not another main-agent reasoning round.', 'Validate summary and source revision before replacing the projection; failed/cancelled work preserves the prior valid view.', 'Summary provenance retains original record/source refs, exact agent scope/history branch/revision and unresolved work. No long-term memory write or canonical-history deletion occurs.'], [
    output('context.compacted', 'History compacted', object({ candidate: compacted, summaryWork }), edges('compact-budget'), 'Scripted summary fixture reduces estimated input to 650 and preserves current user input.'),
    output('context.summary-failed', 'Summary failed', extend(terminal('context_summary_failed'), { summaryWork: replaceField(summaryWork, 'status', fixed('failed')) }), edges('compact-terminal'), 'No permitted fallback or usable summary exists; prior valid snapshot remains unchanged.'),
    output('context.summary-cancelled', 'Summary cancelled', extend(terminal('context_summary_cancelled'), { summaryWork: replaceField(summaryWork, 'status', fixed('cancelled')) }), edges('compact-terminal'), 'Cancellation prevents publishing a partial summary.'),
  ]),
  node('validate', ['Ordered instructions/messages/tools, selection provenance and Model Interface encoding constraints'], ['Non-mutating valid candidate or classified invalid context'], ['Check required content, source revisions and complete tool call/result correlation.', 'Validation does not repair or mutate content. Any future repair must return through budget checking.', 'Check scope/generation vector, exact catalog/schema bindings, instruction trust, required MIME capabilities and declared hook mutations. Hooks cannot invent canonical calls or widen permissions.'], [
    output('context.validated-rich', 'Rich call/result projection valid', richCandidate, edges('validate-publish'), 'Both canonical outcomes remain paired to real selected calls and exact tool catalog bindings.'),
    output('context.validated', 'Context structurally valid', candidate, edges('validate-publish'), 'Required content and call/result relationships pass the declared validation policy.'),
    output('context.validated-after-prune', 'Pruned context valid', pruned, edges('validate-publish'), 'Validation does not mutate revision 1.'),
    output('context.validated-after-compact', 'Compacted context valid', object({ candidate: compacted, summaryWork }), edges('validate-publish'), 'Summary provenance and protected groups validate without mutation.'),
    output('context.validated-feedback', 'Tool feedback valid', feedbackCandidate, edges('validate-publish'), 'Call/result identity correlation remains complete for round-002.'),
    output('context.catalog-inconsistent', 'Catalog projection mismatch', extend(terminal('context_catalog_mismatch'), { toolId: text('tool:docs-demo:search'), schemaDigest: text('sha256:fixture-search-schema'), issue: fixed('input-schema-constraint-lost'), candidateMutated: fixed(false) }), edges('validate-terminal'), 'Projection lost query.minLength or executable binding identity; validation refuses silent reconstruction.'),
    output('context.scope-inconsistent', 'Foreign memory evidence rejected', extend(terminal('context_scope_mismatch'), { rejectedSourceRef: text('memory:another-workspace:private:r1'), sourceReadAuthorized: fixed(false), candidateMutated: fixed(false) }), edges('validate-terminal'), 'Candidate includes a source outside its bound namespace/account scope.'),
    output('context.required-media-unsupported', 'Required media cannot be encoded', extend(terminal('context_media_unsupported'), { artifactRef: text('artifact:input-001:image-001'), mimeType: fixed('image/png'), required: fixed(true), capabilityRef: text('model-capabilities:text-only:v1') }), edges('validate-terminal'), 'Model capability snapshot cannot represent required image evidence and no declared fallback exists.'),
    output('context.invalid', 'Context invalid', extend(terminal('invalid_model_context'), { validationIssues: list(object({ code: fixed('orphan_tool_result'), recordId: text('result-orphan-001'), callId: text('call-missing-001'), expected: text('An actual selected canonical assistant call with the same call ID.') }), undefined, 1) }), edges('validate-terminal'), 'Orphan tool result, missing required instruction, stale source revision or incompatible encoding is detected.'),
  ]),
  node('publish', ['Valid bounded projection and source/selection/reduction evidence'], ['Immutable prepared snapshot for the exact agent/turn/round/revision'], ['Retain exact snapshot content/reference artifacts; a hash alone is not reconstructible evidence.', 'Fixture storage does not claim persistence. Publication grants no model launch authority.', 'Prepare round rechecks authority and stop intent; retries can reuse a valid snapshot, overflow recovery requires a new revision.', 'Retain accepted Model binding/capability/budget profile and scoped opaque replay references without exposing private credential material. Required incompatible continuation cannot be stripped silently.', 'Recheck source/catalog/policy/skill/plugin/model generation vector before returning readiness. Invalidated candidates reprepare within a separate bounded budget; no model attempt starts and counters remain unchanged.'], [
    output('context.reprepare-required', 'Generations changed before publication', reprepare('generation_vector_changed'), edges('publish-reprepare'), 'Account, source, plugin, catalog or policy generations changed after validation; retain logical round and retry counters.'),
    output('context.ready-rich', 'Rich correlated context snapshot', object({ state: field(field(richCandidate, 'request'), 'state'), round: secondRound, contextSnapshot: snapshotFrom(richCandidate, 'context:turn-001:round-002:rich-r0'), sourceRequest: field(richCandidate, 'request') }), edges('publish-prepare'), 'Publish the exact rich candidate without losing correlated errors, successful peers, structured output or original artifacts.'),
    output('context.ready', 'Prepared context snapshot', ready, edges('publish-prepare'), 'Validated snapshot is returned for the existing logical round without changing counters.'),
    output('context.ready-pruned', 'Pruned context snapshot', replaceField(ready, 'contextSnapshot', prunedSnapshot), edges('publish-prepare'), 'Publish the exact masked projection with original artifact references.'),
    output('context.ready-feedback', 'Second-round context snapshot', object({ state: feedbackState, round: secondRound, contextSnapshot: feedbackSnapshot, sourceRequest: feedbackPreparation }), edges('publish-prepare'), 'Return round-002 context without resetting roundsStarted=1, attempts=1 or retained call-001 result.'),
    output('context.ready-revised', 'Revised compacted context snapshot', extend(replaceField(ready, 'contextSnapshot', revisedSnapshot), { summaryWork }), edges('publish-prepare'), 'Request-local summary replaces the eligible older complete group, retains the current input and recent protected call/result group, and publishes revision 1 for the same round.'),
  ]),
];

// Coordinator examples expose scope-dependent policy without granting child runtime support.
contextAssemblyContracts.find(contract => contract.nodeId === 'lina-context-scope')!.contextExamples = [{ label: 'Selected task-packet child source policy', value: replaceField(local, 'scopePolicy', childScope) }];
