import { environmentProjection } from './environmentRecords';
import { choice, count, fixed, flag, list, nullable, object, sample, text, type Payload, type Json } from './schema';
import { modelBinding, modelCapabilities, modelBudgetProfile, modelContinuation } from './modelRecords';

/** Correlated request-local records. References are fixtures, never credentials or permission grants. */
export const extendContextRecord = (value: Payload, fields: Record<string, Payload>) => object({ ...Object.fromEntries(Object.entries(value.schema.properties!).map(([key, schema]) => [key, { schema, example: (value.example as Record<string, Json>)[key] }])), ...fields });
export const contextScope = object({ scopeRef: text('context-scope:lina-main:v1'), workspaceId: text('workspace-demo'), requesterId: text('user-demo'), agentId: text('lina-main'), historyBranchRef: text('history:conversation-001:active'), allowedSourceRoots: list(text('workspace-demo:project')), allowedMemoryNamespaces: list(text('workspace-demo:shared')), accountBindingRefs: list(text('binding:docs-demo:user-demo:v1')), permissionGeneration: count(4), parentAgentId: sample(nullable(text('lina-parent')), null), inheritanceMode: choice(['own-history', 'selected-task-packet', 'explicit-selected-parent-records', 'explicit-transcript-fork']), taskPacketRef: sample(nullable(text('task-packet:child-001:v1')), null), excludedSourceRefs: list(text('history:parent-private:r9'), []), scopeDecisionRef: text('scope-decision:lina-main:1'), grantsAdditionalPermission: fixed(false) });
export const generationVector = object({ history: text('history:conversation-001:r7'), sourceManifest: text('sources:prepare-001:v1'), catalog: text('catalog:demo:7'), registry: count(7), permission: count(4), scope: text('context-scope:lina-main:v1'), skills: text('skills:demo:2'), plugins: text('plugins:demo:3'), modelCapabilities: text('model-capabilities:demo:v1'), modelBinding: text('model-binding:demo:g1'), modelBudgetProfile: text('model-budget:demo:v1'), modelCodec: text('codec:chat:v1') });
const argumentSchema: Payload = { schema: { type: 'object', additionalProperties: true, description: 'The original JSON Schema object retained verbatim; validated by the registry dialect, never reconstructed by Context.' }, example: { type: 'object', properties: { expression: { type: 'string', minLength: 1 } }, required: ['expression'], additionalProperties: false } };
export const catalogEntry = object({ toolId: text('tool:builtin:calculator'), name: text('calculator'), schemaRef: text('tool-schema:calculator:v1'), schemaRevision: text('v1'), schemaDigest: text('sha256:fixture-calculator-schema'), description: text('Evaluate an arithmetic expression.'), permissionRef: text('permissions:turn-001:calculator'), inputSchema: argumentSchema, binding: object({ adapterRef: text('adapter:builtin:v1'), connectionId: sample(nullable(text('conn-docs-demo')), null), accountId: sample(nullable(text('account-docs-demo')), null), ownerId: text('user-demo'), readinessGeneration: count(1) }) });
export const catalogBinding = object({ catalogRef: text('tools:lina:v1'), catalogRevision: text('catalog:demo:7'), registryGeneration: count(7), entries: list(catalogEntry), excludedToolIds: list(text('tool:excluded'), []), selectionPolicyRef: text('tool-selection:permitted:v1'), permissionGeneration: count(4), grantsExecutionPermission: fixed(false) });
export const contribution = object({ contributionId: text('contribution:skill-review:v1'), sourceRef: text('skill:docs-demo:v1:SKILL.md'), sourceRevision: text('v1'), digest: text('sha256:fixture-skill-review'), type: choice(['catalog', 'skill-inventory', 'activated-skill', 'skill-resource', 'connector-resource', 'connector-prompt', 'memory', 'history']), preparationId: text('prepare:turn-001:round-001:r0'), agentId: text('lina-main'), turnId: text('turn-001'), roundId: text('round-001'), revision: count(0), bindingMode: choice(['active-preparation', 'coordinator-bound-inventory']), status: choice(['staged', 'loaded', 'referenced', 'pending', 'denied', 'omitted']), required: flag(false), accountBindingRef: sample(nullable(text('binding:docs-demo:user-demo:v1')), null), acquisitionRef: sample(nullable(text('acquisition:resource-001')), null), omissionReason: sample(nullable(text('optional-source-unavailable')), null) });
export const skillInventoryEntry = object({ skillId: text('skill:docs-demo'), revision: text('v1'), description: text('Review documents and cite source records.'), metadataOnly: fixed(true), instructionBodyIncluded: fixed(false), packageRef: text('package:docs-demo:v1') });
export const observationProjection = object({ callId: text('call-001'), batchId: text('batch-001'), agentId: text('lina-main'), canonicalStatus: choice(['success', 'error', 'denied', 'skipped', 'cancelled', 'unknown']), originalResultRef: text('call-001:result'), content: list(object({ type: choice(['text', 'image', 'audio', 'resource-link']), artifactRef: text('artifact:call-001:text'), mimeType: text('text/plain'), visibleText: sample(nullable(text('4')), '4') })), structuredOutputRef: sample(nullable(text('artifact:search:structured')), null), childResultRef: sample(nullable(text('child-result:001')), null), representation: choice(['inline', 'artifact-reference', 'masked']), omissionReason: sample(nullable(text('unsupported-optional-media')), null), rawArtifactRefs: list(text('artifact:call-001:raw')), reconciliationRef: sample(nullable(text('reconcile:write:1')), null), canonicalRecordsPreserved: fixed(true) });
export const projectionHook = object({ invocationId: text('hook:prepare-001:g0:projection'), hookRef: text('plugin-hook:docs:context:v1'), inputGeneration: count(0), invocationCountForGeneration: fixed(1), inputDigest: text('sha256:fixture-candidate-before'), outputDigest: sample(nullable(text('sha256:fixture-candidate-after')), null), declaredMutation: choice(['append-evidence', 'mask-observation', 'none']), grantsAdditionalPermission: fixed(false), mutatesCanonicalHistory: fixed(false) });

/** Accepted metadata and opaque replay are part of the exact published request view. */
export const contextModelProjection = object({ binding: modelBinding, capabilities: modelCapabilities, budgetProfile: modelBudgetProfile, opaqueContinuations: list(modelContinuation, []), capabilityDependencyId: text('context:model-capabilities:prepare-001'), capabilityDependencyResolved: fixed(true), metadataSource: fixed('versioned-design-fixture'), providerInvokedDuringPreparation: fixed(false) });

/** Bounded observed workspace/runtime metadata; never credentials or authority. */
export const contextEnvironmentProjection = environmentProjection;
