/** Environment services preserve original request identity. Graph branches are
 * design contracts, not evidence that Studio opened a real backend. */
import { ENVIRONMENT_EDGES, ENVIRONMENT_STATE_ROUTES } from '../environmentBlock';
import { choice, count, fixed, flag, list, nullable, object, output, replaceField, sample, text, union, type ContractDefinition, type Json, type Payload } from './schema';
import { environmentIdentity, environmentTarget, environmentProfile, sandboxEnvironmentProfile, remoteEnvironmentProfile, environmentWorkspace, environmentLease, environmentBinding, environmentCommand, environmentFileRequest, environmentOperationIntent, environmentProcess, environmentProcessControl, environmentOutput, environmentObservation, environmentStagingManifest, environmentArtifact, environmentReconciliation, environmentRelease, environmentChildBinding, environmentProjection, environmentPlacement, environmentLocalContext } from './environmentRecords';
const phases = ['profile', 'workspace', 'acquire', 'ready', 'stage', 'files', 'start', 'process', 'collect', 'artifacts', 'reconcile', 'release'];
export const environmentStatuses: Record<string, string[]> = {
 profile: ['resolved', 'bypass', 'refused', 'unavailable'], workspace: ['bound', 'conflict', 'invalid', 'unavailable'],
 acquire: ['attached', 'created', 'reused', 'provisioning', 'failed', 'unknown'], ready: ['ready', 'stale', 'missing-dependency', 'unsupported', 'unavailable'],
 stage: ['verified', 'skipped', 'partial', 'conflict', 'failed', 'unknown'], files: ['success', 'conflict', 'rejected', 'unsupported', 'cancelled', 'unknown'],
 start: ['running', 'success', 'known-unstarted', 'rejected', 'unknown'], process: ['running', 'progress', 'exited', 'cancelled', 'unsupported', 'stale', 'unknown'],
 collect: ['progress', 'success', 'error', 'rejected', 'cancelled', 'unknown'], artifacts: ['retained', 'pending', 'partial', 'failed', 'unknown'],
 reconcile: ['pending-provision', 'running', 'terminal', 'proven-unstarted', 'removed', 'unavailable', 'stale', 'unknown'], release: ['released', 'retained', 'already-released', 'deferred', 'removed', 'failed', 'unknown'],
};
const rules: Record<string, string[]> = {
 profile: ['Resolve trusted configuration independently of whole-harness deployment. Local current workspace is the default and claims no hard isolation.', 'Pure and external-service operations bypass workspace routing. Stdio servers and in-process plugins retain their configured placement.', 'Required sandbox unavailability never authorizes host fallback. Supported capabilities never grant operation permission.'],
 workspace: ['Resolve canonical targets and symlink/mount access policy before permission and Tools conflict scheduling.', 'Commands and file tools use the same filesystem binding. A local cwd is not shell confinement.', 'Attached user roots are not disposable. Shared writable backing files have one conflict identity even across containers.'],
 acquire: ['Record original acquisition intent before creating managed resources. Same identity with changed fingerprint conflicts.', 'Unknown provisioning inspects the original resource; do not create another instance blindly.', 'Each agent owns a lease; inherited environment identity may stay shared. Lease release is different from destruction.'],
 ready: ['Validate actual environment/workspace generation and supported capabilities before use.', 'Requested, supported and enforced restrictions are separate facts. Missing dependency never triggers unadmitted arbitrary installation.', 'Changed mount/target binding invalidates prior authorization; capability readiness cannot issue a launch permit.'],
 stage: ['Import only admitted original custody or selected artifact references into authorized destinations.', 'Keep originals, digest, ordering and immutable custody separate from working copies. Partial or unknown copy is not verified staging.', 'Copy, read-only mount and shared-file binding have distinct access/lifetime semantics.'],
 files: ['Validate actual resolved root, symlink/mount policy and immutable final arguments at effect boundary.', 'An allowed sandbox target cannot be replaced with a host read/write. Unsupported backend file access is explicit.', 'Expected digest/revision conflicts cannot silently overwrite. Unknown write is reconciled under original identity.'],
 start: ['Persist original call/attempt/launch intent and recheck exact environment generation, cancellation and authorization before physical launch.', 'Yield does not establish detached ownership. Environment variables use an explicit private allowlist.', 'Lost launch acknowledgement cannot create replacement command. Short successful commands can return a terminal observation directly.'],
 process: ['Control exact owned process identity and backend generation; PID alone cannot establish identity after restart.', 'Poll/log/stdin/signal/terminate/PTY resize require declared capability and authorization. Output cursors reject stale updates.', 'Cancellation request does not prove exit; exit does not prove filesystem effects absent. Detached work retains explicitly admitted supervisor ownership.'],
 collect: ['Return one correlated per-operation observation to the original requester; Tools owns whole-batch joins.', 'Progress is not terminal. Process exit, effect certainty, artifact custody and Planning acceptance are separate facts.', 'Preserve partial output, redaction/truncation and raw safe references. Context reads return to Context, not tool completion.'],
 artifacts: ['Export selected authorized files into explicit retained custody before destroying a managed workspace.', 'A pathname or successful process exit cannot establish retained artifact custody.', 'Publication is not user delivery. Unknown transfer keeps original identity and required cleanup obligations.'],
 reconcile: ['Inspect original acquisition/process/transfer/cleanup when backend supports it. Reconnect is not relaunch.', 'A missing handle or preserved files do not prove no effect or process survival.', 'Proven unstarted may permit a new admitted attempt through Tools/Safety; this node grants no launch itself.'],
 release: ['Release only exact owned lease/resources. Never delete an attached user project or terminate unrelated processes.', 'Managed destruction requires no other active owner, accounted work and required artifact custody. Child cleanup cannot destroy parent resources.', 'Stop, lease release and destruction differ. Unknown cleanup remains inspectable by original identity and must not fabricate removed status.'],
};
export const environmentExecutionContracts: ContractDefinition[] = phases.map(phase => ({ nodeId: `lina-environment-${phase}`, context: environmentLocalContext, contextSource: 'Trusted owner-scoped configuration and deterministic coordinator records; no live backend or isolation guarantee.', reads: ['Exact original requester, operation identity, binding generation and owner', 'Phase-specific profile, workspace, capability, lease, process or custody evidence'], writes: ['Correlated phase receipt or request to existing Safety/State owner'], rules: rules[phase], outputs: [] }));
export function environmentPhasePayload(phase: string, status: string): Payload {
 const fields: Record<string, Payload> = { identity: environmentIdentity, target: environmentTarget, phase: fixed(phase), status: fixed(status), evidenceSource: fixed('design-fixture'), grantsActionPermission: fixed(false), hostFallback: fixed(false) };
 if (phase === 'profile') { fields.profile = ['resolved', 'bypass'].includes(status) ? union(environmentProfile, sandboxEnvironmentProfile, remoteEnvironmentProfile) : fixed(null); fields.placement = environmentPlacement; fields.workspaceRequired = fixed(status !== 'bypass'); }
 if (phase === 'workspace') { fields.workspace = status === 'bound' ? environmentWorkspace : fixed(null); fields.childAssignment = environmentChildBinding; fields.targetUsedForAdmission = fixed(status === 'bound'); }
 if (phase === 'acquire') { fields.lease = replaceField(environmentLease, 'status', fixed(status === 'unknown' ? 'unknown' : status === 'provisioning' ? 'provisioning' : status === 'failed' ? 'released' : 'active')); fields.acquisitionId = text('acquire:environment:001'); fields.acquisitionFingerprint = text('sha256:fixture-acquire-project'); fields.backendCreated = fixed(status === 'created'); fields.inspectOriginalRequired = fixed(status === 'unknown'); fields.replacementWhileUnknown = fixed(false); }
 if (phase === 'ready') { fields.binding = status === 'ready' ? environmentBinding : fixed(null); fields.projection = status === 'ready' ? environmentProjection : fixed(null); fields.requiredCapability = text('filesystem'); fields.setupMutationAdmitted = flag(false); fields.installDependencyAutomatically = fixed(false); }
 if (phase === 'stage') { fields.manifest = replaceField(environmentStagingManifest, 'status', fixed(status === 'verified' || status === 'skipped' ? 'verified' : status === 'conflict' ? 'failed' : status)); const entry = ((environmentStagingManifest.example as Record<string, Json>).entries as Json[])[0] as Record<string, Json>; fields.manifest = replaceField(fields.manifest, 'entries', { schema: environmentStagingManifest.schema.properties!.entries, example: [{ ...entry, status: status === 'verified' || status === 'skipped' ? 'verified' : status === 'partial' ? 'pending' : status === 'conflict' ? 'conflict' : status, stagedDigest: status === 'verified' || status === 'skipped' ? entry.stagedDigest : entry.stagedDigest }] }); fields.originalCustodyPreserved = fixed(true); fields.copyVerified = fixed(status === 'verified'); }
 if (phase === 'files') { fields.request = environmentFileRequest; fields.observation = replaceField(replaceField(replaceField(environmentObservation, 'status', fixed(status === 'success' ? 'success' : status === 'cancelled' ? 'cancelled' : status === 'unknown' ? 'unknown' : 'rejected')), 'effectCertainty', fixed(status === 'unknown' ? 'unknown' : 'known')), 'effect', fixed(status === 'unknown' ? 'unknown' : status === 'success' ? 'none' : 'not-started')); fields.bindingRechecked = fixed(true); }
 if (phase === 'start') { fields.intent = replaceField(environmentOperationIntent, 'phase', fixed(status === 'running' || status === 'success' ? 'started' : status === 'unknown' ? 'unknown' : 'known-unstarted')); fields.command = environmentCommand; fields.process = status === 'running' ? environmentProcess : fixed(null); fields.immediateResult = status === 'success' ? environmentObservation : fixed(null); fields.launchPermitRechecked = fixed(status === 'running' || status === 'success'); fields.physicalLaunchProven = fixed(status === 'running' || status === 'success'); }
 if (phase === 'process') { fields.process = replaceField(environmentProcess, 'state', fixed(status === 'exited' ? 'exited' : status === 'cancelled' ? 'cancelled' : status === 'unknown' ? 'unknown' : 'running')); fields.control = environmentProcessControl; fields.output = environmentOutput; if (status === 'exited') fields.process = replaceField(fields.process, 'exitCode', count(0)); if (status === 'cancelled') fields.process = replaceField(fields.process, 'signal', text('SIGTERM')); fields.exitObserved = fixed(status === 'exited' || status === 'cancelled'); fields.effectCertainty = choice(['known', 'unknown'], status === 'unknown' || status === 'running' ? 'unknown' : 'known'); fields.eventSequence = count(1); }
 if (phase === 'collect') { fields.observation = replaceField(replaceField(replaceField(replaceField(environmentObservation, 'status', fixed(status)), 'terminal', fixed(status !== 'progress')), 'effectCertainty', fixed(status === 'unknown' ? 'unknown' : 'known')), 'effect', fixed(status === 'unknown' ? 'unknown' : status === 'rejected' ? 'not-started' : status === 'progress' ? 'unknown' : 'performed')); fields.nextModelRoundAllowedByThisReceipt = fixed(false); fields.taskAcceptedByThisReceipt = fixed(false); }
 if (phase === 'artifacts') { fields.artifact = replaceField(replaceField(replaceField(environmentArtifact, 'status', fixed(status)), 'storageRef', status === 'retained' ? text('artifact-store:report:001') : fixed(null)), 'transferReceiptRef', status === 'retained' ? text('transfer-receipt:report:001') : fixed(null)); fields.cleanupEligibleFromExport = fixed(status === 'retained'); }
 if (phase === 'reconcile') { fields.receipt = replaceField(replaceField(environmentReconciliation, 'status', fixed(status)), 'effectCertainty', fixed(status === 'proven-unstarted' || status === 'removed' ? 'known' : 'unknown')); fields.reuseOriginalHandle = fixed(status === 'running'); fields.retryRequiresNewAdmission = fixed(status === 'proven-unstarted'); fields.noEffectProven = fixed(status === 'proven-unstarted'); fields.processTerminalIsNoEffectProof = fixed(false); }
 if (phase === 'release') { fields.receipt = replaceField(environmentRelease, 'status', fixed(status)); if (status === 'removed') fields.receipt = replaceField(replaceField(fields.receipt, 'lease', replaceField(environmentLease, 'resourceOwnership', fixed('managed'))), 'requestedAction', fixed('cleanup-managed')); fields.managedDestructionObserved = fixed(status === 'removed'); fields.resourceOwnership = fixed(status === 'removed' ? 'managed' : 'attached-user'); fields.requiredArtifactsRetained = fixed(status !== 'deferred'); fields.otherLeaseActive = fixed(status === 'deferred'); }
 return object(fields);
}
type Edge = { id: string; source: string; target: string };
/** Contract example correlation must follow a non-tool source owner throughout
 * nested phase evidence as well as the top-level continuation envelope. */
function scopedExample(value: Payload, identity: Payload): Payload {
 const walk = (item: Json): Json => {
  if (Array.isArray(item)) return item.map(walk);
  if (item && typeof item === 'object') {
   if ('runId' in item && 'operationId' in item && 'requesterNodeId' in item) return identity.example;
   return Object.fromEntries(Object.entries(item).map(([key, child]) => [key, walk(child)]));
  }
  return item;
 };
 return { schema: value.schema, example: walk(value.example) };
}

function environmentStatePayload(edge: Edge, outcome?: string): Payload | undefined {
 const route = ENVIRONMENT_STATE_ROUTES.find(item => item.id === edge.id || item.returnId === edge.id);
 if (!route) return undefined;
 const short = route.id.replace('lina-environment-edge-', '').replace(/-state-(record|load)$/, '');
 const transactionPhase = short === 'acquire-inspect' ? 'acquire' : short;
 const records: Record<string, Payload> = { workspace: environmentBinding, acquire: environmentLease, 'acquire-inspect': environmentLease, stage: environmentStagingManifest, files: environmentOperationIntent, start: environmentOperationIntent, process: environmentProcess, collect: environmentObservation, artifacts: environmentArtifact, reconcile: environmentReconciliation, release: environmentRelease };
 const fields: Record<string, Payload> = { identity: environmentIdentity, target: environmentTarget, requesterNodeId: fixed(route.source), returnToNodeId: fixed(route.returnTarget), requestPhase: fixed(route.phase), transactionId: text(`environment-tx:${transactionPhase}:001`), fingerprint: text(`sha256:environment:${transactionPhase}:001`), expectedRevision: count(1), expectedOwnerGeneration: count(2), record: records[short] ?? environmentBinding, persistenceOwner: fixed('state'), environmentSemanticsOwner: fixed('environment'), containsCredentials: fixed(false), replayExternalEffects: fixed(false) };
 if (edge.source.startsWith('lina-state-')) { fields.storageOutcome = fixed(outcome ?? 'found'); fields.acknowledgedRevision = ['applied', 'already-applied'].includes(outcome ?? '') ? count(2) : fixed(null); fields.originalIdentityVerified = fixed(true); fields.inspectBeforeRetry = fixed(['unknown', 'still-unknown'].includes(outcome ?? '')); fields.recordAbsenceProvesEffectAbsent = fixed(false); fields.storageReceiptGrantsLaunch = fixed(false); }
 else { fields.command = fixed(route.phase); fields.retryUsesOriginalIdentity = fixed(true); fields.newMutationWhileUnknown = fixed(false); }
 return object(fields);
}
function handoff(edge: Edge, outcome?: string): Payload {
 const stored = environmentStatePayload(edge, outcome); if (stored) return stored;
 const short = edge.id.replace('lina-environment-edge-', '');
 const fields: Record<string, Payload> = { identity: environmentIdentity, target: environmentTarget, originalRequesterNodeId: text(edge.source), returnToNodeId: text(edge.target), originalOperationRetained: fixed(true), grantsActionPermission: fixed(false), actualBackendExercised: fixed(false) };
 if (short === 'acquire-reconcile' && outcome === 'provisioning') { fields.receipt = replaceField(environmentReconciliation, 'status', fixed('pending-provision')); fields.resourceExistenceCertainty = fixed('known'); fields.provisioningStillPending = fixed(true); fields.replacementLaunchAllowed = fixed(false); }
 else if (short.includes('authorize') || short.includes('safety') || short.includes('policy')) { fields.intent = environmentOperationIntent; fields.reviewedEnvironmentTarget = environmentTarget; fields.currentEnvironmentTarget = environmentTarget; fields.mountRevisionMustMatch = fixed(true); fields.authorizationOwner = fixed('safety'); fields.environmentCanIssuePermit = fixed(false); fields.launchPermitRef = short.startsWith('authorize-') ? text('launch-permit:workspace:001') : fixed(null); fields.exactArgumentsDigest = text('sha256:fixture-workspace-command'); }
 else if (short.includes('subagents')) { fields.assignment = environmentChildBinding; fields.binding = environmentBinding; fields.childOwnsDistinctLease = fixed(true); fields.sharedEnvironmentIdentityUnchanged = fixed(true); fields.detachmentRequiresAdmittedOwnerChange = fixed(true); }
 else if (short.includes('context')) { const contextIdentity = replaceField(replaceField(replaceField(replaceField(environmentIdentity, 'origin', fixed('context-source')), 'callId', fixed(null)), 'batchId', fixed(null)), 'requesterNodeId', fixed('lina-context-load')); fields.identity = contextIdentity; fields.preparationId = text('prepare:turn-001:round-001:r0'); fields.dependencyId = text('context-source:workspace:001'); fields.projection = environmentProjection; fields.sourceRequest = { schema: environmentFileRequest.schema.anyOf![0], example: { ...(environmentFileRequest.example as Record<string, Json>), identity: contextIdentity.example } }; if (edge.source === 'lina-environment-collect') fields.observation = replaceField(replaceField(replaceField(environmentObservation, 'identity', contextIdentity), 'status', fixed(outcome ?? 'success')), 'terminal', fixed(outcome !== 'progress')); fields.contentIsPermission = fixed(false); fields.toolBatchCompletion = fixed(false); }
 else if (short.includes('input')) { fields.identity = replaceField(replaceField(replaceField(replaceField(environmentIdentity, 'origin', fixed('input-staging')), 'callId', fixed(null)), 'batchId', fixed(null)), 'requesterNodeId', fixed('lina-input-custody')); fields.originalCustodyRef = text('original:attachment-001'); fields.stagingManifest = environmentStagingManifest; fields.originalCustodyReplaced = fixed(false); fields.destinationAuthorizationRef = text('authorization:stage:001'); }
 else if (short.includes('profile')) { fields.profile = environmentProfile; fields.placement = environmentPlacement; fields.bindingUsedBeforeScheduling = fixed(true); }
 else if (short.includes('cancel')) { fields.control = replaceField(environmentProcessControl.schema.anyOf ? object({ kind: fixed('stop'), process: environmentProcess, cancellationOwnerRef: text('turn-001'), originalLaunchId: text('launch:workspace:001:1'), ownerAgentId: text('lina-main'), ownerLeaseId: text('lease:main:environment:001'), controlId: text('control:workspace:stop:001'), action: fixed('terminate'), acknowledged: fixed(false) }) : environmentRelease, 'action', fixed('terminate')); fields.sentControlProvesExit = fixed(false); fields.destroyEnvironmentOnStop = fixed(false); }
 else if (short.includes('reconcile') || short.includes('recovery')) { fields.receipt = replaceField(environmentReconciliation, 'status', fixed(environmentStatuses.reconcile.includes(outcome ?? '') ? outcome! : 'running')); fields.reconnectDoesNotRelaunch = fixed(true); fields.inspectionBeforeRetry = fixed(true); }
 else if (short.includes('wait')) { fields.waitId = text('wait:environment:001'); fields.waitRevision = count(1); fields.owner = fixed('environment'); fields.originalContinuationNodeId = text('lina-environment-reconcile'); fields.expiryProvesNoEffect = fixed(false); }
 else if (short.includes('planning')) { fields.observation = environmentObservation; fields.planAttemptRef = text('task-attempt:workspace:001'); fields.taskAcceptanceOwner = fixed('planning'); fields.processSuccessProvesGoal = fixed(false); }
 else if (short.includes('release') || short.includes('settle')) { fields.release = environmentRelease; fields.retainedArtifact = environmentArtifact; fields.turnCompletionOwner = fixed('execution'); fields.noFreshModelLaunch = fixed(true); }
 else if (short.includes('tools')) { fields.intent = environmentOperationIntent; fields.binding = environmentBinding; if (edge.source === 'lina-environment-collect') fields.observation = replaceField(replaceField(replaceField(environmentObservation, 'status', fixed(outcome ?? 'success')), 'terminal', fixed(outcome !== 'progress')), 'effectCertainty', fixed(outcome === 'unknown' ? 'unknown' : 'known')); fields.toolBatchOwner = fixed('tools'); fields.originalCallId = text('call:workspace:001'); fields.resultPublishedExactlyOnceByOwner = fixed(true); }
 else { fields.binding = environmentBinding; fields.request = union(environmentFileRequest, environmentCommand, environmentProcessControl); fields.intent = environmentOperationIntent; }
 return object(fields);
}
const selected: Record<string, string[]> = {
 'profile-tools': ['bypass'], 'profile-workspace': ['resolved'], 'profile-collect': ['refused', 'unavailable'], 'workspace-acquire': ['bound'], 'workspace-collect': ['conflict', 'invalid', 'unavailable'],
 'acquire-ready': ['attached', 'created', 'reused'], 'acquire-reconcile': ['provisioning', 'unknown'], 'acquire-collect': ['failed'], 'ready-workspace': ['stale'], 'ready-collect': ['missing-dependency', 'unsupported', 'unavailable'],
 'stage-input': ['verified', 'skipped', 'partial', 'conflict', 'failed'], 'stage-ready': ['verified', 'skipped'], 'stage-collect': ['verified', 'partial', 'conflict', 'failed'], 'stage-reconcile': ['unknown'], 'files-collect': ['success', 'conflict', 'rejected', 'unsupported', 'cancelled'], 'files-reconcile': ['unknown'],
 'start-process': ['running'], 'start-collect': ['success', 'known-unstarted', 'rejected'], 'start-reconcile': ['unknown'], 'process-process': ['running', 'progress'], 'process-collect': ['progress', 'exited', 'cancelled', 'unsupported', 'stale'], 'process-reconcile': ['unknown'],
 'collect-tools': ['progress', 'success', 'error', 'rejected', 'cancelled'], 'collect-context': ['progress', 'success', 'error', 'rejected', 'cancelled'], 'collect-planning': ['success', 'error', 'rejected', 'cancelled', 'unknown'], 'collect-reconcile': ['unknown'], 'collect-artifacts': ['success'], 'collect-settle': ['error', 'rejected'], 'artifacts-collect': ['retained', 'pending', 'partial', 'failed'], 'artifacts-release': ['retained'], 'artifacts-reconcile': ['unknown'],
 'reconcile-process': ['running'], 'reconcile-ready': ['running'], 'reconcile-collect': ['terminal', 'proven-unstarted', 'unavailable', 'stale'], 'reconcile-release': ['removed', 'proven-unstarted'], 'reconcile-wait': ['pending-provision', 'unknown'],
 'release-reconcile': ['unknown'], 'release-artifacts': ['deferred'], 'release-wait': ['deferred'], 'release-execution': ['released', 'retained', 'already-released', 'removed'], 'release-subagents': ['released', 'retained', 'already-released'],
};
for (const edge of ENVIRONMENT_EDGES) {
 const producer = environmentExecutionContracts.find(item => item.nodeId === edge.source); if (!producer) continue;
 const phase = edge.source.replace('lina-environment-', ''); const short = edge.id.replace('lina-environment-edge-', '');
 if (environmentStatePayload(edge)) producer.outputs.push(output(`environment.${short}.request`, `${phase}: State request`, handoff(edge), [edge.id], 'Request exact original conditional record or inspection; State alone owns persistence.'));
 else {
  const statuses = selected[short] ?? (edge.target.startsWith('lina-environment-') ? [environmentStatuses[phase][0]] : ['ready', 'verified', 'success', 'bound'].filter(status => environmentStatuses[phase].includes(status)));
  for (const status of statuses.length ? statuses : [environmentStatuses[phase][0]]) {
   const continuation = handoff(edge, status);
   const identity = { schema: continuation.schema.properties!.identity, example: (continuation.example as Record<string, Json>).identity };
   producer.outputs.push(output(`environment.${short}.${status}`, `${phase}: ${status} → ${edge.target.replace('lina-', '')}`, scopedExample(object({ phaseOutcome: environmentPhasePayload(phase, status), handoff: continuation }), identity), [edge.id], 'Only the named phase outcome follows the declared requester route. Keep original identity and actual capability/effect evidence.'));
  }
 }
}
/** Attach exact new requests/replies to their existing producer, never rename a
 * received event or silently manufacture a new tool operation. */
export function attachEnvironmentProducerHandoffs(definitions: ContractDefinition[]): void {
 for (const edge of ENVIRONMENT_EDGES.filter(item => !item.source.startsWith('lina-environment-'))) {
  const source = definitions.find(item => item.nodeId === edge.source); if (!source) throw new Error(`Missing Environment producer ${edge.source}`);
  const route = ENVIRONMENT_STATE_ROUTES.find(item => item.returnId === edge.id);
  const outcomes = route ? route.kind === 'record' ? ['applied', 'already-applied', 'conflict', 'failed', 'unknown'] : ['found', 'missing', 'failed', 'still-unknown'] : ['requested'];
  for (const outcome of outcomes) source.outputs.push(output(`environment.${edge.id.replace('lina-environment-edge-', '')}.${outcome}`, `Environment: ${outcome}`, handoff(edge, outcome), [edge.id], route ? 'Return original request and transaction identity; receipt does not establish an external effect or launch.' : 'Existing owner requests/resumes exact admitted environment work.'));
 }
}
// External typed variants cover backend events and trusted configuration without
// treating an arbitrary model request as environment authority.
environmentExecutionContracts.find(item => item.nodeId === 'lina-environment-profile')!.external = [environmentProfile, sandboxEnvironmentProfile, remoteEnvironmentProfile].map((value, index) => ({ label: ['Configured current-PC profile', 'Configured Docker profile', 'Configured remote profile'][index], value, source: 'Trusted host configuration, versioned profile owner' }));
environmentExecutionContracts.find(item => item.nodeId === 'lina-environment-files')!.external = environmentFileRequest.schema.anyOf!.map((schema, index) => ({ label: `Admitted file action ${['read', 'list', 'search', 'stat', 'write', 'edit', 'delete'][index]}`, value: { schema, example: { ...(environmentFileRequest.example as object), action: ['read', 'list', 'search', 'stat', 'write', 'edit', 'delete'][index], query: index === 2 ? 'TODO' : null, contentRef: index === 4 || index === 5 ? 'private:workspace-content:001' : null, mutationPolicy: index >= 4 ? 'replace-if-current' : 'none' } }, source: 'Validated admitted operation with exact target and launch authorization' }));
environmentExecutionContracts.find(item => item.nodeId === 'lina-environment-process')!.external = [{ label: 'Correlated backend progress or exit', value: environmentObservation, source: 'Backend adapter with original attempt identity and monotonic sequence' }, ...environmentProcessControl.schema.anyOf!.map((schema, index) => { const action = ['poll', 'logs', 'stdin', 'signal', 'terminate', 'resize'][index]; return { label: `Admitted process ${action}`, value: { schema, example: { ...(environmentProcessControl.example as Record<string, Json>), action, controlId: `control:process:${action}:001`, authorizationRef: `authorization:process:${action}:001`, inputRef: action === 'stdin' ? 'private:process-input:001' : null, signal: ['signal', 'terminate'].includes(action) ? 'SIGTERM' : null, dimensions: action === 'resize' ? { columns: 120, rows: 40 } : null } }, source: 'Exact process owner, current permission and capability checks' }; })];

environmentExecutionContracts.find(item => item.nodeId === 'lina-environment-start')!.external = [
 { label: 'Admitted argv command', value: object({ intent: environmentOperationIntent, command: { schema: environmentCommand.schema.anyOf![0], example: environmentCommand.example } }), source: 'Trusted executable resolution, validated arguments and exact launch permit' },
 { label: 'Admitted shell command', value: object({ intent: environmentOperationIntent, command: { schema: environmentCommand.schema.anyOf![1], example: { kind: 'shell', scriptRef: 'private:command-script:001', shellRef: 'configured-shell:sh', cwd: '/workspace/project', inheritEnvironment: false, allowedEnvironment: [], stdinRef: null, ptyRequested: false, lifetime: 'foreground' } } }), source: 'Validated script reference and explicit shell placement with exact launch permit' },
];
