import { choice, count, fixed, flag, list, nullable, object, replaceField, sample, text, union } from './schema';

/** Memory knowledge is separate from execution history. These design records
 * preserve evidence and access generations; derived indexes are not authority. */
export const memoryScope = object({ namespace: choice(['user-private', 'workspace-shared', 'agent-private', 'task-local'], 'user-private'), namespaceId: text('user:demo'), principalRef: text('principal:demo'), agentId: text('lina-main'), parentAgentId: sample(nullable(text('lina-main')), null), taskId: text('task:001'), permittedOperations: list(choice(['read', 'propose', 'commit', 'forget', 'consolidate']), ['read', 'propose', 'commit', 'forget']), policyGeneration: count(3), visibilityGeneration: count(7), delegatedAccess: fixed(false), childSharedWriteRequiresParentReview: fixed(true) });
export const memoryCorrelation = object({ schemaVersion: fixed(1), requestId: text('memory-request:001'), operationId: text('memory-operation:001'), requester: object({ nodeId: choice(['lina-context-load', 'lina-tools-dispatch', 'lina-execution-settle', 'lina-memory-consolidate'], 'lina-context-load'), purpose: choice(['profile', 'search', 'exact-read', 'explicit-write', 'automatic-write', 'correction', 'forget', 'maintenance'], 'search'), continuationRef: text('continuation:memory:001') }), turnId: text('turn-001'), scope: memoryScope, synthetic: fixed(true), liveMemoryBackendImplemented: fixed(false) });
export const memoryEvidence = object({ sourceRef: text('accepted-input:001'), sourceRevision: count(1), sourceDigest: text('sha256:fixture-source'), origin: choice(['user-assertion', 'observed-tool-result', 'completed-episode', 'model-interpretation', 'recalled-memory', 'external-content'], 'user-assertion'), authority: choice(['explicit-user-request', 'observed-result', 'interpretation', 'untrusted'], 'explicit-user-request'), observedAt: text('2026-10-08T12:00:00Z'), retentionAllowed: flag(true), extractionEgress: choice(['local-only', 'approved-model-provider', 'blocked'], 'local-only'), parentMemoryRefs: list(text('memory:prior:1'), []), recallIsIndependentEvidence: fixed(false), sensitiveDataClass: choice(['ordinary', 'restricted', 'credential-material'], 'ordinary'), containsCredentials: fixed(false) });
const content = union(
 object({ kind: fixed('fact'), subject: text('user:demo'), predicate: text('preferred-language'), value: text('English'), validFrom: text('2026-10-08T12:00:00Z'), validUntil: sample(nullable(text('2026-11-01T00:00:00Z')), null) }),
 object({ kind: fixed('episode'), taskRef: text('task:001'), observation: text('The user corrected a formatting preference.'), outcome: choice(['successful', 'failed', 'partial', 'unknown'], 'successful'), occurredAt: text('2026-10-08T12:00:00Z') }),
 object({ kind: fixed('procedure'), instruction: text('Check the current preference before drafting.'), applicability: text('Drafting user-facing prose'), evidenceRefs: list(text('episode:001')), executableSkill: fixed(false), independentlyVerified: flag(false) }),
);
export const memoryKnowledge = object({ memoryId: text('memory:preference:001'), revision: count(2), namespaceId: text('user:demo'), content, evidence: list(memoryEvidence, [memoryEvidence.example], 1), status: choice(['active', 'superseded', 'disputed', 'retracted', 'forgotten'], 'active'), authority: choice(['user-asserted', 'observed', 'derived'], 'user-asserted'), confidence: object({ label: choice(['confirmed', 'tentative', 'disputed'], 'confirmed'), calibration: fixed('not-a-probability') }), supersedes: list(text('memory:preference:old'), []), derivedFrom: list(text('memory:source:001'), []), retention: object({ expiresAt: sample(nullable(text('2026-11-01T00:00:00Z')), null), deletionGeneration: count(0) }), createdAt: text('2026-10-08T12:00:00Z'), updatedAt: text('2026-10-08T12:01:00Z') });
export const memoryKnowledgeVariants = [
 memoryKnowledge,
 replaceField(replaceField(memoryKnowledge, 'memoryId', text('memory:episode:001')), 'content', { schema: content.schema.anyOf![1], example: { kind: 'episode', taskRef: 'task:001', observation: 'The formatting correction was applied.', outcome: 'successful', occurredAt: '2026-10-08T12:00:00Z' } }),
 replaceField(replaceField(replaceField(memoryKnowledge, 'memoryId', text('memory:procedure:001')), 'authority', fixed('derived')), 'content', { schema: content.schema.anyOf![2], example: { kind: 'procedure', instruction: 'Check the current preference before drafting.', applicability: 'Drafting user-facing prose', evidenceRefs: ['episode:001'], executableSkill: false, independentlyVerified: false } }),
];
export const memoryCandidate = object({ candidateId: text('memory-candidate:001'), proposedKnowledge: memoryKnowledge, sourceEvidence: list(memoryEvidence), extraction: object({ mode: choice(['explicit-structured', 'automatic-extraction', 'consolidation'], 'explicit-structured'), modelAttemptRef: sample(nullable(text('model-attempt:memory:001')), null), promptRevision: text('memory-extraction:v1'), generatedTextGrantsAuthority: fixed(false) }), admission: object({ status: choice(['pending', 'eligible', 'rejected', 'needs-review'], 'pending'), parentReviewRef: sample(nullable(text('parent-review:001')), null), permissionGranted: fixed(false) }) });
export const memoryQuery = object({ mode: choice(['profile', 'exact-read', 'lexical', 'semantic', 'hybrid'], 'lexical'), originalText: text('What language does the user prefer?'), preparedQueries: list(text('preferred language')), rewriteProvenance: choice(['identity', 'deterministic', 'model-assisted'], 'identity'), exactRefs: list(text('memory:preference:001'), []), filters: object({ kinds: list(choice(['fact', 'episode', 'procedure']), ['fact']), asOf: sample(nullable(text('2026-10-08T12:00:00Z')), null), activeOnly: fixed(true), namespaceIds: list(text('user:demo')) }), maxCandidates: count(20), maxEvidenceTokens: count(800), requiredFreshness: choice(['authoritative-records', 'declared-index-watermark'], 'authoritative-records') });
export const memoryRetrieved = object({ record: memoryKnowledge, sourceRevision: count(2), score: object({ lexical: count(9), semantic: sample(nullable(count(8)), null), recency: count(1), rankScore: count(10), comparableAcrossStrategies: fixed(false) }), indexGeneration: count(6), indexWatermark: count(2), visibilityGeneration: count(7), expansionRefs: list(text('accepted-input:001')) });
export const memorySelection = object({ selectionId: text('memory-selection:001'), records: list(memoryRetrieved), omitted: list(object({ memoryId: text('memory:other:001'), reason: choice(['budget', 'duplicate', 'retired', 'revoked', 'scope', 'stale', 'low-relevance'], 'budget') }), []), consumedEvidenceTokens: count(60), maxEvidenceTokens: count(800), visibilityGeneration: count(7), recheckBeforeNewInvocation: fixed(true), alreadyIssuedSnapshotsAreHistorical: fixed(true), memoryIsInstructionAuthority: fixed(false), contextOwnsFinalModelBudget: fixed(true) });
export const memoryMutation = object({ mutationId: text('memory-mutation:001'), action: choice(['add', 'supersede', 'retract', 'mark-disputed', 'no-op', 'forget'], 'add'), candidateRef: text('memory-candidate:001'), targetRef: sample(nullable(text('memory:preference:old')), null), expectedRecordRevision: sample(nullable(count(1)), null), replacement: nullable(memoryKnowledge), observedRevision: count(2), conflictRef: sample(nullable(text('memory-conflict:001')), null), historicalValidityPreserved: fixed(true), ambiguityAllowsSilentOverwrite: fixed(false) });
export const memoryTransaction = object({ transactionId: text('memory-tx:001'), idempotencyKey: text('memory-write:001'), requestFingerprint: text('sha256:fixture-memory-mutations'), expectedNamespaceRevision: count(4), executionFence: count(8), mutationSet: list(memoryMutation, [memoryMutation.example], 1), requiredCommitBoundary: fixed('all-listed-memory-mutations'), changedFingerprintMayOverwrite: fixed(false), permissionEvidenceRef: text('safety-decision:memory:001'), expectedPolicyGeneration: count(3), expectedVisibilityGeneration: count(7) });
export const memoryForgetPlan = object({ deletionId: text('forget:001'), targetRefs: list(text('memory:preference:001')), descendantRefs: list(text('memory:summary:001')), namespaceId: text('user:demo'), expectedVisibilityGeneration: count(7), newVisibilityGeneration: count(8), immediateRecallRevocation: fixed(true), pendingJobFence: count(8), resurrectionForbidden: fixed(true), tombstoneRetainsContent: fixed(false), coveredCopies: list(choice(['authoritative-records', 'derived-summaries', 'retrieval-indexes', 'selection-caches', 'configured-replicas']), ['authoritative-records', 'derived-summaries', 'retrieval-indexes', 'selection-caches']), excludedCopies: list(object({ owner: text('backup-provider'), reason: text('Configured backup retention is outside immediate purge coverage.'), retentionUntil: nullable(text('2026-11-08T00:00:00Z')) })), pendingCleanupRefs: list(text('cleanup:index:001')), fullyErasedEverywhere: fixed(false), correctIsNotForget: fixed(true) });
export const memoryLocalContext = object({ designOnly: fixed(true), storage: fixed('deterministic-fixture'), liveMemoryBackendImplemented: fixed(false), currentPolicyGeneration: count(3), currentVisibilityGeneration: count(7), namespaceRevision: count(4), indexGeneration: count(6), strategy: fixed('inspectable-records-and-lexical-baseline'), automaticCapture: flag(true), optionalConsolidation: flag(false), credentialMaterialIncluded: fixed(false), currentStopRequested: flag(false) });
