/** Provisional model handoff records. This leaf imports no node contracts: producers
 * and consumers share these records without rebuilding shapes or circular imports. */
import { choice, count, fixed, flag, list, nullable, object, replaceField, sample, text, union, type Json, type Payload } from './schema';
import { argumentObject, authority, jsonValue, turnState, limits } from './shared';
export const modelField = (record: Payload, key: string): Payload => ({ schema: record.schema.properties![key], example: (record.example as Record<string, Json>)[key] });
export const extendModelRecord = (record: Payload, fields: Record<string, Payload>): Payload => object({ ...Object.fromEntries(Object.keys(record.schema.properties!).map(key => [key, modelField(record, key)])), ...fields });
const none = (record: Payload) => sample(nullable(record), null);
export const modelIdentity = object({ agentId: text('lina-main'), turnId: text('turn-001'), roundId: text('round-001'), conversationId: text('conversation-demo'), workspaceId: text('workspace-demo'), requesterId: text('user-demo'), scopeRef: text('context-scope:lina-main:v1'), ownerRevision: count(2), intentId: text('model-intent:turn-001:round-001:1'), preparationId: text('prepare:turn-001:round-001:r0'), attemptId: none(text('model-attempt-001')) });
export const modelBudgetProfile = object({ budgetProfileRef: text('model-budget:demo:v1'), revision: count(1), contextCapacity: count(1000), outputReservation: count(200), protocolOverhead: count(50), reasoningAllocation: count(0), estimationSource: fixed('synthetic-fixture'), effectiveSettingsRef: text('model-settings:demo:v1') });
const feature = (state = 'supported') => object({ state: choice(['supported', 'unsupported', 'unknown'], state), evidenceRef: text('research:provider-protocols:fixture-v1') });
export const modelCapabilities = object({ capabilitiesRef: text('model-capabilities:demo:v1'), revision: count(1), profileRef: text('openai-chat-fixture-v1'), profileRevision: count(1), codecRevision: text('codec:chat:v1'), factsSource: fixed('versioned-design-fixture'), inputModalities: list(choice(['text', 'image', 'audio', 'video', 'file']), ['text', 'image'], 1), tools: feature(), schemaDialect: text('json-schema:provider-subset:v1'), structuredOutput: feature(), reasoning: feature('unsupported'), cache: feature('unknown'), cancellation: object({ local: fixed('abort-and-drain'), remoteConfirmation: feature('unknown') }), budgetProfile: modelBudgetProfile, mediaLimitsRef: text('media-limits:fixture:v1'), supportedSettings: list(text('temperature'), ['temperature', 'maxOutputTokens']) });
export const modelBinding = object({ bindingRef: text('model-binding:demo:g1'), routeGeneration: count(1), requestedProvider: text('fixture-provider'), requestedModel: text('fixture-model'), selectionSource: choice(['configured-default', 'user-explicit', 'subagent-config'], 'configured-default'), fallbackAllowed: fixed(false), protocol: choice(['openai-chat', 'openai-responses', 'anthropic-messages', 'gemini-generate-content']), profileRef: text('openai-chat-fixture-v1'), profileRevision: count(1), codecRevision: text('codec:chat:v1'), endpointRef: text('private:model-endpoint:demo'), accountId: text('model-account-demo'), credentialReadinessRef: text('model-readiness:account-demo:g1'), capabilitiesRef: text('model-capabilities:demo:v1'), budgetProfile: modelBudgetProfile, configuredSettings: jsonValue({ maxOutputTokens: 200, temperature: 0 }), effectiveSettings: jsonValue({ maxOutputTokens: 200, temperature: 0 }), actualCredentialIncluded: fixed(false) });
export const modelMetadataRequest = object({ identity: modelIdentity, purpose: fixed('capabilities'), dependencyId: text('context:model-capabilities:prepare-001'), required: fixed(true), requestedBindingRef: text('model-binding:demo:g1'), configurationRevision: count(1), requiredFeatures: list(text('tools'), ['tools']), requiredInputModalities: list(text('text'), ['text']), modelAttemptLaunched: fixed(false) });
export const modelCapabilitiesReady = object({ request: modelMetadataRequest, identity: modelIdentity, purpose: fixed('capabilities'), capabilities: modelCapabilities, binding: modelBinding, dependencyResolved: fixed(true), resumeSamePreparation: fixed(true), modelAttemptLaunched: fixed(false) });
export const modelCapabilitiesUnavailable = object({ request: modelMetadataRequest, identity: modelIdentity, purpose: fixed('capabilities'), code: choice(['unknown-required-capability', 'unsupported-required-capability', 'route-disabled', 'route-unavailable', 'wait-expired', 'cancelled']), evidenceRef: text('evidence:model-capability-unavailable:1'), preparationMustFail: fixed(true), resumeSamePreparation: fixed(true), modelAttemptLaunched: fixed(false) });
export const modelInvocationIntent = object({ executionState: turnState, round: object({ roundId: text('round-001'), index: count(1) }), identity: modelIdentity, purpose: fixed('invocation'), contextSnapshotRef: text('context:turn-001:round-001:r0'), snapshotArtifactRef: text('artifact:context-snapshot:001'), generationVectorRef: text('context-generations:prepare-001:v1'), catalogRevision: text('catalog:demo:7'), catalogBindingRef: text('tools:lina:v1'), registryGeneration: count(7), requiredSchemaDigests: list(text('sha256:fixture-calculator-schema'), ['sha256:fixture-calculator-schema']), requiredCapabilitiesRef: text('model-capabilities:demo:v1'), requiredBudgetProfileRef: text('model-budget:demo:v1'), requiredCodecRevision: text('codec:chat:v1'), requestedBindingRef: text('model-binding:demo:g1'), launchAuthority: authority, snapshotGrantsLaunchPermission: fixed(false), stopped: flag(false), modelAttemptLaunched: fixed(false) });
export const modelBindingReady = object({ intent: modelInvocationIntent, identity: modelIdentity, binding: modelBinding, capabilities: modelCapabilities, currentnessChecked: fixed(true), modelAttemptLaunched: fixed(false) });
export const modelUsage = union(
 object({ availability: fixed('reported'), input: count(100), output: count(8), cacheRead: none(count(0)), cacheWrite: none(count(0)), reasoning: none(count(0)), total: count(108), streamSemantics: fixed('cumulative-final'), accountingSemantics: text('input-includes-cache'), rawUsageRef: text('artifact:model-usage:attempt-001'), cost: none(jsonValue({ amount: 0, currency: 'USD' })), synthetic: fixed(true) }),
 object({ availability: fixed('partial'), input: none(count(100)), output: count(3), cacheRead: none(count(0)), cacheWrite: none(count(0)), reasoning: none(count(0)), total: none(count(103)), streamSemantics: fixed('cumulative-latest'), accountingSemantics: text('provider-fields-incomplete'), rawUsageRef: text('artifact:model-usage:attempt-001:partial'), cost: fixed(null), synthetic: fixed(true) }),
 object({ availability: fixed('unavailable'), input: fixed(null), output: fixed(null), cacheRead: fixed(null), cacheWrite: fixed(null), reasoning: fixed(null), total: fixed(null), streamSemantics: fixed('unavailable'), accountingSemantics: text('provider-did-not-report'), rawUsageRef: fixed(null), cost: fixed(null), synthetic: fixed(true) }),
);
export const modelUnavailableUsage = { schema: modelUsage.schema, example: { availability: 'unavailable', input: null, output: null, cacheRead: null, cacheWrite: null, reasoning: null, total: null, streamSemantics: 'unavailable', accountingSemantics: 'provider-did-not-report', rawUsageRef: null, cost: null, synthetic: true } } satisfies Payload;
export const modelContinuation = object({ stateRef: text('artifact:model-replay:attempt-001'), agentId: text('lina-main'), accountId: text('model-account-demo'), provider: text('fixture-provider'), protocol: text('openai-responses'), conversationId: text('conversation-demo'), historyRevision: text('history:conversation-demo:r7'), replayOrderRef: text('replay-order:attempt-001'), portable: fixed(false), compatibility: choice(['same-route-only', 'incompatible']), rawSecretsIncluded: fixed(false) });
export const modelToolMapping = object({ toolId: text('tool:builtin:calculator'), canonicalName: text('calculator'), wireName: text('calculator'), schemaRevision: text('v1'), originalSchemaDigest: text('sha256:fixture-calculator-schema'), projectedSchemaDigest: text('sha256:fixture-calculator-schema'), inputSchema: jsonValue({ type: 'object', properties: { expression: { type: 'string', minLength: 1 } }, required: ['expression'], additionalProperties: false }), bindingRef: text('tool-binding:calculator:v1'), binding: object({ adapterRef: text('adapter:builtin:v1'), connectionId: fixed(null), accountId: fixed(null), ownerId: text('user-demo'), readinessGeneration: count(1) }), transforms: list(text('alias'), []), grantsExecutionPermission: fixed(false) });
export const modelEncodingManifest = object({ contextSnapshotRef: text('context:turn-001:round-001:r0'), snapshotArtifactRef: text('artifact:context-snapshot:001'), generationVectorRef: text('context-generations:prepare-001:v1'), preparationId: text('prepare:turn-001:round-001:r0'), bindingRef: text('model-binding:demo:g1'), capabilitiesRef: text('model-capabilities:demo:v1'), budgetProfileRef: text('model-budget:demo:v1'), catalogRevision: text('catalog:demo:7'), catalogBindingRef: text('tools:lina:v1'), registryGeneration: count(7), toolMappings: list(modelToolMapping, undefined, 1), inputMappings: list(object({ recordRef: text('input-001'), wirePath: text('messages[0]'), originalPreserved: fixed(true) })), mediaMappings: list(object({ artifactRef: text('artifact:image:001'), wirePath: text('messages[0].content[1]'), fidelity: choice(['preserved', 'omitted-with-policy']), policyRef: none(text('media-policy:v1')) }), []), transformations: list(text('system-role-to-instructions'), []), replayState: none(modelContinuation), estimatorRef: text('fixture-estimator:v1'), estimatedInput: count(550), outputReservation: count(200), sizeVerdict: fixed('fits'), synthetic: fixed(true) });
export const modelEncodedRequest = object({ intent: modelInvocationIntent, identity: modelIdentity, binding: modelBinding, capabilities: modelCapabilities, manifest: modelEncodingManifest, requestDigest: text('sha256:fixture-model-request:1'), privatePayloadRef: text('private:fixture-payload:1'), safeFixtureBody: jsonValue({ model: 'fixture-model', messages: [{ role: 'user', content: 'What is 2 + 2?' }], tools: [{ type: 'function', function: { name: 'calculator', parameters: { type: 'object', properties: { expression: { type: 'string', minLength: 1 } }, required: ['expression'], additionalProperties: false } } }], max_tokens: 200 }), validation: fixed('valid'), launchAuthority: authority, physicalRequestId: fixed(null), modelAttemptLaunched: fixed(false) });
export const modelAttempt = object({ identity: replaceField(modelIdentity, 'attemptId', text('model-attempt-001')), attemptId: text('model-attempt-001'), physicalRequestId: text('provider-request-001'), binding: modelBinding, requestDigest: text('sha256:fixture-model-request:1'), startedAt: text('2026-10-08T10:00:00Z'), terminalAt: none(text('2026-10-08T10:00:01Z')), localStatus: choice(['active', 'settlement-pending', 'settled']), remoteStatus: choice(['active-reported', 'completed-reported', 'unknown'], 'unknown'), streamSequence: count(0), attemptIncrement: fixed(1), roundIncrement: count(1) });
export const modelDraftCall = object({ wireIndex: count(0), wireCallId: text('provider-call-001'), wireName: text('calculator'), argumentBytes: text('{"expression":"2 +'), complete: fixed(false), executable: fixed(false) });
export const modelProgress = object({ attempt: modelAttempt, sequence: count(1), itemId: text('item:tool:0'), kind: choice(['text-delta', 'call-start', 'call-delta', 'call-end-draft', 'usage', 'heartbeat', 'unknown'], 'call-delta'), draftText: none(text('Working')), callDraft: nullable(modelDraftCall), usage: modelUnavailableUsage, executable: fixed(false), terminal: fixed(false), rawEventRef: text('artifact:model-stream:attempt-001:1') });
export const modelCompleteCall = object({ callId: text('call-001'), wireCallId: nullable(text('provider-call-001')), wireIndex: count(0), name: text('calculator'), arguments: argumentObject, rawArgumentsRef: text('artifact:call-001:arguments'), syntax: fixed('complete-json-object'), mappedUnambiguously: fixed(true), providerConfirmedComplete: fixed(true), schemaValidated: fixed(false), executionAuthorized: fixed(false) });
export const modelObservation = object({ identity: replaceField(modelIdentity, 'attemptId', text('model-attempt-001')), stage: fixed('launched'), attempt: modelAttempt, transportStatus: nullable(count(200)), providerResponseId: nullable(text('response-001')), rawFinishReason: nullable(text('stop')), protocolTerminalObserved: flag(true), terminalMarkerRef: nullable(text('artifact:model-terminal:attempt-001')), content: list(object({ kind: fixed('text'), text: text('4'), itemId: text('item:text:0') })), callBuffers: list(jsonValue({ wireIndex: 0, wireCallId: 'provider-call-001', wireName: 'calculator', argumentBytes: '{"expression":"2 + 2"}', providerConfirmedComplete: true }), []), rawErrorRef: none(text('artifact:model-error:attempt-001')), usage: modelUsage, localSettlement: fixed('settled'), remoteStatus: choice(['completed-reported', 'unknown'], 'completed-reported'), rawEventRefs: list(text('artifact:model-stream:attempt-001:1')), actualResponseModel: nullable(text('fixture-model')), actualResponseProvider: nullable(text('fixture-provider')), continuation: none(modelContinuation), cancellationEvidenceRef: none(text('artifact:model-cancel:attempt-001')) });
export const modelFailure = object({ stage: choice(['resolve', 'encode', 'invoke', 'normalize']), code: text('provider_timeout'), classification: choice(['auth', 'rate-limit', 'context-overflow', 'unsupported', 'invalid-request', 'provider-failure', 'malformed-output', 'refusal', 'cancelled', 'unknown']), retryHint: flag(false), retryAfterMs: none(count(1000)), requestsContextRefresh: flag(false), requestsCredentialReadiness: flag(false), partialOutputRef: none(text('artifact:model-preview:attempt-001')), safeEvidenceRef: text('artifact:model-failure:1'), remoteOutcome: fixed('unknown') });
export const modelPrelaunchFailure = object({ identity: modelIdentity, purpose: fixed('invocation'), stage: fixed('prelaunch'), intent: modelInvocationIntent, failure: replaceField(replaceField(modelFailure, 'stage', fixed('encode')), 'code', text('unsupported_required_input')), usage: modelUnavailableUsage, modelAttemptLaunched: fixed(false), attemptIncrement: fixed(0), roundIncrement: fixed(0) });
export const modelReprepare = object({ identity: modelIdentity, intent: modelInvocationIntent, reason: choice(['binding-changed', 'codec-changed', 'capabilities-changed', 'budget-profile-changed', 'required-schema-changed', 'encoded-request-pressure']), previousSnapshotRef: text('context:turn-001:round-001:r0'), currentBindingRef: text('model-binding:demo:g2'), currentCapabilitiesRef: text('model-capabilities:demo:v2'), currentBudgetProfileRef: text('model-budget:demo:v2'), reprepareAttempts: count(1), maxReprepareAttempts: count(2), countersPreserved: fixed(true), modelAttemptLaunched: fixed(false), priorSnapshotPreserved: fixed(true) });
export const modelCancellation = object({ identity: replaceField(modelIdentity, 'attemptId', text('model-attempt-001')), attemptId: nullable(text('model-attempt-001')), intentId: text('model-intent:turn-001:round-001:1'), cancellationId: text('cancel:model-intent-001'), authority, stopped: fixed(true), invocationRequested: fixed(false), pendingReadinessInvalidated: fixed(true), remoteCancellationConfirmed: fixed(false) });
export const modelPrelaunchCancellation = replaceField(replaceField(modelCancellation, 'attemptId', fixed(null)), 'identity', modelIdentity);
export const modelReadinessWait = object({ owner: fixed('model'), purpose: choice(['capabilities', 'invocation'], 'invocation'), identity: modelIdentity, waitId: text('wait:model-intent-001'), owningNodeId: fixed('lina-model-resolve'), request: union(modelInvocationIntent, modelMetadataRequest), binding: modelBinding, providerAudienceRef: text('model-provider:fixture-provider'), continuationRef: text('private:model-readiness-continuation:1'), eligibleResponderRef: text('person-demo'), expectedAccountId: text('model-account-demo'), expiresAt: text('2026-10-08T10:05:00Z'), retainedWorkRef: text('turn:turn-001:retained-work'), modelAttemptLaunched: fixed(false), dispatchPermitted: fixed(false), waitRegistered: fixed(true) });
export const modelCredentialReadinessRequest = object({ owner: fixed('model'), wait: modelReadinessWait, providerAudienceRef: text('model-provider:fixture-provider'), accountId: text('model-account-demo'), credentialAuthorityRef: text('private:model-credential-owner:1'), credentialProtocol: fixed('native-provider-auth'), modelAttemptLaunched: fixed(false), secretIncluded: fixed(false) });
export const modelCredentialReady = object({ owner: fixed('model'), wait: modelReadinessWait, status: choice(['ready', 'denied', 'expired', 'cancelled']), verifiedAccountId: text('model-account-demo'), readinessGeneration: count(2), authorizationEvidenceRef: text('artifact:model-auth-evidence:1'), secretIncluded: fixed(false), invocationRequested: fixed(false) });
export const modelReadinessResume = object({ owner: fixed('model'), wait: modelReadinessWait, completion: modelCredentialReady, resumeSameIntent: fixed(true), continuationConsumedOnce: fixed(true), recheckCurrentnessAndStop: fixed(true), modelAttemptLaunched: fixed(false) });
export const modelSettlementWait = object({ owner: fixed('model'), purpose: fixed('local-settlement'), identity: replaceField(modelIdentity, 'attemptId', text('model-attempt-001')), waitId: text('wait:model-settlement:attempt-001'), owningNodeId: fixed('lina-model-invoke'), attempt: replaceField(modelAttempt, 'localStatus', fixed('settlement-pending')), continuationRef: text('private:model-settlement:attempt-001'), remoteStatus: fixed('unknown'), cleanReleaseAllowed: fixed(false), newAttemptAllowed: fixed(false) });
export const modelSettlementResume = object({ owner: fixed('model'), wait: modelSettlementWait, evidenceRef: text('artifact:model-local-settlement:attempt-001'), resumeSameAttempt: fixed(true), invocationRequested: fixed(false) });
export const modelOutcome = object({ executionState: replaceField(turnState, 'limits', sample(limits, { roundsStarted: 1, maxRounds: 3, attempts: 1, retriesRemaining: 1 })), round: object({ roundId: text('round-001'), index: count(1) }), identity: replaceField(modelIdentity, 'attemptId', text('model-attempt-001')), stage: choice(['prelaunch', 'launched'], 'launched'), status: choice(['complete', 'incomplete', 'malformed', 'failed', 'aborted', 'unknown']), rawFinishReason: nullable(text('stop')), text: nullable(text('4')), textFinalCandidate: flag(true), toolCalls: list(modelCompleteCall, []), continuationHint: choice(['none', 'next-round', 'unsupported-provider-continuation']), providerResponseId: nullable(text('response-001')), requestedModel: text('fixture-model'), requestedProvider: text('fixture-provider'), actualResponseModel: nullable(text('fixture-model')), actualResponseProvider: nullable(text('fixture-provider')), bindingRef: text('model-binding:demo:g1'), budgetProfileRef: text('model-budget:demo:v1'), usage: modelUsage, failure: none(modelFailure), continuation: none(modelContinuation), localSettlement: fixed('settled'), remoteStatus: choice(['completed-reported', 'unknown'], 'completed-reported'), acceptedAssistantRecordRef: nullable(text('artifact:model-assistant:attempt-001')), rawEvidenceRef: text('artifact:model-observation:attempt-001'), terminalObservationCount: fixed(1), grantsToolPermission: fixed(false) });
export const modelPrelaunchOutcome = extendModelRecord(modelOutcome, { executionState: turnState, identity: modelIdentity, stage: fixed('prelaunch'), status: fixed('failed'), text: fixed(null), textFinalCandidate: fixed(false), rawFinishReason: fixed(null), usage: modelUnavailableUsage, providerResponseId: fixed(null), acceptedAssistantRecordRef: fixed(null), actualResponseModel: fixed(null), actualResponseProvider: fixed(null), remoteStatus: fixed('unknown') });

export const modelAbortRequested = modelCancellation;
export const modelLocalSettlementPending = modelSettlementWait;
export const modelReadinessCancelled = object({ owner: fixed('model'), wait: modelReadinessWait, cancellation: modelPrelaunchCancellation, continuationInvalidated: fixed(true), modelAttemptLaunched: fixed(false), cleanReleaseAllowed: fixed(true) });
export const modelMetadataReadinessWait = extendModelRecord(modelReadinessWait, { purpose: fixed('capabilities'), request: modelMetadataRequest });
export const modelMetadataCredentialReadinessRequest = replaceField(modelCredentialReadinessRequest, 'wait', modelMetadataReadinessWait);
export const modelMetadataCredentialReady = replaceField(modelCredentialReady, 'wait', modelMetadataReadinessWait);
export const modelMetadataReadinessResume = extendModelRecord(modelReadinessResume, { wait: modelMetadataReadinessWait, completion: modelMetadataCredentialReady });
export const modelMetadataReadinessCancelled = extendModelRecord(modelReadinessCancelled, { wait: modelMetadataReadinessWait });
