import { choice, count, fixed, flag, list, nullable, object, output, replaceField, sample, text, type ContractDefinition, type Json, type Payload } from './schema';
import { jsonValue, limits } from './shared';
import { extendModelRecord as extend, modelAttempt, modelBinding, modelBindingReady, modelCapabilities, modelCapabilitiesReady, modelCapabilitiesUnavailable, modelCancellation, modelCompleteCall, modelEncodedRequest, modelEncodingManifest, modelFailure, modelIdentity, modelInvocationIntent, modelMetadataRequest, modelField, modelObservation, modelOutcome, modelPrelaunchCancellation, modelPrelaunchFailure, modelPrelaunchOutcome, modelProgress, modelReadinessResume, modelReadinessWait, modelReprepare, modelSettlementResume, modelSettlementWait, modelUnavailableUsage, modelUsage, modelContinuation } from './modelRecords';
const edges = (...ids: string[]) => ids.map(id => `lina-model-edge-${id}`);
const refine = (record: Payload, fields: Record<string, Payload>): Payload => Object.entries(fields).reduce((value, [key, field]) => replaceField(value, key, field), record);
const local = object({ designOnly: fixed(true), binding: modelBinding, capabilities: modelCapabilities, budgetProfileRef: text('model-budget:demo:v1'), currentOwnerRevision: count(2), currentRouteGeneration: count(1), snapshotStoreRef: text('coordinator:context-snapshots'), privateCredentialOwnerRef: text('private:model-credential-owner:1'), credentialMaterialIncluded: fixed(false), stopped: flag(false), supersededAttemptIds: list(text('model-attempt-old'), []), attemptAccountingOwner: fixed('Turn Execution'), physicalTransportRetry: fixed('disabled'), schemaPermissionOwner: fixed('Tools'), evidenceStore: fixed('fixture-artifact-references') });
const failure = (stage: string, code: string, classification: string, fields: Record<string, Payload> = {}) => refine(modelFailure, { stage: fixed(stage), code: text(code), classification: fixed(classification), ...fields });
const prelaunch = (stage: string, code: string, classification: string) => replaceField(modelPrelaunchFailure, 'failure', failure(stage, code, classification));
const prelaunchAbort = extend(modelPrelaunchFailure, { failure: failure('resolve','stop-before-launch','cancelled'), cancellation: modelPrelaunchCancellation });
const observation = (fields: Record<string, Payload> = {}) => refine(modelObservation, { attempt: refine(modelAttempt, { localStatus: fixed('settled'), terminalAt: nullable(text('2026-10-08T10:00:01Z')) }), ...fields });
const observe = (id: string, label: string, fields: Record<string, Payload>, when: string) => output(id,label,observation(fields),edges('invoke-normalize'),when);
const failedObservation = (code: string, fields: Record<string, Payload> = {}) => ({ rawFinishReason: fixed(null), protocolTerminalObserved: fixed(false), terminalMarkerRef: fixed(null), rawErrorRef: text(`artifact:model-error:${code}`), usage: modelUnavailableUsage, remoteStatus: fixed('unknown'), ...fields });
const outcome = (fields: Record<string, Payload> = {}) => refine(modelOutcome, fields);
const unusable = (status: string, code: string, classification: string, fields: Record<string, Payload> = {}) => outcome({ status: fixed(status), text: fixed(null), textFinalCandidate: fixed(false), toolCalls: fixed([]), acceptedAssistantRecordRef: fixed(null), failure: failure('normalize',code,classification), ...fields });
const calls = [modelCompleteCall.example, { ...modelCompleteCall.example as Record<string,Json>, callId:'call-002',wireCallId:'provider-call-002',wireIndex:1,arguments:{expression:'3 + 3'},rawArgumentsRef:'artifact:call-002:arguments' }];
const completeCalls = list(modelCompleteCall,calls,1);
const callBuffers = list(jsonValue({wireIndex:0,wireCallId:'provider-call-001',wireName:'calculator',argumentBytes:'{"expression":"2 + 2"}',providerConfirmedComplete:true}), [ {wireIndex:0,wireCallId:'provider-call-001',wireName:'calculator',argumentBytes:'{"expression":"2 + 2"}',providerConfirmedComplete:true},{wireIndex:1,wireCallId:'provider-call-002',wireName:'calculator',argumentBytes:'{"expression":"3 + 3"}',providerConfirmedComplete:true} ]);

export const modelInterfaceContracts: ContractDefinition[] = [
 { nodeId:'lina-model-resolve', context:local, contextSource:'Execution owns admission and snapshot references; Context asks for metadata. Shared credential owner provides reference-only native-provider readiness.', reads:['Original purpose, agent/turn/round/preparation identity and configuration','Versioned route, protocol, capabilities and effective budget','Matched readiness evidence or cancellation'], writes:['Same-preparation metadata or invocation-ready binding','Retained readiness, bounded reprepare or prelaunch failure'], rules:['Metadata lookup never allocates a provider attempt or consumes a logical round.','Resume original purpose exactly once; reject wrong-account, stale or cancelled readiness.','Recheck budget profile as well as model/capability/codec revision before reusing a prepared snapshot.','Do not silently rotate accounts, change explicit models or reinterpret provider authentication as MCP OAuth.','Invocation cancellation has no physical attempt; metadata cancellation returns a cancelled dependency to Context.'], outputs:[
  output('model.capabilities-ready','Model metadata ready',modelCapabilitiesReady,edges('resolve-context'),'Resolve exact dependency and resume the same Context preparation.'),
  output('model.capabilities-unavailable','Required metadata unavailable',modelCapabilitiesUnavailable,edges('resolve-context'),'Unknown/unsupported required capability or unavailable route fails this preparation.'),
  output('model.capabilities-cancelled','Metadata dependency cancelled',refine(modelCapabilitiesUnavailable,{code:fixed('cancelled')}),edges('resolve-context'),'Stop invalidates the dependency before any inference.'),
  output('model.binding-ready','Current invocation binding',modelBindingReady,edges('resolve-encode'),'Required account, capabilities and output/reasoning budget remain current.'),
  output('model.binding-unavailable','Unavailable invocation route',prelaunch('resolve','route-unavailable','unsupported'),edges('resolve-normalize'),'Configured route is unavailable; no physical request was sent.'),
  output('model.binding-disabled','Disabled model route',prelaunch('resolve','route-disabled','unsupported'),edges('resolve-normalize'),'A disabled route cannot be made usable by another unrequested provider.'),
  output('model.resolve-cancelled','Invocation intent cancelled',prelaunchAbort,edges('resolve-normalize'),'Invalidate pending intent/readiness, preserving zero prelaunch counters.'),
  output('model.readiness-wait','Native provider readiness pending',modelReadinessWait,edges('resolve-wait'),'Register exact intent before requesting authentication.'),
  output('model.metadata-readiness-wait','Metadata introspection readiness pending',refine(modelReadinessWait,{purpose:fixed('capabilities'),request:modelMetadataRequest}),edges('resolve-wait'),'Optional authenticated introspection retains metadata mode and the same preparation.'),
  output('model.readiness-denied','Readiness denied',prelaunch('resolve','readiness-denied','auth'),edges('resolve-normalize'),'Matched denial returns invocation prelaunch failure rather than creating a request.'),
  output('model.readiness-expired','Readiness expired',prelaunch('resolve','readiness-expired','auth'),edges('resolve-normalize'),'Expiry consumes the owning wait, not a fresh model round.'),
  output('model.resolve-reprepare-required','Changed binding requires Context refresh',modelReprepare,edges('resolve-reprepare'),'Changed route/capability/budget invalidates the prepared invocation within bounded reprepare allowance.'),
 ], external:[{label:'Coordinator metadata lookup',source:'The same Context dependency owner; direct calls use the same producer record',value:object({kind:fixed('model.capabilities-requested'),payload:modelMetadataRequest})},{label:'Matched Model readiness continuation',source:'Execution retained-wait owner',value:object({kind:fixed('model.readiness-resume'),payload:modelReadinessResume})}] },
 { nodeId:'lina-model-encode',context:local,contextSource:'The coordinator resolves an immutable snapshot artifact and compares current generations. Provider profile supplies an explicit codec and supported schema/media subset.',reads:['Exact prepared snapshot, registered schema/tool binding identities and current route','Complete history pairing, safe media and scoped opaque replay state','Final payload pressure and Stop intent'],writes:['Validated provider request with fidelity manifest','Bounded reprepare or unlaunchable preflight failure'],rules:['Encoding mutates a provider projection, not canonical records.','Keep original and projected schema digests, tool aliases, result IDs and media/replay transformations inspectable.','Unsupported required fields fail rather than being silently dropped.','Budget/output allocation changes require Context reprepare; no inference counters change here.','Encoded request has no physical request/attempt ID until dispatch.'],outputs:[
  output('model.request-ready','Validated provider request',modelEncodedRequest,edges('encode-invoke'),'Faithful encoding, current generations, capabilities and size checks pass.'),
  ...[['unsupported-required-media','unsupported'],['unsupported-required-schema','unsupported'],['unsupported-required-setting','unsupported'],['invalid-history-pairing','invalid-request'],['incompatible-continuation','invalid-request'],['request-too-large-nonreducible','invalid-request']].map(([code,classification])=>output(`model.encode-${code}`,code.replaceAll('-',' '),prelaunch('encode',code,classification),edges('encode-normalize'),'Required projection cannot be sent without changing its meaning.')),
  output('model.encode-cancelled','Stop before dispatch',extend(prelaunchAbort,{failure:failure('encode','stop-before-launch','cancelled')}),edges('encode-normalize'),'No request is sent; readiness and invocation continuations cannot revive stopped work.'),
  output('model.encode-reprepare-required','Projection generation or pressure changed',refine(modelReprepare,{reason:fixed('encoded-request-pressure')}),edges('encode-reprepare'),'Reduce or refresh Context within its budget, keeping original round and snapshot evidence.'),
  output('model.encode-budget-changed','Effective output/reasoning budget changed',refine(modelReprepare,{reason:fixed('budget-profile-changed')}),edges('encode-reprepare'),'The same model name no longer implies the same input allowance.'),
 ] },
 { nodeId:'lina-model-invoke',context:local,contextSource:'Execution grants launch authority and owns budgets. The provider adapter owns one physical request and local stream settlement, with no hidden SDK retry.',reads:['Validated encoded request and current authority/Stop check','Per-attempt item IDs, wire indices, terminal/error/usage evidence','Exact abort or retained local-settlement continuation'],writes:['Nonexecutable progress','One terminal local observation or retained settlement wait'],rules:['First dispatch increments logical launched rounds once and physical attempts once; retry increments attempts only.','Allocate physical request/attempt IDs at dispatch, never during metadata or encoding.','Maintain separate buffers for interleaved items/calls; previews cannot reach Tools.','End of stream without required completion marker is not semantic success.','Abort and drain exact local work; pending local settlement retains ownership. Unknown remote compute/billing does not become uncertain tool-write reconciliation.','Late output from stopped/superseded attempts remains diagnostic and cannot resume Tools or a new model round.'],outputs:[
  output('model.progress','Provider draft progress',modelProgress,edges('invoke-progress'),'New correlated stream item is accumulated without execution authority.'),
  output('model.progress-second-call','Interleaved second call preview',refine(modelProgress,{sequence:count(2),itemId:text('item:tool:1'),callDraft:object({wireIndex:count(1),wireCallId:text('provider-call-002'),wireName:text('calculator'),argumentBytes:text('{"expression":"3 +'),complete:fixed(false),executable:fixed(false)})}),edges('invoke-progress'),'Separate call buffer retains its own identity while the first remains incomplete.'),
  output('model.progress-text','Nonfinal streamed text',refine(modelProgress,{kind:fixed('text-delta'),itemId:text('item:text:0'),callDraft:fixed(null),draftText:text('The answer')}),edges('invoke-progress'),'Visible preview is not a committed final answer.'),
  output('model.progress-usage','Cumulative usage update',refine(modelProgress,{kind:fixed('usage'),callDraft:fixed(null),usage:modelUsage}),edges('invoke-progress'),'Replace latest cumulative counters; never sum every usage snapshot.'),
  output('model.progress-heartbeat','Provider heartbeat',refine(modelProgress,{kind:fixed('heartbeat'),callDraft:fixed(null)}),edges('invoke-progress'),'Healthy progress changes no attempt/round count.'),
  output('model.progress-unknown','Unknown provider event retained',refine(modelProgress,{kind:fixed('unknown'),callDraft:fixed(null),rawEventRef:text('artifact:model-unknown-event:1')}),edges('invoke-progress'),'Unknown event is retained as evidence, not assumed completion.'),
  output('model.progress-late','Superseded output retained diagnostically',extend(refine(modelProgress,{callDraft:fixed(null)}),{late:fixed(true),stateMutationAllowed:fixed(false)}),edges('invoke-progress'),'Cancelled/superseded attempt cannot contribute launchable output.'),
  observe('model.attempt-observed','Locally settled answer',{},'Protocol terminal observed and request-local cleanup accounted.'),
  observe('model.attempt-calls-observed','Terminal multiple calls',{rawFinishReason:fixed('tool_calls'),content:fixed([]),callBuffers},'Provider has completed both call argument buffers.'),
  observe('model.attempt-mixed-observed','Text and calls observed',{rawFinishReason:fixed('tool_calls'),callBuffers},'Both content and complete calls are retained; text is not automatically final delivery.'),
  ...[['truncated','length'],['malformed','tool_calls'],['refusal','content_filter'],['unknown-finish','future_reason']].map(([code,reason])=>observe(`model.attempt-${code}-observed`,`${code} terminal observation`,{rawFinishReason:fixed(reason),callBuffers:code==='truncated'?list(jsonValue({wireIndex:0,wireCallId:'provider-call-001',wireName:'calculator',argumentBytes:'{"expression":"2 +',providerConfirmedComplete:false})):fixed([])},'Retain raw protocol reason and buffers; Normalize determines their usability.')),
  observe('model.attempt-missing-terminal','Missing protocol terminal',failedObservation('missing-terminal'),'Socket EOF without required finish evidence is not a complete response.'),
  observe('model.attempt-provider-failed','HTTP or in-stream failure',failedObservation('provider-failed',{transportStatus:nullable(count(503))}),'One physical request failed; Execution owns any later retry.'),
  observe('model.attempt-failed-after-output','Provider failure after draft output',failedObservation('post-output-failure',{content:list(object({kind:fixed('text'),text:text('Partial answer'),itemId:text('item:text:0')}))}),'Keep preview with its failed attempt, without accepting an assistant answer.'),
  observe('model.attempt-http200-error','Semantic error under HTTP200',failedObservation('http200-error',{transportStatus:count(200)}),'Transport success is not provider semantic success.'),
  observe('model.attempt-aborted','Locally settled aborted attempt',failedObservation('aborted',{cancellationEvidenceRef:text('artifact:model-cancel:attempt-001')}),'Local abort/drain is accounted while remote compute and usage remain unknown.'),
  output('model.invoke-prelaunch-stopped','Launch authority revoked before dispatch',extend(prelaunchAbort,{failure:failure('invoke','stop-before-dispatch','cancelled')}),edges('invoke-normalize'),'Final launch gate fails before allocating a physical attempt.'),
  output('model.local-settlement-pending','Await local request settlement',modelSettlementWait,edges('invoke-wait'),'Local worker/transport remains unresolved; no new launch or clean release.'),
 ],external:[{label:'Retained exact-attempt settlement',source:'Execution waiting owner',value:object({kind:fixed('model.settlement-resume'),payload:modelSettlementResume})}] },
 { nodeId:'lina-model-normalize',context:local,contextSource:'Versioned protocol profile interprets terminal observation. Execution supplies preserved turn state; Tools owns registered-schema and permission admission.',reads:['Locally settled observation or prelaunch rejection','Raw provider finish/errors, complete argument buffers and wire→canonical maps','Usage availability and scoped opaque replay evidence'],writes:['Correlated semantic model outcome to Execution decision'],rules:['Normalize never opens a round, launches tools, retries or changes provider.','Only completed unambiguous object calls enter toolCalls; truncated/malformed prefixes stay raw evidence.','Registered schema/permission validity is not implied by JSON syntax.','Keep requested and actual response identities separately; retain unknown finish/error detail.','No automatic JSON repair, truncation continuation or provider-hosted Tools execution in this slice.','Absent usage remains null/unavailable, including failed or cancelled requests.'],outputs:[
  output('model.outcome-ready','Candidate complete answer',modelOutcome,edges('normalize-decide'),'Usable terminal answer returns to existing Execution controls and settlement.'),
  output('model.outcome-calls','Complete multiple calls',outcome({rawFinishReason:fixed('tool_calls'),text:fixed(null),textFinalCandidate:fixed(false),toolCalls:completeCalls}),edges('normalize-decide'),'Provider-complete JSON objects await Tools resolution/schema/permission checks.'),
  output('model.outcome-text-and-calls','Text accompanies complete calls',outcome({rawFinishReason:fixed('tool_calls'),textFinalCandidate:fixed(false),toolCalls:completeCalls}),edges('normalize-decide'),'Retain content and calls without announcing premature final delivery.'),
  output('model.outcome-continuation','Explicit next-round continuation',outcome({continuationHint:fixed('next-round'),textFinalCandidate:fixed(false)}),edges('normalize-decide'),'Execution chooses continuation and applies its logical-round limit.'),
  output('model.outcome-refused','Provider refusal or safety block',unusable('failed','provider-refused','refusal',{rawFinishReason:fixed('content_filter')}),edges('normalize-decide'),'Known refusal terminates without automatic retry or Tools.'),
  output('model.outcome-truncated','Output limit interrupted call',unusable('incomplete','output-truncated','malformed-output',{rawFinishReason:fixed('length')}),edges('normalize-decide'),'Baseline rejects partial calls and preserves raw fragment evidence.'),
  output('model.outcome-malformed','Malformed terminal JSON',unusable('malformed','malformed-tool-arguments','malformed-output'),edges('normalize-decide'),'Complete terminal structure still cannot authorize malformed argument objects.'),
  output('model.outcome-duplicate-call-id','Ambiguous duplicate call identity',unusable('malformed','duplicate-provider-call-id','malformed-output'),edges('normalize-decide'),'Ambiguous wire IDs reject the batch before Tools admission.'),
  output('model.outcome-unknown-finish','Unknown provider terminal',unusable('unknown','unknown-finish-reason','unknown',{rawFinishReason:fixed('future_reason'),remoteStatus:fixed('unknown')}),edges('normalize-decide'),'Unknown reason is inspectable and never defaulted to successful stop.'),
  output('model.outcome-missing-terminal','EOF without required terminal evidence',unusable('incomplete','missing-terminal','provider-failure',{rawFinishReason:fixed(null),usage:modelUnavailableUsage,remoteStatus:fixed('unknown')}),edges('normalize-decide'),'No draft call or apparent text completion is promoted.'),
  output('model.outcome-retryable-failure','Known eligible provider failure',unusable('failed','provider-unavailable','provider-failure',{failure:failure('normalize','provider-unavailable','provider-failure',{retryHint:fixed(true),retryAfterMs:count(1000)}),usage:modelUnavailableUsage,remoteStatus:fixed('unknown')}),edges('normalize-decide'),'Execution assesses bounded retry in the same round.'),
  output('model.outcome-context-overflow','Provider reports context overflow',unusable('failed','context-overflow','context-overflow',{failure:failure('normalize','context-overflow','context-overflow',{requestsContextRefresh:fixed(true)}),remoteStatus:fixed('unknown')}),edges('normalize-decide'),'Execution requests Context refresh rather than automatic provider fallback.'),
  output('model.outcome-auth-failure','Provider authentication failed',unusable('failed','provider-auth-failed','auth',{failure:failure('normalize','provider-auth-failed','auth',{requestsCredentialReadiness:fixed(true)}),usage:modelUnavailableUsage,remoteStatus:fixed('unknown')}),edges('normalize-decide'),'The failed attempt is accounted; readiness does not automatically replay it.'),
  output('model.outcome-aborted','Local abort with remote outcome unknown',unusable('aborted','local-abort-settled','cancelled',{rawFinishReason:fixed(null),usage:modelUnavailableUsage,remoteStatus:fixed('unknown')}),edges('normalize-decide'),'Stop proceeds to cancelled settlement after local work is accounted.'),
  output('model.outcome-failed-after-output','Nonfinal preview retained after failure',unusable('failed','post-output-failure','provider-failure',{text:text('Partial answer'),failure:failure('normalize','post-output-failure','provider-failure',{partialOutputRef:text('artifact:model-preview:attempt-001')}),usage:modelUnavailableUsage,remoteStatus:fixed('unknown')}),edges('normalize-decide'),'Keep evidence under failed attempt; never merge call fragments into the next one.'),
  output('model.outcome-prelaunch-failed','Rejected before physical launch',refine(modelPrelaunchOutcome,{failure:failure('encode','unsupported-required-input','unsupported')}),edges('normalize-decide'),'Counters remain unchanged with null physical attempt/provider response.'),
  output('model.outcome-prelaunch-aborted','Stop before physical launch',refine(modelPrelaunchOutcome,{status:fixed('aborted'),failure:failure('resolve','stop-before-launch','cancelled')}),edges('normalize-decide'),'A retained prelaunch intent terminates without allocating an attempt.'),
  output('model.outcome-unavailable-usage','Complete response without usage telemetry',outcome({usage:modelUnavailableUsage}),edges('normalize-decide'),'Missing usage is unavailable, not zero inference cost.'),
  output('model.outcome-scoped-replay','Opaque provider continuation retained',outcome({continuation:refine(modelContinuation,{protocol:fixed('openai-chat')})}),edges('normalize-decide'),'Replay state is opaque and compatible only with recorded account/history/route.'),
  output('model.outcome-hosted-continuation-unsupported','Provider-hosted continuation unsupported',unusable('failed','provider-hosted-continuation-unsupported','unsupported',{rawFinishReason:fixed('pause_turn'),continuationHint:fixed('unsupported-provider-continuation')}),edges('normalize-decide'),'Hosted tool pause is not misrepresented as Lina Tools or approval.'),
 ] },
];

// Protocol examples show distinct wire encodings while preserving the same admitted
// canonical schema and tool name. These are local, deliberately small fake profiles.
const protocolFixtures: { protocol: string; profile: string; codec: string; body: Json; finish: string }[] = [
 { protocol:'openai-responses',profile:'openai-responses-fixture-v1',codec:'codec:responses:v1',body:{model:'fixture-model',input:[{role:'user',content:[{type:'input_text',text:'What is 2 + 2?'}]}],tools:[{type:'function',name:'calculator',parameters:(modelEncodedRequest.example as any).safeFixtureBody.tools[0].function.parameters}],max_output_tokens:200},finish:'completed' },
 { protocol:'anthropic-messages',profile:'anthropic-messages-fixture-v1',codec:'codec:anthropic:v1',body:{model:'fixture-model',system:'Answer precisely.',messages:[{role:'user',content:[{type:'text',text:'What is 2 + 2?'}]}],tools:[{name:'calculator',input_schema:(modelEncodedRequest.example as any).safeFixtureBody.tools[0].function.parameters}],max_tokens:200},finish:'end_turn' },
 { protocol:'gemini-generate-content',profile:'gemini-generate-content-fixture-v1',codec:'codec:gemini:v1',body:{contents:[{role:'user',parts:[{text:'What is 2 + 2?'}]}],tools:[{functionDeclarations:[{name:'calculator',parametersJsonSchema:(modelEncodedRequest.example as any).safeFixtureBody.tools[0].function.parameters}]}],generationConfig:{maxOutputTokens:200}},finish:'STOP' },
];
for (const fixture of protocolFixtures) {
 const capabilitiesRef=`model-capabilities:${fixture.protocol}:v1`;
 const capabilities = refine(modelCapabilities,{capabilitiesRef:text(capabilitiesRef),profileRef:text(fixture.profile),codecRevision:text(fixture.codec)});
 const bindingRef=`model-binding:${fixture.protocol}:g1`;
 const binding=refine(modelBinding,{bindingRef:text(bindingRef),protocol:fixed(fixture.protocol),profileRef:text(fixture.profile),codecRevision:text(fixture.codec),capabilitiesRef:text(capabilitiesRef)});
 const intent=refine(modelInvocationIntent,{requestedBindingRef:text(bindingRef),requiredCodecRevision:text(fixture.codec),requiredCapabilitiesRef:text(capabilitiesRef)});
 const ready=refine(modelBindingReady,{intent,binding,capabilities});
 const wirePath=fixture.protocol==='openai-responses'?'input[0]':fixture.protocol==='gemini-generate-content'?'contents[0]':'messages[0]';
 const manifest=refine(modelEncodingManifest,{bindingRef:text(bindingRef),capabilitiesRef:text(capabilitiesRef),inputMappings:list(object({recordRef:text('input-001'),wirePath:text(wirePath),originalPreserved:fixed(true)}))});
 const encoded=refine(modelEncodedRequest,{intent,binding,capabilities,manifest,safeFixtureBody:jsonValue(fixture.body)});
 modelInterfaceContracts[0].outputs.push(output(`model.capabilities-ready-${fixture.protocol}`,`${fixture.protocol} metadata`,refine(modelCapabilitiesReady,{request:replaceField(modelMetadataRequest,'requestedBindingRef',text(bindingRef)),capabilities,binding}),edges('resolve-context'),'Versioned metadata resumes the same Context preparation without an inference.'));
 modelInterfaceContracts[0].outputs.push(output(`model.binding-ready-${fixture.protocol}`,`${fixture.protocol} fixture binding`,ready,edges('resolve-encode'),'The explicit profile chooses this protocol without changing canonical history or registered schemas.'));
 modelInterfaceContracts[1].outputs.push(output(`model.request-ready-${fixture.protocol}`,`${fixture.protocol} encoded request`,encoded,edges('encode-invoke'),'Native fixture payload preserves the same tool schema and records its distinct protocol.'));
 modelInterfaceContracts[2].outputs.push(observe(`model.attempt-observed-${fixture.protocol}`,`${fixture.protocol} terminal observation`,{attempt:refine(modelAttempt,{binding,localStatus:fixed('settled'),terminalAt:nullable(text('2026-10-08T10:00:01Z'))}),rawFinishReason:fixed(fixture.finish)},'Profile-specific finish evidence returns through Normalize.'));
 modelInterfaceContracts[3].outputs.push(output(`model.outcome-ready-${fixture.protocol}`,`${fixture.protocol} normalized answer`,outcome({rawFinishReason:fixed(fixture.finish),bindingRef:text(bindingRef)}),edges('normalize-decide'),'Normalize retains the raw protocol reason while returning the same canonical complete answer.'));
}
const retryAttempt=refine(modelAttempt,{identity:replaceField(modelIdentity,'attemptId',text('model-attempt-002')),attemptId:text('model-attempt-002'),physicalRequestId:text('provider-request-002'),roundIncrement:fixed(0),localStatus:fixed('settled')});
modelInterfaceContracts[2].outputs.push(observe('model.attempt-observed-retry','Retry settles inside original logical round',{identity:replaceField(modelIdentity,'attemptId',text('model-attempt-002')),attempt:retryAttempt},'One additional physical dispatch consumes no new logical round.'));
modelInterfaceContracts[3].outputs.push(output('model.outcome-ready-retry','Retried answer retains same round',outcome({identity:replaceField(modelIdentity,'attemptId',text('model-attempt-002')),executionState:replaceField(modelField(modelOutcome,'executionState'),'limits',sample(limits,{roundsStarted:1,maxRounds:3,attempts:2,retriesRemaining:0}))}),edges('normalize-decide'),'Attempt-002 succeeds with one launched logical round, two attempts and consumed retry allowance.'));
modelInterfaceContracts[3].outputs.push(output('model.outcome-unknown-tool','Complete call with unknown tool name',outcome({textFinalCandidate:fixed(false),toolCalls:list(refine(modelCompleteCall,{name:text('unknown-tool'),arguments:jsonValue({query:'example'}),wireCallId:text('provider-call-unknown')}))}),edges('normalize-decide'),'Syntactically complete model request goes to Tools resolution, which may reject an unknown name.'));
modelInterfaceContracts[3].outputs.push(output('model.outcome-minted-call-id','Provider omits wire call identifier',outcome({textFinalCandidate:fixed(false),toolCalls:list(extend(refine(modelCompleteCall,{callId:text('model-attempt-001:wire-index-0'),wireCallId:fixed(null)}),{callIdOrigin:fixed('stable-per-attempt-wire-index'),wireIdentifierAbsent:fixed(true)}))}),edges('normalize-decide'),'Mint a stable per-attempt mapping; preserve omission evidence rather than inventing a provider identifier.'));
/** Downstream semantic fixtures use exact Normalize producer payloads. This module
 * depends only on leaf records, so Context/Execution may consume the map safely. */
export const normalizedModelFixtures: Record<string, Payload> = Object.fromEntries(modelInterfaceContracts.find(contract => contract.nodeId === 'lina-model-normalize')!.outputs.map(branch => [branch.id, modelField(branch, 'payload')]));
