/** Scoped Planning records for Studio inspection. JSON shape checks do not establish
 * dependency validity, authorization, evidence truth or durable persistence. */
import { choice, count, fixed, flag, list, nullable, object, sample, text, union } from './schema';

export const planningScope = object({ workspaceId: text('workspace-demo'), agentId: text('lina-main'), conversationId: text('conversation-demo'), historyBranchRef: text('history:main:active') });
export const planningIdentity = object({ goalId: text('goal:review:001'), planId: text('plan:review:001'), revision: count(3), scope: planningScope });
export const planningPolicy = object({ strategy: choice(['direct', 'model-led', 'authored-workflow'], 'model-led'), requirement: choice(['optional', 'plan-first'], 'optional'), executionMode: choice(['execute', 'plan-only', 'review-before-execution']), explorationCapabilityRefs: list(text('capability:source-read:v1')), maxReplans: count(3), replansUsed: count(1), mainLoopBudgetRef: text('budget:turn:001'), planningConsumesMainBudget: fixed(true), planAcceptanceGrantsActionPermission: fixed(false), policyRevision: count(2) });
export const planningAssessment = object({ assessmentRef: text('assessment:source:001'), method: choice(['deterministic-check', 'parent-model-review', 'specialist-model-review', 'human-review', 'model-assertion'], 'parent-model-review'), status: choice(['accepted', 'insufficient', 'failed', 'blocked', 'uncertain']), criterionIds: list(text('criterion:source:001')), evidenceRefs: list(text('artifact:source-findings:001')), assessorRef: text('agent:lina-main'), assessedAt: text('2026-10-08T12:00:00Z'), independentlyVerified: flag(false), rationale: text('The cited source revision supports the declared requirement.') });
export const planningDependency = object({ taskId: text('task:inspect'), condition: choice(['accepted-success', 'terminal-outcome']), producingAttemptId: nullable(text('attempt:inspect:001')), inputBinding: nullable(object({ field: text('sourceFindings'), artifactRef: text('artifact:source-findings:001'), artifactRevision: count(1), producerAttemptId: text('attempt:inspect:001'), immutable: fixed(true) })) });
export const planningAttempt = object({ attemptId: text('attempt:inspect:001'), taskId: text('task:inspect'), admittedRevision: count(3), executionKind: choice(['tool', 'subagent', 'main-agent', 'exploration']), operationId: text('operation:inspect:001'), callId: nullable(text('call:inspect:001')), childTaskId: sample(nullable(text('child-task:inspect:001')), null), childAgentId: sample(nullable(text('lina-child:001')), null), controllerRef: text('tools:turn:001'), permissionDecisionRef: text('safety:allow:inspect:001'), fingerprint: text('sha256:inspect-operation:001'), lifecycleGeneration: count(1), status: choice(['reserved', 'running', 'completed', 'failed', 'cancelled', 'unknown'], 'completed'), outcomeCertainty: choice(['known', 'unknown']), resultRefs: list(text('result:inspect:001')), unresolvedEffectRefs: list(text('effect:inspect:001'), []), replacedByAttemptId: sample(nullable(text('attempt:inspect:002')), null), lateResultCompletesReplacement: fixed(false) });
export const planningTask = object({ taskId: text('task:inspect'), title: text('Inspect changed source'), required: flag(true), dependsOn: list(planningDependency, []), status: choice(['pending', 'ready', 'in_progress', 'blocked', 'completed', 'failed', 'cancelled', 'skipped'], 'completed'), acceptanceCriteria: list(object({ criterionId: text('criterion:source:001'), description: text('Relevant source revisions inspected and referenced.'), evidenceMethod: choice(['deterministic-check', 'parent-model-review', 'specialist-model-review', 'human-review', 'model-assertion'], 'parent-model-review') }), undefined, 1), attemptIds: list(text('attempt:inspect:001')), evidenceRefs: list(text('artifact:source-findings:001')), assessment: nullable(planningAssessment), blockerRefs: list(text('blocker:source-unavailable:001'), []), skippedByAcceptedRevision: sample(nullable(count(4)), null) });
const pendingTask = { ...(planningTask.example as Record<string, import('./schema').Json>), taskId: 'task:synthesize', title: 'Synthesize findings', status: 'pending', dependsOn: [planningDependency.example], attemptIds: [], evidenceRefs: [], assessment: null, acceptanceCriteria: [{ criterionId: 'criterion:synthesis:001', description: 'Claims cite retained source evidence.', evidenceMethod: 'parent-model-review' }] };
export const planningPlan = object({ schemaVersion: fixed(1), identity: planningIdentity, goal: text('Review the proposed change and report supported findings.'), goalCriteria: list(object({ criterionId: text('criterion:goal:001'), description: text('Required source checks and synthesis are accepted.'), evidenceMethod: choice(['deterministic-check', 'parent-model-review', 'human-review', 'model-assertion'], 'parent-model-review') }), undefined, 1), constraints: list(text('Read-only review; cite inspected artifacts.')), policy: planningPolicy, status: choice(['draft', 'active', 'waiting', 'paused', 'completed', 'failed', 'cancelled', 'superseded'], 'active'), tasks: list(planningTask, [planningTask.example, pendingTask]), attempts: list(planningAttempt), supersedesRevision: nullable(count(2)), replanReasonRef: nullable(text('observation:additional-source:001')), acceptedGoalRevisionRef: text('goal-revision:001'), authorityFromPlan: fixed(false) });
export const planningProjection = object({ identity: planningIdentity, projectionRef: text('context-plan:review:r3'), goal: text('Review proposed change.'), constraints: list(text('Read-only review.')), activeTaskIds: list(text('task:synthesize')), blockedTaskIds: list(text('task:missing-source'), []), acceptedEvidenceRefs: list(text('artifact:source-findings:001')), omittedTaskIds: list(text('task:archived'), []), sourceRecordRef: text('state:plan:review:r3'), tokenBudget: count(500), canonicalPlanMutatedByCompaction: fixed(false), classification: choice(['workspace', 'private'], 'private'), provenance: fixed('scoped-canonical-task-plan'), instructionAuthority: fixed(false) });
const commandBase = { commandId: text('plan-update:001'), callId: text('call:plan-update:001'), planId: text('plan:review:001'), scope: planningScope, actorAgentId: text('lina-main'), expectedRevision: count(3), fingerprint: text('sha256:plan-update:001'), reasonRef: text('decision:begin-synthesis:001') };
export const planningCommandVariants = [
 object({ ...commandBase, operation: fixed('create_plan'), expectedRevision: fixed(0), proposedPlan: sample(planningPlan, { ...(planningPlan.example as Record<string, import('./schema').Json>), identity: { ...(planningIdentity.example as Record<string, import('./schema').Json>), revision: 1 }, status: 'draft', tasks: [{ ...(planningTask.example as Record<string, import('./schema').Json>), status: 'pending', attemptIds: [], evidenceRefs: [], assessment: null }], attempts: [], supersedesRevision: null, replanReasonRef: null }) }),
 object({ ...commandBase, operation: fixed('update_task'), taskId: text('task:synthesize'), set: object({ status: choice(['pending', 'in_progress', 'blocked', 'completed', 'failed', 'cancelled', 'skipped']), assessment: sample(nullable(planningAssessment), null), blockerRefs: list(text('blocker:source-unavailable:001'), []), evidenceRefs: list(text('artifact:source-findings:001'), []) }), requirementChanged: fixed(false) }),
 object({ ...commandBase, operation: fixed('revise_plan'), proposedPlan: planningPlan, acceptedGoalRevisionRef: text('goal-revision:002'), preserveCompletedAttemptIds: list(text('attempt:inspect:001')), runningExecutionControlIds: list(text('control:cancel:inspect:001'), []), planEditImplicitlyCancelsWork: fixed(false) }),
 object({ ...commandBase, operation: fixed('record_assessment'), taskId: text('task:inspect'), attemptId: text('attempt:inspect:001'), assessment: planningAssessment }),
 object({ ...commandBase, operation: fixed('set_plan_status'), status: choice(['active', 'waiting', 'paused', 'failed', 'cancelled']), reasonRef: text('user-control:pause:001') }),
];
export const planningCommand = union(...planningCommandVariants);
export const planningCommandFor = (operation: string) => planningCommandVariants.find(value => (value.example as Record<string, import('./schema').Json>).operation === operation)!;
export const planningMutationReceipt = object({ commandId: text('plan-update:001'), callId: text('call:plan-update:001'), planId: text('plan:review:001'), scope: planningScope, fingerprint: text('sha256:plan-update:001'), status: choice(['applied', 'duplicate', 'conflict', 'invalid', 'failed', 'unknown']), previousRevision: count(3), revision: nullable(count(4)), receiptRef: nullable(text('state-receipt:plan-update:001')), errors: list(object({ code: choice(['missing-dependency', 'self-dependency', 'cyclic-dependency', 'revision-conflict', 'fingerprint-conflict', 'scope-denied', 'required-task-skipped', 'uncertain-effect', 'storage-unavailable']), taskId: nullable(text('task:synthesize')), message: text('Dependency refers to a task outside this accepted plan revision.') }), []), launchedWork: fixed(false), inspectOriginalTransaction: flag(false), retriesUseOriginalIdentity: fixed(true) });
export const planningReadiness = object({ identity: planningIdentity, readyTaskIds: list(text('task:synthesize')), blocked: list(object({ taskId: text('task:cleanup'), reason: choice(['dependency-pending', 'dependency-failed', 'evidence-not-accepted', 'explicit-blocker', 'running-attempt', 'scope-refused']), dependencyTaskIds: list(text('task:inspect')), blockerRefs: list(text('blocker:source-unavailable:001'), []) }), []), runningAttemptIds: list(text('attempt:inspect:001'), []), concurrency: choice(['sequential', 'independent-parallel']), requiredTaskIds: list(text('task:synthesize')), completionCandidate: flag(false), dependencyGraphValidated: fixed(true), launchesExecution: fixed(false), permissionGranted: fixed(false) });
export const planningLocalContext = object({ storage: fixed('fixture-only'), scope: planningScope, policy: planningPolicy, currentPlan: nullable(planningPlan), projection: nullable(planningProjection), planRecordRevision: count(3), currentOwnerGeneration: count(2), originalCommand: nullable(planningCommand), unresolvedEffectRefs: list(text('effect:inspect:unknown'), []), sharedChildMutablePlan: fixed(false), trustedCoordinatorSuppliesContext: fixed(true) });
