import { environmentTarget } from './environmentRecords';
/** Shared, reference-only Safety design records. Studio fixtures make no claim of
 * real durable storage, atomic dispatch or authenticated human review. */
import { choice, count, fixed, flag, list, nullable, object, replaceField, text, union, type Json, type Payload } from './schema';
import { jsonValue, permissionApprovalChoices } from './shared';
export const safetyChoices = permissionApprovalChoices;
export function safetyField(record: Payload, key: string): Payload {
 const example = record.example as Record<string, Json>;
 const properties = record.schema.properties ?? record.schema.anyOf?.find(branch => branch.properties?.kind?.const === example.kind)?.properties;
 if (!properties?.[key]) throw new Error(`Missing Safety record field ${key}`);
 return { schema: properties[key], example: example[key] };
}
export const extendSafetyRecord = (record: Payload, fields: Record<string, Payload>): Payload => object({ ...Object.fromEntries(Object.entries(record.schema.properties!).map(([key, schema]) => [key, { schema, example: (record.example as Record<string, Json>)[key] }])), ...fields });
const absent = (record: Payload) => ({ schema: nullable(record).schema, example: null });
export const safetyBinding = object({ adapterRef: text('adapter:builtin:v1'), capabilityId: text('tool:builtin:calculator'), catalogRevision: text('catalog:demo:7'), schemaDigest: text('sha256:fixture-calculator-schema'), connectionId: absent(text('conn-docs-demo')), accountId: absent(text('account-demo')), readinessGeneration: count(1), hookGeneration: count(3), environmentTarget: absent(environmentTarget) });
export const safetyIdentity = object({ requestId: text('safety-request:call-001:1'), operationId: text('call-001'), principalId: text('person-demo'), workspaceId: text('workspace-demo'), agentId: text('lina-main'), permissionSessionId: text('permission-session:demo:1'), permissionSessionEpoch: count(1), turnId: text('turn-001'), roundId: nullable(text('round-001')), ownerNodeId: choice(['lina-tools-permissions', 'lina-tools-resource-read', 'lina-tools-prompt-get']), ownerRevision: count(1), executionFence: count(1) });
const tool = object({ kind: fixed('tool-call'), callId: text('call-001'), batchId: text('batch-001'), name: text('calculator'), arguments: jsonValue({ expression: '2 + 2' }), argumentDigest: text('sha256:fixture-arguments-2plus2'), target: text('builtin:calculator'), effectClass: choice(['read', 'write', 'unknown'], 'read') });
const acquisition = (kind: string, dependencyId: string, selection: Payload, digest: string) => object({ kind: fixed(kind), dependencyId: text(dependencyId), preparationId: text('prepare:turn-001:round-001:r0'), snapshotCandidateId: text('candidate-001'), candidateRevision: count(0), required: flag(true), selection, argumentDigest: text(digest), effectClass: fixed('read'), maxBytes: count(32768) });
export const safetyResourceOperation = acquisition('resource-read', 'context-dependency-001', object({ uri: text('docs://guide'), inventoryRevision: text('resources:7') }), 'sha256:fixture-resource-selection');
export const safetyPromptOperation = extendSafetyRecord(acquisition('prompt-get', 'context-dependency-002', object({ name: text('review-document'), inventoryRevision: text('prompts:7') }), 'sha256:fixture-prompt-arguments'), { arguments: object({ documentId: text('document-001') }) });
export const safetyOperation = object({ identity: safetyIdentity, operation: union(tool, safetyResourceOperation, safetyPromptOperation), binding: safetyBinding, validatedAfterHooks: fixed(true), originalOwnerRequestRef: text('retained:batch-001:call-001'), siblingEvidenceRef: text('batch-001:settled-siblings'), modelRoundStartedByPermission: fixed(false), credentialsIncluded: fixed(false) });
export const safetyAcquisitionOperation = (kind: 'resource-read' | 'prompt-get'): Payload => {
 const isResource = kind === 'resource-read';
 const identity = replaceField(replaceField(replaceField(safetyIdentity, 'ownerNodeId', fixed(`lina-tools-${kind}`)), 'operationId', text(isResource ? 'context-dependency-001' : 'context-dependency-002')), 'requestId', text(`safety-request:${kind}:1`));
 const binding = replaceField(replaceField(replaceField(replaceField(safetyBinding, 'adapterRef', text('adapter:mcp-http:v1')), 'connectionId', text('conn-docs-demo')), 'accountId', text('account-demo')), 'capabilityId', text(isResource ? 'resource:docs-guide' : 'prompt:review-document'));
 const scopedBinding = replaceField(binding, 'schemaDigest', text(isResource ? 'sha256:fixture-resource-selection' : 'sha256:fixture-prompt-schema'));
 return replaceField(replaceField(replaceField(replaceField(safetyOperation, 'identity', identity), 'operation', isResource ? safetyResourceOperation : safetyPromptOperation), 'binding', scopedBinding), 'originalOwnerRequestRef', text(isResource ? 'retained:resource-read:context-dependency-001' : 'retained:prompt-get:context-dependency-002'));
};
export const safetyScope = object({ matcherKind: choice(['exact-operation', 'reviewed-resource'], 'exact-operation'), principalId: text('person-demo'), workspaceId: text('workspace-demo'), agentId: text('lina-main'), capabilityId: text('tool:builtin:calculator'), adapterRef: text('adapter:builtin:v1'), connectionId: absent(text('conn-docs-demo')), accountId: absent(text('account-demo')), target: text('builtin:calculator'), argumentMatcher: object({ kind: fixed('exact-digest'), digest: text('sha256:fixture-arguments-2plus2') }), schemaDigest: text('sha256:fixture-calculator-schema'), delegateToChildren: fixed(false), environmentTarget: absent(environmentTarget), reviewDescription: text('Calculator with exactly expression 2 + 2, in this workspace and agent.') });
export const safetyPolicy = object({ policyRef: text('permission-policy:demo:v1'), revision: count(1), generation: count(1), source: fixed('trusted-coordinator-configuration'), precedence: fixed(['hard-deny', 'mandatory-review', 'policy-allow-or-grant', 'ask']), defaultDecision: fixed('ask'), ruleId: text('fixture:review-calculator'), decision: choice(['allow', 'deny', 'ask'], 'ask'), grantReuseAllowed: flag(true), supportedChoices: list(choice(safetyChoices), safetyChoices, 1), childScopeCeilingRef: text('policy:children:nondelegable'), annotationsAreAuthority: fixed(false) });
export const safetyPolicyRequest = object({ request: safetyOperation, requiredPolicyGeneration: count(1) });
export const safetyPolicyReady = object({ request: safetyOperation, policy: safetyPolicy });
export const safetyEvaluation = object({ request: safetyOperation, decisionRef: text('safety-decision:call-001:1'), decision: choice(['allow', 'deny', 'approval-required', 'unavailable'], 'allow'), reason: text('eligible-scoped-grant-within-current-policy'), policy: safetyPolicy, matchingGrantRef: nullable(text('grant:call-001:1')), admissionGeneration: count(1), permitsPhysicalLaunch: fixed(false), knownNoEffect: fixed(true) });
export const safetyApprovalRequest = object({ request: safetyOperation, policy: safetyPolicy, waitId: text('wait:approval:call-001'), promptId: text('prompt-001'), waitRevision: count(1), eligibleResponderIds: list(text('person-demo'), ['person-demo'], 1), expiresAt: text('2026-10-08T12:05:00Z'), displayedScope: safetyScope, choices: list(choice(safetyChoices), safetyChoices, 1), registered: flag(false), dispatched: fixed(false), settledSiblingResultsPreserved: fixed(true) });
export const safetyRegisteredWait = replaceField(safetyApprovalRequest, 'registered', fixed(true));
export const safetyAnswer = object({ retainedWait: safetyRegisteredWait, promptId: text('prompt-001'), waitId: text('wait:approval:call-001'), waitRevision: count(1), operationId: text('call-001'), responderId: text('person-demo'), choice: choice(safetyChoices), answerEvidenceRef: text('approval-answer:prompt-001:1'), acceptedInputId: text('input-answer-001'), decisionSource: choice(['human', 'trusted-client-policy'], 'human'), matchedScopeDigest: text('sha256:fixture-reviewed-scope'), receivedAt: text('2026-10-08T12:01:00Z') });
export const safetyApprovalResolution = object({ retainedWait: safetyRegisteredWait, status: choice(['allowed', 'denied', 'expired', 'cancelled'], 'allowed'), selectedChoice: choice(safetyChoices), grantLifetime: choice(['logical-operation', 'permission-session', 'persistent', 'none'], 'logical-operation'), decisionSource: choice(['human', 'trusted-client-policy', 'expiry', 'stop'], 'human'), answerEvidenceRef: nullable(text('approval-answer:prompt-001:1')), waitConsumedRevision: count(2), permanentDenyCreated: fixed(false), grantsLaunchPermission: fixed(false) });
export const safetyGrant = object({ grantId: text('grant:call-001:1'), grantRevision: count(1), grantGeneration: count(1), lifetime: choice(['logical-operation', 'permission-session', 'persistent'], 'logical-operation'), scope: safetyScope, operationId: nullable(text('call-001')), permissionSessionId: nullable(text('permission-session:demo:1')), permissionSessionEpoch: nullable(count(1)), expiresAt: nullable(text('2026-10-08T12:05:00Z')), status: choice(['active', 'revoked', 'expired'], 'active'), sourceDecisionRef: text('approval-answer:prompt-001:1'), policyGenerationAtIssue: count(1), storage: choice(['operation-local', 'runtime-session-fixture', 'durable-store-fixture'], 'operation-local'), persisted: flag(false), survivesRuntimeRestart: flag(false), useAfterKnownNoEffectRetry: fixed('same-logical-operation-fresh-attempt-admission'), delegateToChildren: fixed(false) });
export const safetyLookup = object({ action: fixed('lookup'), request: safetyOperation, policy: safetyPolicy, lookupId: text('grant-lookup:call-001:1') });
export const safetyLookupResult = object({ lookup: safetyLookup, status: choice(['matched', 'missing', 'expired', 'revoked', 'unavailable'], 'matched'), grant: nullable(safetyGrant), evidenceRef: text('grant-lookup-evidence:call-001:1'), grantsLaunchPermission: fixed(false) });
export const safetyCommit = object({ action: fixed('commit'), transactionId: text('grant-tx:call-001:1'), resolution: safetyApprovalResolution, grant: safetyGrant, idempotencyKey: text('grant-commit:prompt-001:revision-1'), storageOwnerRef: text('fixture:safety-grant-store'), liveDurableStoreImplemented: fixed(false) });
export const safetyCommitResult = object({ command: safetyCommit, transactionId: text('grant-tx:call-001:1'), status: choice(['applied', 'already-applied', 'failed', 'unknown', 'conflict'], 'applied'), grant: nullable(safetyGrant), acknowledged: flag(true), mayDispatch: flag(true), inspectBeforeRetry: flag(false), evidenceRef: text('grant-tx-evidence:1'), externalEffectUncertainty: fixed(false) });
export const safetyLaunchRequest = object({ request: safetyOperation, admission: safetyEvaluation, attemptId: text('tool-attempt-001'), launchId: text('launch:call-001:attempt-001'), expectedAdmissionGeneration: count(1), currentAdmissionGeneration: count(1), currentPolicyGeneration: count(1), currentGrantGeneration: count(1), currentBinding: safetyBinding, currentArgumentsDigest: text('sha256:fixture-arguments-2plus2'), currentOwnerRevision: count(1), currentExecutionFence: count(1), stopped: flag(false), knownNoEffectRetryEvidenceRef: absent(text('evidence:call-001:known-no-effect')) });
export const safetyReservation = object({ action: choice(['reserve', 'consume', 'release'], 'reserve'), transactionId: text('grant-reservation-tx:call-001:attempt-001'), launch: safetyLaunchRequest, grantId: text('grant:call-001:1'), expectedGrantGeneration: count(1), reservationId: text('reservation:call-001:attempt-001'), idempotencyKey: text('launch:call-001:attempt-001'), releaseRequiresKnownNoEffect: fixed(true) });
export const safetyReservationResult = object({ command: safetyReservation, status: choice(['reserved', 'consumed', 'released', 'already-applied', 'conflict', 'failed', 'unknown'], 'reserved'), reservationId: text('reservation:call-001:attempt-001'), grantGeneration: count(1), evidenceRef: text('reservation-evidence:1'), grantsPhysicalLaunch: fixed(false) });
export const safetyLaunchDecision = object({ launch: safetyLaunchRequest, status: choice(['allowed', 'denied', 'stale', 'cancelled', 'unavailable'], 'allowed'), reason: text('live-operation-policy-grant-and-owner-match'), launchPermitRef: nullable(text('launch-permit:call-001:attempt-001')), reservationRef: nullable(text('reservation:call-001:attempt-001')), admissionGeneration: count(1), exactLaunchId: text('launch:call-001:attempt-001'), singlePhysicalAttempt: fixed(true), dispatcherMustCompareFenceAtLaunch: fixed(true), effectOccurred: fixed(false), atomicRuntimeEnforcementImplemented: fixed(false) });
export const safetyInvalidation = object({ operationId: text('call-001'), requestId: text('safety-request:call-001:1'), waitId: nullable(text('wait:approval:call-001')), reason: choice(['stop', 'session-ended', 'policy-changed', 'grant-revoked', 'owner-superseded'], 'stop'), newAdmissionGeneration: count(2), persistentGrantsAutomaticallyRevoked: fixed(false), alreadyStartedEffectsRolledBack: fixed(false), siblingEvidencePreserved: fixed(true) });
/** Derive every correlated permission record from the retained producer request,
 * including acquisition dependency IDs. A shared schema must not fabricate a
 * calculator call identity when illustrating a resource or prompt retrieval. */
export function safetyScopeFor(request: Payload): Payload {
 const identity = safetyField(request, 'identity');
 const operation = safetyField(request, 'operation');
 const binding = safetyField(request, 'binding');
 const operationExample = operation.example as Record<string, Json>;
 const selection = operationExample.selection as Record<string, Json> | undefined;
 const target = String(operationExample.target ?? selection?.uri ?? selection?.name);
 return extendSafetyRecord(safetyScope, { principalId: safetyField(identity, 'principalId'), workspaceId: safetyField(identity, 'workspaceId'), agentId: safetyField(identity, 'agentId'), capabilityId: safetyField(binding, 'capabilityId'), adapterRef: safetyField(binding, 'adapterRef'), connectionId: safetyField(binding, 'connectionId'), accountId: safetyField(binding, 'accountId'), target: text(target), argumentMatcher: object({ kind: fixed('exact-digest'), digest: safetyField(operation, 'argumentDigest') }), schemaDigest: safetyField(binding, 'schemaDigest'), environmentTarget: safetyField(binding, 'environmentTarget'), reviewDescription: text(`Exactly the selected ${String(operationExample.kind)} operation on ${target}, in this workspace and agent.`) });
}
export function safetyApprovalFor(request: Payload, registered = false): Payload {
 const operationId = (safetyField(request, 'identity').example as Record<string, Json>).operationId as string;
 return extendSafetyRecord(safetyApprovalRequest, { request, waitId: text(`wait:approval:${operationId}`), promptId: text(`prompt:${operationId}`), displayedScope: safetyScopeFor(request), registered: fixed(registered) });
}
export function safetyAnswerFor(request: Payload): Payload {
 const wait = safetyApprovalFor(request, true);
 return extendSafetyRecord(safetyAnswer, { retainedWait: wait, promptId: safetyField(wait, 'promptId'), waitId: safetyField(wait, 'waitId'), operationId: safetyField(safetyField(request, 'identity'), 'operationId') });
}
export function safetyLaunchFor(request: Payload): Payload {
 const operationId = (safetyField(request, 'identity').example as Record<string, Json>).operationId as string;
 return extendSafetyRecord(safetyLaunchRequest, { request, admission: replaceField(safetyEvaluation, 'request', request), attemptId: text(`attempt:${operationId}:1`), launchId: text(`launch:${operationId}:1`), currentBinding: safetyField(request, 'binding'), currentArgumentsDigest: safetyField(safetyField(request, 'operation'), 'argumentDigest') });
}
export function safetyLaunchDecisionFor(request: Payload): Payload {
 const launch = safetyLaunchFor(request);
 return extendSafetyRecord(safetyLaunchDecision, { launch, exactLaunchId: safetyField(launch, 'launchId') });
}
