import { choice, count, fixed, flag, list, nullable, object, output, replaceField, text, type ContractDefinition, type Json, type Payload } from './schema';
import { approvalPromptAnswer } from './shared';
import { extendSafetyRecord as extend, safetyAcquisitionOperation, safetyApprovalFor, safetyAnswerFor, safetyLaunchFor, safetyLaunchDecisionFor, safetyAnswer, safetyApprovalRequest, safetyApprovalResolution, safetyBinding, safetyChoices, safetyCommit, safetyCommitResult, safetyEvaluation, safetyGrant, safetyIdentity, safetyInvalidation, safetyLaunchDecision, safetyLaunchRequest, safetyLookup, safetyLookupResult, safetyOperation, safetyPolicy, safetyPolicyReady, safetyPolicyRequest, safetyRegisteredWait, safetyReservation, safetyReservationResult, safetyScope } from './safetyRecords';
const edges = (...ids: string[]) => ids.map(id => `lina-safety-edge-${id}`);
const refine = (value: Payload, fields: Record<string, Payload>) => Object.entries(fields).reduce((record, [key, field]) => replaceField(record, key, field), value);
const local = object({ designOnly: fixed(true), grantStore: fixed('deterministic-fixture'), liveDurableStoreImplemented: fixed(false), policyGeneration: count(1), grantGeneration: count(1), admissionGeneration: count(1), permissionSessionId: text('permission-session:demo:1'), permissionSessionEpoch: count(1), sessionActive: flag(true), runtimeRestartInvalidatesSessionGrants: fixed(true), stopped: flag(false), trustedConfigurationOwner: fixed('coordinator'), privateCredentialsIncluded: fixed(false), statePersistenceDependency: fixed('future-State-owner-not-implemented'), delegateToChildren: fixed(false) });
const definition = (id: string, reads: string[], writes: string[], rules: string[], outputs: ContractDefinition['outputs'], external: ContractDefinition['external'] = []): ContractDefinition => ({ nodeId: `lina-safety-${id}`, context: local, contextSource: 'Retained operation owner supplies immutable bindings and live generations. Trusted coordinator policy and the deterministic grant fixture supply reference-only dependencies.', reads, writes, rules, outputs, external });
const rejected = (code: string) => object({ retainedWait: safetyRegisteredWait, answer: safetyAnswer, reason: fixed(code), authorizationGranted: fixed(false), owningWaitPreserved: fixed(true), siblingEvidencePreserved: fixed(true) });
const decision = (status: string, reason: string) => refine(safetyEvaluation, { decision: fixed(status), reason: text(reason) });
const noLaunch = (status: string, reason: string) => refine(safetyLaunchDecision, { status: fixed(status), reason: text(reason), launchPermitRef: fixed(null), reservationRef: fixed(null) });
const operationDecision = object({ evaluation: safetyEvaluation, grantEvidenceRef: nullable(text('grant-tx-evidence:1')), status: choice(['allowed', 'denied', 'unavailable', 'cancelled'], 'allowed'), authorizationStage: fixed('scheduling-admission'), admissionGeneration: count(1), permitsPhysicalLaunch: fixed(false), settledSiblingResultsPreserved: fixed(true) });
const denyResolution = (status: string, source: string) => refine(safetyApprovalResolution, { status: fixed(status), selectedChoice: fixed('deny'), grantLifetime: fixed('none'), decisionSource: fixed(source) });
const lifetimes = [
 { choice: 'allow-once', lifetime: 'logical-operation', storage: 'operation-local', persisted: false, survives: false },
 { choice: 'allow-session', lifetime: 'permission-session', storage: 'runtime-session-fixture', persisted: false, survives: false },
 { choice: 'allow-always', lifetime: 'persistent', storage: 'durable-store-fixture', persisted: true, survives: true },
];
export const safetyPermissionContracts: ContractDefinition[] = [
 definition('policy', ['Exact operation principal, agent/workspace scope and required policy revision', 'Trusted configuration and explicit precedence'], ['Versioned rules or unavailable policy evidence'], ['Model text, plugin metadata, OAuth readiness and server read-only hints cannot amend policy.', 'Hard deny wins over mandatory review; mandatory review wins over reusable allow unless the rule explicitly permits reuse.', 'Required configuration errors withhold dispatch; missing rules do not fabricate authority.'], [
  output('safety.policy-ready', 'Trusted policy resolved', safetyPolicyReady, edges('policy-evaluate'), 'Required trusted policy generation is available.'),
  output('safety.policy-hard-deny', 'Hard deny policy resolved', replaceField(safetyPolicyReady, 'policy', refine(safetyPolicy, { decision: fixed('deny'), ruleId: text('managed:deny-target'), grantReuseAllowed: fixed(false) })), edges('policy-evaluate'), 'Hard deny cannot be overridden by a saved grant.'),
  output('safety.policy-always-review', 'Mandatory review resolved', replaceField(safetyPolicyReady, 'policy', refine(safetyPolicy, { decision: fixed('ask'), ruleId: text('managed:always-review'), grantReuseAllowed: fixed(false) })), edges('policy-evaluate'), 'A matching grant cannot satisfy this always-review rule.'),
  output('safety.policy-unavailable', 'Required policy unavailable', object({ request: safetyOperation, status: fixed('unavailable'), requiredPolicyGeneration: count(1), code: choice(['missing-configuration', 'evaluation-error', 'stale-policy'], 'missing-configuration'), permitsDispatch: fixed(false), evidenceRef: text('policy-error:1') }), edges('policy-evaluate'), 'Missing or erroneous required policy holds the operation.'),
 ]),
 definition('evaluate', ['Post-hook validated operation and immutable bindings', 'Correlated policy and grant lookup response'], ['Dependency requests and reasoned operation decision'], ['Resolve required policy once per operation generation and join the matching lookup response. Dependency returns are not fresh tool requests.', 'Compare actor/workspace/agent, adapter/account/target, argument/schema digest and grant lifetime.', 'Authentication and tool visibility are independent of permission. Acquisition retains its Context preparation/dependency identity without opening a model round.'], [
  output('safety.policy-requested', 'Resolve operation policy', safetyPolicyRequest, edges('evaluate-policy'), 'A fresh validated request needs its trusted policy.'),
  output('safety.grant-lookup', 'Find matching scoped grant', safetyLookup, edges('evaluate-grants'), 'Policy permits grant reuse and scope evidence is current.'),
  output('safety.operation-allowed', 'Policy or scoped grant allows scheduling', safetyEvaluation, edges('evaluate-authorize'), 'An eligible policy or matching grant allows scheduling admission.'),
  output('safety.operation-denied', 'Policy denies operation', decision('deny', 'hard-deny-rule'), edges('evaluate-authorize'), 'Hard deny does not create a prompt or grant.'),
  output('safety.operation-unavailable', 'Required permission evidence unavailable', decision('unavailable', 'required-policy-or-grant-store-unavailable'), edges('evaluate-authorize'), 'No launch while required evidence is missing.'),
  output('safety.approval-required', 'Exact operation requires review', safetyApprovalRequest, edges('evaluate-approval'), 'No eligible reusable grant satisfies the current policy.'),
 ]),
 definition('approval', ['Exact retained operation, reviewed matcher, supported choices and eligible responders', 'Execution registration acknowledgment and owner-forwarded answer/control'], ['Retained wait, prompt request or typed resolution'], ['Register the retained wait before delivering the prompt. Auto advances simulation steps but does not impersonate human approval.', 'Match wait/prompt/operation/revision/responder, reviewed scope and expiry. Wrong and duplicate answers leave the real wait and siblings intact.', 'Deny refuses this operation without creating a standing deny rule. Stop does not revoke unrelated persistent grants.', 'Record decision source separately because a trusted client can automatically resolve protocol permission requests.'], [
  output('safety.approval-waiting', 'Operation approval retained by Tools', safetyApprovalRequest, edges('approval-wait-tools'), 'Retain call before asking Execution to register its wait.'),
  output('safety.resource-approval-waiting', 'Resource approval retained by acquisition owner', safetyApprovalFor(safetyAcquisitionOperation('resource-read')), edges('approval-wait-resource'), 'Retain resource preparation and dependency, not a fabricated model call.'),
  output('safety.prompt-approval-waiting', 'Prompt approval retained by acquisition owner', safetyApprovalFor(safetyAcquisitionOperation('prompt-get')), edges('approval-wait-prompt'), 'Retain prompt retrieval under its existing acquisition owner.'),
  output('safety.approval-prompt-requested', 'Four-choice operation review prompt', object({ retainedWait: safetyRegisteredWait, deliveryId: text('delivery:prompt-001'), destinationRef: text('destination:accepted-input:1'), category: fixed('challenge'), text: text('Allow calculator expression 2 + 2 with the displayed scope?'), choices: list(choice(safetyChoices), safetyChoices, 1), scope: safetyScope, eligibleResponderIds: list(text('person-demo'), ['person-demo'], 1), deliveredMeansApproved: fixed(false) }), edges('approval-prompt'), 'Execution acknowledged registration; delivery can now show the exact matcher and supported choices.'),
  output('safety.approval-denied', 'Pending operation denied', denyResolution('denied', 'human'), edges('approval-authorize'), 'Eligible responder selected Deny; no permanent rule is saved.'),
  output('safety.approval-expired', 'Pending approval expired', denyResolution('expired', 'expiry'), edges('approval-authorize'), 'Expiry releases no launch authority.'),
  output('safety.approval-cancelled', 'Stop cancels unstarted operation', denyResolution('cancelled', 'stop'), edges('approval-authorize'), 'The exact operation is invalidated; a late answer cannot revive it.'),
  ...['wrong-responder', 'wrong-prompt', 'wrong-operation', 'expired-answer', 'duplicate-answer', 'changed-arguments', 'changed-binding', 'changed-policy', 'unsupported-choice'].map(code => output(`safety.approval-rejected-${code}`, `Review answer rejected: ${code}`, rejected(code), [], 'Keep the owning unresolved wait and inspect rejection evidence.')),
 ]),
 definition('grants', ['Tagged lookup, commit, inspect, reservation, release, consumption and revocation commands', 'Current permission-session epoch and trusted storage acknowledgments'], ['Scoped matching evidence and idempotent transaction outcomes'], ['Every command has a stable transaction/lookup/launch identity. Replayed answers cannot create another grant.', 'Session grants expire on session end and do not survive runtime restart. Stop of one operation does not end the permission session.', 'Persistent grants are acknowledged before claiming success; unknown storage acknowledgment is inspected by transaction ID before retry.', 'Reservation is launch-specific. A known-no-effect retry may reuse the same logical-operation grant with fresh attempt admission; unknown external effects require Tools reconciliation.', 'Revocation changes the admission generation and cannot undo an already-started effect. Grant storage uncertainty never becomes external-effect uncertainty.', 'Child delegation is disabled by default; model-generated commands cannot grant, broaden or revoke trusted authority.'], [
  output('safety.grant-matched', 'Eligible scoped grant found', safetyLookupResult, edges('grants-evaluate'), 'Scope and lifetime match current policy.'),
  ...['missing', 'expired', 'revoked', 'unavailable'].map(status => output(`safety.grant-${status}`, `Grant lookup ${status}`, refine(safetyLookupResult, { status: fixed(status), grant: fixed(null) }), edges('grants-evaluate'), 'A nonmatching or unavailable grant supplies no permission.')),
  output('safety.grant-committed', 'Grant transaction acknowledged', safetyCommitResult, edges('grants-authorize'), 'Fixture storage acknowledges this exact transaction; this is not live durable persistence.'),
  ...['failed', 'unknown', 'conflict'].map(status => output(`safety.grant-commit-${status}`, `Grant commit ${status}`, refine(safetyCommitResult, { status: fixed(status), grant: fixed(null), acknowledged: fixed(false), mayDispatch: fixed(false), inspectBeforeRetry: fixed(status === 'unknown') }), edges('grants-authorize'), 'Failed/uncertain commit cannot advertise a saved grant or authorize dispatch.')),
  output('safety.grant-reserved', 'Exact launch reservation acquired', safetyReservationResult, edges('reservation-authorize'), 'One launch reserves the matching logical-operation grant.'),
  ...['consumed', 'released', 'already-applied', 'conflict', 'failed', 'unknown'].map(status => output(`safety.reservation-${status}`, `Launch reservation ${status}`, refine(safetyReservationResult, { status: fixed(status), command: replaceField(safetyReservation, 'action', fixed(status === 'released' ? 'release' : status === 'consumed' ? 'consume' : 'reserve')) }), edges('reservation-authorize'), 'Transaction outcome remains correlated to the same launch; duplicate launch never creates a second physical permit.')),
  output('safety.grant-inspected', 'Unknown commit inspected by stable transaction ID', object({ action: fixed('inspect'), transactionId: text('grant-tx:call-001:1'), status: choice(['applied', 'absent', 'still-unknown'], 'applied'), grant: nullable(safetyGrant), replayBeforeInspection: fixed(false), evidenceRef: text('grant-inspection:1') }), edges('grants-authorize'), 'Inspect the original transaction before deciding whether a bounded idempotent retry is safe.'),
  output('safety.grant-revocation-applied', 'Trusted revocation acknowledged', object({ grantId: text('grant:call-001:1'), action: fixed('revoke'), previousGeneration: count(1), newGeneration: count(2), invalidation: replaceField(safetyInvalidation, 'reason', fixed('grant-revoked')), alreadyStartedEffectsRolledBack: fixed(false) }), [], 'Trusted revocation rejects subsequent stale admissions; started effects remain owned by Tools.'),
  output('safety.session-ended', 'Session grants invalidated', object({ permissionSessionId: text('permission-session:demo:1'), previousEpoch: count(1), currentEpoch: count(2), runtimeSessionGrantsInvalidated: fixed(true), persistentGrantsInvalidated: fixed(false) }), [], 'Session end or restart invalidates runtime-only grants, independently of operation Stop.'),
 ], [{ label: 'Trusted grant management command', source: 'Explicit trusted user/policy management, separate from model tool requests', value: object({ action: choice(['revoke', 'inspect', 'session-end'], 'revoke'), transactionId: text('grant-management:1'), grantId: nullable(text('grant:call-001:1')), authorizedManagementPrincipalId: text('person-demo'), source: fixed('trusted-coordinator') }) }]),
 definition('authorize', ['Admission decision or exact queued launch, current generations and Stop state', 'Acknowledged grant commit/reservation or typed approval refusal'], ['Scheduling admission, reservation request and bounded exact-launch permit'], ['Scheduling admission is not a physical launch permit. Recheck final arguments, schema/account/adapter, policy/grant generation, live owner/fence and Stop after queueing.', 'A permit binds one physical attempt and admission epoch; dispatcher must compare the epoch at actual launch. Studio documents this fence but does not implement a production atomic transaction.', 'A reservation alone does not establish launch or effect success; consume/launch admission and recording remain one specified future runtime boundary.', 'Revocation/Stop forbids new launch without fabricating rollback of started siblings. Authentication answers cannot resolve operation approval.', 'Unknown grant transaction outcomes hold dispatch. Unknown external effects remain with Tools rather than being converted to permission denials.'], [
  output('safety.operation-decided', 'Allowed operation returns to scheduling owner', operationDecision, edges('decision-tools'), 'Current admission returns to Tools permissions, then existing scheduling.'),
  ...['denied', 'unavailable', 'cancelled'].map(status => output(`safety.operation-decided-${status}`, `Operation admission ${status}`, refine(operationDecision, { status: fixed(status), evaluation: decision(status === 'cancelled' ? 'deny' : status === 'denied' ? 'deny' : 'unavailable', `operation-${status}`) }), edges('decision-tools'), 'Tools records a known unstarted result and preserves siblings.')),
  output('safety.resource-operation-decided', 'Resource admission returns to its owner', replaceField(operationDecision, 'evaluation', replaceField(safetyEvaluation, 'request', safetyAcquisitionOperation('resource-read'))), edges('resource-read-return'), 'Acquisition retains required/optional dependency handling and proceeds to its final launch check.'),
  output('safety.prompt-operation-decided', 'Prompt admission returns to its owner', replaceField(operationDecision, 'evaluation', replaceField(safetyEvaluation, 'request', safetyAcquisitionOperation('prompt-get'))), edges('prompt-get-return'), 'No inference round starts to obtain this dependency permission.'),
  output('safety.grant-reservation-requested', 'Reserve or consume exact physical launch', safetyReservation, edges('authorize-grants'), 'Live binding/policy/grant and owner checks pass before one-attempt reservation.'),
  output('safety.launch-decided', 'Fresh exact-attempt launch permit', safetyLaunchDecision, edges('authorize-dispatch'), 'Current authority and transaction evidence authorize this one queued attempt.'),
  ...[['denied', 'grant-revoked'], ['stale', 'arguments-or-binding-changed'], ['stale', 'policy-generation-changed'], ['cancelled', 'stop-before-launch'], ['unavailable', 'grant-store-outcome-unknown']].map(([status, reason]) => output(`safety.launch-${reason}`, `No launch: ${reason}`, noLaunch(status, reason), edges('authorize-dispatch'), 'Do not dispatch under a stale or unavailable permission decision.')),
  output('safety.resource-launch-decided', 'Resource exact-attempt launch decision', safetyLaunchDecisionFor(safetyAcquisitionOperation('resource-read')), edges('resource-read-return'), 'Acquisition compares this bounded generation immediately before its read.'),
  output('safety.prompt-launch-decided', 'Prompt exact-attempt launch decision', safetyLaunchDecisionFor(safetyAcquisitionOperation('prompt-get')), edges('prompt-get-return'), 'Acquisition compares this bounded generation immediately before its retrieval.'),
  output('safety.authorization-invalidated', 'Stop invalidates pending launch authority', safetyInvalidation, [], 'Cancel invalidates unstarted work while Tools settles every already-started attempt.'),
 ]),
];
for (const variant of lifetimes) {
 const persistent = variant.lifetime === 'persistent';
 const grant = refine(safetyGrant, { lifetime: fixed(variant.lifetime), storage: fixed(variant.storage), persisted: fixed(variant.persisted), survivesRuntimeRestart: fixed(variant.survives), operationId: variant.choice === 'allow-once' ? text('call-001') : fixed(null), permissionSessionId: variant.choice === 'allow-session' ? text('permission-session:demo:1') : fixed(null), permissionSessionEpoch: variant.choice === 'allow-session' ? count(1) : fixed(null), expiresAt: persistent ? fixed(null) : nullable(text('2026-10-08T12:05:00Z')) });
 const resolution = refine(safetyApprovalResolution, { selectedChoice: fixed(variant.choice), grantLifetime: fixed(variant.lifetime) });
 // Commit candidate is not persisted until its matching acknowledgment. The saved
 // persistent example below separately demonstrates the applied record.
 const candidate = persistent ? replaceField(grant, 'persisted', fixed(false)) : grant;
 const commit = refine(safetyCommit, { resolution, grant: candidate });
 safetyPermissionContracts.find(node => node.nodeId === 'lina-safety-approval')!.outputs.push(output(`safety.approval-${variant.choice}`, `Selected ${variant.choice}`, commit, edges('approval-grants'), 'Accepted eligible review commits the displayed scope with its actual lifetime.'));
 safetyPermissionContracts.find(node => node.nodeId === 'lina-safety-grants')!.outputs.push(output(`safety.grant-committed-${variant.choice}`, `${variant.lifetime} grant acknowledged`, refine(safetyCommitResult, { command: commit, grant }), edges('grants-authorize'), 'Applied fixture transaction preserves the selected lifetime; saved status follows acknowledgment.'));
}

/** Attach cross-block producer records to their actual owners. Target inspectors
 * receive these exact event payloads unchanged; coordinator state remains local.
 * Keeping this wiring here avoids circular imports between leaf record modules. */
export function attachSafetyProducerHandoffs(definitions: ContractDefinition[]): void {
 const attach = (nodeId: string, id: string, label: string, value: Payload, connections: string[], when: string) => {
  const node = definitions.find(item => item.nodeId === nodeId);
  if (!node) throw new Error(`Missing Safety handoff producer ${nodeId}`);
  node.outputs.push(output(id, label, value, edges(...connections), when));
 };
 for (const selectedChoice of safetyChoices) {
  const answer = replaceField(approvalPromptAnswer, 'answer', fixed(selectedChoice));
  const inputOwner = definitions.find(node => node.nodeId === 'lina-input-prompt')!;
  inputOwner.outputs.push(output(`input.prompt.approval-${selectedChoice}`, 'Explicit operation approval correlated by Input', answer, ['lina-execution-edge-prompt-answer'], 'Input matches the retained prompt, operation and responder. Safety still validates this typed choice and current scope before granting permission.'));
  const executionOwner = definitions.find(node => node.nodeId === 'lina-execution-wait')!;
  executionOwner.outputs.push(output(`execution.wait.approval-${selectedChoice}`, 'Typed choice forwarded to retained Tools owner', replaceField(safetyAnswer, 'choice', fixed(selectedChoice)), ['lina-execution-edge-wait-approval'], 'Forward the explicit lifetime choice to the same owning operation without inferring authority from ordinary text.'));
 }
 attach('lina-tools-permissions', 'tools.safety-operation-requested', 'Post-hook validated operation enters Safety', safetyOperation, ['tool-request'], 'Schema validation and final argument digests precede permission evaluation.');
 attach('lina-tools-permissions', 'tools.safety-answer-forwarded', 'Matched answer reaches owning Safety wait', safetyAnswer, ['approval-answer'], 'Existing Input → Execution wait → Tools owner routing preserves typed four-choice answer.');
 attach('lina-tools-dispatch', 'tools.safety-launch-requested', 'Queued attempt asks for current launch authority', safetyLaunchRequest, ['dispatch-authorize'], 'Scheduling has completed; each physical launch now needs fresh authorization.');
 attach('lina-execution-wait', 'execution.safety-wait-registered', 'Retained operation wait registered before prompt', safetyRegisteredWait, ['wait-registered'], 'Registration acknowledgment is emitted once for the exact owner/wait revision.');
 attach('lina-execution-cancel', 'execution.safety-approval-cancelled', 'Invalidate pending operation approvals', safetyInvalidation, ['cancel-approval'], 'Stop marks pending waits invalid without consuming a new model round.');
 attach('lina-execution-cancel', 'execution.safety-authorization-cancelled', 'Invalidate pending launch permits', safetyInvalidation, ['cancel-authorization'], 'Advance admission generation; existing Tools cancellation still settles started effects.');
 for (const kind of ['resource-read', 'prompt-get'] as const) {
  const owner = `lina-tools-${kind}`;
  const operation = safetyAcquisitionOperation(kind);
  attach('lina-execution-wait', `execution.safety-${kind}-wait-registered`, 'Acquisition approval wait registered', safetyApprovalFor(operation, true), ['wait-registered'], 'Exact acquisition preparation and dependency remain retained before prompt delivery.');
  attach(owner, `tools.safety-${kind}-requested`, 'Selected Context dependency enters Safety', operation, [`${kind}-request`], 'The original preparation/dependency identity survives permission evaluation.');
  attach(owner, `tools.safety-${kind}-launch-requested`, 'Dependency acquisition asks for fresh launch authority', safetyLaunchFor(operation), [`${kind}-authorize`], 'Check permission immediately before acquiring the selected source.');
  attach(owner, `tools.safety-${kind}-answer-forwarded`, 'Dependency owner forwards its matched approval', safetyAnswerFor(operation), [`${kind}-answer`], 'Execution resumes the acquisition owner, which forwards the same correlated answer.');
 }
}

for (const kind of ['resource-read', 'prompt-get'] as const) {
 const request = safetyAcquisitionOperation(kind);
 const wait = safetyApprovalFor(request);
 const registered = safetyApprovalFor(request, true);
 const scope = (wait.example as Record<string, Json>).displayedScope;
 const scopedScope: Payload = { schema: wait.schema.properties!.displayedScope, example: scope };
 const scopedGrant = refine(safetyGrant, { scope: scopedScope, operationId: text((request.example as any).identity.operationId) });
 const resolution = replaceField(safetyApprovalResolution, 'retainedWait', registered);
 const commit = refine(safetyCommit, { resolution, grant: scopedGrant });
 const add = (id: string, eventId: string, value: Payload, edge: string) => safetyPermissionContracts.find(node => node.nodeId === `lina-safety-${id}`)!.outputs.push(output(`safety.${eventId}-${kind}`, `${kind} permission handoff`, value, edges(edge), 'Retain the original acquisition identity and reviewed matcher throughout the dependency.'));
 add('evaluate', 'policy-requested', replaceField(safetyPolicyRequest, 'request', request), 'evaluate-policy');
 add('policy', 'policy-ready', replaceField(safetyPolicyReady, 'request', request), 'policy-evaluate');
 const lookup = replaceField(safetyLookup, 'request', request);
 add('evaluate', 'grant-lookup', lookup, 'evaluate-grants');
 add('grants', 'grant-lookup-result', refine(safetyLookupResult, { lookup, grant: scopedGrant }), 'grants-evaluate');
 add('evaluate', 'approval-required', wait, 'evaluate-approval');
 add('evaluate', 'operation-allowed', replaceField(safetyEvaluation, 'request', request), 'evaluate-authorize');
 const prompt = object({ retainedWait: registered, deliveryId: text(`delivery:${kind}:1`), destinationRef: text('destination:accepted-input:1'), category: fixed('challenge'), text: text(`Allow this exact ${kind} acquisition with the displayed scope?`), choices: list(choice(safetyChoices), safetyChoices, 1), scope: scopedScope, eligibleResponderIds: list(text('person-demo'), ['person-demo'], 1), deliveredMeansApproved: fixed(false) });
 add('approval', 'review-prompt-requested', prompt, 'approval-prompt');
 add('approval', 'grant-commit-requested', commit, 'approval-grants');
 add('grants', 'grant-commit-applied', refine(safetyCommitResult, { command: commit, grant: scopedGrant }), 'grants-authorize');
 add('approval', 'approval-denied', refine(resolution, { status: fixed('denied'), selectedChoice: fixed('deny'), grantLifetime: fixed('none') }), 'approval-authorize');
 const launch = safetyLaunchFor(request);
 const reservation = replaceField(safetyReservation, 'launch', launch);
 add('authorize', 'reservation-requested', reservation, 'authorize-grants');
 add('grants', 'reservation-ready', replaceField(safetyReservationResult, 'command', reservation), 'reservation-authorize');
 add('authorize', 'acquisition-denied', refine(operationDecision, { status: fixed('denied'), evaluation: replaceField(decision('deny', 'permission-denied'), 'request', request) }), `${kind}-return`);
 add('authorize', 'acquisition-cancelled', refine(operationDecision, { status: fixed('cancelled'), evaluation: replaceField(decision('deny', 'stop-requested'), 'request', request) }), `${kind}-return`);
 add('authorize', 'acquisition-launch-stale', refine(safetyLaunchDecisionFor(request), { status: fixed('stale'), reason: text('changed-acquisition-binding'), launchPermitRef: fixed(null), reservationRef: fixed(null) }), `${kind}-return`);
}
