import { environmentBinding, environmentLease, environmentOperationIntent, environmentProcess, environmentObservation, environmentStagingManifest, environmentArtifact, environmentRelease } from './environmentRecords';
import { planningPlan, planningAttempt, planningAssessment, planningMutationReceipt } from './planningRecords';
import { choice, count, fixed, flag, list, nullable, object, replaceField, sample, text, union, type Payload } from './schema';

/** Provisional persisted records. Payload references address safe artifacts; tokens
 * remain in the protected credential owner, never inside the execution journal. */
export const stateScope = object({ workspaceId: text('workspace-demo'), conversationId: text('conversation-demo'), agentId: text('lina-main') });
export const stateRecordRevision = object({ recordRef: text('turn:001'), revision: count(4), digest: text('sha256:fixture-record-4') });
const binding = object({ capabilityRef: text('capability:calculator:1'), accountRef: text('account:demo'), bindingGeneration: count(1), requestFingerprint: text('sha256:fixture-request'), credentialRef: nullable(text('protected-credential:demo')) });
const owner = object({ turnId: text('turn-001'), ownerRevision: count(4), executionFence: count(8), leaseExpiresAt: nullable(text('2026-10-08T12:05:00Z')), status: choice(['active', 'released', 'expired', 'cancelled']), unresolvedWorkRefs: list(text('operation:call-002'), []) });
const operation = object({ operationId: text('call-001'), attemptId: text('attempt:call-001:1'), launchId: text('launch:call-001:1'), ownerNodeId: choice(['lina-tools-dispatch', 'lina-model-invoke', 'lina-execution-settle'], 'lina-tools-dispatch'), binding, effectStatus: choice(['known-unstarted', 'launched', 'complete', 'known-no-effect', 'unknown'], 'known-unstarted'), intentRef: text('intent:call-001:1'), resultRef: sample(nullable(text('artifact:result:call-001')), null), externalOperationRef: nullable(text('remote:operation:001')), replayAuthorized: fixed(false) });
const wait = object({ waitId: text('wait:approval:call-002'), promptId: text('prompt:call-002:1'), operationId: text('call-002'), waitRevision: count(1), ownerNodeId: text('lina-tools-permissions'), requestFingerprint: text('sha256:fixture-reviewed-request'), eligibleResponderRefs: list(text('principal:person-demo')), expiresAt: text('2026-10-08T12:05:00Z'), continuationRef: text('continuation:call-002:permission-answer'), status: choice(['registered', 'consumed', 'cancelled', 'expired']), binding });
const grant = object({ grantId: text('grant:call-001:1'), transactionId: text('grant-tx:call-001:1'), scopeRef: text('reviewed-scope:call-001:1'), lifetime: choice(['logical-operation', 'permission-session', 'persistent'], 'persistent'), permissionSessionId: sample(nullable(text('permission-session:demo:1')), null), permissionSessionEpoch: count(1), generation: count(1), policyGeneration: count(1), status: choice(['active', 'reserved', 'consumed', 'revoked']), reservedLaunchId: nullable(text('launch:call-001:1')), survivesRuntimeRestart: flag(true), delegateToChildren: fixed(false) });
const receipt = object({ transportEventId: text('transport:demo:event-001'), inputId: text('input-001'), acceptedPayloadRef: text('artifact:accepted-input:001'), originalRouteRef: text('route:original:001'), custodyRef: text('custody:input-001'), acceptanceReceiptRef: nullable(text('receipt:001')), status: choice(['claimed', 'accepted', 'rejected']) });
const queue = object({ entryId: text('queue:input-002'), inputId: text('input-002'), order: count(2), status: choice(['queued', 'transferring', 'claimed', 'removed']), successorOwnerRef: nullable(text('owner:turn-002')), removalRequiresSuccessorAcknowledgment: fixed(true) });
const history = object({ sessionRef: text('session:demo'), messageIds: list(text('message:001')), contextSnapshotRef: nullable(text('artifact:context:round-001')), provenanceRef: text('context-transform:round-001'), acceptedMessagesOnly: fixed(true) });
const stop = object({ turnId: text('turn-001'), stopId: text('stop:001'), admissionGeneration: count(2), requestedAt: text('2026-10-08T12:00:00Z'), pendingLaunchesInvalidated: fixed(true), startedEffectsRolledBack: fixed(false) });
const delivery = object({ deliveryId: text('delivery:turn-001:reply'), replyArtifactRef: text('artifact:reply:turn-001'), destinationRef: text('destination:accepted-input:1'), attemptId: nullable(text('delivery-attempt:1')), status: choice(['owed', 'sending', 'acknowledged', 'unknown'], 'owed'), externalReceiptRef: nullable(text('remote:receipt:1')), rerunAgentToRecreateReply: fixed(false) });
const child = object({ parentTurnId: text('turn-001'), childTaskId: text('child-task:001'), status: choice(['submitted', 'running', 'complete', 'unknown']), resultRef: nullable(text('artifact:child-result:001')), runnableOrchestrationImplemented: fixed(false) });
const transaction = object({ transactionId: text('transaction:acceptance:001'), idempotencyKey: text('accepted-input:account-demo:event-001'), requestFingerprint: text('sha256:fixture-acceptance'), commitStatus: choice(['applied', 'absent', 'unknown']), acknowledgedRevision: nullable(count(4)) });
const record = (kind: string, payload: Payload): Payload => object({ kind: fixed(kind), recordRef: text(`${kind}:001`), revision: count(4), payload, containsCredentials: fixed(false), synthetic: fixed(true) });
export const stateRecordKinds = ['input-claim', 'accepted-input', 'input-receipt', 'queue-membership', 'execution-owner', 'history', 'context-snapshot', 'pending-wait', 'permission-grant', 'grant-reservation', 'operation-intent', 'operation-result', 'stop-intent', 'delivery-obligation', 'child-task', 'transaction', 'task-plan', 'task-attempt', 'task-assessment', 'plan-mutation', 'environment-binding', 'environment-lease', 'environment-intent', 'environment-process', 'environment-observation', 'environment-staging', 'environment-artifact', 'environment-release'] as const;
export const stateRecordsByKind: Record<string, Payload> = {
 'environment-binding': record('environment-binding', environmentBinding), 'environment-lease': record('environment-lease', environmentLease), 'environment-intent': record('environment-intent', environmentOperationIntent), 'environment-process': record('environment-process', environmentProcess), 'environment-observation': record('environment-observation', environmentObservation), 'environment-staging': record('environment-staging', environmentStagingManifest), 'environment-artifact': record('environment-artifact', environmentArtifact), 'environment-release': record('environment-release', environmentRelease),
 'task-plan': record('task-plan', planningPlan), 'task-attempt': record('task-attempt', planningAttempt), 'task-assessment': record('task-assessment', planningAssessment), 'plan-mutation': record('plan-mutation', planningMutationReceipt),
 'input-claim': record('input-claim', receipt), 'accepted-input': record('accepted-input', replaceField(receipt, 'status', fixed('accepted'))), 'input-receipt': record('input-receipt', replaceField(receipt, 'status', fixed('accepted'))),
 'queue-membership': record('queue-membership', queue), 'execution-owner': record('execution-owner', owner), 'history': record('history', history), 'context-snapshot': record('context-snapshot', history),
 'pending-wait': record('pending-wait', wait), 'permission-grant': record('permission-grant', grant), 'grant-reservation': record('grant-reservation', grant),
 'operation-intent': record('operation-intent', operation), 'operation-result': record('operation-result', replaceField(replaceField(operation, 'effectStatus', fixed('complete')), 'resultRef', text('artifact:result:call-001'))), 'stop-intent': record('stop-intent', stop), 'delivery-obligation': record('delivery-obligation', delivery), 'child-task': record('child-task', child), 'transaction': record('transaction', transaction),
};
export const stateRecord = union(...Object.values(stateRecordsByKind));
export const stateCheckpointManifest = object({
 schemaVersion: fixed(1), checkpointId: text('checkpoint:turn-001:4'), implementationRevision: text('lina-design:state-v1'), agentId: text('lina-main'), turnId: text('turn-001'), roundId: text('round-001'), ownerRevision: count(4), executionFenceAtSave: count(8),
 recordRevisions: list(stateRecordRevision), taskPlanReferences: list(object({ planId: text('plan:review:001'), goalId: text('goal:review:001'), revision: count(3), agentId: text('lina-main'), historyBranchRef: text('history:main:active'), recordRef: text('task-plan:001'), attemptIds: list(text('attempt:inspect:001')), replaysCompletedEffects: fixed(false) }), []), resumeEntry: choice(['lina-execution-prepare', 'lina-execution-controls', 'lina-execution-settle', 'lina-execution-wait'], 'lina-execution-wait'), contextSnapshotRef: text('artifact:context:round-001'),
 environmentReferences: list(object({ environmentId: text('environment:project:001'), environmentGeneration: count(2), workspaceId: text('workspace-demo'), workspaceGeneration: count(1), mountRevision: count(1), leaseRecordRef: text('environment-lease:001'), processRecordRefs: list(text('environment-process:001'), []), unresolvedOperationRefs: list(text('operation:workspace:001:1'), []), inspectionRequiredBeforeReuse: fixed(true), checkpointProvesProcessAlive: fixed(false), liveHandlesSerialized: fixed(false) }), []),
 requiredArtifacts: list(object({ artifactRef: text('artifact:result:call-001'), digest: text('sha256:fixture-result') })),
 settledWork: list(object({ operationId: text('call-001'), status: fixed('complete'), resultRef: text('artifact:result:call-001') })),
 pendingWork: list(object({ operationId: text('call-002'), waitId: text('wait:approval:call-002'), waitRevision: count(1), ownerNodeId: text('lina-tools-permissions'), status: fixed('waiting'), launched: fixed(false) })),
 unresolvedEffects: list(object({ operationId: text('call-003'), intentRef: text('intent:call-003:1'), effectStatus: fixed('unknown'), reconciliationOwner: fixed('lina-input-reconcile') }), []),
 counters: object({ roundsStarted: count(1), physicalModelAttempts: count(1) }), stopIntentRef: sample(nullable(text('stop:001')), null), deliveryObligationRefs: list(text('delivery:turn-001:reply'), []),
 containsCredentials: fixed(false), synthetic: fixed(true),
});
export const stateLocalContext = object({ designOnly: fixed(true), storage: fixed('deterministic-fixture'), liveExecutionStoreImplemented: fixed(false), coordinatorOwnsLifecycle: fixed(true), currentOwnerRevision: count(4), currentExecutionFence: count(8), schemaVersion: fixed(1), credentialMaterialIncluded: fixed(false), authoritativeTelemetry: fixed(false), automaticRecordToCheckpoint: fixed(false) });
