import { SUBAGENTS_EDGES, SUBAGENT_STATE_ROUTES } from '../subagentsBlock';
import { choice, count, fixed, list, nullable, object, output, replaceField, sample, text, union, type ContractDefinition, type Payload } from './schema';
import { subagentBudget, subagentChildTurn, subagentConfiguration, subagentContextHandoff, subagentControl, subagentCorrelation, subagentDelivery, subagentJoin, subagentLaunch, subagentLocalContext, subagentOwner, subagentResult, subagentSession } from './subagentRecords';

const phases = ['validate', 'prepare', 'launch', 'coordinate', 'join', 'cancel', 'reconcile', 'return'];
const rules: Record<string, string[]> = {
 validate: ['The model requests delegation; trusted harness policy admits the exact task and scopes. Neither child output nor profile text grants permission.', 'Reserve capacity atomically against depth, active siblings and aggregate task-tree budgets. Recursive children use the same tree ledger; no separate unlimited budget.', 'Persistent follow-up, status, steering, join and cancellation are distinct admitted operations. Recheck current access and session revisions; detached launch requires a durable owner.'],
 prepare: ['Fresh, selected and transcript-fork context are explicit modes. Copy allowed immutable source revisions and complete tool call/result groups with original authority.', 'Child history and loop counters are separate. A fork never shares mutable parent history, approval grants or credential material.', 'Worker profile, model, tools, skills, connectors, Memory and environment scopes are the intersection of admitted restrictions. Follow-up acquires a new serialized turn in the existing child session.'],
 launch: ['Record stable launch identity and fingerprint before execution. Persisted intent is not evidence that a child started.', 'Recheck admission, cancellation and ownership immediately before starting a child through the existing agent loop. Unknown startup requires inspection of the original launch, never a fresh duplicate child.', 'Foreground/background specifies parent waiting; attached/detached specifies lifecycle ownership. Child launch does not create ordinary user ingress or external user output.'],
 coordinate: ['Child events carry instance, turn, sequence and lifecycle generation. Duplicate and late events cannot resurrect a completed parent or cross a newer child turn fence.', 'Background handles can return before terminal results. Follow-up and steering require current authorization; status and delivery do not silently start a new turn.', 'Persistent sessions retain their own history. Parent release, child completion and child owner release are separate facts; explicitly detached work remains owned by its supervisor.'],
 join: ['Join only the requested owned child set, using all/any/quorum, deadline and declared partial-failure policy. Preserve each outcome and unresolved effect.', 'A wait timeout does not cancel children or prove completion. Successful siblings cannot erase failed or uncertain siblings.', 'Persist join identity and accepted result revisions. A duplicate event produces one parent observation; selective joins leave other children owned and inspectable.'],
 cancel: ['Parent Stop fences pending attached launches and cascades attached descendants. Explicit detached work follows its separately admitted supervisor policy.', 'Cancellation acknowledgment does not reverse acknowledged writes or prove all remote effects stopped. Keep unresolved ownership until inspected.', 'Control identity is idempotent; release task-tree capacity from settled ownership evidence, never merely from a stop request. Simulation Reset clears design fixtures, not remote work.'],
 reconcile: ['Inspect exact original launch/control/result identity, fingerprint and fence before any retry. Reattach known execution or return retained results.', 'Proven-unstarted launch may retry the same reauthorized intent. Unknown launch never repeats child tools or starts another child.', 'Resume only compatible child checkpoints and current permissions; record unavailable/incompatible evidence honestly and block unsafe parent release.'],
 return: ['Bind bounded handle or results to the exact parent agent, turn, call and continuation. Validate structured output and retain original artifacts and trace.', 'Child content remains observation evidence. It cannot become a policy instruction, grant, or direct external user answer.', 'Use retained at-least-once delivery with idempotent acceptance. Lost delivery acknowledgment inspects the original delivery; it never reruns the child. Stale-parent results remain retained without reopening that turn.'],
};
export const subagentOrchestrationContracts: ContractDefinition[] = phases.map(phase => ({ nodeId: `lina-subagents-${phase}`, context: subagentLocalContext, contextSource: 'Trusted design coordinator supplies scoped instance and ownership records. These schemas describe fixtures, not a live child scheduler.', reads: ['Exact delegation identity, current authority and task-tree ledger', 'Phase-specific child/session/result/control records'], writes: ['Correlated phase outcome retaining child and parent continuation identity'], rules: rules[phase], outputs: [] }));
const statusByPhase: Record<string, string[]> = {
 validate: ['admitted', 'capacity-wait', 'refused', 'invalid', 'budget-exhausted', 'failed', 'unknown'], prepare: ['packet-ready', 'source-unavailable', 'scope-refused', 'invalid-session', 'cancelled'], launch: ['started', 'known-unstarted', 'failed', 'unknown'], coordinate: ['running', 'waiting', 'terminal-observed', 'released', 'control-accepted', 'control-rejected', 'unknown'], join: ['pending', 'results-ready', 'partial-terminal', 'wait-expired', 'unresolved'], cancel: ['prevented-before-launch', 'cancel-requested', 'settled', 'unresolved'], reconcile: ['known-running', 'known-unstarted', 'known-terminal', 'still-unknown', 'incompatible'], return: ['handle', 'success', 'invalid-result', 'failed', 'exhausted', 'cancelled', 'unresolved', 'delivery-pending', 'stale-parent'],
};
export function subagentPhasePayload(phase: string, status: string): Payload {
 const fields: Record<string, Payload> = { correlation: subagentCorrelation, phase: fixed(phase), status: fixed(status), storage: fixed('fixture-only'), owner: subagentOwner, credentialsIncluded: fixed(false), reopensEndedParent: fixed(false) };
 if (phase === 'validate') { fields.operation = choice(['spawn', 'follow-up', 'resume', 'status', 'steer', 'join', 'cancel', 'close-session']); fields.budget = subagentBudget; fields.configuration = subagentConfiguration; fields.admitted = fixed(status === 'admitted'); fields.reviewRef = status === 'admitted' ? text('admission:delegation:001') : fixed(null); }
 if (phase === 'prepare') { fields.contextHandoff = subagentContextHandoff; fields.childTurn = subagentChildTurn; fields.session = subagentSession; fields.packetReady = fixed(status === 'packet-ready'); }
 if (phase === 'launch') { fields.launch = replaceField(replaceField(subagentLaunch, 'status', fixed(status)), 'childExecutionRef', status === 'known-unstarted' || status === 'failed' ? fixed(null) : nullable(text('execution:child:001'))); fields.childTurn = subagentChildTurn; fields.inspectBeforeRetry = fixed(status === 'unknown'); }
 if (phase === 'coordinate') { fields.operation = choice(['status', 'steer', 'follow-up', 'recursive-spawn', 'close-session']); fields.session = subagentSession; fields.control = subagentControl; fields.event = object({ eventId: text('child-event:001'), sequence: count(1), lifecycleGeneration: count(3), childTurnId: text('turn:child:001'), kind: choice(['progress', 'wait', 'terminal', 'owner-release', 'control-receipt']), acceptedForCurrentGeneration: fixed(true), duplicateApplication: fixed(false), staleEventsRetainedAsEvidenceOnly: fixed(true) }); fields.result = sample(nullable(subagentResult), status === 'terminal-observed' ? subagentResult.example : null); }
 if (phase === 'join') { fields.join = replaceField(subagentJoin, 'unresolvedChildIds', list(text('lina-child:001'), ['pending', 'unresolved', 'wait-expired'].includes(status) ? ['lina-child:001'] : [])); fields.results = list(subagentResult, ['results-ready', 'partial-terminal'].includes(status) ? [subagentResult.example] : []); fields.waitExpiredCancelsChildren = fixed(false); fields.successfulSiblingImpliesWholeJoinSuccess = fixed(false); }
 if (phase === 'cancel') { fields.control = subagentControl; fields.attachedDescendantsFenced = fixed(true); fields.detachedOwnerRetained = fixed(true); fields.acknowledgedEffectsReversed = fixed(false); fields.capacityReleased = fixed(status === 'settled' || status === 'prevented-before-launch'); fields.unresolvedEffectRefs = list(text('effect:child:unknown'), status === 'unresolved' ? ['effect:child:unknown'] : []); }
 if (phase === 'reconcile') { fields.originalLaunch = subagentLaunch; fields.originalIdentityInspected = fixed(true); fields.sameIdentityRetryAllowed = fixed(status === 'known-unstarted'); fields.childToolReplayAllowed = fixed(false); fields.checkpointCompatibility = choice(['compatible', 'incompatible', 'not-needed'], status === 'incompatible' ? 'incompatible' : 'compatible'); fields.evidenceRef = text('reconciliation:child:001'); }
 if (phase === 'return') {
  const result = status === 'invalid-result' ? replaceField(subagentResult, 'structuredResult', object({ schemaRef: text('schema:research-result:v1'), payloadRef: text('artifact:child:structured:001'), validation: fixed('invalid'), validationErrors: list(text('missing required citations')) })) : ['failed', 'exhausted', 'cancelled'].includes(status) ? replaceField(subagentResult, 'outcome', fixed(status)) : subagentResult;
  fields.result = sample(nullable(result), ['handle', 'unresolved'].includes(status) ? null : result.example);
  fields.delivery = status === 'unresolved' ? object({ deliveryId: text('delivery:unresolved-child:001'), kind: fixed('unresolved-observation'), correlation: subagentCorrelation, evidenceRef: text('reconciliation:child:001'), unresolvedEffectsRetained: fixed(true), childRerunOnLostDeliveryAck: fixed(false), grantsParentRelease: fixed(false) }) : status === 'handle' ? object({ deliveryId: text('delivery:child-handle:001'), kind: fixed('accepted-handle'), correlation: subagentCorrelation, childSessionRef: text('session:child:001'), terminalResultKnown: fixed(false), acknowledgmentMeansChildCompleted: fixed(false), childRerunOnLostDeliveryAck: fixed(false) }) : replaceField(replaceField(subagentDelivery, 'result', result), 'outcome', fixed(status === 'delivery-pending' ? 'pending' : status === 'stale-parent' ? 'stale-parent-fence' : 'accepted'));
  fields.handle = object({ childAgentId: text('lina-child:001'), sessionId: text('session:child:001'), launchId: text('launch:delegation:001'), lifecycleGeneration: count(3), terminalResultKnown: fixed(!['handle', 'unresolved'].includes(status)) });
  fields.structuredResultAccepted = fixed(status === 'success'); fields.childRerunRequired = fixed(false);
 }

 return object(fields);
}

const stateRecordFor = (phase: string): Payload => {
 if (phase.includes('capacity') || phase.includes('reservation')) return object({ kind: fixed('task-tree-reservation'), budget: subagentBudget, correlation: subagentCorrelation });
 if (phase.includes('packet')) return object({ kind: fixed('child-task-packet'), context: subagentContextHandoff, childTurn: subagentChildTurn });
 if (phase.includes('launch')) return object({ kind: fixed('child-launch'), launch: subagentLaunch });
 if (phase.includes('join')) return object({ kind: fixed('child-join'), join: subagentJoin });
 if (phase.includes('cancel')) return object({ kind: fixed('child-control'), control: subagentControl });
 if (phase.includes('delivery')) return object({ kind: fixed('child-result-delivery'), delivery: subagentDelivery });
 if (phase.includes('results')) return object({ kind: fixed('child-results'), results: list(subagentResult) });
 if (phase.includes('reconciliation') || phase.includes('certainty')) return object({ kind: fixed('child-reconciliation'), launch: subagentLaunch, sameIdentityInspected: fixed(true), toolsReplayed: fixed(false), evidenceRef: text('reconciliation:child:001') });
 return object({ kind: fixed('child-session-and-lifecycle'), session: subagentSession, result: sample(nullable(subagentResult), null) });
};
const transactionPhase = (phase: string) => ({ 'inspect-original-child-launch': 'record-child-launch-intent', 'inspect-parent-result-delivery': 'record-parent-result-delivery', 'inspect-descendant-cancellation': 'record-child-cancel-intent', 'inspect-task-tree-reservation': 'reserve-delegation-capacity' } as Record<string, string>)[phase] ?? phase;
type Edge = { id: string; source: string; target: string };
function dependencyPayload(edge: Edge, storageOutcome?: string): Payload {
 const route = SUBAGENT_STATE_ROUTES.find(item => item.id === edge.id || item.returnId === edge.id);
 if (route) {
  const txPhase = transactionPhase(route.phase);
  const base = { correlation: subagentCorrelation, requestPhase: fixed(route.phase), requesterNodeId: fixed(route.source), returnToNodeId: fixed(route.returnTarget), transactionId: text(`subagent-tx:${txPhase}:001`), fingerprint: text(`sha256:subagent:${txPhase}:001`), expectedRecordRevision: count(2), expectedOwnerGeneration: count(3), record: stateRecordFor(route.phase), semanticAdmissionOwnedBySubagents: fixed(true), childLaunchedByStorageAck: fixed(false), credentialMaterialIncluded: fixed(false) };
  if (edge.source.startsWith('lina-state-')) return object({ ...base, storageOutcome: fixed(storageOutcome ?? 'found'), inspectBeforeRetry: fixed(['unknown', 'still-unknown'].includes(storageOutcome ?? '')), originalIdentityVerified: fixed(true), absenceProvesExternalEffectAbsent: fixed(false), acknowledgedRevision: ['applied', 'already-applied'].includes(storageOutcome ?? '') ? count(3) : fixed(null) });
  return object({ ...base, command: fixed(route.phase), requiredCommitBoundary: fixed(route.phase === 'reserve-delegation-capacity' ? 'atomic-task-tree-reservation-and-child-identity' : 'all-listed-phase-records'), rerunChildTools: fixed(false) });
 }
 if (edge.id.endsWith('launch-child-start')) return subagentChildTurn;
 if (edge.id.includes('child-settle') || edge.id.includes('child-release')) return object({ correlation: subagentCorrelation, origin: fixed('internal-child-turn'), childResult: subagentResult, ownerReleased: fixed(edge.id.includes('release')), terminalObserved: fixed(true), routesToExternalUser: fixed(false), siblingOrParentCountersMutated: fixed(false), deduplicationEventId: text(edge.id.includes('release') ? 'child-release:001' : 'child-terminal:001') });
 if (edge.source.startsWith('lina-safety-')) return object({ correlation: subagentCorrelation, reviewedFingerprint: text('sha256:fixture-delegation-001'), decision: choice(['allow-once', 'allow-session', 'allow-always', 'deny']), effectiveConfiguration: subagentConfiguration, policyGeneration: count(4), ownerGeneration: count(3), inheritsParentApprovalGrant: fixed(false), childOutputGrantsPermission: fixed(false) });
 if (edge.target.startsWith('lina-safety-')) return object({ correlation: subagentCorrelation, operation: choice(['delegate', 'start-child', 'resume-child']), requestedConfiguration: subagentConfiguration, budget: subagentBudget, owner: subagentOwner, reviewedFingerprint: text('sha256:fixture-delegation-001'), contextScopeRef: text('context-policy:child:001'), memoryPublicationApprovalIncluded: fixed(false) });
 if (edge.source === 'lina-execution-cancel' || edge.target === 'lina-execution-cancel' || edge.target === 'lina-execution-controls') return object({ control: edge.source === 'lina-execution-cancel' || edge.target === 'lina-execution-cancel' ? replaceField(subagentControl, 'action', fixed('cancel')) : replaceField(subagentControl, 'action', fixed('steer')), correlation: subagentCorrelation, routing: fixed(edge.source === 'lina-execution-cancel' ? 'parent-to-attached-descendants' : 'exact-child-instance'), retainDetachedSupervisorOwnership: fixed(true), rollbackAcknowledgedEffects: fixed(false), matchedGenerationRequired: fixed(true) });
 if (edge.source === 'lina-execution-wait' || edge.target === 'lina-execution-wait') return object({ correlation: subagentCorrelation, waitId: text(edge.id.includes('join') ? 'wait:child-join:001' : 'wait:child-capacity:001'), owner: fixed('subagents'), kind: choice(['child-capacity', 'child-join', 'child-reconcile'], edge.id.includes('join') ? 'child-join' : edge.id.includes('reconcile') ? 'child-reconcile' : 'child-capacity'), join: edge.id.includes('join') ? subagentJoin : fixed(null), generation: count(3), matchedEventRequired: fixed(true), timeoutMeansChildCancelled: fixed(false), syntheticSuccessOnTimeout: fixed(false), resumeRechecksAdmission: fixed(true) });
 if (edge.source === 'lina-input-reconcile' || edge.target === 'lina-input-reconcile') return object({ correlation: subagentCorrelation, originalLaunch: subagentLaunch, requiredChildIds: list(text('lina-child:001')), evidenceRef: text('reconciliation:child:001'), parentReleaseAllowed: fixed(false), unknownEffectsRemainVisible: fixed(true), newChildLaunchAllowed: fixed(false) });
 return object({ correlation: subagentCorrelation, operation: choice(['spawn', 'follow-up', 'resume', 'status', 'steer', 'join', 'cancel', 'close-session']), task: object({ taskRef: text('task:delegation:001'), instruction: text('Research the two supplied sources and return citations.'), expectedOutputSchemaRef: text('schema:research-result:v1') }), requestedConfiguration: subagentConfiguration, contextHandoff: subagentContextHandoff, budget: subagentBudget, owner: subagentOwner, control: subagentControl, join: subagentJoin, currentAuthorityRef: text('authority:parent:turn:main:001'), operationRequiresAdmission: fixed(true) });
}
const branchStatuses: Record<string, string[]> = {
 'validate-prepare': ['admitted'], 'validate-coordinate': ['admitted'], 'validate-join': ['admitted'], 'validate-cancel': ['admitted'], 'validate-return': ['refused', 'invalid', 'budget-exhausted', 'failed'], 'validate-wait': ['capacity-wait'],
 'prepare-coordinate': ['packet-ready'], 'prepare-launch': ['packet-ready'], 'prepare-return': ['source-unavailable', 'scope-refused', 'invalid-session', 'cancelled'], 'launch-coordinate': ['started'], 'launch-reconcile': ['unknown'], 'launch-return': ['known-unstarted', 'failed'],
 'coordinate-validate': ['control-accepted'], 'coordinate-join': ['running', 'waiting', 'terminal-observed', 'released'], 'coordinate-return': ['running', 'waiting', 'control-accepted', 'control-rejected', 'terminal-observed'], 'coordinate-cancel': ['control-accepted'], 'coordinate-reconcile': ['unknown'],
 'join-wait': ['pending'], 'join-return': ['results-ready', 'partial-terminal', 'wait-expired'], 'join-reconcile': ['unresolved'], 'cancel-coordinate': ['cancel-requested', 'settled'], 'cancel-reconcile': ['unresolved'], 'cancel-return': ['prevented-before-launch', 'settled'],
 'reconcile-coordinate': ['known-running', 'known-terminal'], 'reconcile-launch': ['known-unstarted'], 'reconcile-return': ['known-unstarted', 'known-terminal', 'still-unknown', 'incompatible'], 'return-join': ['delivery-pending'], 'return-tools': ['handle', 'success', 'invalid-result', 'failed', 'exhausted', 'cancelled', 'unresolved', 'stale-parent'],
};
for (const edge of SUBAGENTS_EDGES) {
 const definition = subagentOrchestrationContracts.find(item => item.nodeId === edge.source);
 if (!definition) continue;
 const phase = edge.source.replace('lina-subagents-', '');
 const short = edge.id.replace('lina-subagents-edge-', '');
 const dependency = edge.target.startsWith('lina-state-') || edge.target.startsWith('lina-safety-') || edge.target.startsWith('lina-execution-') || edge.target === 'lina-input-reconcile';
 if (dependency) definition.outputs.push(output(`subagents.${phase}.${short}`, `${phase}: exact dependency request`, dependencyPayload(edge), [edge.id], 'Only after this phase admits the exact operation; preserve original identity and instance routing.'));
 else for (const status of branchStatuses[short] ?? statusByPhase[phase]) definition.outputs.push(output(`subagents.${phase}.${status}.${short}`, `${phase}: ${status}`, subagentPhasePayload(phase, status), [edge.id], 'Follow this path only for the matched request mode and named outcome; failure never becomes launch.'));
}

/** Attach caller-owned producers without replacing their existing loop records. */
export function attachSubagentProducerHandoffs(definitions: ContractDefinition[]): void {
 for (const edge of SUBAGENTS_EDGES) {
  if (edge.source.startsWith('lina-subagents-')) continue;
  const definition = definitions.find(item => item.nodeId === edge.source);
  if (!definition) throw new Error(`Missing Subagents producer ${edge.source}`);
  const route = SUBAGENT_STATE_ROUTES.find(item => item.returnId === edge.id);
  const statuses = route ? route.kind === 'record' ? ['applied', 'already-applied', 'conflict', 'failed', 'unknown'] : route.phase.startsWith('inspect') ? ['found', 'absent', 'still-unknown', 'unavailable'] : ['found', 'missing', 'stale', 'unavailable', 'denied'] : [undefined];
  for (const status of statuses) definition.outputs.push(output(`subagents.handoff.${edge.id}${status ? `.${status}` : ''}`, `Subagents ${status ?? 'request or continuation'}`, dependencyPayload(edge, status), [edge.id], 'Preserve admitted instance, parent operation, lifecycle generation and original continuation.'));
 }
}
subagentOrchestrationContracts.find(item => item.nodeId === 'lina-subagents-validate')!.external = ['spawn', 'follow-up', 'resume', 'status', 'steer', 'join', 'cancel', 'close-session'].map(operation => ({ label: `Admitted ${operation} request`, source: 'Registered capability invoked by a parent model or explicit authorized lifecycle owner', value: object({ operation: fixed(operation), correlation: subagentCorrelation, control: subagentControl, owner: subagentOwner, budget: subagentBudget, configuration: subagentConfiguration, context: subagentContextHandoff, parentModelRequestsButHarnessAdmits: fixed(true), automaticallyGrantsChildPermissions: fixed(false) }) }));

// Inspectable alternate coordinator snapshots keep default settings separate
// from supported capability range; no variant claims live worker persistence.
const foregroundOwner = subagentOwner.example as Record<string, import('./schema').Json>;
const detachedOwner = { ...foregroundOwner, mode: 'detached', parentWaiting: 'continue', attachment: 'detached', lifecycleOwnerRef: 'supervisor:workspace:001', parentStop: 'retain-explicit-detached-work', parentRelease: 'retain-under-supervisor-owner', orphanRecoveryRef: 'owner:workspace-supervisor:001' } as import('./schema').Json;
const backgroundOwner = { ...foregroundOwner, mode: 'background', parentWaiting: 'continue', lifecycleOwnerRef: 'session:main:001', parentRelease: 'retain-under-session-owner' } as import('./schema').Json;
for (const definition of subagentOrchestrationContracts) definition.contextExamples = [
 { label: 'Foreground attached child', value: subagentLocalContext },
 { label: 'Background attached persistent child', value: replaceField(subagentLocalContext, 'owner', sample(subagentOwner, backgroundOwner)) },
 { label: 'Explicitly detached supervisor-owned child', value: replaceField(subagentLocalContext, 'owner', sample(subagentOwner, detachedOwner)) },
 { label: 'Recursive child at depth four', value: replaceField(subagentLocalContext, 'budget', replaceField(subagentBudget, 'depth', count(4))) },
];
