import { environmentChildBinding } from './environmentRecords';
/** Provisional child lifecycle records for Studio inspection, not live workers. */
import { choice, count, fixed, flag, list, nullable, object, sample, text, union } from './schema';

export const subagentCorrelation = object({ delegationId: text('delegation:001'), parentAgentId: text('lina-main'), parentTurnId: text('turn:main:001'), parentCallId: text('call:delegate:001'), childAgentId: text('lina-child:001'), childSessionId: text('session:child:001'), treeId: text('tree:main:001'), operationId: text('launch:delegation:001'), fingerprint: text('sha256:fixture-delegation-001'), continuationRef: text('continuation:call:delegate:001'), eventSequence: count(1), lifecycleGeneration: count(3) });
export const subagentBudget = object({ depth: count(1), maxDepth: count(5), maxConcurrentChildren: count(4), maxTreeAgents: count(12), reservedSlots: count(1), treeActiveAgents: count(2), maxTreeModelAttempts: count(40), treeModelAttemptsUsed: count(3), childMaxModelAttempts: count(8), maxTreeToolCalls: count(80), treeToolCallsUsed: count(4), childMaxToolCalls: count(12), deadlineAt: text('2026-10-08T12:05:00Z'), treeBudgetRef: text('budget:tree:main:001'), reservationId: text('reservation:delegation:001'), siblingReservationsCounted: fixed(true), descendantsDebitSameTreeBudget: fixed(true), childLimitsCannotExpandParentAuthority: fixed(true) });
export const subagentOwner = union(
 object({ mode: fixed('foreground'), parentWaiting: fixed('wait'), attachment: fixed('attached'), lifecycleOwnerRef: text('turn:main:001'), parentStop: fixed('cancel-descendants'), parentRelease: fixed('wait-for-required-child-work'), simulationReset: fixed('clear-fixture-only'), orphanRecoveryRef: text('owner:main-session:001') }),
 object({ mode: fixed('background'), parentWaiting: fixed('continue'), attachment: fixed('attached'), lifecycleOwnerRef: text('session:main:001'), parentStop: fixed('cancel-descendants'), parentRelease: fixed('retain-under-session-owner'), simulationReset: fixed('clear-fixture-only'), orphanRecoveryRef: text('owner:main-session:001') }),
 object({ mode: fixed('detached'), parentWaiting: choice(['wait', 'continue'], 'continue'), attachment: fixed('detached'), lifecycleOwnerRef: text('supervisor:workspace:001'), parentStop: fixed('retain-explicit-detached-work'), parentRelease: fixed('retain-under-supervisor-owner'), simulationReset: fixed('clear-fixture-only'), orphanRecoveryRef: text('owner:workspace-supervisor:001') }),
);
export const subagentSource = object({ sourceRef: text('source:task:001'), revision: count(2), authority: choice(['trusted-policy', 'user-task', 'tool-observation', 'external-untrusted', 'memory-evidence']), role: choice(['system-policy', 'user', 'assistant', 'tool', 'resource']), classification: choice(['public', 'workspace', 'private', 'sensitive']), permittedForChild: flag(true), sourcePermissionRef: text('source-admission:001'), retentionPolicyRef: text('retention:task-local'), contentArtifactRef: text('artifact:source:001'), grantFromContent: fixed(false) });
export const subagentContextHandoff = object({ mode: choice(['fresh-task', 'selected-parent-context', 'transcript-fork']), taskRef: text('task:delegation:001'), immutablePacketRef: text('child-packet:001:r1'), sourceHistoryBranchRef: nullable(text('history:parent:r5')), childHistoryBranchRef: text('history:child:001'), parentHistoryCursor: count(5), admittedSources: list(subagentSource), excludedSourceRefs: list(text('history:parent:private'), ['history:parent:private']), completeToolGroups: list(object({ assistantRecordRef: text('history:assistant:tool-round:001'), callIds: list(text('call:search:001')), resultRefs: list(text('result:search:001')), unresolvedCalls: list(text('call:pending:001'), []), everyCallHasResultOrExplicitUnresolvedMarker: fixed(true) })), partialToolGroupsAllowed: fixed(false), copiedContentRemainsOriginalAuthority: fixed(true), forkMutatesParentBranch: fixed(false), selectedPolicyRef: text('context-policy:child:001'), currentPermissionGeneration: count(4) });
export const subagentConfiguration = object({ profileRef: text('profile:researcher:v1'), profileRevision: count(1), requestedModelRef: text('model:worker-fast'), effectiveModelRef: text('model:worker-fast'), toolCapabilityRefs: list(text('tool:search:v1')), skillRefs: list(text('skill:research:v1')), connectorBindingRefs: list(text('binding:docs:child:v1')), credentialHandleRefs: list(text('credential-handle:docs:001'), []), environmentRef: text('environment:project:001'), environmentAssignment: environmentChildBinding, permissionPolicyRef: text('policy:child:restricted'), permissionGeneration: count(4), memoryReadNamespaces: list(text('workspace:demo:shared')), memoryWriteNamespace: text('agent:lina-child:001:private'), sharedPublicationRequiresParentReview: fixed(true), restrictionsIntersectParentAndProfile: fixed(true), credentialMaterialIncluded: fixed(false), automaticApprovalInheritance: fixed(false), provenance: list(object({ field: choice(['model', 'tools', 'skills', 'connectors', 'environment', 'memory']), requestedBy: text('agent:lina-main'), admissionDecisionRef: text('admission:delegation:001'), effectiveValueRef: text('tool:search:v1') })) });
export const subagentResult = object({ resultId: text('child-result:001'), correlation: subagentCorrelation, childTurnId: text('turn:child:001'), resultRevision: count(1), outcome: choice(['completed', 'failed', 'cancelled', 'exhausted', 'timed-out']), summary: text('Found two relevant sources.'), artifactRefs: list(text('artifact:child:report:001')), structuredResult: object({ schemaRef: text('schema:research-result:v1'), payloadRef: text('artifact:child:structured:001'), validation: choice(['valid', 'invalid', 'not-requested']), validationErrors: list(text('missing required citations'), []) }), traceRef: text('trace:child:001'), usageRef: text('usage:child:001'), childHistoryRef: text('history:child:001'), retainedUnderOwnerRef: text('session:main:001'), childOutputIsInstructionAuthority: fixed(false), permissionsExpandedByResult: fixed(false) });
export const subagentChildTurn = object({ origin: fixed('internal-child-turn'), correlation: subagentCorrelation, childTurnId: text('turn:child:001'), admissionRef: text('admission:delegation:001'), packetRef: text('child-packet:001:r1'), historyBranchRef: text('history:child:001'), configuration: subagentConfiguration, budget: subagentBudget, owner: subagentOwner, newUserIngressRequired: fixed(false), userDeliveryAllowed: fixed(false), resultReturnRef: text('return:call:delegate:001'), executionFence: count(3) });
export const subagentSession = object({ sessionId: text('session:child:001'), childAgentId: text('lina-child:001'), owner: subagentOwner, historyBranchRef: text('history:child:001'), persistent: flag(true), revision: count(2), currentTurnId: nullable(text('turn:child:001')), status: choice(['idle', 'running', 'waiting', 'closing', 'closed']), admissionGeneration: count(4), followupRechecksCurrentPermission: fixed(true), followupSerializesPerSession: fixed(true), resumeReplaysExternalEffects: fixed(false) });
export const subagentControl = object({ controlId: text('control:child:001'), correlation: subagentCorrelation, action: choice(['status', 'steer', 'follow-up', 'resume', 'cancel', 'close-session']), guidanceArtifactRef: sample(nullable(text('artifact:child:guidance:001')), null), targetChildIds: list(text('lina-child:001')), includeDescendants: flag(true), actorRef: text('actor:parent:main'), expectedSessionRevision: count(2), expectedLifecycleGeneration: count(3), currentPermissionRecheck: fixed(true), crossesOwnershipBoundary: flag(false), idempotencyKey: text('control:child:001') });
export const subagentJoin = object({ joinId: text('join:children:001'), parentTurnId: text('turn:main:001'), parentCallId: text('call:join:001'), treeId: text('tree:main:001'), requestedChildIds: list(text('lina-child:001')), condition: choice(['all-selected', 'any-selected', 'quorum']), quorum: count(1), deadlineAt: text('2026-10-08T12:05:00Z'), requiredForParentCompletion: flag(true), cancelUnselectedChildren: fixed(false), siblingOutcomesPreserved: fixed(true), terminalFailureCountsAsSettled: flag(true), returnedResultRefs: list(text('child-result:001')), unresolvedChildIds: list(text('lina-child:002'), []), ownerRef: text('session:main:001') });
export const subagentDelivery = object({ deliveryId: text('delivery:child-result:001'), result: subagentResult, destination: object({ parentAgentId: text('lina-main'), parentTurnId: text('turn:main:001'), parentCallId: text('call:delegate:001'), continuationRef: text('continuation:call:delegate:001'), ownerRef: text('session:main:001') }), deliverySequence: count(1), expectedParentFence: count(2), outcome: choice(['pending', 'accepted', 'duplicate-acknowledged', 'parent-unavailable', 'stale-parent-fence']), atLeastOnceDelivery: fixed(true), acceptanceIdempotencyKey: text('delivery:child-result:001'), childRerunOnLostDeliveryAck: fixed(false), userOutputRoute: fixed(false) });
export const subagentLaunch = object({ correlation: subagentCorrelation, launchId: text('launch:delegation:001'), requestFingerprint: text('sha256:fixture-delegation-001'), status: choice(['intent-recorded', 'started', 'known-unstarted', 'failed', 'unknown']), childExecutionRef: nullable(text('execution:child:001')), reservationRef: text('reservation:delegation:001'), originalIdentityMustBeInspected: fixed(true), newLaunchPermittedWhileUnknown: fixed(false), repeatedChangedFingerprint: fixed('conflict'), fence: count(3) });
export const subagentLocalContext = object({ storage: fixed('fixture-only'), correlation: subagentCorrelation, budget: subagentBudget, owner: subagentOwner, configuration: subagentConfiguration, session: subagentSession, knownSiblings: list(object({ childAgentId: text('lina-child:002'), sessionRef: text('session:child:002'), state: choice(['admitted', 'running', 'waiting', 'completed', 'failed', 'cancelled', 'unknown']), resultRef: sample(nullable(text('child-result:002')), null) }), []), policyRevision: count(4), currentFence: count(3), trustedCoordinatorSuppliesContext: fixed(true), untrustedChildOutputCanGrantPermission: fixed(false) });
