import { choice, count, fixed, flag, list, nullable, object, output, sample, text, union, replaceField, type ContractDefinition, type Payload, type Json } from './schema';
import { turnState, limits, toolCall, toolResult } from './shared';
import { modelCredentialReady, modelCredentialReadinessRequest, modelMetadataCredentialReady, modelMetadataCredentialReadinessRequest } from './modelRecords';

const edges = (...ids: string[]) => ids.map(id => `lina-tools-edge-${id}`);
const extend = (value: Payload, fields: Record<string, Payload>) => object({ ...Object.fromEntries(Object.entries(value.schema.properties ?? {}).map(([key, schema]) => [key, { schema, example: (value.example as Record<string, Json>)[key] }])), ...fields });
const empty = (value: Payload) => sample(nullable(value), null);
/** Open JSON Schema document received from a tool provider. The host validates the
 * document with its selected dialect before registry acceptance. This field is
 * schema data, not the schema of a concrete call's arguments. */
export const toolSchemaDocument: Payload = { schema: { type: 'object', additionalProperties: true }, example: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'], additionalProperties: false } };
export const toolCapabilityDescriptor = object({
  capabilityId: text('tool:files:read_file'), alias: text('files_read_file'), upstreamName: text('read_file'), description: text('Read a file from the permitted workspace.'), source: choice(['builtin', 'mcp', 'native-connector', 'plugin'], 'mcp'), connectionId: nullable(text('connection:files')), ownerScope: text('owner:demo'), accountId: nullable(text('account:demo')), schemaRevision: text('sha256:fixture-schema-v1'), adapterRef: text('adapter:mcp-http:v1'), inputSchema: toolSchemaDocument, outputSchema: sample(nullable(toolSchemaDocument), { type: 'object', properties: { content: { type: 'string' }, truncated: { type: 'boolean' } }, required: ['content', 'truncated'], additionalProperties: false }), schemaDialect: text('https://json-schema.org/draft/2020-12/schema'), provenance: object({ providerRef: text('mcp:files'), definitionRevision: text('catalog:files:r1'), wireMetadataRef: text('artifact:discovery:files:r1') }), advertisedHints: object({ readOnly: flag(true), destructive: flag(false), idempotent: flag(true), openWorld: flag(false) }), localPolicy: object({ effect: choice(['read', 'write', 'unknown'], 'read'), parallelEligible: flag(true), conflictKeys: list(text('workspace:demo'), []), policyRef: text('tools-policy:files:v1') }), availability: choice(['ready', 'needs-auth', 'disconnected', 'disabled'], 'ready'), connectionGeneration: count(1), permissionRef: text('permissions:owner-demo:files')
});
export const capabilityDiscovery = object({ connectionId: text('connection:files'), ownerScope: text('owner:demo'), accountId: nullable(text('account:demo')), connectionGeneration: count(1), discoveryRevision: text('catalog:files:r1'), definitions: list(toolCapabilityDescriptor), resourceInventory: object({ revision: text('resources:files:r1'), supported: flag(true), entries: list(object({ uri: text('file:///workspace/demo/README.md'), mimeType: text('text/markdown'), name: text('Workspace readme'), sourceRevision: text('r1') })), templatesRef: nullable(text('resource-templates:files:r1')) }), promptInventory: object({ revision: text('prompts:files:r1'), supported: flag(true), entries: list(object({ name: text('review-document'), argumentSchema: toolSchemaDocument, sourceRevision: text('r1') })) }), clientSupport: object({ sampling: fixed('unsupported'), roots: fixed('unsupported'), subscriptions: choice(['supported', 'unsupported']), continuation: choice(['supported', 'unsupported']) }), paginationComplete: fixed(true), originalMetadataRef: text('artifact:discovery:files:r1'), visibilityScopeRef: text('scopes:files:read'), invalidatedDefinitionIds: list(text('tool:files:removed'), []) });

const remoteCall = sample(toolCall, { callId: 'call-001', name: 'files_read_file', arguments: { path: 'README.md' } });
const pendingExecution = object({ state: replaceField(turnState, 'limits', sample(limits, { roundsStarted: 1, maxRounds: 3, attempts: 1, retriesRemaining: 1 })), round: object({ roundId: text('round-001'), index: count(1) }), batch: object({ batchId: text('batch-001'), calls: list(toolCall, [remoteCall.example], 1) }) });
const callContinuation = object({ execution: pendingExecution, agentId: text('lina-main'), turnId: text('turn-001'), roundId: text('round-001'), batchId: text('batch-001'), callIds: list(text('call-001'), ['call-001'], 1), resumeRef: text('continuation:batch-001:auth'), dispatchState: fixed('not-started') });
const parallelPendingExecution = replaceField(pendingExecution, 'batch', object({ batchId: text('batch-001'), calls: list(toolCall, [remoteCall.example, { callId: 'call-002', name: 'calculator', arguments: { expression: '3 + 3' } }], 1) }));
const parallelContinuation = replaceField(replaceField(callContinuation, 'execution', parallelPendingExecution), 'callIds', list(text('call-001'), ['call-001', 'call-002'], 1));
const trigger = union(object({ reason: fixed('startup'), continuation: empty(callContinuation) }), object({ reason: choice(['call-readiness', 'scope-step-up']), continuation: callContinuation }), object({ reason: choice(['configuration-change', 'reconnect', 'disconnect']), continuation: empty(callContinuation) }));
const binding = object({ connectionId: text('connection:files'), ownerScope: text('owner:demo'), accountId: nullable(text('account:demo')), resource: text('https://mcp.example.test/files'), issuer: nullable(text('https://auth.example.test')), credentialRef: nullable(text('credential:owner-demo:files:account-demo')), requiredScopes: list(text('files:read')), audienceKind: choice(['mcp-resource', 'native-provider', 'process-environment'], 'mcp-resource') });
const oauthConfig = object({ mode: fixed('oauth'), resourceMetadataRef: text('metadata:files:protected-resource:r1'), issuerMetadataRef: text('metadata:files:issuer:r1'), registration: choice(['pre-registered', 'client-id-metadata-document', 'dynamic-registration']), clientIdRef: text('oauth-client:files:v1'), requestedScopes: list(text('files:read')) });
const authConfig = union(object({ mode: fixed('none') }), object({ mode: fixed('static'), secretRef: text('secret:files:api-key'), injection: choice(['authorization-header', 'provider-header', 'environment']) }), oauthConfig, object({ mode: fixed('provider-specific'), scheme: choice(['github-installation', 'signed-request', 'service-account']), acquisitionAdapterRef: text('auth-adapter:provider:v1'), identityRef: text('provider-identity:demo'), privateMaterialRef: text('secret:provider:private-material') }));
const httpConfig = object({ kind: fixed('mcp-http'), endpoint: text('https://mcp.example.test/files'), supportedVersions: list(text('2026-07-28'), ['2026-07-28', '2025-11-25'], 1), protocolMode: choice(['modern', 'legacy', 'auto'], 'auto'), auth: sample(authConfig, oauthConfig.example), redirectPolicyRef: text('network-policy:no-cross-origin-credentials'), tlsPolicyRef: text('tls-policy:system-trust') });
const stdioConfig = object({ kind: fixed('mcp-stdio'), executableRef: text('installed-command:files-server:v1'), arguments: list(text('--workspace'), ['--workspace', '/workspace/demo']), workingDirectoryRef: text('workspace:demo'), environmentSecretRefs: list(object({ name: text('FILES_API_KEY'), secretRef: text('secret:files:api-key') })), inheritEnvironment: fixed(false), supportedVersions: list(text('2025-11-25')), auth: object({ mode: fixed('process-environment') }) });
const nativeConfig = object({ kind: fixed('native-connector'), provider: text('example-files'), endpointRef: text('provider-endpoint:example-files:v1'), adapterRef: text('adapter:native-files:v1'), auth: sample(authConfig, { mode: 'static', secretRef: 'secret:files:api-key', injection: 'provider-header' }), providerApiVersion: text('v1') });
export const toolsConnectionConfig = object({ binding, trigger, configurationRevision: text('connection-config:files:r1'), enabled: flag(true), route: union(httpConfig, stdioConfig, nativeConfig), configurationTrustRef: text('trust:owner-demo:connection-files'), adapterPolicyRef: text('adapter-policy:files:v1') });
const policyContext = object({ designOnly: fixed(true), connectionStoreRef: text('connections:owner-demo:r1'), credentialStoreAdapterRef: text('credential-store:protected:v1'), authorityRef: text('authority:owner-demo'), clockRef: text('clock:fixture-2026-10-08'), registrationPolicyRef: text('oauth-registration-policy:v1'), callbackPolicyRef: text('oauth-callback-policy:v1'), networkPolicyRef: text('network-policy:files:v1'), protocolAdapterRef: text('adapter:mcp:v1'), catalogPolicyRef: text('catalog-policy:v1') });
const readiness = object({ binding, trigger, configurationRevision: text('connection-config:files:r1'), route: union(httpConfig, stdioConfig, nativeConfig), credentialLeaseRef: nullable(text('credential-lease:files:g1')), credentialGeneration: count(1), readinessGeneration: count(1), authStatus: choice(['not-required', 'ready'], 'ready') });
const publicBinding = replaceField(replaceField(binding, 'issuer', empty(text('unused-issuer'))), 'credentialRef', empty(text('unused-credential')));
const stdioBinding = replaceField(replaceField(publicBinding, 'audienceKind', fixed('process-environment')), 'resource', text('process:files-server'));
const nativeBinding = replaceField(replaceField(binding, 'audienceKind', fixed('native-provider')), 'issuer', empty(text('unused-static-issuer')));
const failure = (stage: string, code: string) => object({ binding, trigger, stage: fixed(stage), code: fixed(code), disposition: choice(['unavailable', 'reauthorization-required', 'retry-setup', 'closed'], 'unavailable'), retryToolCall: fixed(false), diagnosticRef: text(`diagnostic:files:${stage}`) });
const credentialMetadata = object({ binding, scheme: choice(['oauth', 'static', 'provider-specific', 'process-environment'], 'oauth'), secretRecordRef: text('secret-record:files:g1'), generation: count(1), issuedAt: text('2026-10-08T08:00:00Z'), expiresAt: nullable(text('2026-10-08T09:00:00Z')), refreshAvailable: flag(true), grantedScopes: list(text('files:read')), revoked: flag(false), storageClass: choice(['os-keychain', 'encrypted-local-store', 'hosted-secret-store']), provenanceRef: text('authorization:files:attempt-001') });
const credentialLookup = object({ binding, trigger, configurationRevision: text('connection-config:files:r1'), route: union(httpConfig, stdioConfig, nativeConfig), lookupKey: object({ ownerScope: text('owner:demo'), connectionId: text('connection:files'), accountId: nullable(text('account:demo')), issuer: nullable(text('https://auth.example.test')), resource: text('https://mcp.example.test/files'), scheme: choice(['oauth', 'static', 'provider-specific'], 'oauth') }), requestedScopes: list(text('files:read')) });
const retrieved = extend(credentialLookup, { credential: credentialMetadata, retrievalAccessRef: text('secret-store-access:files:001') });
const missing = extend(credentialLookup, { reason: fixed('credential-not-found'), previousGeneration: count(0) });
const authorizationRequest = extend(credentialLookup, { reason: choice(['credential-not-found', 'expired-without-refresh', 'scope-step-up', 'invalid-grant'], 'credential-not-found'), previousGeneration: count(0), consentRequired: fixed(true) });
const attempt = object({ attemptId: text('auth-attempt-001'), binding, continuation: empty(callContinuation), expectedIssuer: text('https://auth.example.test'), resource: text('https://mcp.example.test/files'), redirectUri: text('http://127.0.0.1:8765/oauth/callback'), clientIdRef: text('oauth-client:files:v1'), requestedScopes: list(text('files:read')), stateRef: text('private:oauth-state:attempt-001'), pkceVerifierRef: text('private:pkce-verifier:attempt-001'), pkceMethod: fixed('S256'), createdAt: text('2026-10-08T08:00:00Z'), expiresAt: text('2026-10-08T08:05:00Z'), consumed: flag(false), issuerParameterRequired: flag(true) });
const authorizationWait = object({ binding, trigger, attempt, status: fixed('authorization-required'), userActionRef: text('ui-action:authorize:attempt-001'), dispatchBlocked: fixed(true), waitRef: text('wait:files:authorization:001') });
const callback = object({ attemptId: text('auth-attempt-001'), callbackEnvelopeRef: text('private:oauth-callback:attempt-001'), receivedAt: text('2026-10-08T08:01:00Z'), checks: object({ stateMatches: flag(true), notExpired: flag(true), notConsumed: flag(true), ownerMatches: flag(true), connectionMatches: flag(true), resourceMatches: flag(true), issuerMatches: flag(true) }), response: choice(['code', 'access-denied', 'invalid'], 'code') });
const pendingStore = object({ binding, trigger, accountVerification: object({ expectedAccountId: text('account:demo'), providerAccountId: text('account:demo'), identityEvidenceRef: text('private:provider-account-evidence:001'), ownerChecked: fixed(true), issuerChecked: fixed(true), resourceChecked: fixed(true), accountChecked: fixed(true) }), attemptId: text('auth-attempt-001'), validatedCallbackRef: text('private:validated-callback:attempt-001'), privateExchangeResultRef: text('private:token-exchange-result:attempt-001'), expectedGeneration: count(0), nextCredential: credentialMetadata, consumedAttempt: fixed(true) });
const refreshRequest = extend(replaceField(retrieved, 'credential', replaceField(credentialMetadata, 'expiresAt', text('2026-10-08T07:59:00Z'))), { reason: fixed('expired-access-credential'), refreshLockKey: text('credential:owner-demo:files:account-demo:g1'), expectedGeneration: count(1), refreshAttemptRef: text('refresh:files:g1:001') });
const refreshStore = object({ binding, trigger, accountVerification: object({ ownerChecked: fixed(true), issuerChecked: fixed(true), resourceChecked: fixed(true), accountChecked: fixed(true), identityEvidenceRef: text('private:provider-account-evidence:001') }), refreshAttemptRef: text('refresh:files:g1:001'), privateExchangeResultRef: text('private:refresh-result:files:g2'), expectedGeneration: count(1), nextCredential: sample(credentialMetadata, { ...(credentialMetadata.example as Record<string, Json>), secretRecordRef: 'secret-record:files:g2', generation: 2, expiresAt: '2026-10-08T10:00:00Z' }), rotatedRefreshSecret: flag(true), refreshLockRef: text('lock:files:g1') });
const connected = extend(readiness, { connectionGeneration: count(1), handleRef: text('connection-handle:files:g1'), status: fixed('open'), startedAt: text('2026-10-08T08:01:02Z') });
const legacyProtocol = object({ era: fixed('legacy'), version: text('2025-11-25'), exchange: fixed('initialize-then-initialized'), sessionRef: nullable(text('private:mcp-session:files:g1')), capabilitiesRef: text('mcp-capabilities:files:legacy'), notificationMode: choice(['none', 'negotiated-stream'], 'negotiated-stream') });
const modernProtocol = object({ era: fixed('modern'), version: text('2026-07-28'), exchange: fixed('per-request-metadata'), discoveryProbe: choice(['performed', 'not-required'], 'performed'), delivery: choice(['json-or-request-sse', 'stdio']), protocolSession: fixed(false), capabilitiesRef: text('mcp-capabilities:files:modern'), notificationMode: choice(['none', 'subscription-listen'], 'subscription-listen') });
const nativeProtocol = object({ era: fixed('native-provider'), providerApiVersion: text('v1'), adapterRef: text('adapter:native-files:v1'), protocolSession: fixed(false) });
const compatible = extend(connected, { compatibility: union(modernProtocol, legacyProtocol, nativeProtocol), implementedClientHandlers: list(choice(['roots', 'sampling', 'elicitation']), []), compatibilityEvidenceRef: text('protocol-check:files:g1') });
const monitoring = object({ binding, trigger, connectionGeneration: count(1), catalogRevision: text('catalog:files:r1'), readinessGeneration: count(1), subscriptionsRef: nullable(text('subscription:files:tools-changed')), processCleanupRef: nullable(text('process-cleanup:files:g1')), state: fixed('ready') });
const disconnect = object({ binding, trigger: sample(trigger, { reason: 'disconnect', continuation: null }), expectedGeneration: count(1), disconnectRequestRef: text('disconnect:files:001'), outstandingCallIds: list(text('call-001'), []), revokeRemote: flag(true), revocationSupported: flag(true), noNewDispatch: fixed(true) });
const removed = object({ binding, disconnectRequestRef: text('disconnect:files:001'), removedCredentialGeneration: count(1), localDeletion: fixed('complete'), remoteRevocation: choice(['confirmed', 'unsupported', 'failed', 'not-requested'], 'confirmed'), outstandingCallIds: list(text('call-001'), []), dispatchedEffectsReversed: fixed(false), connectionState: fixed('closed'), catalogInvalidationRequired: fixed(true), auditRef: text('credential-audit:files:removed') });
const node = (id: string, reads: string[], writes: string[], rules: string[], outputs: ContractDefinition['outputs'], external?: ContractDefinition['external']): ContractDefinition => ({ nodeId: `lina-tools-${id}`, context: policyContext, contextSource: 'Server-owned connection, credential, protocol and permission policy. This is reference design metadata; protected values never enter the exported graph.', reads, writes, rules, outputs, ...(external ? { external } : {}) });

/** Reference lifecycle contracts. Secret-store operations, OAuth exchanges and
 * network connections are design obligations; Studio does not perform them. */
export const toolsConnectionContracts: ContractDefinition[] = [
  node('config', ['Owner-scoped trusted configuration and requested startup/change'], ['Validated transport-specific connection configuration'], ['Configuration is host-owned; a model call cannot select an arbitrary endpoint or executable.', 'Stdio passes an explicit environment allowlist. Native provider identity and MCP resource identity remain distinct.'], [
    output('tools.connection-configured', 'Remote MCP configuration resolved', toolsConnectionConfig, edges('config-auth'), 'Enabled remote connection has a trusted endpoint and adapter configuration.'),
    output('tools.connection-stdio-configured', 'Local process configuration resolved', replaceField(replaceField(toolsConnectionConfig, 'route', stdioConfig), 'binding', stdioBinding), edges('config-auth'), 'Local process configuration is trusted; environment contains references only.'),
    output('tools.connection-native-configured', 'Native connector configuration resolved', replaceField(replaceField(toolsConnectionConfig, 'route', nativeConfig), 'binding', nativeBinding), edges('config-auth'), 'Native provider adapter and credential scheme are configured.'),
    output('tools.connection-config-rejected', 'Configuration rejected', failure('configuration', 'untrusted_or_invalid_route'), [], 'Endpoint/process policy or configuration validation fails; no connection is opened.'),
  ], [{ label: 'Connection startup request', value: toolsConnectionConfig, source: 'Trusted startup/configuration store' }]),
  node('auth', ['Transport authentication mode, credential readiness and optional owning call continuation'], ['Scoped authentication readiness, credential lookup request or resumed call'], ['Account authentication does not authorize a tool operation.', 'Resume the same batch/call ownership and immutable original arguments after authorization. Load the retained continuation record, never reconstruct a new call from a callback. Recheck schema digest/catalog, permission, cancellation and launch certainty.', 'Stdio credential references are for explicit process environment; public HTTP endpoints require no invented consent.'], [
    output('tools.auth-lookup-required', 'Credential readiness required', credentialLookup, edges('auth-credential-reference'), 'Configured static, OAuth or provider identity needs a scoped store lookup.'),
    output('tools.auth-ready', 'Authenticated connection ready', readiness, edges('auth-connect'), 'Scoped credential lease passed validity checks; adapter receives private material outside graph records.'),
    output('tools.auth-not-required', 'Public connection ready', replaceField(replaceField(replaceField(replaceField(readiness, 'binding', publicBinding), 'route', replaceField(httpConfig, 'auth', object({ mode: fixed('none') }))), 'authStatus', fixed('not-required')), 'credentialLeaseRef', empty(text('credential-lease:unused'))), edges('auth-connect'), 'Configured endpoint is public; OAuth is unnecessary.'),
    output('tools.auth-stdio-ready', 'Process environment ready', replaceField(replaceField(readiness, 'route', stdioConfig), 'binding', stdioBinding), edges('auth-connect'), 'Explicit process environment references were resolved; MCP HTTP OAuth does not apply.'),
    output('tools.auth-call-resumed', 'Readiness returns to retained wait', extend(pendingExecution, { connectionReadiness: replaceField(readiness, 'trigger', object({ reason: fixed('call-readiness'), continuation: callContinuation })), continuation: callContinuation, pendingCallIds: list(text('call-001'), ['call-001']), settledSiblingResults: list(toolResult, []), doNotRedispatchSettledSiblings: fixed(true), launchPermissionRecheckRequired: fixed(true), bindingRecheckRequired: fixed(true) }), edges('auth-resolve'), 'A matching authorization completion resumes the retained call before fresh admission. No uncertain launched operation is replayed.'),
    output('tools.auth-parallel-batch-resumed', 'Two-call readiness returns to retained wait', extend(parallelPendingExecution, { connectionReadiness: replaceField(readiness, 'trigger', object({ reason: fixed('call-readiness'), continuation: parallelContinuation })), continuation: parallelContinuation, pendingCallIds: list(text('call-001'), ['call-001']), settledSiblingResults: list(toolResult, [{ callId: 'call-002', outcome: 'success', value: 6 }]), doNotRedispatchSettledSiblings: fixed(true), launchPermissionRecheckRequired: fixed(true), bindingRecheckRequired: fixed(true) }), edges('auth-resolve'), 'Matching account authorization resumes the same two-call batch; both call IDs, original argument records and round counters remain unchanged.'),
  ]),
  node('credential-reference', ['Connection/owner/account/issuer/resource lookup binding'], ['Exact credential store key or explicit absence'], ['The same server name with another owner, issuer, resource or account is a different credential binding.', 'A credential reference is an opaque identifier, never a token or a model-supplied grant.'], [
    output('tools.credential-reference-resolved', 'Credential key resolved', credentialLookup, edges('credential-reference-credential-retrieve'), 'Configured identity is complete and scope permitted.'),
    output('tools.credential-reference-rejected', 'Credential scope lookup rejected', failure('credential-reference', 'invalid_identity_or_lookup_scope_denied'), edges('credential-reference-monitor'), 'Owner/account/resource binding is invalid or private store lookup authority is denied; no secret is retrieved.'),
    output('tools.credential-reference-absent', 'No prior reference recorded', replaceField(credentialLookup, 'binding', replaceField(binding, 'credentialRef', empty(text('credential:missing')))), edges('credential-reference-credential-retrieve'), 'First authorization still uses the exact private store namespace; no prior credential reference exists.'),
  ]),
  node('credential-retrieve', ['Scoped lookup key and secret-store access policy'], ['Credential lease metadata, explicit missing record or store failure'], ['Secrets stay in the private credential adapter. Export only lease/record references and safe metadata.', 'Missing credentials and an unavailable store are different outcomes; storage failure must not silently trigger a replacement login.'], [
    output('tools.credential-retrieved', 'Private credential record found', retrieved, edges('credential-retrieve-credential-validity'), 'Store returns a private lease with account-bound metadata.'),
    output('tools.credential-missing', 'No credential stored', missing, edges('credential-retrieve-credential-validity'), 'The scoped key has no record.'),
    output('tools.credential-store-unavailable', 'Credential store unavailable', failure('credential-retrieval', 'secret_store_unavailable'), edges('credential-retrieve-monitor'), 'Store is locked, unreachable or access denied; no secret leaves storage.'),
  ]),
  node('credential-validity', ['Credential lease metadata or missing-store result, required resource and scopes'], ['Ready lease, refresh request or explicit authorization requirement'], ['Verify owner/account/issuer/resource, revocation, expiry margin and required scopes before dispatch.', 'Static credentials need configured validity/revocation policy; do not invent OAuth expiry or refresh behavior for an API key.', 'Never infer permission to execute from authentication readiness.'], [
    output('tools.credential-valid', 'Credential ready for adapter', readiness, edges('credential-validity-auth'), 'Binding, required scopes and validity checks passed.'),
    output('tools.credential-authorization-required', 'Authorization required', authorizationRequest, edges('credential-validity-credential-authorize'), 'Credential is absent or cannot be refreshed, or current operation needs explicit scope step-up.'),
    output('tools.credential-scope-step-up', 'Additional account scope required', replaceField(replaceField(replaceField(replaceField(authorizationRequest, 'reason', fixed('scope-step-up')), 'previousGeneration', count(1)), 'requestedScopes', list(text('files:read'), ['files:read', 'files:write'])), 'binding', replaceField(binding, 'requiredScopes', list(text('files:write')))), edges('credential-validity-credential-authorize'), 'Authenticated account has files:read but operation requires files:write; accumulated scopes need explicit reauthorization.'),
    output('tools.credential-expired-refreshable', 'Refreshable access credential expired', refreshRequest, edges('credential-validity-credential-refresh'), 'OAuth refresh is available and owner/resource binding still matches.'),
    output('tools.credential-binding-rejected', 'Credential binding rejected', failure('credential-validity', 'owner_account_issuer_resource_mismatch'), [], 'A stored credential belongs to another binding; it is neither used nor silently rebound.'),
  ]),
  node('credential-authorize', ['Account-bound authorization request and separately received private callback'], ['Consent wait, validated exchange for storage or rejected/cancelled attempt'], ['Validate issuer metadata, resource metadata, registration strategy and advertised S256 PKCE support before opening consent.', 'Bind the attempt to owner/account/connection/resource/issuer/redirect/scopes and expiry. Store state, code and verifier privately.', 'After token exchange verify the actual provider account, issuer and resource against the retained owner/connection binding before committing. Reject mismatches without replacing the prior record.', 'Consume a validated callback once. Reject expired/replayed/mismatched state or issuer before token exchange. Validate present issuer even when not advertised, require it when advertised.', 'Provider-specific authorization runs its own acquisition adapter. MCP OAuth is for HTTP and includes the target resource in authorization and token requests.'], [
    output('tools.authorization-wait', 'Await account authorization', authorizationWait, [], 'Explicit authorization has been requested; owning work remains blocked and its continuation retained.'),
    output('tools.authorization-exchanged', 'Validated exchange ready to store', pendingStore, edges('credential-authorize-credential-store'), 'Callback validation passes and the private token exchange returns a bound credential record.'),
    output('tools.authorization-step-up-exchanged', 'Scope step-up exchange ready to store', replaceField(replaceField(pendingStore, 'expectedGeneration', count(1)), 'nextCredential', replaceField(replaceField(replaceField(credentialMetadata, 'generation', count(2)), 'secretRecordRef', text('secret-record:files:g2')), 'grantedScopes', list(text('files:read'), ['files:read', 'files:write']))), edges('credential-authorize-credential-store'), 'Validated scope step-up exchange targets the existing credential generation and preserves previous granted scopes.'),
    output('tools.authorization-callback-rejected', 'Invalid callback rejected', extend(failure('authorization', 'invalid_callback_state_or_issuer'), { attemptId: text('auth-attempt-001'), tokenExchangeOccurred: fixed(false), oldCredentialPreserved: fixed(true) }), edges('credential-authorize-monitor'), 'State/issuer/expiry/replay/owner binding validation fails; no code is exchanged.'),
    output('tools.authorization-denied', 'Consent denied or cancelled', extend(failure('authorization', 'consent_denied'), { attemptId: text('auth-attempt-001'), tokenExchangeOccurred: fixed(false), oldCredentialPreserved: fixed(true) }), edges('credential-authorize-monitor'), 'Validated callback indicates denial, or the owning user cancels authorization.'),
    output('tools.authorization-registration-unavailable', 'No usable client registration', failure('authorization', 'registration_or_pkce_unavailable'), edges('credential-authorize-monitor'), 'No compatible trusted client identity or PKCE support exists; do not guess an OAuth strategy.'),
    output('tools.authorization-static-configured', 'Static credential installation requested', object({ binding, trigger, privateMaterialRef: text('private:static-secret-import:001'), expectedGeneration: count(0), nextCredential: replaceField(replaceField(replaceField(credentialMetadata, 'scheme', fixed('static')), 'expiresAt', empty(text('unused-expiry'))), 'refreshAvailable', fixed(false)), configuredBy: text('owner:demo') }), edges('credential-authorize-credential-store'), 'User explicitly supplies a provider static credential to a private intake surface; no OAuth callback is required.'),
  ], [{ label: 'Private OAuth callback notification', value: object({ attempt, callback }), source: 'Callback listener. References point into a private store; no authorization code, state or verifier is exported.' }, { label: 'Matching callback after call-triggered authorization', value: object({ attempt: replaceField(attempt, 'continuation', callContinuation), callback }), source: 'Callback listener correlated to the retained batch and call' }, { label: 'Rejected callback binding', value: object({ attempt, callback: replaceField(callback, 'checks', object({ stateMatches: fixed(false), notExpired: fixed(true), notConsumed: fixed(true), ownerMatches: fixed(true), connectionMatches: fixed(true), resourceMatches: fixed(true), issuerMatches: fixed(false) })) }), source: 'Private callback intake. Validation fails before code exchange.' }, { label: 'Denied consent callback', value: object({ attempt, callback: replaceField(callback, 'response', fixed('access-denied')) }), source: 'Validated callback listener reports denied consent; prior credentials remain untouched.' }]),
  node('credential-store', ['Validated exchange/import result or locked refresh result'], ['Atomically committed credential generation and private lease metadata'], ['Write secret material and metadata atomically under the expected generation. Concurrent writers must not overwrite a newer record.', 'Rotating refresh credentials replace the whole protected record; release refresh lock after commit. Do not claim durable readiness before storage succeeds.', 'Failed commits preserve the prior usable record and never export the exchanged secrets.'], [
    output('tools.credential-stored', 'Credential generation committed', retrieved, edges('credential-store-credential-validity'), 'Initial authorization/import was committed as generation 1.'),
    output('tools.credential-refresh-stored', 'Rotated credential committed', extend(retrieved, { credential: refreshStore.schema.properties ? { schema: refreshStore.schema.properties.nextCredential, example: (refreshStore.example as Record<string, Json>).nextCredential } : credentialMetadata }), edges('credential-store-credential-validity'), 'Generation 1 was replaced atomically by generation 2 under the refresh lock.'),
    output('tools.credential-step-up-stored', 'Expanded scopes committed', replaceField(retrieved, 'credential', replaceField(replaceField(replaceField(credentialMetadata, 'generation', count(2)), 'secretRecordRef', text('secret-record:files:g2')), 'grantedScopes', list(text('files:read'), ['files:read', 'files:write']))), edges('credential-store-credential-validity'), 'Matching generation 1 was replaced by scope-expanded generation 2 after explicit authorization.'),
    output('tools.credential-write-conflict', 'Credential changed during commit', object({ binding, expectedGeneration: count(1), actualGeneration: count(2), code: fixed('generation_conflict'), discardedExchangeRef: text('private:discarded-exchange:001'), previousRecordOverwritten: fixed(false), reReadRequired: fixed(true) }), edges('credential-store-monitor'), 'Another authorized writer installed newer credentials; re-read rather than overwrite.'),
    output('tools.credential-store-failed', 'Protected commit failed', extend(failure('credential-storage', 'protected_commit_failed'), { previousRecordPreserved: fixed(true), readinessPublished: fixed(false) }), edges('credential-store-monitor'), 'Storage is unavailable or commit fails; readiness is withheld.'),
  ]),
  node('credential-refresh', ['Expired credential metadata and expected generation'], ['Locked refreshed result or reauthorization requirement'], ['Serialize refresh per credential binding/generation, including cross-process coordination where shared storage is used.', 'A lock waiter must re-read generation; reuse the winner record instead of consuming a rotating refresh token twice.', 'An invalid grant marks reauthorization required. Refreshing the connection does not establish a right to replay a remote tool operation.'], [
    output('tools.credential-refreshed', 'Refresh response ready to commit', refreshStore, edges('credential-refresh-credential-store'), 'Expected generation remains current under the lock; private exchange succeeded.'),
    output('tools.credential-refresh-invalid-grant', 'Reauthorization required', replaceField(failure('credential-refresh', 'invalid_grant'), 'disposition', fixed('reauthorization-required')), edges('credential-refresh-monitor'), 'Refresh token is invalid, revoked or unavailable; automatic refresh stops.'),
    output('tools.credential-refresh-transient-failure', 'Refresh service unavailable', failure('credential-refresh', 'token_endpoint_unavailable'), edges('credential-refresh-monitor'), 'Refresh failed without a new committed generation; eligible credential maintenance retry remains bounded.'),
    output('tools.credential-refresh-already-completed', 'Concurrent refresh winner exists', extend(credentialLookup, { requestedGeneration: count(1), committedGeneration: count(2), recordRef: text('secret-record:files:g2'), refreshPerformedByThisWaiter: fixed(false), reReadRequired: fixed(true) }), edges('credential-refresh-credential-retrieve'), 'The lock holder already committed a newer generation; waiter returns to scoped retrieval/validity through its coordinator.'),
  ]),
  node('connect', ['Ready transport configuration and privately resolved credential lease'], ['Open adapter/process handle or classified connection failure'], ['A connection handle is not a durable tool receipt. Reconnecting does not replay previously launched calls.', 'HTTP credentials are injected only into authorized requests for the bound resource; never forward tokens in URLs or across unauthorized redirects.', 'Native connectors own provider credential schemes. Stdio owns selected environment injection, process exit and cleanup.'], [
    output('tools.connection-opened', 'Connection opened', connected, edges('connect-protocol'), 'Configured transport or native client opens successfully.'),
    output('tools.connection-stdio-opened', 'Stdio process opened', replaceField(replaceField(connected, 'route', stdioConfig), 'binding', stdioBinding), edges('connect-protocol'), 'Trusted local command starts with explicit environment and owned cleanup handle.'),
    output('tools.connection-native-opened', 'Native provider client ready', replaceField(replaceField(connected, 'route', nativeConfig), 'binding', nativeBinding), edges('connect-protocol'), 'Configured provider adapter acquires its account-bound client.'),
    output('tools.connection-failed', 'Connection unavailable', failure('connection', 'transport_open_failed'), edges('connect-monitor'), 'DNS/TLS/process/client setup fails; no tool call is launched.'),
  ]),
  node('protocol', ['Opened adapter and supported protocol versions'], ['Era-specific compatibility evidence or unsupported protocol outcome'], ['Legacy MCP uses initialize and initialized; modern MCP uses per-request metadata and optional discovery. Do not make initialize universal.', 'Recognized modern errors do not automatically justify legacy fallback. Native providers validate their own API compatibility.', 'Advertise roots, sampling or elicitation only if complete handlers and permission boundaries are installed.'], [
    output('tools.protocol-modern-ready', 'Modern MCP compatible', compatible, edges('protocol-discover'), 'Adapter supports 2026-07-28 per-request metadata and its negotiated/discovered capability behavior.'),
    output('tools.protocol-legacy-ready', 'Legacy MCP initialized', replaceField(compatible, 'compatibility', legacyProtocol), edges('protocol-discover'), 'Adapter completed the legacy initialization handshake with a supported version.'),
    output('tools.protocol-feature-refused', 'Unsupported client capability refused', object({ connectionId: text('connection:files'), feature: choice(['sampling', 'roots', 'elicitation', 'subscriptions', 'input-continuation']), code: fixed('client-handler-unavailable'), grantedPermission: fixed(false), protocolResponseRef: text('protocol-evidence:unsupported-feature:1') }), edges('protocol-monitor'), 'No complete configured handler/policy boundary exists for the requested client capability.'), output('tools.protocol-native-ready', 'Native API compatible', replaceField(replaceField(replaceField(compatible, 'route', nativeConfig), 'binding', nativeBinding), 'compatibility', nativeProtocol), edges('protocol-discover'), 'Provider API version and adapter compatibility checks pass.'),
    output('tools.protocol-incompatible', 'Protocol unsupported', failure('protocol', 'no_supported_protocol_version'), edges('protocol-monitor'), 'No supported protocol/API version exists; connection capabilities are withheld.'),
  ]),
  node('discover', ['Compatible connection and account-scoped catalog visibility'], ['Complete versioned definitions, refresh invalidations and monitoring snapshot'], ['Follow pagination to completion; validate schema dialect/documents before registering. Keep upstream names and wire metadata provenance.', 'Server effect annotations are hints. Trusted local scheduling policy establishes parallel eligibility and conflicts.', 'MCP tools/resources/prompts are distinct capabilities. Definitions do not authorize execution. Catalog changes invalidate pending bindings and approvals before launch.'], [
    output('tools.capabilities-discovered', 'Complete capability contribution', capabilityDiscovery, edges('discover-register'), 'All catalog pages were fetched under the same account and connection generation.'),
    output('tools.capabilities-empty', 'Empty catalog discovered', replaceField(capabilityDiscovery, 'definitions', list(toolCapabilityDescriptor, [])), edges('discover-register'), 'The account legitimately exposes no tools; empty discovery is not a transport failure.'),
    output('tools.connection-monitoring-ready', 'Connection status observed', monitoring, edges('discover-monitor'), 'Compatible connection and catalog revision are ready for monitoring.'),
    output('tools.discovery-failed', 'Capability discovery failed', failure('discovery', 'catalog_unavailable'), edges('discover-monitor'), 'Discovery fails or pagination cannot complete; do not publish a partial catalog as complete.'),
  ]),
  node('monitor', ['Lifecycle observations, authorization failures, explicit disconnect and capability-change notifications'], ['Bounded setup request, rediscovery request, credential removal or stable unavailable state'], ['Catalog notification/poll refresh uses a still-compatible ready connection. Reconnect returns through configuration/auth/protocol checks.', 'Disconnect disables new dispatch immediately; started work retains its own outcome accounting. Local deletion and remote revocation are separately reported.', 'Credential-maintenance retries and tool-call replay have different guarantees. Never replay uncertain operations from this lifecycle.'], [
    output('tools.connection-reconnect-requested', 'Bounded reconnect requested', toolsConnectionConfig, edges('monitor-config'), 'Configured retry budget permits reconnect after connection failure or configuration change.'),
    output('tools.catalog-refresh-requested', 'Catalog rediscovery requested', extend(compatible, { changeRef: text('catalog-change:files:002'), previousRevision: text('catalog:files:r1') }), edges('monitor-discover'), 'Tools changed notification or permitted poll invalidates discovery while connection remains compatible.'),
    output('tools.connection-disconnect-requested', 'Disconnect and secret removal requested', disconnect, edges('monitor-credential-remove'), 'Owner explicitly disconnects this account binding; new dispatch is blocked.'),
    output('tools.readiness-invalidated', 'Readiness/catalog eligibility invalidated', object({ connectionId: text('connection:files'), ownerScope: text('owner:demo'), accountId: text('account:demo'), previousReadinessGeneration: count(1), currentReadinessGeneration: count(2), previousCatalogRevision: text('catalog:files:r1'), invalidatedBindingRefs: list(text('binding:files:g1')), invalidatedDecisionRefs: list(text('permission:files:call-001')), reason: choice(['disconnected', 'revoked', 'account-changed', 'catalog-changed']), safeEventRef: text('connection-event:files:g2'), replayAuthorized: fixed(false), pendingEffectsPreserved: fixed(true) }), [], 'Coordinator invalidates fresh admission and projects safe lifecycle evidence; no State/Observability backend is claimed.'), output('tools.connection-unavailable', 'Connection unavailable', failure('monitor', 'authorization_or_connection_required'), [], 'No authorized retry or matching user action is ready; catalog eligibility is invalidated and pending owning calls remain blocked or receive classified outcomes.'),
  ], [{ label: 'Scoped disconnect request', value: disconnect, source: 'Connection owner control surface' }, { label: 'Compatible catalog changed notification', value: monitoring, source: 'Negotiated MCP notification/subscription or native adapter event' }]),
  node('credential-remove', ['Authorized disconnect binding and expected generation'], ['Local deletion and separate revocation outcome'], ['Block new dispatch before removal and invalidate account-scoped catalog bindings.', 'Delete local credential material even when remote revocation is unsupported or fails. Report both results; preserve safe audit evidence only.', 'Deleting credentials does not undo already dispatched side effects; calls keep their outcomes and uncertainty accounting.'], [
    output('tools.credential-removed', 'Credentials removed and revocation confirmed', removed, edges('credential-remove-monitor'), 'Protected local deletion completed and provider confirmed supported remote revocation.'),
    output('tools.credential-removed-revocation-unsupported', 'Local deletion complete; revocation unsupported', replaceField(removed, 'remoteRevocation', fixed('unsupported')), edges('credential-remove-monitor'), 'Provider has no supported revocation operation; local access remains removed.'),
    output('tools.credential-removed-revocation-failed', 'Local deletion complete; remote revocation failed', replaceField(removed, 'remoteRevocation', fixed('failed')), edges('credential-remove-monitor'), 'Remote revocation failed; expose that limitation without restoring local credentials.'),
    output('tools.credential-removal-failed', 'Local removal failed', extend(failure('credential-removal', 'secret_store_delete_failed'), { newDispatchBlocked: fixed(true), localDeletion: fixed('failed'), remoteRevocation: fixed('not-attempted') }), edges('credential-remove-monitor'), 'Store deletion fails; connection remains blocked and cleanup needs operator attention.'),
  ]),
];


// Model authentication reuses the protected credential owner, while retaining its
// provider audience and native auth scheme. It never acquires an MCP session.
const sharedCredentialOwner = toolsConnectionContracts.find(definition => definition.nodeId === 'lina-tools-auth')!;
sharedCredentialOwner.rules.push('Tagged owner:model readiness requests use the configured model-provider audience/account and native credential adapter. Do not reinterpret them as MCP OAuth, connector discovery or a tool invocation.', 'The shared owner returns only verified account/readiness/evidence metadata to the retained Execution wait. No secrets or direct uncorrelated Resolve resume leave this boundary.');
sharedCredentialOwner.external = [...(sharedCredentialOwner.external ?? []), { label: 'Protected model-provider credential readiness request', value: modelCredentialReadinessRequest, source: 'Execution retained Model wait; provider credential owner consumes configured account and audience' }];
sharedCredentialOwner.outputs.push(
  output('tools.model-credential-ready', 'Model provider readiness confirmed', modelCredentialReady, edges('auth-resolve'), 'Shared protected owner verifies the exact provider account/readiness generation; resume through the original Model wait with no automatic inference replay.'),
  output('tools.model-credential-denied', 'Model provider readiness denied', replaceField(modelCredentialReady, 'status', fixed('denied')), edges('auth-resolve'), 'Provider readiness is refused under the same retained wait/account. No Model request starts.'),
  output('tools.model-credential-expired', 'Model provider readiness expired', replaceField(modelCredentialReady, 'status', fixed('expired')), edges('auth-resolve'), 'Readiness continuation expired; Resolve classifies the original metadata/invocation purpose without allocating an attempt.'),
  output('tools.model-credential-cancelled', 'Model provider readiness cancelled', replaceField(modelCredentialReady, 'status', fixed('cancelled')), edges('auth-resolve'), 'Cancelled readiness stays cancelled; a late callback cannot revive the original intent.'),
);

sharedCredentialOwner.external!.push({ label: 'Protected capability-metadata credential readiness request', value: modelMetadataCredentialReadinessRequest, source: 'Execution retained Context capability dependency; shared provider credential owner' });
for (const status of ['ready', 'denied', 'expired', 'cancelled'] as const) {
  sharedCredentialOwner.outputs.push(output(`tools.model-metadata-credential-${status}`, `Context capability readiness ${status}`, replaceField(modelMetadataCredentialReady, 'status', fixed(status)), edges('auth-resolve'), 'Return verified metadata-purpose readiness to its retained Execution wait. No inference or Tool operation is launched.'));
}
