import test from 'node:test';
import assert from 'node:assert/strict';
import { linaArchitecture } from '../src/features/lina/architectureDocument';
import { startSimulation, advanceSimulation, answerSimulation, stopSimulation, resetSimulation, type SimulationState } from '../src/features/lina/inputSimulation';
import { OUTPUT_CASES, withOutput, renderOutputFixture, DEFAULT_OUTPUT_SETTINGS, type OutputCase } from '../src/features/lina/outputFixtures';
const start = (scenario: OutputCase, automatic = false, channel: 'cli' | 'telegram' | 'whatsapp' = 'cli') => startSimulation(channel, linaArchitecture, automatic, 'direct-answer', 3, 'fits', 'parallel', 'openai-chat', 'answer', 'policy-allow', [], 'fresh', 'baseline', 'disabled', {}, 'disabled', {}, 'disabled', {}, scenario);
function finish(state: SimulationState) { for (let limit = 0; limit < 5000 && !['completed', 'blocked'].includes(state.status); limit++) {
    if (state.status === 'waiting') {
        const wait = state.wait!;
        state = answerSimulation(state, linaArchitecture, wait.owner === 'output' ? wait.kind === 'output-policy' ? 'allow-once' : wait.kind === 'output-receipt' ? 'ready' : 'known-success' : wait.kind === 'approval' || wait.kind === 'memory-review' ? 'allow-once' : 'ready', wait.id);
    }
    else
        state = advanceSimulation(state, linaArchitecture);
} assert.notEqual(state.status, 'blocked', state.error); assert.equal(state.status, 'completed'); return state; }
for (const { value } of OUTPUT_CASES)
    test(`${value}: Auto/Next share deterministic path and retained output ledger`, () => { const manual = finish(start(value)), automatic = finish(start(value, true)); assert.deepEqual(automatic.outputSnapshot, manual.outputSnapshot); assert.equal(automatic.attempts, manual.attempts); assert.equal(resetSimulation(manual, linaArchitecture).outputCase, value); });
test('real final text reaches Output without a new agent/model attempt', () => { const state = finish(start('final')); assert.ok(state.route.includes('lina-output-intent')); assert.equal(Object.values(state.outputSnapshot!.intents)[0].content.text, state.modelOutcome!.text); assert.equal(state.attempts, 1); assert.equal(Object.values(state.outputSnapshot!.obligations)[0].status, 'accepted'); });
test('unknown output accepts only matching evidence, never reruns model or duplicates send', () => { let state = start('unknown-send'); while (state.status !== 'waiting')
    state = advanceSimulation(state, linaArchitecture); const before = state.attempts, sendCount = Object.keys(state.outputSnapshot!.attempts).length; assert.equal(answerSimulation(state, linaArchitecture, 'stale').wait!.id, state.wait!.id); state = finish(answerSimulation(state, linaArchitecture, 'known-success', state.wait!.id)); assert.equal(state.attempts, before); assert.equal(Object.keys(state.outputSnapshot!.attempts).length, sendCount); assert.equal(Object.values(state.outputSnapshot!.obligations)[0].status, 'accepted'); });
test('preview promotion reuses native message identity but final acquires required custody', () => { const state = finish(start('preview-promote')), rows = Object.values(state.outputSnapshot!.obligations), preview = rows.find(row => !row.required)!, final = rows.find(row => row.required)!; assert.equal(final.parts[0].providerId, preview.parts[0].providerId); assert.equal(final.parts[0].payload.operation, 'edit-promote'); assert.equal(final.status, 'accepted'); });
test('confirmed tool message suppresses identical final while distinct content remains owed', () => { const deduped = finish(start('tool-dedupe')), distinct = finish(start('distinct-tool-content')); assert.ok(Object.values(deduped.outputSnapshot!.intents).some(intent => intent.suppressed === 'confirmed-same-target-digest')); assert.equal(Object.values(deduped.outputSnapshot!.obligations).length, 1); assert.equal(Object.values(distinct.outputSnapshot!.obligations).length, 2); });
test('Output upload State intent precedes effect and unknown upload inspects same identity', () => { let state = start('upload-unknown'); while (state.status !== 'waiting')
    state = advanceSimulation(state, linaArchitecture); const artifact = Object.values(state.outputSnapshot!.artifacts)[0], id = artifact.uploadAttempt!.id; assert.equal(artifact.uploadAttempt!.outcome, 'unknown'); assert.ok(state.events.slice(0, state.step + 1).some(event => event.nodeId === 'lina-state-record' && event.outputEvidence?.phase === 'media')); state = finish(answerSimulation(state, linaArchitecture, 'known-success', state.wait!.id)); assert.equal(Object.values(state.outputSnapshot!.artifacts)[0].uploadAttempt!.id, id); });
test('receipt thresholds respect native capabilities and release before waiting for WhatsApp fact', () => { const cli = finish(start('read-threshold')); assert.equal(Object.values(cli.outputSnapshot!.obligations)[0].status, 'unresolved'); let whatsapp = start('read-threshold', false, 'whatsapp'); while (whatsapp.status !== 'waiting')
    whatsapp = advanceSimulation(whatsapp, linaArchitecture); assert.ok(whatsapp.route.slice(0, whatsapp.step + 1).includes('lina-execution-release')); const done = finish(answerSimulation(whatsapp, linaArchitecture, 'ready', whatsapp.wait!.id)); assert.equal(Object.values(done.outputSnapshot!.obligations)[0].parts[0].status, 'read'); });
test('Stop retains uncertain external send and prevents another output attempt', () => { let state = start('unknown-send'); while (state.status !== 'waiting')
    state = advanceSimulation(state, linaArchitecture); const count = Object.keys(state.outputSnapshot!.attempts).length; state = stopSimulation(state, linaArchitecture); state = finish(state); assert.equal(Object.keys(state.outputSnapshot!.attempts).length, count); assert.equal(Object.values(state.outputSnapshot!.obligations)[0].status, 'unresolved'); });
test('clarification preserves actual tool input wait and uses typed input rather than approval grants', () => { let state = start('clarification'); for (let steps = 0; steps < 5000 && state.status !== 'waiting' && state.status !== 'blocked'; steps++)
    state = advanceSimulation(state, linaArchitecture); assert.equal(state.status, 'waiting', state.error); assert.equal(state.wait!.kind, 'input'); const prompt = Object.values(state.outputSnapshot!.intents).find(intent => intent.finality === 'prompt')!.content; assert.equal(prompt.prompt!.kind, 'clarification'); assert.deepEqual(prompt.choices, []); assert.ok(prompt.prompt!.answerSchema); const grants = state.safetyGrants.length; state = finish(answerSimulation(state, linaArchitecture, 'ready', state.wait!.id)); assert.equal(state.safetyGrants.length, grants); });
for (const scenario of ['crash-before-admission', 'crash-after-admission', 'crash-after-send-start', 'crash-after-acceptance', 'crash-before-receipt-persist'] as const)
    test(`${scenario}: recovered identities and bytes do not replay the model or accepted attempt`, () => { const state = finish(start(scenario)), store = state.outputSnapshot!, recovery = store.recoveries[0], snapshot = store.recoverySnapshots[recovery.stage], obligation = Object.values(store.obligations)[0]; assert.equal(state.attempts, 1); assert.ok(recovery); assert.equal(Object.keys(store.attempts).length, 1); assert.equal(obligation.parts[0].digest, recovery.preparedDigests[0] ?? obligation.parts[0].digest); const attempt = Object.values(store.attempts)[0]; assert.equal(attempt.outcome, 'accepted'); if (scenario === 'crash-before-admission' || scenario === 'crash-after-admission') {
        assert.equal(attempt.fence, obligation.generation);
        assert.equal(attempt.fence, store.ownerFence);
        assert.equal(Object.keys(snapshot.attempts).length, 0);
    }
    else {
        assert.equal(snapshot.attempts[attempt.id].outcome, 'started');
        assert.equal(snapshot.observations.length, 0);
        assert.equal(attempt.fence, 1);
    } });
test('late old-attempt fact is retained without authorizing new native work', () => { const state = finish(start('late-ack')), store = state.outputSnapshot!; assert.ok(store.stopped); assert.equal(Object.keys(store.attempts).length, 1); assert.ok(store.observations.some(row => row.projection === 'late' && row.fact === 'delivered')); assert.equal(Object.values(store.obligations)[0].parts[0].status, 'delivered'); });
test('Stop after custody transfer preserves completed execution outcome and exactly one owner release', () => { let state = start('unknown-send'); while (state.status !== 'waiting')
    state = advanceSimulation(state, linaArchitecture); const outcome = state.outcome; assert.equal(state.events.slice(0, state.step + 1).filter(event => event.nodeId === 'lina-execution-release' && !event.sourceNodeId?.startsWith('lina-state-')).length, 1); state = finish(stopSimulation(state, linaArchitecture)); assert.equal(state.outcome, outcome); assert.equal(state.events.filter(event => event.nodeId === 'lina-execution-release' && !event.sourceNodeId?.startsWith('lina-state-')).length, 1); });
