import assert from 'node:assert/strict';
import test from 'node:test';
import { linaArchitecture as document } from '../src/features/lina/architectureDocument';
import { MEMORY_CASES, createMemoryFixtureState, commitMemoryFixture, forgetMemoryFixture, selectMemoryFixture, withMemory, type MemoryRecord } from '../src/features/lina/memoryFixtures';
import { startSimulation, advanceSimulation, answerSimulation, type SimulationEvent, type SimulationState } from '../src/features/lina/inputSimulation';
const base:SimulationEvent[]=[{id:'context',nodeId:'lina-context-load',update:{contextPreparations:1}},{id:'work',nodeId:'lina-tools-dispatch',update:{attempts:1},operations:[{callId:'original-call',batchId:'batch',attemptId:'attempt',nodeId:'lina-tools-dispatch',status:'running',effectClass:'read',accountId:'account',catalogRevision:7}]},{id:'settled',nodeId:'lina-execution-settle',update:{outcome:'completed'},results:[{callId:'original-call',status:'success',artifactRef:'original-result'}]}];
const result=(scenario:Parameters<typeof withMemory>[2])=>withMemory(base,document,scenario);
const last=(events:ReturnType<typeof result>)=>events.flatMap(event=>event.memorySnapshot?[event.memorySnapshot]:[]).at(-1)!;
for(const {value} of MEMORY_CASES)test(`${value}: deterministic memory branches use maintained graph edges and preserve main work`,()=>{
 const first=result(value),second=result(value);assert.deepEqual(first,second);
 for(const event of first.filter(event=>event.memoryEvidence)){const edge=document.edges.find(edge=>edge.id===event.edgeId);assert.ok(edge,`${event.id}: ${event.sourceNodeId} → ${event.nodeId}`);assert.equal(edge.source,event.sourceNodeId);assert.equal(edge.target,event.nodeId);assert.equal(event.modelEvent,undefined);assert.equal(event.operations,undefined);assert.equal(event.results,undefined);assert.equal(event.update.attempts,undefined);}
 for(const original of base)assert.deepEqual(first.find(event=>event.id===original.id),original);
});
test('private namespace is denied to child, shared child sees no parent-private or user-private records',()=>{
 const denied=result('child-denied');assert.ok(denied.some(event=>event.memoryEvidence?.outcome==='denied'));assert.equal(denied.some(event=>event.memoryEvidence?.phase==='retrieve'),false);
 const shared=result('child-shared');const selected=shared.find(event=>event.memoryEvidence?.phase==='select'&&event.memoryEvidence.outcome==='selected');assert.deepEqual(selected?.memoryEvidence?.recordIds,['episode']);
});
test('disabled, absent candidates and unavailable are distinguishable recall outcomes',()=>{
 assert.ok(result('disabled').some(event=>event.memoryEvidence?.outcome==='disabled'));
 assert.ok(result('no-matches').some(event=>event.memoryEvidence?.outcome==='no-matches'));
 assert.ok(result('unavailable').some(event=>event.memoryEvidence?.outcome==='unavailable'));
});
test('explicit recall returns to Tools collection rather than Context',()=>{const events=result('explicit-search');const start=events.findIndex(event=>event.sourceNodeId==='lina-tools-dispatch'&&event.nodeId==='lina-memory-scope');const returnEvent=events.slice(start).find(event=>event.sourceNodeId==='lina-memory-select');assert.equal(returnEvent?.nodeId,'lina-tools-collect');});
test('structured explicit writes bypass extraction and preserve user-assertion provenance',()=>{const events=result('remember');assert.equal(events.some(event=>event.nodeId==='lina-memory-extract'),false);assert.equal(last(events).records.remembered.origin,'user-assertion');});
test('automatic source-backed observation is a candidate before validated commit',()=>{const events=result('baseline');const phases=events.filter(event=>event.memoryEvidence).map(event=>event.memoryEvidence!.phase);assert.ok(phases.indexOf('extract')<phases.indexOf('validate'));assert.ok(phases.indexOf('validate')<phases.indexOf('commit'));assert.equal(last(events).records.remembered.origin,'observed-result');});
test('correction preserves historical meaning while excluding superseded record from new recall',()=>{const store=last(result('correction'));assert.equal(store.records.preference.status,'superseded');assert.equal(store.records['preference-current'].supersedes,'preference');assert.equal(store.records.preference.text,'Prefer concise answers');assert.deepEqual(selectMemoryFixture(store,['preference','preference-current'],['user-private']).map(row=>row.id),['preference-current']);});
test('ambiguous contradiction never overwrites committed preference',()=>{const store=last(result('conflict'));assert.equal(store.records.preference.text,'Prefer concise answers');assert.deepEqual(store.transactions,{});});
test('lost acknowledgment inspects original transaction and duplicate write retains revision one',()=>{for(const scenario of ['lost-ack','duplicate-write'] as const){const events=result(scenario);const commit=events.find(event=>event.memoryEvidence?.phase==='commit'&&event.memoryEvidence.operationId)!;const inspect=events.find(event=>event.memoryEvidence?.phase==='inspect'&&event.memoryEvidence.operationId)!;assert.equal(commit.memoryEvidence!.operationId,inspect.memoryEvidence!.operationId);assert.equal(last(events).records.remembered.revision,1);assert.equal(Object.keys(last(events).transactions).length,1);}});
test('transaction mismatch and stale revision preserve authoritative content',()=>{const store=createMemoryFixtureState();const row:MemoryRecord={...store.records.preference,revision:2,text:'Changed'};assert.equal(commitMemoryFixture(store,'change',row,1),'applied');assert.equal(commitMemoryFixture(store,'change',row,1),'already-applied');assert.equal(commitMemoryFixture(store,'change',{...row,text:'Different'},1),'conflict');assert.equal(commitMemoryFixture(store,'stale',{...row,text:'Stale'},1),'conflict');assert.equal(store.records.preference.text,'Changed');});
test('index lag distinguishes authoritative commit from searchable revision',()=>{const store=last(result('index-lag'));assert.equal(store.records.remembered.revision,1);assert.equal(store.index.recordRevisions.remembered,undefined);assert.ok(store.index.pending.includes('remembered'));assert.equal(selectMemoryFixture(store,['remembered'],['workspace-shared']).length,1);});
test('consolidation retains source lineage and does not activate a procedure as instructions',()=>{const store=last(result('consolidate'));assert.deepEqual(store.records.lesson.derivedFrom,['episode']);assert.equal(store.records.lesson.kind,'procedure');assert.equal(store.records.lesson.origin,'derived');assert.equal(store.job?.status,'committed');});
test('forget immediately excludes descendants before physical cleanup and reports replica coverage',()=>{const events=result('forget-pending');const revoked=events.find(event=>event.memoryEvidence?.outcome==='logically-removed')!.memorySnapshot!;assert.deepEqual(selectMemoryFixture(revoked,['preference','lesson'],['user-private','workspace-shared']),[]);assert.equal(revoked.selection,undefined);assert.equal(revoked.job?.status,'cancelled');const store=last(events);assert.equal(store.cleanup?.status,'pending');assert.deepEqual(store.cleanup?.pending,['configured remote replica']);assert.equal(store.records.preference.text,'');assert.equal(store.records.lesson.text,'');assert.equal(store.index.recordRevisions.preference,undefined);});
test('revocation rejects stale cache and pending consolidation cannot recreate source',()=>{const store=createMemoryFixtureState();store.selection={recordIds:['preference'],visibilityGeneration:1,recordRevisions:{preference:1}};store.job={status:'proposed',sourceIds:['preference']};forgetMemoryFixture(store,'preference',true);assert.equal(store.selection,undefined);const derived:MemoryRecord={...store.records.episode,id:'resurrected',derivedFrom:['preference'],origin:'derived'};assert.equal(commitMemoryFixture(store,'resurrect',derived,0),'revoked-source');assert.equal(store.records.resurrected,undefined);const events=result('stale-recall');assert.ok(events.some(event=>event.memoryEvidence?.phase==='select'&&event.memoryEvidence.outcome==='no-matches'));});
test('recalled malicious instruction fails admission without new write',()=>{const events=result('poisoned-source');assert.ok(events.some(event=>event.memoryEvidence?.phase==='validate'&&event.memoryEvidence.outcome==='rejected'));assert.deepEqual(last(events).transactions,{});});
test('cancellation distinguishes unstarted extraction and retained applied write',()=>{assert.deepEqual(last(result('cancel-beforewrite')).transactions,{});assert.ok(last(result('cancel-afterwrite')).records.remembered);const seed=last(result('remember'));const stopped=withMemory([{id:'stop',nodeId:'lina-execution-cancel',update:{}},{id:'settled-stop',nodeId:'lina-execution-settle',update:{outcome:'cancelled'}}],document,'baseline',seed,{stopped:true});assert.deepEqual(last(stopped).records,seed.records);assert.equal(stopped.some(event=>event.memoryEvidence?.phase==='extract'),false);});

test('memory intent stays unpublished until State acknowledgment and auxiliary Model purpose is separate',()=>{
 const events=result('baseline');const intent=events.find(event=>event.memoryEvidence?.outcome==='intent')!;assert.equal(intent.memorySnapshot?.records.remembered,undefined);
 const ack=events.find(event=>event.sourceNodeId==='lina-state-record'&&event.nodeId==='lina-memory-commit'&&event.memoryEvidence?.outcome==='applied')!;assert.equal(ack.memorySnapshot!.records.remembered.revision,1);
 const modelNodes=events.filter(event=>event.memoryEvidence&&event.nodeId.startsWith('lina-model-'));assert.deepEqual(modelNodes.map(event=>event.nodeId),['lina-model-resolve','lina-model-encode','lina-model-invoke','lina-model-normalize']);assert.ok(modelNodes.every(event=>event.memoryEvidence!.reason.includes('memory-extraction')));
});
test('correction records validity periods and original call identity survives the write path',()=>{const events=result('correction'),store=last(events);assert.equal(store.records.preference.validUntil,store.records['preference-current'].validFrom);assert.equal(store.records.preference.revision,2);assert.ok(events.some(event=>event.memoryEvidence?.operationId==='memory-operation:original-call'));assert.equal(store.index.recordRevisions.preference,undefined);});

test('an unverified final assistant answer alone creates no automatic memory',()=>{const events=withMemory([{id:'context-empty',nodeId:'lina-context-load',update:{}},{id:'done-no-evidence',nodeId:'lina-execution-settle',update:{outcome:'completed'}}],document,'baseline');assert.deepEqual(last(events).transactions,{});assert.ok(events.some(event=>event.memoryEvidence?.phase==='capture'&&event.memoryEvidence.outcome==='no-op'));});

test('child shared publication remains a candidate until parent review and only a matched one-time decision commits',()=>{
 const pending=withMemory(base,document,'child-proposal');const wait=pending.find(event=>event.id==='memory:parent-review')!;assert.equal(wait.wait?.kind,'memory-review');assert.equal(wait.memorySnapshot?.records.remembered,undefined);assert.equal(pending.some(event=>event.memoryEvidence?.outcome==='applied'),false);
 const approved=withMemory(base,document,'child-proposal',undefined,{answers:{'memory:parent-review':'allow-once'}});assert.equal(last(approved).records.remembered.namespace,'workspace-shared');assert.deepEqual(last(approved).records.remembered.sources,['child:fixture:source']);assert.equal(approved.find(event=>event.id==='memory:parent-review')?.wait,undefined);
 for(const answer of ['deny','expire','allow-session','allow-always'] as const){const rejected=withMemory(base,document,'child-proposal',undefined,{answers:{'memory:parent-review':answer}});assert.equal(last(rejected).records.remembered,undefined);assert.deepEqual(last(rejected).transactions,{});}
 const wrong=withMemory(base,document,'child-proposal',undefined,{answers:{'wrong-review':'allow-once'}});assert.equal(wrong.find(event=>event.id==='memory:parent-review')?.wait?.kind,'memory-review');
});

function play(state:SimulationState):SimulationState{
 for(let cursor=0;cursor<2500&&!['completed','blocked'].includes(state.status);cursor++){
  if(state.status==='waiting')state=answerSimulation(state,document,state.wait?.kind==='memory-review'||state.wait?.kind==='approval'?'allow-once':state.wait?.kind==='reconciliation'?'known-success':'ready');else state=advanceSimulation(state,document);
 }
 assert.equal(state.status,'completed',state.error);return state;
}
for(const {value} of MEMORY_CASES)test(`${value}: Auto and Next retain the same memory evidence and main execution`,()=>{
 const initial=(automatic:boolean)=>startSimulation('cli',document,automatic,'direct-answer',3,'fits','parallel','openai-chat','answer','policy-allow',[],'fresh',value);
 const manual=play(initial(false)),auto=play(initial(true));assert.deepEqual(manual.memorySnapshot,auto.memorySnapshot);assert.deepEqual(manual.results,auto.results);assert.equal(manual.attempts,auto.attempts);assert.equal(manual.rounds,auto.rounds);
});
