/** Public browser paths shared by navigation and feature links. */
export const appPaths = {
  overview: "/",
  coverage: "/coverage",
  runs: "/runs",
  experiments: "/experiments",
  platforms: "/platforms",
  scenarios: "/scenarios",
  architecture: "/architecture",
  repository: "/repository",
  settings: "/settings",
  docs: "/docs",
  studio: "/studio",
  studioLina: "/studio/lina",
  studioChat: "/studio/chat",
  studioHermes: "/studio/hermes",
  studioComparison: "/studio/comparison",
  studioExplorers: "/studio/explorers",
  studioOpenClaw: "/studio/openclaw",
  studioPi: "/studio/pi",
  studioWaku: "/studio/waku",
  components: "/components",
  platform: (platformId: string) => `/platforms/${platformId}`,
  platformSection: (platformId: string, section: string) => `/platforms/${platformId}/${section}`,
  component: (areaId: string) => `/components/${areaId}`,
} as const;
