import type {
  ComponentAreaDescriptor,
  ComponentCaseDescriptor,
  ComponentStrategyDescriptor,
  ContextEvidenceItem,
} from "./componentTypes";

const proposalDocument = {
  documentId: "docs/planning/component-lab.md",
  label: "Studio components proposal",
} as const;

export const componentAreas: readonly ComponentAreaDescriptor[] = [
  {
    id: "input-perception",
    name: "Input and perception",
    summary: "Normalize raw input and identify the task before planning begins.",
    status: "planned",
    nextAction: "Define canonical input blocks for text, files, images, and API payloads.",
    document: proposalDocument,
  },
  {
    id: "context-management",
    name: "Context management",
    summary: "Inspect which prior messages reach the model under two Context selection policies.",
    status: "implemented",
    nextAction: "Compare the two available Context implementations against the fixed old-fact case.",
    document: proposalDocument,
  },
  {
    id: "planning-reasoning",
    name: "Planning and reasoning",
    summary: "Break a goal into work and inspect how the agent reasons between actions.",
    status: "planned",
    nextAction: "Choose a first planning case that keeps control flow separate.",
    document: proposalDocument,
  },
  {
    id: "memory",
    name: "Memory",
    summary: "Study working, episodic, semantic, and procedural memory as separate concerns.",
    status: "planned",
    nextAction: "Define a memory case with inspectable writes, reads, and provenance.",
    document: proposalDocument,
  },
  {
    id: "tool-use",
    name: "Tool use",
    summary: "Select, validate, dispatch, normalize, and recover from tool calls.",
    status: "planned",
    nextAction: "Start with a read-only tool case before introducing side effects.",
    document: proposalDocument,
  },
  {
    id: "computer-use",
    name: "Computer use",
    summary: "Observe and act on interactive interfaces, then verify and recover from the resulting state.",
    status: "planned",
    nextAction: "Define a deterministic browser fixture and compare observation, action, and verification strategies.",
    document: proposalDocument,
  },
  {
    id: "control-orchestration",
    name: "Control and orchestration",
    summary: "Compare loops, graphs, state machines, delegation, and termination rules.",
    status: "planned",
    nextAction: "Hold planning constant while defining the first loop comparison.",
    document: proposalDocument,
  },
  {
    id: "execution-environment",
    name: "Execution environment",
    summary: "Make isolation, permissions, resource limits, and lifecycle visible.",
    status: "planned",
    nextAction: "Describe one environment fixture with explicit capability limits.",
    document: proposalDocument,
  },
  {
    id: "output-actions",
    name: "Output and actions",
    summary: "Separate response rendering from proposed, verified, and committed actions.",
    status: "planned",
    nextAction: "Define a case that distinguishes proposal from irreversible execution.",
    document: proposalDocument,
  },
  {
    id: "safety-guardrails",
    name: "Safety and guardrails",
    summary: "Inspect filtering, anomaly detection, scope checks, and confirmation gates.",
    status: "planned",
    nextAction: "Add a deterministic adversarial-input case and its observable decision.",
    document: proposalDocument,
  },
  {
    id: "model-interface",
    name: "Model interface",
    summary: "Compare routing, prompt formatting, retry policy, and cost instrumentation.",
    status: "planned",
    nextAction: "Keep the model fixed while defining the first interface variable.",
    document: proposalDocument,
  },
  {
    id: "observability",
    name: "Observability",
    summary: "Capture traces, metrics, artifacts, and diagnostics without secrets or hidden reasoning.",
    status: "planned",
    nextAction: "Define the minimum evidence record for one focused component run.",
    document: proposalDocument,
  },
] as const;

export const contextStrategies: readonly ComponentStrategyDescriptor[] = [
  {
    id: "deterministic-context-assembler",
    name: "Budget-fitted recent history",
    summary: "Consider the ordered prior messages, then retain complete messages that fit the shared context budget.",
    status: "implemented",
    identity: {
      packageName: "@agent-harness-lab/module-context",
      packageVersion: "0.6.0",
      implementation: { id: "deterministic-context-assembler", version: "0.4.0" },
    },
    parameters: [{
      id: "selection-policy",
      label: "Selection policy",
      description: "This implementation applies the shared token budget to recent history.",
      options: ["Budget-fitted recent history"],
      defaultValue: "Budget-fitted recent history",
    }],
    inputs: ["Fixed prior-message fixture", "Current task", "Shared token budget"],
    outputs: ["Exact model messages", "Included and omitted source IDs", "Token estimate and basis"],
    limitations: ["Replay describes the request shape; it does not establish answer quality."],
  },
  {
    id: "fixed-recent-message-window",
    name: "Fixed recent-message window",
    summary: "Keep the newest configured number of prior messages before applying the shared token budget.",
    status: "implemented",
    identity: {
      packageName: "@agent-harness-lab/module-context",
      packageVersion: "0.6.0",
      implementation: { id: "fixed-recent-message-window", version: "0.1.0" },
    },
    parameters: [{
      id: "maxRecentMessages",
      label: "Recent prior messages",
      description: "The run control sets this from 1 to 12 prior messages. The default is four.",
      options: Array.from({ length: 12 }, (_, index) => String(index + 1)),
      defaultValue: "4",
    }],
    inputs: ["Fixed prior-message fixture", "Current task", "Recent-message count", "Shared token budget"],
    outputs: ["Exact model messages", "Included and omitted source IDs with reasons", "Token estimate and basis"],
    limitations: ["An older relevant message can be omitted by the window.", "Replay does not measure answer quality."],
  },
  {
    id: "full-history",
    name: "Full history",
    summary: "Pass the available conversation history into the request until the budget is reached.",
    status: "planned",
    parameters: [{
      id: "overflow",
      label: "Overflow handling",
      description: "What the future adapter should do when the full history no longer fits.",
      options: ["Stop with an explicit error", "Compact before sending", "Drop oldest turns"],
      defaultValue: "Stop with an explicit error",
    }],
    inputs: ["System instructions", "Ordered conversation history", "Tool-result fixture"],
    outputs: ["Retained source IDs", "Budget estimate", "Overflow decision"],
    limitations: ["Context grows with the transcript.", "It does not rank older material by relevance."],
  },
  {
    id: "relevance-ranked",
    name: "Relevance-ranked retention",
    summary: "Rank candidate context by task relevance and retain the highest-scoring material first.",
    status: "planned",
    parameters: [{
      id: "ranking",
      label: "Ranking signal",
      description: "The signal that the future implementation will use to order candidate sources.",
      options: ["Lexical match", "Recency plus lexical match", "Explicit source priority"],
      defaultValue: "Recency plus lexical match",
    }],
    inputs: ["Current task", "Candidate context sources", "Source priority"],
    outputs: ["Ranked source IDs", "Dropped source IDs", "Ranking details", "Budget estimate"],
    limitations: ["A ranking score is not a correctness guarantee.", "The ranking policy can hide unexpected omissions."],
  },
  {
    id: "hierarchical-summary",
    name: "Hierarchical summary",
    summary: "Replace older groups of turns with summaries at more than one level of detail.",
    status: "planned",
    parameters: [{
      id: "levels",
      label: "Summary levels",
      description: "How many summary layers the future implementation may keep available.",
      options: ["One level", "Two levels", "Three levels"],
      defaultValue: "Two levels",
    }],
    inputs: ["Conversation groups", "Summary policy", "Current task"],
    outputs: ["Summary source IDs", "Retained recent turns", "Compaction record", "Budget estimate"],
    limitations: ["Summaries can lose wording and provenance.", "Summary quality must be graded separately from context fit."],
  },
  {
    id: "token-budget-allocation",
    name: "Token-budget allocation",
    summary: "Split a bounded context budget across source groups before selecting their contents.",
    status: "planned",
    parameters: [{
      id: "allocation",
      label: "Allocation profile",
      description: "The future policy for dividing the available budget among context sources.",
      options: ["History-heavy", "Balanced", "Task-heavy"],
      defaultValue: "Balanced",
    }],
    inputs: ["Total token budget", "Source groups", "Reserved output budget"],
    outputs: ["Per-source budgets", "Selected source IDs", "Unfilled or exceeded budget", "Allocation details"],
    limitations: ["A fair allocation can still select the wrong content.", "Budget estimates may be conservative."],
  },
] as const;

export const contextCases: readonly ComponentCaseDescriptor[] = [
  {
    id: "long-conversation",
    name: "Long conversation",
    task: "Answer the current question while retaining the turns that explain the user's ongoing goal.",
    fixtureSummary: "A multi-turn conversation contains recent filler, an early task constraint, and a final question.",
    intendedObservation: "Which source turns survive as the context budget tightens?",
    controls: ["Same conversation fixture", "Same current question", "Same token limit"],
  },
  {
    id: "old-important-fact",
    name: "Old important fact",
    scenarioId: "context-stress",
    fixtureId: "old-important-fact",
    fixtureVersion: "1",
    taskId: "old-important-fact:task:v1",
    task: "Using the prior conversation, identify the preference stated for future meal suggestions.",
    fixtureSummary: "Six synthetic prior messages contain an early meal preference followed by unrelated garden and desk-light details.",
    intendedObservation: "Compare the source messages each policy passes to Replay; this is a selection-boundary observation, not an answer-quality measure.",
    controls: ["Same six prior messages", "Same task and Replay model", "Same empty Memory state", "Same reference assembly and token budget"],
  },
  {
    id: "conflicting-instructions",
    name: "Conflicting instructions",
    task: "Follow the higher-priority instruction when a later source conflicts with it.",
    fixtureSummary: "System, user, and tool-result sources contain deliberately conflicting directions.",
    intendedObservation: "Whether selection preserves source priority and makes omissions inspectable.",
    controls: ["Same source priorities", "Same conflict text", "Same model settings"],
  },
  {
    id: "large-tool-output",
    name: "Large tool output",
    task: "Answer using the relevant part of a large tool result without exceeding the request budget.",
    fixtureSummary: "A tool returns a large structured result with a small relevant region and noisy fields.",
    intendedObservation: "How each strategy treats large tool output and whether it preserves provenance.",
    controls: ["Same tool result", "Same relevant record", "Same output reservation"],
  },
  {
    id: "strict-token-budget",
    name: "Strict token budget",
    task: "Produce a useful answer when the input budget leaves little room for output.",
    fixtureSummary: "The context window is intentionally small and the output reservation is explicit.",
    intendedObservation: "Where each strategy spends the budget and how it reports pressure or failure.",
    controls: ["Same small window", "Same output reservation", "Same task grader"],
  },
] as const;

export const contextEvidenceItems: readonly ContextEvidenceItem[] = [
  {
    label: "Source ledger",
    description: "Included and omitted source IDs, including whether the window or token budget omitted a message.",
  },
  {
    label: "Token count and basis",
    description: "The context token count and the estimator basis reported by the Context module.",
  },
  {
    label: "Implementation used",
    description: "The Context package and implementation identity, configuration, and shared reference assembly.",
  },
  {
    label: "Replay request evidence",
    description: "The exact messages sent to deterministic Replay and its output; this is not an answer-quality grade.",
  },
] as const;
