import type { ConnectionRecord } from "./managementApi";

export type ConnectorAccess = "read" | "read_write";

export interface GuidedConnectorPreset {
  readonly id: string;
  readonly name: string;
  readonly provider: string;
  readonly category: string;
  readonly resource: string;
  readonly issuer: string;
  readonly description: string;
  readonly readOnlyAvailable: boolean;
  readonly readAccessLabel: string;
  readonly writeAccessLabel: string;
  readonly accessNote?: string;
  readonly baseScopes: readonly string[];
  readonly writeScopes: readonly string[];
  readonly documentationUrl: string;
}

/**
 * Services in this catalog have a hosted Streamable HTTP MCP endpoint and
 * OAuth metadata that supports client registration by the Lab. Their actual
 * tool definitions are always discovered from the provider after authorization.
 */
export const guidedConnectorCatalog: readonly GuidedConnectorPreset[] = [
  {
    id: "notion",
    name: "Notion",
    provider: "Notion",
    category: "Notes and documents",
    resource: "https://mcp.notion.com/mcp",
    issuer: "https://mcp.notion.com",
    description: "Search and work with pages and databases in your Notion workspace.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Notion workspace access",
    accessNote: "Notion uses one default OAuth scope for its MCP connection. Review the access request on Notion's consent page. Each write action still needs your review in the Lab.",
    baseScopes: ["default"],
    writeScopes: [],
    documentationUrl: "https://www.notion.com/help/notion-mcp",
  },
  {
    id: "linear",
    name: "Linear",
    provider: "Linear",
    category: "Project management",
    resource: "https://mcp.linear.app/mcp",
    issuer: "https://mcp.linear.app",
    description: "Connect your workspace to find and update issues, projects, and comments.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Read and write access",
    accessNote: "The hosted endpoint asks for both read and write scopes. Linear documents read-only options, but the Lab currently follows this endpoint's request. Each write action still needs your review.",
    baseScopes: ["read", "write"],
    writeScopes: [],
    documentationUrl: "https://linear.app/docs/mcp",
  },
  {
    id: "atlassian-rovo",
    name: "Atlassian Rovo",
    provider: "Atlassian",
    category: "Jira and Confluence",
    resource: "https://mcp.atlassian.com/v2/mcp",
    issuer: "https://auth.atlassian.com/VCeDsk8ZHncYF1g234fKtc4lNipbBhu3",
    description: "Search Jira and Confluence, with optional permission to create and edit content.",
    readOnlyAvailable: true,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Read and make changes",
    baseScopes: [
      "read:me",
      "read:account",
      "offline_access",
      "read:jira:agent-interface",
      "search:jira:agent-interface",
      "read:confluence:agent-interface",
      "search:confluence:agent-interface",
      "search:rovo:agent-interface",
      "search:code:agent-interface",
    ],
    writeScopes: ["write:jira:agent-interface", "write:confluence:agent-interface"],
    documentationUrl: "https://developer.atlassian.com/cloud/rovo-mcp/guides/getting-started/",
  },
  {
    id: "monday",
    name: "monday.com",
    provider: "monday.com",
    category: "Project management",
    resource: "https://mcp.monday.com/mcp",
    issuer: "https://auth.monday.com/mcp",
    description: "Find and update boards, items, and work in your monday.com account.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "monday.com account access",
    accessNote: "The provider does not publish separate scopes for this MCP grant. Your account permissions determine access, and a workspace admin may need to approve this connector and its callback address.",
    baseScopes: [],
    writeScopes: [],
    documentationUrl: "https://developer.monday.com/api-reference/docs/mcp-dynamic-client-registration",
  },
  {
    id: "miro",
    name: "Miro",
    provider: "Miro",
    category: "Whiteboards and collaboration",
    resource: "https://mcp.miro.com/",
    issuer: "https://mcp.miro.com/",
    description: "Search and work with boards in a Miro team you choose.",
    readOnlyAvailable: true,
    readAccessLabel: "Read board content",
    writeAccessLabel: "Read and change boards",
    accessNote: "Miro asks you to select a team during sign-in. Enterprise administrators may need to enable MCP first. Each write action still needs your review in the Lab.",
    baseScopes: ["boards:read", "openid", "email"],
    writeScopes: ["boards:write"],
    documentationUrl: "https://developers.miro.com/docs/miro-mcp",
  },
  {
    id: "intercom",
    name: "Intercom",
    provider: "Intercom",
    category: "Customer support",
    resource: "https://mcp.intercom.com/mcp",
    issuer: "https://mcp.intercom.com",
    description: "Search and manage customer-support conversations and records.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Intercom MCP access",
    accessNote: "The general Intercom MCP currently supports US-hosted workspaces. The provider requests its `mcp` and `operator` scopes; select only the tools you need and review write actions in the Lab.",
    baseScopes: ["mcp", "operator"],
    writeScopes: [],
    documentationUrl: "https://developers.intercom.com/docs/guides/mcp",
  },
  {
    id: "posthog",
    name: "PostHog",
    provider: "PostHog",
    category: "Product analytics",
    resource: "https://mcp.posthog.com/mcp",
    issuer: "https://oauth.posthog.com",
    description: "Explore product analytics, dashboards, feature flags, and errors.",
    readOnlyAvailable: true,
    readAccessLabel: "Read analytics and settings",
    writeAccessLabel: "Read and update PostHog",
    accessNote: "PostHog MCP is hosted and routes you to your account region. Some tools use PostHog AI and may incur separate AI spend. Each write action still needs your review in the Lab.",
    baseScopes: ["organization:read", "project:read", "query:read", "dashboard:read", "insight:read", "feature_flag:read", "error_tracking:read"],
    writeScopes: ["dashboard:write", "insight:write", "feature_flag:write", "error_tracking:write"],
    documentationUrl: "https://posthog.com/docs/model-context-protocol",
  },
  {
    id: "new-relic-us",
    name: "New Relic (US)",
    provider: "New Relic",
    category: "Monitoring and observability",
    resource: "https://mcp.newrelic.com/mcp/",
    issuer: "https://oauth2.service.newrelic.com",
    description: "Investigate telemetry and observability data in a US-region account.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Read-only observability access",
    accessNote: "This catalog entry targets New Relic's US region and requests read-only observability access. EU and Japan accounts use different MCP endpoints and are not listed yet.",
    baseScopes: ["observability:read", "offline", "offline_access"],
    writeScopes: [],
    documentationUrl: "https://docs.newrelic.com/docs/agentic-ai/mcp/setup/",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    provider: "Cloudflare",
    category: "Cloud infrastructure",
    resource: "https://mcp.cloudflare.com/mcp",
    issuer: "https://mcp.cloudflare.com",
    description: "Work with Cloudflare accounts, DNS, Workers, R2, and security services.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Cloudflare account access",
    accessNote: "Choose the permissions to grant on Cloudflare's OAuth page. Start with read access and grant broader permissions only when your task needs them. Review write actions in the Lab.",
    baseScopes: ["user:read", "account:read"],
    writeScopes: [],
    documentationUrl: "https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/",
  },
  {
    id: "cloudflare-observability",
    name: "Cloudflare Observability",
    provider: "Cloudflare",
    category: "Monitoring and observability",
    resource: "https://observability.mcp.cloudflare.com/mcp",
    issuer: "https://observability.mcp.cloudflare.com",
    description: "Investigate logs and analytics for your Cloudflare applications.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Cloudflare observability access",
    accessNote: "This is a focused Cloudflare connection for observability data. Your OAuth grant and Cloudflare account permissions control what it can see; review any write tools before enabling them.",
    baseScopes: [],
    writeScopes: [],
    documentationUrl: "https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/",
  },
  {
    id: "railway",
    name: "Railway",
    provider: "Railway",
    category: "Cloud infrastructure",
    resource: "https://mcp.railway.com",
    issuer: "https://backboard.railway.com",
    description: "Inspect and operate services, projects, and deployments on Railway.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Railway workspace access",
    accessNote: "Railway requires the `workspace:member` scope. The connection follows your Railway workspace permissions; select tools carefully and review write actions in the Lab.",
    baseScopes: ["workspace:member"],
    writeScopes: [],
    documentationUrl: "https://docs.railway.com/ai/mcp-server",
  },
  {
    id: "supabase",
    name: "Supabase",
    provider: "Supabase",
    category: "Databases and backend",
    resource: "https://mcp.supabase.com/mcp",
    issuer: "https://api.supabase.com",
    description: "Connect to Supabase projects and work with their database and backend tools.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Supabase project access",
    accessNote: "Supabase asks you to choose projects and permissions during sign-in. The MCP server can expose database and project-changing tools, so enable only what you need and review write actions in the Lab.",
    baseScopes: [],
    writeScopes: [],
    documentationUrl: "https://supabase.com/docs/guides/ai-tools/mcp",
  },
  {
    id: "gitlab",
    name: "GitLab",
    provider: "GitLab",
    category: "Code and project management",
    resource: "https://gitlab.com/api/v4/mcp",
    issuer: "https://gitlab.com",
    description: "Use GitLab project and repository tools with your GitLab account.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "GitLab MCP access",
    accessNote: "GitLab.com MCP is currently beta. An administrator can disable automatic OAuth app registration; when that happens, this guided connection will not work until a client is configured.",
    baseScopes: ["mcp"],
    writeScopes: [],
    documentationUrl: "https://docs.gitlab.com/user/model_context_protocol/mcp_server/",
  },
  {
    id: "stripe",
    name: "Stripe",
    provider: "Stripe",
    category: "Payments",
    resource: "https://mcp.stripe.com",
    issuer: "https://access.stripe.com/mcp",
    description: "Explore Stripe account data and payment workflows through Stripe's MCP tools.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "Stripe account access",
    accessNote: "Stripe uses one MCP OAuth scope, so permissions are chosen on Stripe's authorization page. Review that request carefully and keep write tools set to review in the Lab.",
    baseScopes: ["mcp"],
    writeScopes: [],
    documentationUrl: "https://docs.stripe.com/mcp",
  },
  {
    id: "wordpress-com",
    name: "WordPress.com",
    provider: "WordPress.com",
    category: "Web publishing",
    resource: "https://public-api.wordpress.com/wpcom/v2/mcp/v1",
    issuer: "https://public-api.wordpress.com",
    description: "Search and manage sites, posts, comments, and media in WordPress.com.",
    readOnlyAvailable: false,
    readAccessLabel: "Read-only",
    writeAccessLabel: "WordPress.com content access",
    accessNote: "Some WordPress.com plans are required. Its MCP permissions use the same content scopes for reading and writing, so enable only the tools you need and review every content change in the Lab.",
    baseScopes: ["auth", "sites", "posts", "comments", "media"],
    writeScopes: [],
    documentationUrl: "https://developer.wordpress.com/docs/mcp/",
  },
];

export function scopesForConnector(preset: GuidedConnectorPreset, access: ConnectorAccess): string[] {
  return [...new Set([...preset.baseScopes, ...(access === "read_write" ? preset.writeScopes : [])])];
}

export function connectionForConnector(
  preset: GuidedConnectorPreset,
  access: ConnectorAccess,
  ref: string,
  displayName: string,
  origin: string,
): ConnectionRecord {
  return {
    ref,
    displayName,
    provider: preset.provider,
    owner: "local-workspace",
    resource: preset.resource,
    scopes: scopesForConnector(preset, access),
    enabled: true,
    auth: {
      kind: "oauth",
      clientId: "auto",
      redirectUri: `${origin}/api/management/connections/${ref}/callback`,
      issuer: preset.issuer,
      discovery: { kind: "mcp", allowedIssuers: [preset.issuer] },
    },
  };
}
