import { canReviewAction, toolOutcomeView } from "./connectedToolState";
import { StableReviewFocus } from "./StableReviewFocus";
import type { InvocationDecision, InvocationReviewView, RunView } from "./platformApi";

/** A server-owned exact-call card. Text generated by the assistant cannot create this control. */
export function InvocationReviewPanel({ run, action, busy, uncertain, now, evidenceUrl, onSubmit }: {
  readonly run: RunView; readonly action: InvocationReviewView; readonly busy: boolean;
  readonly uncertain?: InvocationDecision; readonly now: number; readonly evidenceUrl: string;
  readonly onSubmit: (choice?: InvocationDecision["decision"], renewal?: boolean) => void;
}) {
  const terminal = ["completed", "failed", "cancelled", "reconciliation_required"].includes(run.status);
  const expired = action.status === "expired" || action.status === "pending" && !canReviewAction(action, now);
  const outcome = run.events.findLast(event => event.payload.toolCallId === action.call.toolCallId && ["ToolExecutionCompleted", "ToolExecutionUnknown", "ToolExecutionFailed", "ToolExecutionCancelled", "ToolPolicyDenied"].includes(event.kind));
  const effect = outcome?.payload.effect;
  const outcomeView = outcome ? toolOutcomeView(outcome.payload, outcome.kind) : null;
  const specificUnknown = outcomeView?.uncertain ?? false;
  const knownEffectLabel = effect && typeof effect === "object" && "state" in effect && effect.state !== "unknown" ? outcomeView?.label : null;
  const conclusive = !specificUnknown && (outcome !== undefined || ["completed", "denied", "cancelled"].includes(action.status));
  const dispatchObserved = action.status === "dispatching" || run.events.some(event => event.payload.toolCallId === action.call.toolCallId && event.kind === "ToolExecutionStarted");
  // Another call can put the run into reconciliation. Retain this call's own known result.
  const unknown = specificUnknown || run.status === "reconciliation_required" && !conclusive && dispatchObserved;
  const stopped = terminal && !conclusive || outcome?.kind === "ToolExecutionFailed" || outcome?.kind === "ToolExecutionCancelled";
  const label = action.status === "denied" && !specificUnknown ? "Denied" : knownEffectLabel ?? (unknown ? "Outcome unknown"
    : outcome?.kind === "ToolExecutionCompleted" ? "Completed"
    : action.status === "denied" || outcome?.kind === "ToolPolicyDenied" ? "Denied"
    : stopped || action.status === "cancelled" ? "Stopped"
    : action.status === "completed" ? "Finished · inspect evidence"
    : action.delivery?.status === "pending" ? "Decision saved · waiting to resume"
    : action.delivery?.status === "stopped" ? "Delivery stopped"
    : action.status === "approved" && run.status === "suspended" ? "Approved · waiting to resume"
    : action.status === "dispatching" ? "Running"
    : expired ? "Review expired" : action.status.replaceAll("_", " "));
  return <StableReviewFocus className="invocation-review" aria-label={`Action review: ${action.call.name}`}>
    <header><strong>{action.presentation?.displayName ?? action.call.name}</strong><span role="status">{label}</span></header>
    {action.presentation && <p>{action.presentation.description}</p>}
    {outcomeView?.presentation && <small>Response: {outcomeView.presentation}</small>}
    <small>Exact action{action.presentation ? ` · ${action.presentation.risk} action` : ""}</small>
    <dl className="invocation-arguments">{Object.entries(action.displayArguments).map(([name, value]) => <div key={name}><dt>{action.presentation?.argumentLabels[name] ?? name}</dt><dd>{boundedArgument(value)}</dd></div>)}</dl>
    {action.delivery?.status === "pending" && !terminal && <p>The decision is saved. The server is retrying delivery of this same reviewed action.</p>}
    {action.delivery?.status === "stopped" && <p>Delivery stopped. Inspect the recorded run state before continuing.</p>}
    {action.status === "denied" && <p>This action was denied. Approval did not authorize dispatch.</p>}
    {stopped && !unknown && <p>The run stopped. This does not establish whether a dispatched action changed provider state. Inspect the recorded evidence before repeating it.</p>}
    {unknown && <p>Inspect provider state and the recorded receipt before repeating this action. Cancellation does not roll back a dispatched call.</p>}
    <details className="chat-activity"><summary>Details</summary>
      <small>Revision {action.revision} · call {action.call.toolCallId}</small>
      {action.presentation && <small>Source {action.presentation.source.id} · version {action.presentation.source.version}</small>}
      <a href={evidenceUrl} target="_blank" rel="noreferrer">Inspect action evidence</a>
    </details>
    {!terminal && !unknown && <>
      {(action.decision && ["approved", "denied"].includes(action.status) && run.status === "suspended" || uncertain) && <button type="button" className="quiet-button" disabled={busy} onClick={() => onSubmit()}>{uncertain ? "Retry retained decision" : "Continue reviewed action"}</button>}
      {expired && <button type="button" className="quiet-button" disabled={busy} onClick={() => onSubmit(undefined, true)}>Request fresh review</button>}
      {action.status === "pending" && !expired && !uncertain && <div className="invocation-review-actions">
        <small>Review expires {new Date(action.expiresAt).toLocaleTimeString()}</small>
        <button type="button" className="quiet-button" disabled={busy} onClick={() => onSubmit("denied")}>Deny</button>
        <button type="button" className="button button-primary" disabled={busy} onClick={() => onSubmit("approved")}>{busy ? "Submitting…" : "Approve action"}</button>
      </div>}
    </>}
  </StableReviewFocus>;
}
export function boundedArgument(value: unknown): string {
  const text = typeof value === "string" ? value : JSON.stringify(value, null, 2) ?? "null";
  return text.length > 4000 ? `${text.slice(0, 4000)}\n… truncated` : text;
}
