import type { PlatformDescriptor } from "./platformTypes";

const noComputerEnvironment: readonly string[] = [];

export const platformCatalog: readonly PlatformDescriptor[] = [
  {
    id: "computer-native",
    name: "Computer Native",
    role: "External computer-native agent harness",
    description: "An independently developed computer-native harness studied through the Lab integration boundary.",
    kind: "computer-native",
    language: "TypeScript",
    runtime: "Independent local or remote runner",
    executionModel: "Computer-native model and tool loop",
    durabilityModel: "Owned by the external harness",
    status: "planned",
    computerEnvironmentIds: ["local-workspace", "sandboxed-container", "remote-vm"],
    backendProfiles: [],
    infrastructure: [],
    implementationDocumentId: "integrations/computer-native/README.md",
    variants: [{ id: "baseline", name: "Computer Native baseline", description: "The external harness's first Lab-compatible release.", status: "planned" }],
  },
  {
    id: "temporal",
    name: "Temporal",
    role: "Durable workflow execution",
    description: "An agent runtime hosted in workflows and activities with durable history and recovery.",
    kind: "backend",
    language: "TypeScript",
    runtime: "Node.js worker + Temporal",
    executionModel: "Workflow-coordinated agent loop",
    durabilityModel: "Workflow history, retries, timers, and signals",
    status: "planned",
    computerEnvironmentIds: noComputerEnvironment,
    backendProfiles: [{ id: "local-temporal-stack", name: "Local Temporal stack", description: "A Lab server, Temporal server, database, and worker for local development.", status: "planned" }],
    infrastructure: [
      { id: "temporal-server", name: "Temporal server", description: "Stores workflow history and coordinates tasks, timers, signals, and retries.", requirement: "required", status: "planned" },
      { id: "temporal-worker", name: "Temporal worker", description: "Runs the workflow and activity code for the selected agent variant.", requirement: "required", status: "planned" },
    ],
    implementationDocumentId: "platforms/temporal/README.md",
    variants: [{ id: "baseline", name: "Temporal baseline", description: "A single workflow-hosted agent with explicit activity boundaries.", status: "planned" }],
  },
  {
    id: "restate",
    name: "Restate",
    role: "Durable application runtime",
    description: "A service-oriented agent runtime using durable handlers, state, and communication.",
    kind: "backend",
    language: "TypeScript",
    runtime: "Node.js service + Restate",
    executionModel: "Durable service handler loop",
    durabilityModel: "Durable invocations, state, and messages",
    status: "planned",
    computerEnvironmentIds: noComputerEnvironment,
    backendProfiles: [{ id: "local-restate-stack", name: "Local Restate stack", description: "A Lab server, Restate runtime, and agent service for local development.", status: "planned" }],
    infrastructure: [{ id: "restate-server", name: "Restate runtime", description: "Coordinates durable invocations, state, and communication for the service.", requirement: "required", status: "planned" }],
    implementationDocumentId: "platforms/restate/README.md",
    variants: [{ id: "baseline", name: "Restate baseline", description: "A single agent exposed through durable service handlers.", status: "planned" }],
  },
  {
    id: "langgraph",
    name: "LangGraph",
    role: "Graph and state-machine orchestration",
    description: "An explicit graph of nodes, transitions, and state for long-running agent work.",
    kind: "backend",
    language: "Python",
    runtime: "Python application service",
    executionModel: "Graph-driven state transitions",
    durabilityModel: "Graph checkpointing and application-managed persistence",
    status: "planned",
    computerEnvironmentIds: noComputerEnvironment,
    backendProfiles: [{ id: "local-langgraph-service", name: "Local LangGraph service", description: "A Lab server and LangGraph application service for local development.", status: "planned" }],
    infrastructure: [],
    implementationDocumentId: "platforms/langgraph/README.md",
    variants: [{ id: "baseline", name: "LangGraph baseline", description: "A single-agent graph whose state and transitions remain inspectable.", status: "planned" }],
  },
  {
    id: "openai-agents",
    name: "OpenAI Agents SDK",
    role: "Lightweight agent SDK",
    description: "Code-first agent primitives for model interaction, tools, handoffs, and sessions.",
    kind: "backend",
    language: "TypeScript",
    runtime: "Node.js application service",
    executionModel: "SDK-managed agent loop",
    durabilityModel: "SDK sessions plus application-managed persistence",
    status: "planned",
    computerEnvironmentIds: noComputerEnvironment,
    backendProfiles: [{ id: "local-sdk-service", name: "Local SDK service", description: "A Lab server and Node.js agent service for local development.", status: "planned" }],
    infrastructure: [],
    implementationDocumentId: "platforms/openai-agents/README.md",
    variants: [{ id: "baseline", name: "OpenAI Agents SDK baseline", description: "A single SDK agent connected to Lab contracts at its outer seams.", status: "planned" }],
  },
  {
    id: "mastra",
    name: "Mastra",
    role: "TypeScript agent platform",
    description: "A TypeScript-native platform for agents, workflows, tools, and supporting services.",
    kind: "backend",
    language: "TypeScript",
    runtime: "Node.js application service",
    executionModel: "Platform-managed agent and workflow primitives",
    durabilityModel: "Platform and application persistence choices",
    status: "planned",
    computerEnvironmentIds: noComputerEnvironment,
    backendProfiles: [{ id: "local-mastra-service", name: "Local Mastra service", description: "A Lab server and Mastra application service for local development.", status: "planned" }],
    infrastructure: [],
    implementationDocumentId: "platforms/mastra/README.md",
    variants: [{ id: "baseline", name: "Mastra baseline", description: "A single Mastra agent with platform-native details retained in evidence.", status: "planned" }],
  },
  {
    id: "vercel-ai-sdk",
    name: "Vercel AI SDK",
    role: "TypeScript model and tool primitives",
    description: "A TypeScript-native foundation for model streaming, structured output, and tool loops.",
    kind: "backend",
    language: "TypeScript",
    runtime: "Node.js application service",
    executionModel: "Application-owned tool loop using SDK primitives",
    durabilityModel: "Application-managed state and recovery",
    status: "planned",
    computerEnvironmentIds: noComputerEnvironment,
    backendProfiles: [{ id: "local-vercel-ai-service", name: "Local Vercel AI SDK service", description: "A Lab server and Node.js application service for local development.", status: "planned" }],
    infrastructure: [{ id: "vercel-services", name: "Vercel services", description: "Optional hosted services. The variant must record whether they participate in a run.", requirement: "optional", status: "planned" }],
    implementationDocumentId: "platforms/vercel-ai-sdk/README.md",
    variants: [{ id: "baseline", name: "Vercel AI SDK baseline", description: "A code-first tool loop built from Vercel AI SDK primitives.", status: "planned" }],
  },
];

export function getPlatform(platformId: string | undefined): PlatformDescriptor | undefined {
  return platformCatalog.find((platform) => platform.id === platformId);
}
