import type { LinaDocument, LinaNode } from './linaModel';

const research = 'Audit: docs/research/lina/revisit-context.md.\nResearch: docs/research/lina/context-research.md.\nPinned source studies: context-hermes-openclaw.md and context-pi-waku.md in the same directory.\nThese nodes are Lina design responsibilities; playback uses synthetic fixtures, not a context runtime or measured provider usage.';

function node(id: string, title: string, x: number, y: number, purpose: string, inputs: string, outputs: string, decisions: string, references: string, experiments: string): LinaNode {
  return { id: `lina-context-${id}`, title, area: 'Context', status: 'proposed', x, y, purpose, inputs, outputs, decisions, references: `${references}\n\n${research}`, experiments };
}

/** Proposed per-round context projection. Canonical execution records remain unchanged. */
export const linaContextBlock: LinaDocument = {
  version: 1,
  nodes: [
    node('scope', 'Bind context scope', 80, 4480,
      '- Bind the coordinator-approved workspace, requester, account, history branch and source scope before reads.',
      '- Correlated preparation and declared parent/child inheritance policy.',
      '- Scope-bound preparation or denied scope to settlement.',
      '- Context consumes permission decisions; it cannot grant access. Child history is isolated unless selected records are explicitly allowed. Memory and Model paths are design fixtures; live runtimes remain unimplemented.',
      'Cross-block revisit: explicit source access and child isolation.',
      '- Compare explicit selected inheritance policies with identical tasks and tools.'),
    node('load', 'Load context sources', 460, 4480,
      '- Resolve permitted, versioned instructions, history, task references and tool catalog for this agent and logical round.',
      '- Preparation identity, source references, policies and model capabilities. A child would supply its own history and task packet.',
      '- Staged source manifest joined by preparation identity; acquisition requests, pending sources, bounded reprepare, optional omissions or required-source failure.',
      '- Unloaded references stay references. A missing required source cannot silently become empty successful context. Loading does not grant access or change turn ownership.',
      'Hermes session/prompt snapshots; OpenClaw context-engine assembly; Pi active-branch resource loading; Waku session context.',
      '- Compare turn-start snapshots, per-round refresh and explicit invalidation; measure stale evidence and source reads.'),
    node('instructions', 'Build instructions', 840, 4480,
      '- Order harness, agent and applicable project instruction sections with their origins and versions.',
      '- Source bundle and declared instruction precedence policy.',
      '- Ordered instruction sections with origin, package/contribution digest, activation ID, host trust and declared precedence; inventory metadata excludes unactivated bodies.',
      '- Retrieved content and tool results remain evidence, not higher-priority instructions. Required instruction failures terminate through source loading.',
      'Hermes instruction tiers; OpenClaw bootstrap/system prompt; Pi resource loader; Waku per-turn system prompt.',
      '- Compare permitted instruction/evidence ordering while keeping instruction content and precedence fixed.'),
    node('history', 'Select conversation history', 1220, 4480,
      '- Project the active conversation branch into complete message and tool-call/result groups.',
      '- Canonical history, prior summaries, current input and recorded round outcomes.',
      '- Scoped active-branch complete groups, unresolved work references and included/excluded identities; duplicate or foreign-agent results are rejected.',
      '- Never delete canonical evidence. Preserve matching assistant tool calls and results; recent history selection must not create orphan tool results.',
      'Pi branch projection; OpenClaw history limiting; Waku completed-exchange window; Hermes request-selection seam.',
      '- Compare full history, recent complete groups, and selected older evidence plus recent groups.'),
    node('task', 'Add task context', 1600, 4480,
      '- Insert selected task evidence with permitted source references and explicit omission information.',
      '- Attachments, task-local notes, permitted retrieval results and future child task packet.',
      '- Typed scoped evidence including selected connector resources/prompts, memory and skill resources, attachment MIME/digests and child artifacts; supplied prompt roles stay intact.',
      '- Memory owns retrieval and durable writes; this node selects permitted results. Attachment bytes need not all be loaded eagerly.',
      'Hermes explicit references; Waku memory/skill selection; Pi file and skill resources.',
      '- Compare eager loading, pre-retrieval, on-demand loading and hybrid acquisition under the same task.'),
    node('tools', 'Prepare tool context', 1980, 4480,
      '- Select the permitted catalog while preserving exact executable revision, schema and account binding identity.',
      '- Versioned allowed tools and selected recorded tool groups with artifact references.',
      '- Permission-neutral model catalog with exact tool IDs, schemas, digests and binding references; observations are shaped separately.',
      '- Use the same versioned tool definitions and permitted catalog that Tools resolves at dispatch; context selection cannot invent executable tools. No tool execution or permission grants. Masked/truncated observations retain original artifact references and identity. Parallel batch results remain paired by call ID regardless of completion order.',
      'Hermes result shaping/spill; OpenClaw result pruning; Pi and Waku live tool feedback.',
      '- Compare raw observations, head/tail truncation and masking; compare full versus curated permitted catalogs.'),
    node('observations', 'Shape observations', 2360, 4480,
      '- Project rich canonical tool and child outcomes into model-visible content independently of tool definitions.',
      '- Candidate, complete correlated groups, original artifacts and coordinator model-content capabilities.',
      '- Shaped observations to budget; declared projection hook request; classified invalid observations.',
      '- Preserve terminal status, uncertainty, call IDs, structured-output and raw artifact references. Required unsettled effects cannot authorize continuation. Invoke each declared hook once per candidate generation; every return is budgeted and validated.',
      'Tools rich outcomes and cross-block revisit projection boundary.',
      '- Compare inline, referenced and masked observations while keeping canonical results fixed.'),
    node('budget', 'Check context budget', 2740, 4480,
      '- Estimate the entire candidate request against input capacity and output reservation.',
      '- Instructions, messages, tool schemas, multimodal references, provider overhead and bounded reduction history.',
      '- Complete request estimate including skill inventory/bodies, prompt roles, rich media and hook additions; separate acquisition/summary work accounting; bounded reduction decisions.',
      '- Estimates record tokenizer/provider version and uncertainty. Bound reduction attempts and require progress; no unlimited compact/check loop. Context work never resets logical-round counters.',
      'Hermes pressure checks; Pi compaction threshold; OpenClaw budget and compaction preflight.',
      '- Compare source quotas versus priority allocation; record overflow and retained constraints. Simulation estimates are not measured tokens.'),
    node('prune', 'Prune context', 2740, 4720,
      '- Apply deterministic selection, truncation or masking to the model-visible projection.',
      '- Candidate, selected reduction policy and protected groups.',
      '- Revised projection preserving complete groups, uncertainty, raw artifacts and child references; no-progress consumes a bounded attempt.',
      '- Preserve canonical records and protected current task/tool relationships. Pruning does not produce a summary or memory write.',
      'OpenClaw tool-result pruning; Waku bounded history; observation-masking research.',
      '- Compare observation masking, bounded histories and truncation with artifact recovery.'),
    node('compact', 'Compact history', 1980, 4960,
      '- Replace eligible older groups in this request with a derived summary and source provenance.',
      '- Candidate, older groups, retained recent groups, prior summary and compaction policy.',
      '- Scope-specific request-local summary naming exact branch/revision and unresolved work; stale/failed/cancelled summary preserves prior valid snapshot.',
      '- Initial summaries are scripted fixtures and request-local. Failure/cancellation cannot overwrite the last valid view. Real summary calls would have separate usage, cost and cancellation records, not another main reasoning round.',
      'Hermes guarded summaries; Pi compaction with retained boundaries; OpenClaw compaction. No general compactor found in pinned Waku loop.',
      '- Compare no summary, summary plus recent groups, and masking before summary; count summarizer overhead.'),
    node('validate', 'Validate model context', 3120, 4480,
      '- Check structural validity, required content and linked call/result groups before publication.',
      '- Candidate context, provenance and Model Interface encoding constraints.',
      '- Non-mutating checks of source scope, generations, instruction precedence, exact catalog schemas/bindings, correlated groups, media capabilities and declared hook mutations.',
      '- Validation is non-mutating. A future content repair must return through budget checking. Provider encoding stays in Model Interface.',
      'Pi message conversion; Hermes sanitization; OpenClaw history validation/repair boundaries.',
      '- Compare explicit validation policies without inventing missing canonical tool calls.'),
    node('publish', 'Publish context snapshot', 3500, 4480,
      '- Publish an immutable, inspectable context snapshot for this agent, turn, round and projection revision.',
      '- Valid candidate, source revisions, selection manifest, reduction history and budget estimate.',
      '- Snapshot with source/catalog/policy/skill/plugin/model generation vector and contribution digests; stale candidate returns for bounded reprepare without model launch.',
      '- Snapshot content and provenance stay inspectable; publication is not proof of a database write. Readiness cannot grant authority or launch a different round. Retry may reuse its snapshot; overflow recovery creates a revised projection.',
      'Lina boundary derived from source agents separating canonical records, derived views and model requests.',
      '- Compare refresh policies and stable prefixes; provider cache behavior belongs to Model Interface and real-run measurements.'),
  ],
  edges: [
    { id: 'lina-context-edge-prepare-scope', source: 'lina-execution-prepare', target: 'lina-context-scope', label: 'context.prepare' },
    { id: 'lina-context-edge-scope-load', source: 'lina-context-scope', target: 'lina-context-load', label: 'context.scope-bound' },
    { id: 'lina-context-edge-scope-terminal', source: 'lina-context-scope', target: 'lina-execution-settle', label: 'context.scope-denied' },
    { id: 'lina-context-edge-load-instructions', source: 'lina-context-load', target: 'lina-context-instructions', label: 'permitted source bundle' },
    { id: 'lina-context-edge-instructions-history', source: 'lina-context-instructions', target: 'lina-context-history', label: 'ordered instructions' },
    { id: 'lina-context-edge-history-task', source: 'lina-context-history', target: 'lina-context-task', label: 'selected complete history groups' },
    { id: 'lina-context-edge-task-tools', source: 'lina-context-task', target: 'lina-context-tools', label: 'selected task evidence' },
    { id: 'lina-context-edge-tools-observations', source: 'lina-context-tools', target: 'lina-context-observations', label: 'context.tools-prepared' },
    { id: 'lina-context-edge-observations-budget', source: 'lina-context-observations', target: 'lina-context-budget', label: 'context.observations-shaped' },
    { id: 'lina-context-edge-observations-terminal', source: 'lina-context-observations', target: 'lina-execution-settle', label: 'context.observation-invalid' },
    { id: 'lina-context-edge-observations-hooks', source: 'lina-context-observations', target: 'lina-tools-hooks', label: 'context.projection-hook-requested' },
    { id: 'lina-context-edge-load-reprepare', source: 'lina-context-load', target: 'lina-execution-prepare', label: 'context.reprepare-required' },
    { id: 'lina-context-edge-publish-reprepare', source: 'lina-context-publish', target: 'lina-execution-prepare', label: 'context.reprepare-required' },
    { id: 'lina-tools-edge-context-resource-request', source: 'lina-context-load', target: 'lina-tools-resource-read', label: 'context.resource-requested' },
    { id: 'lina-tools-edge-context-prompt-request', source: 'lina-context-load', target: 'lina-tools-prompt-get', label: 'context.prompt-requested' },
    { id: 'lina-context-edge-budget-validate', source: 'lina-context-budget', target: 'lina-context-validate', label: 'fits estimated context budget' },
    { id: 'lina-context-edge-budget-prune', source: 'lina-context-budget', target: 'lina-context-prune', label: 'pruning permitted; attempt remains' },
    { id: 'lina-context-edge-prune-budget', source: 'lina-context-prune', target: 'lina-context-budget', label: 'revised projection / no-progress record' },
    { id: 'lina-context-edge-budget-compact', source: 'lina-context-budget', target: 'lina-context-compact', label: 'summary permitted; attempt remains' },
    { id: 'lina-context-edge-compact-budget', source: 'lina-context-compact', target: 'lina-context-budget', label: 'validated fixture summary; recheck budget' },
    { id: 'lina-context-edge-budget-terminal', source: 'lina-context-budget', target: 'lina-execution-settle', label: 'protected content too large / reduction exhausted' },
    { id: 'lina-context-edge-compact-terminal', source: 'lina-context-compact', target: 'lina-execution-settle', label: 'summary unavailable; no allowed fallback' },
    { id: 'lina-context-edge-validate-terminal', source: 'lina-context-validate', target: 'lina-execution-settle', label: 'invalid model context' },
    { id: 'lina-context-edge-load-terminal', source: 'lina-context-load', target: 'lina-execution-settle', label: 'required source unavailable / denied' },
    { id: 'lina-context-edge-validate-publish', source: 'lina-context-validate', target: 'lina-context-publish', label: 'structurally valid projection' },
    { id: 'lina-context-edge-publish-prepare', source: 'lina-context-publish', target: 'lina-execution-prepare', label: 'ready snapshot; recheck launch authority' },
  ],
};
