import type { LinaDocument, LinaNode } from './linaModel';
import type { StateRequestRoute } from './stateBlock';

/** State receipts resume the exact owner phase; they cannot independently launch work. */
const storage = (short: string, owner: string, kind: StateRequestRoute['kind'], phase: string): StateRequestRoute => ({ id: `lina-environment-edge-${short}-state-${kind}`, source: `lina-environment-${owner}`, target: `lina-state-${kind}`, kind, phase, returnId: `lina-environment-edge-state-${kind}-${short}`, returnTarget: `lina-environment-${owner}` });
export const ENVIRONMENT_STATE_ROUTES: readonly StateRequestRoute[] = [
  storage('workspace', 'workspace', 'load', 'read-exact-workspace-binding'),
  storage('acquire', 'acquire', 'record', 'record-acquisition-intent-and-lease'),
  storage('acquire-inspect', 'acquire', 'load', 'inspect-original-acquisition'),
  storage('stage', 'stage', 'record', 'record-input-transfer-custody'),
  storage('start', 'start', 'record', 'record-command-launch-intent'),
  storage('files', 'files', 'record', 'record-filesystem-intent-and-observation'),
  storage('process', 'process', 'record', 'record-process-control-and-observation'),
  storage('collect', 'collect', 'record', 'record-correlated-execution-evidence'),
  storage('artifacts', 'artifacts', 'record', 'record-retained-artifact-custody'),
  storage('reconcile', 'reconcile', 'load', 'inspect-original-environment-operation'),
  storage('release', 'release', 'record', 'record-lease-and-cleanup-outcome'),
] ;
const references = 'docs/research/lina/environment-research.md; environment-hermes-openclaw.md; environment-backends-and-patterns.md; environment-existing-design-audit.md. Branches are architectural simulation, not actual process execution or measured sandbox guarantees.';
const node = (id: string, title: string, x: number, y: number, purpose: string, inputs: string, outputs: string, decisions: string, experiments: string): LinaNode => ({ id: `lina-environment-${id}`, title, area: 'Execution Environment', status: 'proposed', x, y, purpose, inputs, outputs, decisions, references, experiments });
const edge = (id: string, source: string, target: string, label: string) => ({ id: `lina-environment-edge-${id}`, source: source.startsWith('lina-') ? source : `lina-environment-${source}`, target: target.startsWith('lina-') ? target : `lina-environment-${target}`, label });
export const linaEnvironmentBlock: LinaDocument = {
  version: 1,
  nodes: [
    node("profile", "Resolve environment profile", 7400, 600, "Resolve trusted placement independently from whole-harness deployment.", "Run/agent preferences, requested capabilities, private profile references and access ceilings.", "Versioned local/sandbox/remote profile, effective restrictions, bypass or unavailable.", "Local uses the selected host workspace and claims no hard sandbox. External APIs and MCP retain declared placement. A required sandbox never falls back to host.", "Local versus remote placement under equal task and dependency controls."),
    node("workspace", "Bind workspace", 7820, 600, "Bind canonical workspace identity, access mappings and sharing ownership.", "Profile, selected project, parent binding, child assignment and allowed root references.", "Workspace generation, copy/bind/remote mappings and shared/private access agreement, or conflict.", "Sharing a profile is not sharing writable files or process control. Writable mounts change their backing project. Never treat user-owned directories as disposable.", "Shared versus private worktrees or copied child workspaces."),
    node("acquire", "Acquire environment", 8240, 600, "Attach or create a scoped backend with original acquisition identity.", "Profile/workspace revisions, original operation fingerprint and lease owner.", "Attached/created/reused handle and lease, known failure or unknown provisioning.", "Persist intent before creation. Repeated acquisition inspects the original instance. Created and borrowed resources have distinct cleanup authority.", "Warm reuse versus ephemeral allocation and startup overhead."),
    node("ready", "Verify environment readiness", 8660, 600, "Observe runtime capabilities and readiness for the exact binding generation.", "Backend handle, image/template, required dependencies, requested limits and authority generation.", "Readiness receipt with actual supported/enforced capabilities, or missing/stale/unsupported result.", "Readiness grants no action authority. Requested limits may be advisory or unsupported; local cwd is not confinement. Setup is separately admitted, never arbitrary silent installation.", "Image/preparation strategies at fixed dependency versions."),
    node("stage", "Stage workspace inputs", 7400, 880, "Import admitted input references into the bound workspace while preserving custody.", "Attachment/artifact custody, destination/access scope, transfer identity and size/digest limits.", "Verified imported reference or existing shared binding; conflict/failure/unknown transfer.", "Validate destination and original custody. Unknown transfer inspects the same operation. Input custody remains valid independently of temporary workspace lifetime.", "Copy versus mount inputs and staging overhead."),
    node("files", "Execute filesystem operation", 7820, 880, "Execute admitted read/list/search/write/edit on the actual bound filesystem.", "Exact operation, backend path mapping, workspace generation, access and authorization binding.", "Read/search/patch receipt with provenance, rejected/unsupported/unknown effect.", "Commands and file tools follow one declared binding. Container-only bridge limitations fail explicitly, never read hidden host files. Canonical root/symlink checks remain operation-specific.", "Bridge strategies and conflict handling under unchanged access rules."),
    node("start", "Start command", 8240, 880, "Record launch intent and admit one exact command attempt into its environment.", "Operation/call/attempt, command/cwd/private environment references, owner, deadline and launch permit.", "Correlated process handle, terminal prelaunch failure or unknown launch.", "Generation or authority changes require fresh admission. Lost acknowledgement never starts a replacement command blindly. Yield is not an independent background lifetime.", "Foreground versus independent service scheduling and launch cost."),
    node("process", "Manage process session", 8660, 880, "Observe and control the exact process instance under its recorded owner.", "Handle/generation and admitted status/log/stdin/signal request with output cursor.", "Running/terminal observation, bounded output/input/control receipt, unsupported or uncertain stop.", "PID alone is not identity. Invocation yield, process timeout, lease expiry and retention expiry differ. Clearing output records does not stop a process; Stop targets owned process trees.", "Output collection and session interaction strategies."),
    node("collect", "Collect execution evidence", 8660, 1160, "Join correlated file/process/transfer observations into original requester evidence.", "Exact operation/attempt, partial output, exit/signal/deadline facts, provenance and effect certainty.", "Bounded observation/terminal receipt, retained raw references and explicit unresolved outcome.", "Process exit, effect certainty, artifact custody and task acceptance are separate. Preserve successful siblings and truncation metadata. Return to Tools or Context by recorded requester.", "Output retention/projection strategies under equal evidence requirements."),
    node("artifacts", "Publish workspace artifacts", 8240, 1160, "Retain selected outputs outside disposable environments before cleanup.", "Selected files, source environment/generation, export identity, access/retention policy and digest.", "Retained artifact reference and custody receipt; pending/failed/unknown export.", "A pathname alone is not durable custody. Publication does not deliver a user message. Export must obey access policy and preserve source provenance.", "Artifact retention and bounded transfer approaches."),
    node("reconcile", "Reconcile environment work", 7820, 1160, "Inspect original provisioning, launch, transfer or termination before recovery decisions.", "Original operation identities, saved observations, owner generation and backend inspection capabilities.", "Known running/terminal/unstarted/removed, incompatible/unavailable or still unknown.", "Filesystem survival does not establish process survival or output recovery. Reattach only proven identity; known unstarted retry needs fresh owner admission. Unknown does not mean safe to replay.", "Reconnect/snapshot strategies within declared provider capabilities."),
    node("release", "Release environment", 7400, 1160, "Release leases or retain/retire resources under their lifecycle owner.", "Exact lease/generation, outstanding operations, shared consumers and required artifact custody.", "Released/retained/removed/already-released, deferred or cleanup uncertain.", "Release is not destruction. Preserve borrowed projects, detached supervisor work and sibling leases. Destruction requires managed ownership and accounted exports; failed cleanup remains inspectable.", "Retention/cleanup profiles and orphan reconciliation."),
  ],
  edges: [
    ...ENVIRONMENT_STATE_ROUTES.flatMap(route => [{ id: route.id, source: route.source, target: route.target, label: route.phase }, { id: route.returnId, source: route.target, target: route.returnTarget, label: `${route.phase}; same operation and requester` }]),
    edge('start-profile', 'lina-execution-start', 'profile', "optional workspace binding before first demand"),
    edge('tools-profile', 'lina-tools-resolve', 'profile', "resolve declared workspace placement"),
    edge('profile-tools', 'profile', 'lina-tools-resolve', "same capability requester; external/local-independent bypass"),
    edge('profile-workspace', 'profile', 'workspace', "workspace-backed capability"),
    edge('profile-collect', 'profile', 'collect', "required profile refused or unavailable"),
    edge('workspace-acquire', 'workspace', 'acquire', "bound access and sharing identity"),
    edge('workspace-collect', 'workspace', 'collect', "invalid or conflicting binding"),
    edge('acquire-ready', 'acquire', 'ready', "known attached or created handle"),
    edge('acquire-reconcile', 'acquire', 'reconcile', "unknown original provisioning"),
    edge('acquire-collect', 'acquire', 'collect', "known backend/image unavailable"),
    edge('ready-stage', 'ready', 'stage', "admitted workspace input references"),
    edge('ready-files', 'ready', 'files', "same admitted filesystem request"),
    edge('ready-start', 'ready', 'start', "same admitted command request"),
    edge('ready-process', 'ready', 'process', "same admitted process control"),
    edge('ready-prepare', 'ready', 'lina-execution-prepare', "original preparation requester readiness receipt"),
    edge('ready-context', 'ready', 'lina-context-load', "original context source requester readiness receipt"),
    edge('ready-subagents', 'ready', 'lina-subagents-prepare', "same child assignment environment receipt"),
    edge('ready-collect', 'ready', 'collect', "missing dependency/resource or stale capability"),
    edge('ready-workspace', 'ready', 'workspace', "changed binding requires rebinding"),
    edge('stage-ready', 'stage', 'ready', "verified input handles; resume original requester"),
    edge('stage-collect', 'stage', 'collect', "input transfer evidence"),
    edge('stage-reconcile', 'stage', 'reconcile', "uncertain original import"),
    edge('files-collect', 'files', 'collect', "correlated read/write/search evidence"),
    edge('files-reconcile', 'files', 'reconcile', "unknown filesystem effect"),
    edge('start-process', 'start', 'process', "known original process handle"),
    edge('start-collect', 'start', 'collect', "known terminal or prelaunch failure"),
    edge('start-reconcile', 'start', 'reconcile', "lost original launch acknowledgement"),
    edge('process-process', 'process', 'process', "same owned process; subsequent log/input/status observation"),
    edge('process-collect', 'process', 'collect', "terminal or bounded process observation"),
    edge('process-reconcile', 'process', 'reconcile', "uncertain termination or lost handle"),
    edge('collect-settle', 'collect', 'lina-execution-settle', 'original preparation failed; no model or tool launch'),
    edge('collect-tools', 'collect', 'lina-tools-collect', "same tool call/attempt result; one settlement"),
    edge('collect-context', 'collect', 'lina-context-load', "same workspace source requester with provenance"),
    edge('collect-stage', 'collect', 'stage', "same transfer requester receipt"),
    edge('collect-artifacts', 'collect', 'artifacts', "selected outputs require retained custody"),
    edge('collect-reconcile', 'collect', 'reconcile', "unresolved effect remains owned"),
    edge('artifacts-collect', 'artifacts', 'collect', "retained export receipt; same publication requester"),
    edge('artifacts-release', 'artifacts', 'release', "required export custody acknowledged"),
    edge('artifacts-reconcile', 'artifacts', 'reconcile', "original export acknowledgement uncertain"),
    edge('reconcile-process', 'reconcile', 'process', "proven original live process reconnect"),
    edge('reconcile-ready', 'reconcile', 'ready', "proven same environment generation usable"),
    edge('reconcile-collect', 'reconcile', 'collect', "terminal/unstarted/unsupported observations; no automatic replay"),
    edge('reconcile-release', 'reconcile', 'release', "proven cleanup eligibility"),
    edge('reconcile-wait', 'reconcile', 'lina-execution-wait', "original observation unresolved; retained owner"),
    edge('wait-reconcile', 'lina-execution-wait', 'reconcile', "matched original operation evidence"),
    edge('release-reconcile', 'release', 'reconcile', "unknown cleanup acknowledgement"),
    edge('release-artifacts', 'release', 'artifacts', "required retained custody absent"),
    edge('release-wait', 'release', 'lina-execution-wait', "active shared consumer or unresolved owner"),
    edge('release-execution', 'release', 'lina-execution-release', "same lease released/retained; original turn release"),
    edge('release-subagents', 'release', 'lina-subagents-coordinate', "same child owner lease receipt"),
    edge('tools-files', 'lina-tools-dispatch', 'files', "admitted exact workspace file call"),
    edge('tools-start', 'lina-tools-dispatch', 'start', "admitted exact command attempt"),
    edge('tools-process', 'lina-tools-dispatch', 'process', "admitted exact process interaction"),
    edge('context-workspace', 'lina-context-load', 'workspace', "permitted workspace source request"),
    edge('context-files', 'lina-context-load', 'files', "same admitted bound workspace source read"),
    edge('input-stage', 'lina-input-custody', 'stage', "admitted attachment custody reference"),
    edge('stage-input', 'stage', 'lina-input-custody', "same input custody requester receipt"),
    edge('subagents-workspace', 'lina-subagents-prepare', 'workspace', "shared/private child workspace assignment"),
    edge('subagents-acquire', 'lina-subagents-prepare', 'acquire', "child-owned environment lease request"),
    edge('workspace-subagents', 'workspace', 'lina-subagents-prepare', "same child workspace binding; no permission expansion"),
    edge('subagents-cancel-process', 'lina-subagents-cancel', 'process', "exact child-owned process termination request"),
    edge('subagents-reconcile', 'lina-subagents-reconcile', 'reconcile', "original child environment observations"),
    edge('reconcile-subagents', 'reconcile', 'lina-subagents-reconcile', "same child recovery owner receipt"),
    edge('safety-profile', 'profile', 'lina-safety-policy', "trusted environment access ceiling"),
    edge('policy-profile', 'lina-safety-policy', 'profile', "same policy requester; placement grants no authority"),
    edge('ready-safety', 'ready', 'lina-safety-evaluate', "setup/mount/network mutation requires admission"),
    edge('authorize-ready', 'lina-safety-authorize', 'ready', "same admitted setup request; readiness recheck"),
    edge('start-authorize', 'start', 'lina-safety-authorize', "final binding generation and launch recheck"),
    edge('authorize-start', 'lina-safety-authorize', 'start', "exact launch permit; no fresh operation"),
    edge('files-authorize', 'files', 'lina-safety-authorize', "final root and mutation binding recheck"),
    edge('authorize-files', 'lina-safety-authorize', 'files', "same admitted filesystem operation"),
    edge('cancel-process', 'lina-execution-cancel', 'process', "stop exact request-owned process tree"),
    edge('cancel-release', 'lina-execution-cancel', 'release', "cancelled before launch; release only owned lease"),
    edge('recovery-reconcile', 'lina-state-recover', 'reconcile', "restored exact handles/generations; inspect before use"),
    edge('settle-release', 'lina-execution-settle', 'release', "account owned environment obligations before release"),
    edge('reconcile-owner', 'lina-input-reconcile', 'reconcile', "original workspace effect inspection"),
    edge('owner-reconcile', 'reconcile', 'lina-input-reconcile', "same lifecycle owner certainty receipt"),
    edge('collect-planning', 'collect', 'lina-planning-review', "correlated task evidence; no implied task success"),
  ],
};
export const ENVIRONMENT_EDGES = linaEnvironmentBlock.edges;
