import type { LinaDocument, LinaNode } from './linaModel';

const research = 'Completeness audit: docs/research/lina/turn-execution-completeness-audit.md.\nComparative study: docs/research/lina/turn-execution-research.md.\nPinned studies: Hermes ddc0e659; OpenClaw e40ed06f; Pi a276dabe; Waku 24b4cbb6.\nThese are responsibility mappings, not one shared runtime contract.';

function node(id: string, title: string, x: number, y: number, purpose: string, inputs: string, outputs: string, decisions: string, references: string, experiments: string): LinaNode {
  return { id: `lina-execution-${id}`, title, area: 'Turn Execution', status: 'proposed', x, y, purpose, inputs, outputs, decisions, references: `${references}\n\n${research}`, experiments };
}

/** Proposed lifecycle design. Scripted traversal does not implement a Lina runtime. */
export const linaExecutionBlock: LinaDocument = {
  version: 1,
  nodes: [
    node('start', 'Start turn', 80, 3260,
      '- Consume admitted work and initialize working state and execution limits.',
      '- Existing conversation/turn identity, ownership authority and ordered admitted inputs.\n- Original content, attachment references and reply destination.',
      '- One initialized turn for the first model round.',
      '- Proposed: admission grants ownership; this node consumes it without allocating a second turn.\n- Open: limits, initial state and ownership protocol. Checkpoint resumes bypass Start turn and retain the recorded turn, round and fenced authority. Checkpoint safety and recovery claims remain open.',
      'Hermes agent/turn_facade.py and agent/turn_context.py; OpenClaw logical entry/session admission; Pi AgentSession.prompt; Waku respond().',
      '- Later: initialization and budget policies under the same admitted request.'),
    node('limits', 'Check execution limits', 460, 3260,
      '- Check the logical model-round budget before opening another round.\n- Keep provider-attempt retry limits separate from round limits.\n- Check stop intent and current ownership authority before continuation.',
      '- Turn identity, launched logical rounds, configured round limit and current execution authority.\n- Continuation intent after tool outcomes or an explicit model continuation.',
      '- Permission to prepare the next logical round, or an exhausted terminal reason.',
      '- Proposed: each new model round consumes the round budget; retrying a failed provider attempt remains within its original logical round.\n- Proposed: exhaustion prevents a new model round and settles with an explicit exhausted outcome.\n- Attempt retries remain bounded by Recover. Preparation and Model still recheck stop/launch permission.\n- The configured budget is a scripted simulation policy, not a runtime safety guarantee.',
      'Hermes conversation_loop.py iteration budget and inner API retries; OpenClaw assistant cycles versus retry-budget.ts attempt accounting; Pi agent-loop rounds and AgentSession retry; Waku run_loop iteration limit.',
      '- Later: model-round, provider-attempt, time and cost budget policies.'),
    node('prepare', 'Prepare round', 840, 3260,
      '- Request the Context block when no valid snapshot exists for this round/revision, including recorded results and accepted guidance.\n- Recheck stop intent and current ownership authority before another request.\n- Route pending controls or preparation failure before launching the model.',
      '- Turn state, admitted inputs, previous tool results and current continuation decision.',
      '- Context preparation request, or a model request using the returned/reused snapshot and round identity.\n- Classified preparation failure or pending controls.',
      '- Proposed: a round belongs to the existing turn. Context pressure can request refresh/recovery; fatal preparation errors settle the turn.\n- Context and Memory own assembly and retrieval mechanisms; this node coordinates their handoff.\n- Proposed: recheck launch permission after preparation; stop or exhaustion cannot launch another model request.\n- Context playback prepares a synthetic snapshot, then returns here for the launch check. A provider retry reuses the valid snapshot. Checks are design contracts, not an implemented runtime governor.',
      'Hermes prepare_iteration/assemble_messages; OpenClaw embedded run attempt preparation; Pi agent-loop context conversion; Waku session context construction before run_loop.',
      '- Later: context strategies and when to refresh context between rounds.'),
    node('model', 'Call model', 1220, 3260,
      '- Delegate an invocation intent to Model Interface after Context is accepted.\n- Forward cancellation for the exact active Invoke attempt; no provider request is launched here.',
      '- Prepared snapshot, logical-round identity, immutable model binding/capability/budget revisions and invocation intent; exact-attempt cancellation.',
      '- Invocation requested to Resolve model binding, or abort signal to Invoke. Model Normalize returns terminal evidence directly to Decide next action.',
      '- Invoke increments physical attempts at dispatch, counting a logical round only on its first dispatch. Metadata/encoding/readiness waits consume no attempts.\n- Normalize interprets terminal response evidence; Recover decides bounded retry. No direct provider-outcome bypass remains.\n- Model Interface scripts wire profiles and outcomes; viewing pace is not provider latency.',
      'Hermes _run_api_retry_loop; OpenClaw embedded run attempts; Pi streamAssistantResponse; Waku waku/loop/agent.py run_loop provider call.',
      '- Later: streaming, model selection and provider retry policies.'),
    node('decide', 'Decide next action', 1600, 3260,
      '- Consume Model Interface normalized complete, incomplete, malformed, failed, aborted or unknown outcomes.\n- Choose tools, a candidate answer, explicit client continuation, failure recovery or settlement.',
      '- Model response/failure, execution limits and current turn state.',
      '- Tool work, a candidate answer, recovery request or terminal reason.',
      '- Proposed: a text response is a candidate completion; controls and settlement still follow.\n- Cases script responses, tool outcomes and bounded recovery.\n- Proposed: no-tool responses can explicitly continue. Never execute incomplete or invalid tool arguments from truncated responses.\n- Open: exact continuation gates, response repair and exhaustion policy.',
      'Hermes turn_final_response.py continuation gates; OpenClaw logical result evaluation; Pi agent-loop stop/tool branches; Waku run_loop reply/tool branches.',
      '- Later: termination gates, continuation criteria and execution budgets.'),
    node('tools', 'Delegate tool batch', 1600, 3500,
      '- Hand requested calls to Tools for validation, permission checks and dispatch.\n- Recheck stop/budget permission before each new launch and record call intent before effects according to the selected persistence contract.\n- Require Tools to run independent calls concurrently within configured limits and serialize dependent or conflicting operations.\n- Collect outcomes paired to call IDs before the next round; uncertain effects go to reconciliation.',
      '- Tool calls, execution authority, turn identity and cancellation state.',
      '- Per-call success, failure, denial, skipped or cancelled results paired to requests.\n- Uncertain effects for reconciliation; partial updates do not count as settled results.\n- Pending wait status retains call/prompt identity until the owning work resolves it.',
      '- Proposed: Tools owns validation, approvals, scheduling and actual operations.\n- Proposed: known tool failures can be model-visible results; fatal controller failures end the turn. Unstarted calls get explicit skipped outcomes.\n- Proposed: await started work and apply an explicit result-order policy before continuation. Never blindly retry an uncertain external effect.\n- Scripted batches have known success, correctable error or fatal failure. This node is a handoff, not the detailed Tools implementation.\n- Proposed: a pending approval/external wait retains its owning operation; matched answers resolve that work, and denial/expiry produce explicit outcomes.\n- Required design baseline: bounded parallel execution for independent calls, ordered execution for dependencies/conflicts, and a join before the next model round.\n- Detailed design delegates to the Tools block and returns through its publication node. Playback follows the detailed Tools nodes with overlapping independent calls, ordered conflicts, retained waits and uncertain-effect reconciliation. These are deterministic fixtures, not real adapter execution.',
      'Hermes turn_tool_round.py/tool_executor.py ordered segments; OpenClaw tool execution; Pi executeToolCalls parallel/sequential modes; Waku run_loop with sequential ToolRegistry execution.',
      '- Required: schema validation, permission checks, call/result identity, cancellation accounting and safe effect handling.\n- Experiments: concurrency limits, scheduling among eligible calls and result representation. Sequential-only execution is a comparison mode; ordered dependent operations are required correctness. Incremental result consumption would change the round/join contract and needs a separate design.'),
    node('tool-outcomes', 'Handle tool outcomes', 1600, 3740,
      '- Classify known results paired to their tool calls before deciding whether execution can continue.\n- Expose correctable tool errors to the model without silently retrying the tool.\n- Send fatal or nonretryable outcomes to failed settlement.',
      '- Settled per-call outcomes and error classification, retained tool call/result identities and execution authority.',
      '- Success or correctable-error results for the next model round.\n- A terminal failure reason when continuation is unavailable.',
      '- Proposed: known, correctable tool errors can become model-visible results; the model decides the next action.\n- Proposed: fatal or nonretryable tool outcomes settle failed. This classification does not authorize automatic effect replay.\n- Uncertain effects bypass this known-outcome path and retain the existing reconciliation handoff.\n- Initial fixtures contain a successful batch, a correctable error followed by a successful replacement call and answer, or a fatal tool failure.',
      'Hermes tool_executor.py result commitment and turn_tool_round.py failure gates; OpenClaw tool result settlement/termination; Pi executeToolCalls error results; Waku ToolRegistry exception-to-result handling.',
      '- Later: error taxonomy, model-visible failure detail and terminal tool policies.'),
    node('controls', 'Apply pending controls', 840, 3740,
      '- Consume pending guidance or stop intent while preserving the intended next action at a defined checkpoint.\n- Route matched waiting answers to their owning work without starting another turn.',
      '- Round outcomes, next-action intent and controls targeting this exact active turn.\n- Matched answers for deferred waiting work.',
      '- Continue with updated state or proceed to settlement.\n- Answer/control acknowledgement to the owning coordinator where relevant.',
      '- Proposed: checkpoint consumption and active-work cancellation are distinct; cancellation can be signalled before this checkpoint.\n- Waiting answers route to Await external work, separate from guidance checkpoints and fresh admission.\n- Detailed playback can retain waits and signal cancellation; concrete runtime persistence and provider behavior remain unimplemented.',
      'Hermes steer/redirect/interrupt_control.py; OpenClaw steering and abort boundaries; Pi getSteeringMessages/getFollowUpMessages and AgentSession settlement.',
      '- Later: steering boundaries, stop settlement and waiting/resumption policies.'),
    node('recover', 'Recover', 1980, 3500,
      '- Classify provider failure or preparation/context pressure for bounded recovery within the current turn.',
      '- Observed provider/preparation failure, retained results, attempt history and remaining retry budget.',
      '- Safe retry or Context refresh through preparation, or a terminal failure reason.',
      '- Proposed: in-turn attempt recovery preserves turn identity and the logical model round; another provider attempt does not open a new round.\n- Proposed: bound and classify retries; preserve settled tool results instead of replaying the original task. Re-enter preparation gates before another model launch.\n- Initial simulation allows one provider retry before success and never repeats tool work.\n- Restart intake recovery remains separate; uncertain effects retain authority in Turn Execution reconciliation.',
      'Hermes _run_api_retry_loop/apply_retry_restarts; OpenClaw candidate retry/fallback; Pi AgentSession retry/compaction; Waku has no equivalent general recovery lifecycle.',
      '- Later: bounded retries, context-overflow recovery and fallback policies.'),
    node('settle', 'Settle turn', 460, 3980,
      '- Record why execution ended and join/reconcile required outstanding work.\n- Withhold release-ready status while required work or uncertain effects remain unresolved.\n- Make produced output available to the existing delivery boundary.',
      '- Candidate answer or failure/cancellation reason, recorded tool outcomes and outstanding work.',
      '- Settled execution outcome and output record.\n- Release-ready authority state, subject to the future settlement contract; unresolved work retains or transfers fenced ownership to reconciliation.',
      '- Proposed: answer production, settlement and delivery are distinct boundaries.\n- Proposed: terminal reasons include completed, failed, cancelled and exhausted. A failed required write or cleanup must be classified before release.\n- Initial successful cases have no outstanding uncertain work.\n- Open: persistence, cleanup failures, child-work joins and uncertain-outcome reconciliation. A delivery handoff does not prove user receipt.',
      'Hermes turn_finalizer.py then facade cleanup; OpenClaw terminal settlement; Pi agent_end versus agent_settled; Waku completed exchange before gateway delivery.',
      '- Later: terminal gates, required-work joins and evidence persistence policies.'),
    node('release', 'Release turn', 80, 3980,
      '- Release execution ownership and emit its lifecycle event to the conversation service.',
      '- Settled turn identity, outcome and ownership authority.',
      '- Owner-release information for Conversation queue admission.\n- Terminal boundary for this scripted simulation.',
      '- Proposed: the existing queue rechecks admission after release; this node does not itself run queued work.\n- Initial playback ends here.\n- Open: safe release under cancellation, failed persistence, lease loss or uncertain work.',
      'Hermes facade lease release; OpenClaw lane/logical completion; Pi session settlement/idle; Waku gateway worker serialization.',
      '- Later: release rules and queue progression after different terminal outcomes.'),
    node('wait', 'Await external work', 2740, 3500,
      '- Retain exact turn, batch/call or model preparation/intent/attempt identity while external work needs readiness or local settlement.',
      '- Correlated wait registration, matched answer evidence, verified connection readiness or expiry.\n- Settled sibling results remain retained.',
      '- Resume the exact owner after it revalidates the continuation, or retain/reject the wait.\n- Stop/Interrupt reaches cancellation without another turn.',
      '- Wait registration is a side notification, never a second authorization workflow.\n- Model provider readiness uses its own audience and tagged continuation through the shared protected credential owner. It never becomes MCP authorization or an arbitrary chat token.\n- Pending local model work blocks release until locally accounted; remote billing may remain unknown. Expiry is operation-specific.',
      'Cross-block revisit: docs/research/lina/revisit-input-execution.md.', ''),
    node('cancel', 'Cancel active work', 2740, 3740,
      '- Latch exact-turn cancellation, prevent fresh launches and signal active operation owners.',
      '- Stop/Interrupt, fenced authority, active attempt/call IDs, pending waits and settled results.',
      '- Provider/adapter cancellation signals; known settlement or uncertain-effect reconciliation.',
      '- Before Model dispatch, invalidate Resolve/Encode intents and retained readiness tokens without consuming an attempt.\n- During streaming, signal the exact Invoke attempt and retain local ownership until accounted. Late output stays diagnostic.\n- A cancellation request does not prove remote compute/billing stopped or an effect was undone. Preserve settled siblings.',
      'Cross-block revisit: docs/research/lina/revisit-input-execution.md.', ''),
    {
    "id": "lina-input-reconcile",
    "title": "Execution reconciliation",
    "area": "Turn Execution",
    "status": "proposed",
    "x": 3120,
    "y": 3740,
    "purpose": "- Inspect uncertain execution and side effects before further work.",
    "inputs": "- Execution records, unknown outcomes, and available operator decisions.",
    "outputs": "- Known safe follow-up/resume or recorded status requesting a decision.",
    "decisions": "- Agreed: uncertain tools must not be blindly repeated.\n- Proposed: runtime owns execution reconciliation beyond the input boundary; unresolved work retains or transfers fenced ownership instead of emitting a clean release.\n- Open: evidence, decision authority, checkpoints, and owner release.\n- Reconciled batches return to Tools publication preserving all calls and settled siblings; checkpoint restart is separate.",
    "references": "- Lina agreement: docs/research/lina/input-design.md, recovery.\n- Exact reconciliation mechanism remains open.",
    "experiments": ""
},
  ],
  edges: [
    { id: 'lina-execution-edge-wait-auth-request', source: 'lina-execution-wait', target: 'lina-tools-auth', label: 'registered wait → authorization request' },
    { id: 'lina-execution-edge-handoff', source: 'lina-input-runtime', target: 'lina-execution-start', label: 'admitted turn; initialize' },
    { id: 'lina-execution-edge-start-limits', source: 'lina-execution-start', target: 'lina-execution-limits', label: 'request first round' },
    { id: 'lina-execution-edge-limits-prepare', source: 'lina-execution-limits', target: 'lina-execution-prepare', label: 'new round permitted' },
    { id: 'lina-execution-edge-limits-terminal', source: 'lina-execution-limits', target: 'lina-execution-settle', label: 'round limit exhausted' },
    { id: 'lina-execution-edge-prepare-model', source: 'lina-execution-prepare', target: 'lina-execution-model', label: 'prepared request; launch permitted' },
    { id: 'lina-execution-edge-decide-tools', source: 'lina-execution-decide', target: 'lina-execution-tools', label: 'tool requests; admission checks required' },
    { id: 'lina-execution-edge-outcomes-controls', source: 'lina-execution-tool-outcomes', target: 'lina-execution-controls', label: 'success / correctable error; inform model' },
    { id: 'lina-execution-edge-outcomes-terminal', source: 'lina-execution-tool-outcomes', target: 'lina-execution-settle', label: 'fatal / nonretryable tool failure' },
    { id: 'lina-execution-edge-controls-continue', source: 'lina-execution-controls', target: 'lina-execution-limits', label: 'continue; check next-round limit' },
    { id: 'lina-execution-edge-decide-answer', source: 'lina-execution-decide', target: 'lina-execution-controls', label: 'answer' },
    { id: 'lina-execution-edge-controls-finish', source: 'lina-execution-controls', target: 'lina-execution-settle', label: 'candidate completion' },
    { id: 'lina-execution-edge-decide-recover', source: 'lina-execution-decide', target: 'lina-execution-recover', label: 'recoverable failure' },
    { id: 'lina-execution-edge-recover-prepare', source: 'lina-execution-recover', target: 'lina-execution-prepare', label: 'retry; same turn' },
    { id: 'lina-execution-edge-decide-terminal', source: 'lina-execution-decide', target: 'lina-execution-settle', label: 'terminal failure / exhausted' },
    { id: 'lina-execution-edge-recover-terminal', source: 'lina-execution-recover', target: 'lina-execution-settle', label: 'retry unavailable / exhausted' },
    { id: 'lina-execution-edge-settle-release', source: 'lina-execution-settle', target: 'lina-execution-release', label: 'release-ready; required work resolved' },
    { id: 'lina-execution-edge-turn-control', source: 'lina-input-control', target: 'lina-execution-cancel', label: 'Stop / Interrupt active work' },
    { id: 'lina-execution-edge-prompt-answer', source: 'lina-input-prompt', target: 'lina-execution-wait', label: 'matched answer → retained wait' },
    { id: 'lina-execution-edge-output', source: 'lina-execution-settle', target: 'lina-input-delivery', label: 'external/main-turn output only; child outcome routes to coordination' },
    { id: 'lina-execution-edge-decide-continue', source: 'lina-execution-decide', target: 'lina-execution-controls', label: 'explicit continuation; no tools' },
    { id: 'lina-execution-edge-prepare-controls', source: 'lina-execution-prepare', target: 'lina-execution-controls', label: 'pending guidance / stop before launch' },
    { id: 'lina-execution-edge-prepare-recover', source: 'lina-execution-prepare', target: 'lina-execution-recover', label: 'context pressure; refresh before retry' },
    { id: 'lina-execution-edge-prepare-terminal', source: 'lina-execution-prepare', target: 'lina-execution-settle', label: 'preparation failed / budget exhausted' },
    { id: 'lina-execution-edge-tools-terminal', source: 'lina-execution-tools', target: 'lina-execution-settle', label: 'fatal execution failure / stopped batch' },
    { id: 'lina-execution-edge-tools-uncertain', source: 'lina-execution-tools', target: 'lina-input-reconcile', label: 'uncertain effect; reconcile under retained authority' },
    { id: 'lina-execution-edge-settle-unresolved', source: 'lina-execution-settle', target: 'lina-input-reconcile', label: 'unresolved work; release withheld' },
    { id: 'lina-execution-edge-owner-release', source: 'lina-execution-release', target: 'lina-input-queue', label: 'main conversation owner released; child release routes to coordination' },
    { id: 'lina-execution-edge-resume-prepare', source: 'lina-input-runtime', target: 'lina-execution-prepare', label: 'safe checkpoint resume: prepare; same turn' },
    { id: 'lina-execution-edge-resume-controls', source: 'lina-input-runtime', target: 'lina-execution-controls', label: 'safe checkpoint resume: controls; same turn' },
    { id: 'lina-execution-edge-resume-settle', source: 'lina-input-runtime', target: 'lina-execution-settle', label: 'safe checkpoint resume: settle; same turn' },
    { id: 'lina-execution-edge-turn-steer', source: 'lina-input-control', target: 'lina-execution-controls', label: 'exact-turn guidance' },
    { id: 'lina-execution-edge-controls-cancel', source: 'lina-execution-controls', target: 'lina-execution-cancel', label: 'checkpoint Stop / Interrupt' },
    { id: 'lina-execution-edge-resume-wait', source: 'lina-input-runtime', target: 'lina-execution-wait', label: 'restore retained wait' },
    { id: 'lina-execution-edge-wait-approval', source: 'lina-execution-wait', target: 'lina-tools-permissions', label: 'matched approval; owner revalidates' },
    { id: 'lina-execution-edge-wait-auth', source: 'lina-execution-wait', target: 'lina-tools-resolve', label: 'verified readiness; resolve again' },
    { id: 'lina-execution-edge-wait-input', source: 'lina-execution-wait', target: 'lina-tools-collect', label: 'original protocol continuation' },
    { id: 'lina-execution-edge-wait-cancel', source: 'lina-execution-wait', target: 'lina-execution-cancel', label: 'cancel retained work' },
    { id: 'lina-execution-edge-cancel-model', source: 'lina-execution-cancel', target: 'lina-execution-model', label: 'signal exact provider attempt' },
    { id: 'lina-execution-edge-cancel-tools', source: 'lina-execution-cancel', target: 'lina-tools-collect', label: 'signal adapter owners; collect outcomes' },
    { id: 'lina-execution-edge-cancel-settle', source: 'lina-execution-cancel', target: 'lina-execution-settle', label: 'required work known settled' },
    { id: 'lina-execution-edge-cancel-reconcile', source: 'lina-execution-cancel', target: 'lina-input-reconcile', label: 'unknown effects; retain authority' },
    { id: 'lina-execution-edge-reconcile-publish', source: 'lina-input-reconcile', target: 'lina-tools-publish', label: 'evidence-resolved full batch' },
    { id: 'lina-execution-edge-reconcile-settle', source: 'lina-input-reconcile', target: 'lina-execution-settle', label: 'evidence-resolved terminal' },
  ],
};
