import type { LinaDocument, LinaNode } from './linaModel';
import type { StateRequestRoute } from './stateBlock';

/** Responses retain requester and operation identity. Context recall and explicit
 * Tools operations share admission but never return to the other requester. */
export const MEMORY_REQUEST_ROUTES = [
  { id: 'lina-memory-edge-context-request', source: 'lina-context-load', target: 'lina-memory-scope', phase: 'context-recall', returnId: 'lina-memory-edge-select-context', returnSource: 'lina-memory-select', returnTarget: 'lina-context-load' },
  { id: 'lina-memory-edge-tools-request', source: 'lina-tools-dispatch', target: 'lina-memory-scope', phase: 'explicit-memory-operation', returnId: 'lina-memory-edge-select-tools', returnSource: 'lina-memory-select', returnTarget: 'lina-tools-collect' },
] as const;
const storage = (short: string, source: string, kind: StateRequestRoute['kind'], phase: string): StateRequestRoute => ({ id: `lina-memory-edge-${short}-state-${kind}`, source: `lina-memory-${source}`, target: `lina-state-${kind}`, kind, phase, returnId: `lina-memory-edge-state-${kind}-${short}`, returnTarget: `lina-memory-${source}` });
export const MEMORY_STATE_ROUTES: readonly StateRequestRoute[] = [
  storage('scope', 'scope', 'load', 'read-memory-access-generation'),
  storage('retrieve', 'retrieve', 'load', 'read-memory-records'),
  storage('resolve', 'resolve', 'load', 'read-current-memory-revisions'),
  storage('commit', 'commit', 'record', 'commit-memory-mutation'),
  storage('commit-inspect', 'commit', 'load', 'inspect-memory-transaction'),
  storage('index', 'index', 'record', 'record-memory-index-watermark'),
  storage('consolidate', 'consolidate', 'load', 'read-memory-maintenance-cursor'),
  storage('consolidate', 'consolidate', 'record', 'record-memory-maintenance-progress'),
  storage('forget', 'forget', 'load', 'read-memory-deletion-lineage'),
  storage('forget', 'forget', 'record', 'revoke-memory-visibility'),
  storage('forget-inspect', 'forget', 'load', 'inspect-memory-revocation'),
  storage('forget-receipt', 'forget', 'record', 'record-memory-purge-receipt'),
];
const references = 'docs/research/lina/memory-research.md; memory-hermes-openclaw.md; memory-pi-waku.md; memory-mechanisms-and-evaluation.md. Versioned records, recall and maintenance are deterministic design fixtures, not a live memory backend or measured retrieval quality.';
const node = (id: string, title: string, x: number, y: number, purpose: string, inputs: string, outputs: string, decisions: string, experiments: string): LinaNode => ({ id: `lina-memory-${id}`, title, area: 'Memory', status: 'proposed', x, y, purpose, inputs, outputs, decisions, references, experiments });
const edge = (id: string, source: string, target: string, label: string) => ({ id: `lina-memory-edge-${id}`, source: source.startsWith('lina-') ? source : `lina-memory-${source}`, target: target.startsWith('lina-') ? target : `lina-memory-${target}`, label });
export const linaMemoryBlock: LinaDocument = {
  version: 1,
  nodes: [
    node('scope', 'Resolve memory access', 80, 10000, 'Bind requester and namespace to permitted memory operations and current visibility generation.', 'Context recall, explicit Tools operation or requested maintenance; user/workspace/agent/task identity and granted namespaces.', 'Admitted read/write/maintenance/forget operation, denied, disabled or unavailable.', 'Private unless shared. Child access uses admitted namespaces; shared child publication requires parent review. Ranking never grants access. Disabled differs from empty and unavailable.', 'Compare namespace-sharing policies while preserving isolation.'),
    node('query', 'Prepare recall query', 500, 10000, 'Prepare bounded original or rewritten recall queries with temporal filters.', 'Admitted search intent, original query, task, provenance and query budget.', 'Query ready, no recall needed or invalid.', 'Exact/profile reads bypass query generation. Rewriting changes search terms, not caller authority. No extra main-agent round is charged for a fixture query.', 'Original, rewritten or multiple queries with fixed downstream budgets.'),
    node('retrieve', 'Retrieve candidates', 920, 10000, 'Read a profile, exact record or bounded search candidates from permitted versioned records.', 'Scoped query/read request, record/index generations and consistency requirement.', 'Candidates, no matches, stale index, denied or unavailable.', 'Versioned records are authoritative; indexes are replaceable. A committed record may be directly readable before searchable. Report actual watermarks and known fallback.', 'Exact/lexical baseline versus vector/hybrid candidates on the same corpus.'),
    node('select', 'Select recall evidence', 1340, 10000, 'Recheck visibility, rank and deduplicate bounded evidence before returning to its requester.', 'Candidate records, revision/trust/validity, source expansion and selection budget.', 'Selected evidence, no matches, invalidated selection or unavailable; omission reasons.', 'Retired or revoked records cannot be newly recalled. A historical snapshot stays historical. Context owns final model budget; selected procedures remain evidence, not executable instructions.', 'Ranking, source expansion and diversity at a fixed evidence budget.'),
    node('capture', 'Capture memory evidence', 80, 10280, 'Bind eligible source events and observed outcomes before forming memories.', 'Explicit remember/correct request or automatic evidence window with retention/egress policy.', 'Evidence ready, structured mutation, rejected or no-op.', 'Preserve assertion versus observation, source time and validity time. Recalled evidence cannot repeatedly become new independent support. Unverified assistant claims are not verified outcomes.', 'Evidence windows and write timing under the same source eligibility.'),
    node('extract', 'Propose memories', 500, 10280, 'Form candidate facts, preferences or episodes from permitted evidence.', 'Evidence bundle and bounded extraction purpose/model budget.', 'Candidates, no-op, cancelled or failed.', 'Explicit structured writes bypass model extraction. Model formation creates candidates only; it grants no persistence or broader scope. Retain source links and extractor revision.', 'Rules versus model extraction, same sources and write admission.'),
    node('validate', 'Validate candidates', 920, 10280, 'Validate schema, provenance, sensitive-data policy and publication scope.', 'Candidates or structured explicit mutation plus evidence and policy revisions.', 'Eligible, rejected, parent review required or permission review required.', 'Automatic candidates undergo admission. Shared child contributions require parent review by default. Semantic validation does not replace Safety authorization. Skills require separate activation.', 'Admission policies with false-addition and omission evidence.'),
    node('resolve', 'Resolve memory changes', 1340, 10280, 'Compare current claims and revisions to determine semantic mutations.', 'Eligible candidate, current records, expected revisions and temporal authority.', 'Add, update, supersede, retract, no-op or unresolved conflict.', 'Correction preserves historical meaning; forgetting revokes recall and purges coverage. Never use latest-write-wins for ambiguous contradictions. Model confidence is not verification.', 'Keyed correction versus linked claims under identical temporal semantics.'),
    node('commit', 'Commit memory changes', 1340, 10560, 'Commit an admitted versioned mutation set and inspect uncertain acknowledgments.', 'Stable transaction/fingerprint, expected revisions, reviewed scope and Stop/owner generation.', 'Applied, already-applied, conflict, failed or unknown; record revisions and index status.', 'Final authority recheck precedes commit. Unknown acknowledgments inspect the same transaction before retry. Applied writes survive Stop. State supplies persistence evidence and does not choose semantic changes.', 'Commit boundaries and duplicate/conflict recovery with fixed guarantees.'),
    node('index', 'Maintain retrieval index', 920, 10560, 'Update derived search views and report committed versus searchable generations.', 'Acknowledged additions, updates or visibility revocations with index cursor.', 'Ready, pending, failed or not-required; watermark and coverage.', 'Derived views never become authoritative records. Recall filters visibility even when purge/index cleanup lags. Direct record adapters may need no index.', 'Synchronous versus asynchronous indexes with direct-read fallback.'),
    node('consolidate', 'Consolidate memories', 500, 10560, 'Run one requested, bounded maintenance pass over eligible records.', 'Maintenance request/cursor, admitted record range, source lineage and separate budget.', 'Linked candidates, no-op, cancelled or failed; resumable progress.', 'Optional maintenance has no fictional daemon. Summaries/lessons re-enter validation, not free mutation. Preserve evidence links and deduplicate repeated work. Stop keeps acknowledged writes.', 'None, summaries, reflection or linked notes including maintenance cost.'),
    node('forget', 'Forget or retire memory', 80, 10560, 'Immediately revoke recall of authorized targets and descendants, then track deletion coverage.', 'Authorized forget selector, lineage, visibility generation and storage/index/cache coverage.', 'Logically removed, purge pending, erased within declared coverage, denied or unknown.', 'Exclude immediately, then delete covered records and derived copies. Pending consolidation cannot recreate revoked content. Report retained exceptions without claiming universal erasure. Audit metadata avoids retained content.', 'Backend cleanup strategies while preserving immediate exclusion.'),
  ],
  edges: [
    ...MEMORY_REQUEST_ROUTES.flatMap(route => [{ id: route.id, source: route.source, target: route.target, label: route.phase }, { id: route.returnId, source: route.returnSource, target: route.returnTarget, label: `${route.phase}; same requester evidence` }]),
    ...MEMORY_STATE_ROUTES.flatMap(route => [{ id: route.id, source: route.source, target: route.target, label: route.phase }, { id: route.returnId, source: route.target, target: route.returnTarget, label: `${route.phase}; correlated acknowledgment` }]),
    edge('scope-query', 'scope', 'query', 'admitted search'), edge('query-retrieve', 'query', 'retrieve', 'bounded query ready'), edge('scope-retrieve', 'scope', 'retrieve', 'exact/profile read; bypass rewrite'), edge('retrieve-select', 'retrieve', 'select', 'candidates / no match / unavailable'),
    edge('settle-scope', 'lina-execution-settle', 'scope', 'policy-selected automatic evidence; check access before capture'),
    edge('scope-capture', 'scope', 'capture', 'admitted explicit or automatic write'), edge('capture-extract', 'capture', 'extract', 'eligible extraction evidence'), edge('capture-validate', 'capture', 'validate', 'structured explicit mutation; bypass extraction'), edge('extract-validate', 'extract', 'validate', 'source-backed candidates'), edge('validate-resolve', 'validate', 'resolve', 'eligible reviewed candidates'), edge('resolve-commit', 'resolve', 'commit', 'conditional semantic mutation'), edge('commit-index', 'commit', 'index', 'acknowledged record revisions'),
    edge('scope-consolidate', 'scope', 'consolidate', 'requested bounded maintenance'), edge('consolidate-validate', 'consolidate', 'validate', 'derived candidates retain lineage'), edge('scope-forget', 'scope', 'forget', 'authorized forget selector'), edge('forget-resolve', 'forget', 'resolve', 'revoked targets; admitted purge mutation'), edge('index-forget', 'index', 'forget', 'purge watermark / pending coverage'), edge('forget-index', 'forget', 'index', 'acknowledged visibility revocation; cleanup derived indexes'),
    edge('extract-model', 'extract', 'lina-model-resolve', 'memory-extraction purpose; separate budget'), edge('consolidate-model', 'consolidate', 'lina-model-resolve', 'memory-consolidation purpose; separate budget'), edge('model-extract', 'lina-model-normalize', 'extract', 'same extraction operation; candidates / failure'), edge('model-consolidate', 'lina-model-normalize', 'consolidate', 'same maintenance operation; candidates / failure'),
    edge('validate-review', 'validate', 'lina-safety-evaluate', 'exact memory publication review'), edge('review-validate', 'lina-safety-authorize', 'validate', 'same mutation admission decision'), edge('commit-authorize', 'commit', 'lina-safety-authorize', 'final exact mutation authority recheck'), edge('authorize-commit', 'lina-safety-authorize', 'commit', 'bounded commit admission / no launch'),
    ...['scope','query','capture','extract','validate','resolve','commit','index','consolidate','forget'].map(source => edge(`${source}-tools`, source, 'lina-tools-collect', 'same explicit memory operation outcome / failure')),
    ...['scope','capture','extract','validate','resolve','commit','index','consolidate','forget'].map(source => edge(`${source}-settle`, source, 'lina-execution-settle', 'same automatic or maintenance operation outcome; no new turn')),
    edge('scope-context', 'scope', 'lina-context-load', 'same recall denied / disabled / unavailable'), edge('query-context', 'query', 'lina-context-load', 'same recall no-op / invalid'),
    ...['extract','commit','consolidate','forget'].map(target => edge(`cancel-${target}`, 'lina-execution-cancel', target, 'Stop exact memory operation; retain acknowledged writes')),
    ...['extract','commit','consolidate','forget'].map(source => edge(`${source}-cancel`, source, 'lina-execution-cancel', 'cancellation settlement / unresolved acknowledgment')),
    edge('validate-parent-wait', 'validate', 'lina-execution-wait', 'retain parent publication review; no fabricated subagent runtime'), edge('parent-review-validate', 'lina-execution-wait', 'validate', 'matched parent decision; recheck scope and revisions'),
    edge('index-context', 'index', 'lina-context-load', 'invalidate stale recall selection; reprepare before new invocation'), edge('forget-context', 'forget', 'lina-context-load', 'visibility revocation invalidates selected memory'),
  ],
};

/** Shared graph inventory for contract and playback compilation. */
export const MEMORY_EDGES = linaMemoryBlock.edges;
