import type { LinaDocument, LinaNode } from './linaModel';
import type { StateRequestRoute } from './stateBlock';
/** Durable receipts resume the same output phase, never a fresh send. */
const storage = (short: string, owner: string, kind: StateRequestRoute['kind'], phase: string): StateRequestRoute => ({ id: `lina-output-edge-${short}-state-${kind}`, source: `lina-output-${owner}`, target: `lina-state-${kind}`, kind, phase, returnId: `lina-output-edge-state-${kind}-${short}`, returnTarget: `lina-output-${owner}` });
export const OUTPUT_STATE_ROUTES: readonly StateRequestRoute[] = [
    storage('media', 'media', 'record', 'record-output-upload'),
    storage('media-inspect', 'media', 'load', 'inspect-original-output-upload'),
    storage('register', 'register', 'record', 'record-output-obligation'),
    storage('register-inspect', 'register', 'load', 'inspect-original-output-registration'),
    storage('schedule', 'schedule', 'record', 'claim-output-lane'),
    storage('send', 'send', 'record', 'record-output-send-start'),
    storage('observe', 'observe', 'record', 'record-output-observation'),
    storage('reconcile', 'reconcile', 'load', 'inspect-original-output-attempt'),
    storage('settle', 'settle', 'record', 'record-output-settlement'),
];
const references = 'docs/research/lina/output-research.md; output-hermes-openclaw.md; output-channels-and-protocols.md; output-existing-design-audit.md. Delivery facts are controlled fixtures, not live sends or remote exactly-once guarantees.';
const node = (id: string, title: string, x: number, y: number, purpose: string, inputs: string, outputs: string, decisions: string, experiments: string): LinaNode => ({ id: `lina-output-${id}`, title, area: 'Output and delivery', status: 'proposed', x, y, purpose, inputs, outputs, decisions, references, experiments });
const edge = (id: string, source: string, target: string, label: string) => ({ id: `lina-output-edge-${id}`, source: source.startsWith('lina-') ? source : `lina-output-${source}`, target: target.startsWith('lina-') ? target : `lina-output-${target}`, label });
/** Required finals and prompts acquire retained custody. Previews and internal
 * returns branch separately; only admitted parts enter the native adapter. */
export const linaOutputBlock: LinaDocument = {
    version: 1,
    nodes: [
        node("intent", "Capture output intent", 80, 11000, "Normalize producer identity, audience, finality and typed output without inventing a new agent round.", "Saved answer, prompt, progress, admitted tool message, notification or child result.", "External intent, internal return, quiet or invalid output.", "Internal child results return to their parent. Distinct new content is preserved; confirmed same-target tool sends can suppress duplicate finals. Quiet completion is explicit.", "Duplicate suppression policy under identical target-specific evidence."),
        node("route", "Resolve delivery route", 500, 11000, "Bind authorized account, conversation, thread and reply target to native adapter capabilities.", "Canonical intent, originating route, explicit authorized override and binding generation.", "Recipient plans, independent fanout, missing, stale or ambiguous route.", "Never silently switch accounts or threads. Fanout creates separate obligations and outcomes. CLI TTY, text, JSONL and RPC declare different capabilities.", "Recipient scheduling under preserved route authority."),
        node("policy", "Check output policy", 920, 11000, "Resolve public disclosure, current permission and native notification eligibility before exposure.", "Intent, immutable route, Safety decision and native service-window/template policy.", "Allowed, permission wait, defer, reject or suppress.", "Preview text requires the same disclosure checks as final text. Platform eligibility and authentication do not grant permission. Stop invalidates prompt controls.", "Progress disclosure within fixed permission constraints."),
        node("render", "Render delivery parts", 1340, 11000, "Preserve canonical typed content while preparing ordered channel-native parts.", "Admitted intent, capability revision, text/structured result and interactive prompt choices.", "Validated parts, documented fallback or unsupported content.", "Enforce versioned limits, escaping and code-fence closure. Preserve all four approval choices even when native buttons are fewer. Machine stdout excludes diagnostics.", "Chunked text versus retained artifact presentation."),
        node("media", "Prepare outbound media", 1760, 11000, "Resolve authorized retained bytes and account-scoped upload handles.", "Artifact identity, digest, access/retention policy and native upload capability.", "Ready media, expired handle, denied/unavailable bytes or unknown upload.", "Pathnames are not custody. Reuse handles only under exact digest/account/expiry policy. Unknown upload inspects the original attempt rather than recreating bytes.", "Fresh upload versus valid handle reuse."),
        node("stream", "Manage reply stream", 1340, 11280, "Coalesce admitted progress and serialize mutable preview revisions through shared transport.", "Visible model events, revision/sequence and final boundary or cancellation.", "Prepared preview, completed block, promotion candidate, stale or aborted revision.", "No token event directly sends. Draft acceptance is not owed-final settlement. Partial exposure cannot be retracted; stale revisions cannot overwrite a final.", "Final-only versus editable previews and native drafts."),
        node("register", "Register delivery obligation", 1760, 11280, "Transfer prepared recipient parts and artifact custody to retained output ownership.", "Stable output/delivery ID, prepared bytes/digest, required or best-effort policy and State receipt.", "Stored obligation, already registered, explicit best-effort or storage failure.", "Required custody precedes dispatch and execution release. Lost storage acknowledgement inspects the original transaction. Registration proves neither send nor delivery.", "Outbox persistence profiles with unchanged ownership semantics."),
        node("schedule", "Schedule outbound work", 1760, 11560, "Claim due work under account/target/thread ordering and declared budgets.", "Retained obligation, lane, priority, deadline, current owner fence and Stop.", "Ready exact part, deferred, superseded/cancelled or deadline exhausted.", "Independent recipients can run concurrently. Coalescing can drop declared best-effort progress, never silently erase an owed final. Claims do not authorize effects.", "Queue priorities and coalescing within preserved lane order."),
        node("send", "Execute transport attempt", 1340, 11560, "Recheck the exact part, revision, claim and native readiness immediately before transport.", "Admitted operation/attempt, policy generation, authenticated adapter and send-start record.", "Accepted, proven unsent/rejected, partial or unknown acknowledgement.", "Persist effect boundary before dispatch. Use opaque credentials only. No blind repeat of non-idempotent sends; accepted parts survive failure of siblings.", "Adapter scheduling and transport choices under equal content."),
        node("observe", "Record delivery observations", 920, 11560, "Correlate native receipts and preserve raw evidence without regressing known facts.", "Attempt result or incoming account/provider/recipient-bound status event.", "Accepted/delivered/read, partial, duplicate/stale or unmatched evidence.", "Read is a provider fact, not proof a person read. Late receipts can resolve original effects but cannot revive stopped prompts or dispatch work.", "Receipt projection and retention while preserving raw evidence."),
        node("retry", "Decide delivery retry", 500, 11560, "Classify delivery failures against original part identity, deadline and retry budget.", "Failure certainty, provider wait, retained custody and confirmed-part set.", "Safe retry, defer, exhausted/permanent failure or reconciliation.", "Retry only known-safe unsent parts with fresh admission. Never rerun the agent or resend confirmed chunks. Rate-limit waits retain original ownership.", "Bounded backoff under equal provider constraints."),
        node("reconcile", "Reconcile uncertain delivery", 500, 11280, "Inspect original attempt evidence after ambiguous sends, partial failure or restart.", "Original intent/part/claim identities, persisted observations and adapter/operator evidence.", "Confirmed sent, proven unsent, unresolved or contradictory facts.", "Default unknown sends remain unresolved until evidence proves a safe choice. Local identity does not prove remote deduplication. Warned resend requires explicit policy.", "Conservative hold versus authorized duplicate-risk resend."),
        node("settle", "Settle output obligation", 80, 11560, "Record independent per-recipient terminal outcomes and release retained custody under policy.", "Part facts, completion threshold, deadline/Stop, prompt lifecycle and retention owner.", "Accepted, failed, suppressed, cancelled/stale or unresolved obligation.", "Final acceptance, provider delivery, read and turn release differ. Transfer artifact retention before cleanup. An accepted preview cannot discharge required final output.", "Acceptance versus delivery thresholds where receipts exist."),
    ],
    edges: [
        edge("wait-intent", "lina-execution-wait", "intent", "already registered clarification or readiness prompt; original wait identity"),
        edge("settle-wait", "settle", "lina-execution-wait", "prompt notification custody; exact retained wait still owns the answer"),
        edge("reconcile-wait", "reconcile", "lina-execution-wait", "retain original output reconciliation wait"),
        edge("wait-reconcile", "lina-execution-wait", "reconcile", "matched original output evidence; never redispatch"),
        edge("stream-policy", "stream", "policy", "new public preview revision requires disclosure admission"),
        edge("intent-coordinate", "intent", "lina-subagents-coordinate", "internal child result only; no user delivery"),
        ...OUTPUT_STATE_ROUTES.flatMap(route => [{ id: route.id, source: route.source, target: route.target, label: route.phase }, { id: route.returnId, source: route.target, target: route.returnTarget, label: `${route.phase}; same output and requester` }]),
        edge("input-intent", "lina-input-delivery", "intent", "saved reply handoff; never rerun execution"),
        edge("input-observe", "lina-input-delivery", "observe", "correlated provider status observation"),
        edge("execution-intent", "lina-execution-settle", "intent", "authoritative saved final/error output"),
        edge("approval-intent", "lina-safety-approval", "intent", "registered four-choice prompt"),
        edge("tools-intent", "lina-tools-dispatch", "intent", "admitted native message operation"),
        edge("intent-tools", "settle", "lina-tools-collect", "same message tool call delivery observation"),
        edge("model-stream", "lina-model-invoke", "stream", "admitted visible draft events; no final authority"),
        edge("child-intent", "lina-subagents-return", "intent", "internal parent result or authorized announcement"),
        edge("intent-route", "intent", "route", "external canonical intent"),
        edge("intent-settle", "intent", "settle", "explicit quiet, invalid or confirmed duplicate final"),
        edge("route-policy", "route", "policy", "bound recipient plans"),
        edge("route-settle", "route", "settle", "missing, ambiguous or stale destination"),
        edge("policy-safety", "policy", "lina-safety-evaluate", "exact disclosure or message operation review"),
        edge("safety-policy", "lina-safety-authorize", "policy", "same output request; bounded current admission"),
        edge("policy-wait", "policy", "lina-execution-wait", "retain output permission or eligibility wait"),
        edge("wait-policy", "lina-execution-wait", "policy", "matched output readiness; recheck route and policy"),
        edge("policy-render", "policy", "render", "allowed content and recipient eligibility"),
        edge("policy-settle", "policy", "settle", "rejected, suppressed or permanent native ineligibility"),
        edge("render-media", "render", "media", "prepared parts require retained media"),
        edge("render-register", "render", "register", "final-only parts ready"),
        edge("render-stream", "render", "stream", "mutable preview or block stream policy"),
        edge("render-settle", "render", "settle", "invalid typed result or unsupported fallback"),
        edge("media-register", "media", "register", "verified native media handles and retained bytes"),
        edge("media-environment", "media", "lina-environment-artifacts", "resolve original retained authorized artifact"),
        edge("environment-media", "lina-environment-artifacts", "media", "same artifact requester custody receipt"),
        edge("media-reconcile", "media", "reconcile", "unknown original upload"),
        edge("media-settle", "media", "settle", "unavailable, denied or expired unrecoverable media"),
        edge("stream-register", "stream", "register", "prepared preview, sealed block or final promotion"),
        edge("stream-settle", "stream", "settle", "stale, superseded or aborted stream revision"),
        edge("register-release", "register", "lina-execution-release", "acknowledged required output custody; delivery remains independently owned"),
        edge("register-schedule", "register", "schedule", "acknowledged obligation custody or declared best-effort"),
        edge("register-settle", "register", "settle", "required storage failed; dispatch withheld"),
        edge("schedule-send", "schedule", "send", "exact due part and current lane claim"),
        edge("schedule-schedule", "schedule", "schedule", "provider wait or bounded lane defer"),
        edge("schedule-settle", "schedule", "settle", "cancelled, superseded or expired before send"),
        edge("send-auth", "send", "lina-tools-auth", "original native channel account readiness request"),
        edge("auth-send", "lina-tools-auth", "send", "same account readiness; fresh exact attempt recheck"),
        edge("send-observe", "send", "observe", "native acceptance, rejection or partial receipt"),
        edge("send-reconcile", "send", "reconcile", "send-start exists; acknowledgement uncertain"),
        edge("send-retry", "send", "retry", "proven pre-effect failure"),
        edge("observe-stream", "observe", "stream", "same accepted preview revision native handle"),
        edge("observe-schedule", "observe", "schedule", "accepted part; next unsent sibling"),
        edge("observe-settle", "observe", "settle", "required threshold reached or stale/unmatched observation"),
        edge("observe-retry", "observe", "retry", "correlated known failure"),
        edge("observe-reconcile", "observe", "reconcile", "partial evidence leaves original effect uncertain"),
        edge("retry-schedule", "retry", "schedule", "bounded proven-unsent retry; original part identity"),
        edge("retry-reconcile", "retry", "reconcile", "unknown effect cannot be retried blindly"),
        edge("retry-settle", "retry", "settle", "permanent failure or exhausted deadline/budget"),
        edge("reconcile-observe", "reconcile", "observe", "original receipt confirms sent part"),
        edge("reconcile-schedule", "reconcile", "schedule", "original part proven unsent; fresh admission"),
        edge("reconcile-settle", "reconcile", "settle", "still unknown or contradictory; retain obligation"),
        edge("recovery-reconcile", "lina-state-recover", "reconcile", "restore original uncertain output attempt"),
        edge("cancel-stream", "lina-execution-cancel", "stream", "invalidate owned preview and prompt revisions"),
        edge("cancel-schedule", "lina-execution-cancel", "schedule", "Stop withholds new sends; preserves started effects"),
        edge("settle-release", "settle", "lina-execution-release", "same original output owner settlement; never release turn twice"),
        edge("settle-input", "settle", "lina-input-delivery", "same saved output and provider observation handoff"),
        edge("settle-environment", "settle", "lina-environment-release", "output artifact custody retained or transferred before cleanup"),
        edge("settle-child", "settle", "lina-subagents-coordinate", "same authorized child announcement outcome"),
    ],
};
/** Shared edge inventory keeps source-owned schema examples tied to actual paths. */
export const OUTPUT_EDGES = linaOutputBlock.edges;
